/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 79
#define ALIAS_COUNT 0
#define TOKEN_COUNT 53
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 20
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_use = 2,
  anon_sym_fn = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_end = 5,
  anon_sym_ret = 6,
  anon_sym_mov = 7,
  anon_sym_read = 8,
  anon_sym_add = 9,
  anon_sym_sub = 10,
  anon_sym_mul = 11,
  anon_sym_and = 12,
  anon_sym_or = 13,
  anon_sym_xor = 14,
  anon_sym_shl = 15,
  anon_sym_shr = 16,
  anon_sym_eq = 17,
  anon_sym_ne = 18,
  anon_sym_lt = 19,
  anon_sym_le = 20,
  anon_sym_gt = 21,
  anon_sym_ge = 22,
  anon_sym_get = 23,
  anon_sym_at = 24,
  anon_sym_write = 25,
  anon_sym_div = 26,
  anon_sym_rem = 27,
  anon_sym_udiv = 28,
  anon_sym_urem = 29,
  anon_sym_puts = 30,
  anon_sym_select = 31,
  anon_sym_set = 32,
  anon_sym_put = 33,
  anon_sym_arr = 34,
  anon_sym_rec = 35,
  anon_sym_call = 36,
  anon_sym_fold = 37,
  anon_sym_loop = 38,
  anon_sym_text = 39,
  sym_primitive_type = 40,
  aux_sym_array_type_token1 = 41,
  aux_sym_array_type_token2 = 42,
  anon_sym_LPAREN = 43,
  anon_sym_COMMA = 44,
  anon_sym_RPAREN = 45,
  sym_parameter = 46,
  sym_integer = 47,
  anon_sym_true = 48,
  anon_sym_false = 49,
  sym_string = 50,
  sym_comment = 51,
  sym__newline = 52,
  sym_source_file = 53,
  sym_use_declaration = 54,
  sym_function_definition = 55,
  sym_parameter_types = 56,
  sym_return_statement = 57,
  sym_instruction = 58,
  sym__expression = 59,
  sym_operation = 60,
  sym_aggregate_expression = 61,
  sym_call_expression = 62,
  sym_direct_call_expression = 63,
  sym_fold_expression = 64,
  sym_loop_expression = 65,
  sym_text_expression = 66,
  sym__operand = 67,
  sym__type = 68,
  sym_array_type = 69,
  sym_tuple_type = 70,
  sym_boolean = 71,
  aux_sym_source_file_repeat1 = 72,
  aux_sym_source_file_repeat2 = 73,
  aux_sym_source_file_repeat3 = 74,
  aux_sym_function_definition_repeat1 = 75,
  aux_sym_parameter_types_repeat1 = 76,
  aux_sym_aggregate_expression_repeat1 = 77,
  aux_sym_tuple_type_repeat1 = 78,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_use] = "use",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_end] = "end",
  [anon_sym_ret] = "ret",
  [anon_sym_mov] = "operator",
  [anon_sym_read] = "operator",
  [anon_sym_add] = "operator",
  [anon_sym_sub] = "operator",
  [anon_sym_mul] = "operator",
  [anon_sym_and] = "operator",
  [anon_sym_or] = "operator",
  [anon_sym_xor] = "operator",
  [anon_sym_shl] = "operator",
  [anon_sym_shr] = "operator",
  [anon_sym_eq] = "operator",
  [anon_sym_ne] = "operator",
  [anon_sym_lt] = "operator",
  [anon_sym_le] = "operator",
  [anon_sym_gt] = "operator",
  [anon_sym_ge] = "operator",
  [anon_sym_get] = "operator",
  [anon_sym_at] = "operator",
  [anon_sym_write] = "operator",
  [anon_sym_div] = "operator",
  [anon_sym_rem] = "operator",
  [anon_sym_udiv] = "operator",
  [anon_sym_urem] = "operator",
  [anon_sym_puts] = "operator",
  [anon_sym_select] = "operator",
  [anon_sym_set] = "operator",
  [anon_sym_put] = "operator",
  [anon_sym_arr] = "operator",
  [anon_sym_rec] = "operator",
  [anon_sym_call] = "call",
  [anon_sym_fold] = "fold",
  [anon_sym_loop] = "loop",
  [anon_sym_text] = "text",
  [sym_primitive_type] = "primitive_type",
  [aux_sym_array_type_token1] = "array_type_token1",
  [aux_sym_array_type_token2] = "array_type_token2",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_parameter] = "parameter",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_use_declaration] = "use_declaration",
  [sym_function_definition] = "function_definition",
  [sym_parameter_types] = "parameter_types",
  [sym_return_statement] = "return_statement",
  [sym_instruction] = "instruction",
  [sym__expression] = "_expression",
  [sym_operation] = "operation",
  [sym_aggregate_expression] = "aggregate_expression",
  [sym_call_expression] = "call_expression",
  [sym_direct_call_expression] = "direct_call_expression",
  [sym_fold_expression] = "fold_expression",
  [sym_loop_expression] = "loop_expression",
  [sym_text_expression] = "text_expression",
  [sym__operand] = "_operand",
  [sym__type] = "_type",
  [sym_array_type] = "array_type",
  [sym_tuple_type] = "tuple_type",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_parameter_types_repeat1] = "parameter_types_repeat1",
  [aux_sym_aggregate_expression_repeat1] = "aggregate_expression_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_ret] = anon_sym_ret,
  [anon_sym_mov] = anon_sym_mov,
  [anon_sym_read] = anon_sym_mov,
  [anon_sym_add] = anon_sym_mov,
  [anon_sym_sub] = anon_sym_mov,
  [anon_sym_mul] = anon_sym_mov,
  [anon_sym_and] = anon_sym_mov,
  [anon_sym_or] = anon_sym_mov,
  [anon_sym_xor] = anon_sym_mov,
  [anon_sym_shl] = anon_sym_mov,
  [anon_sym_shr] = anon_sym_mov,
  [anon_sym_eq] = anon_sym_mov,
  [anon_sym_ne] = anon_sym_mov,
  [anon_sym_lt] = anon_sym_mov,
  [anon_sym_le] = anon_sym_mov,
  [anon_sym_gt] = anon_sym_mov,
  [anon_sym_ge] = anon_sym_mov,
  [anon_sym_get] = anon_sym_mov,
  [anon_sym_at] = anon_sym_mov,
  [anon_sym_write] = anon_sym_mov,
  [anon_sym_div] = anon_sym_mov,
  [anon_sym_rem] = anon_sym_mov,
  [anon_sym_udiv] = anon_sym_mov,
  [anon_sym_urem] = anon_sym_mov,
  [anon_sym_puts] = anon_sym_mov,
  [anon_sym_select] = anon_sym_mov,
  [anon_sym_set] = anon_sym_mov,
  [anon_sym_put] = anon_sym_mov,
  [anon_sym_arr] = anon_sym_mov,
  [anon_sym_rec] = anon_sym_mov,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_fold] = anon_sym_fold,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_text] = anon_sym_text,
  [sym_primitive_type] = sym_primitive_type,
  [aux_sym_array_type_token1] = aux_sym_array_type_token1,
  [aux_sym_array_type_token2] = aux_sym_array_type_token2,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_parameter] = sym_parameter,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_use_declaration] = sym_use_declaration,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_types] = sym_parameter_types,
  [sym_return_statement] = sym_return_statement,
  [sym_instruction] = sym_instruction,
  [sym__expression] = sym__expression,
  [sym_operation] = sym_operation,
  [sym_aggregate_expression] = sym_aggregate_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_direct_call_expression] = sym_direct_call_expression,
  [sym_fold_expression] = sym_fold_expression,
  [sym_loop_expression] = sym_loop_expression,
  [sym_text_expression] = sym_text_expression,
  [sym__operand] = sym__operand,
  [sym__type] = sym__type,
  [sym_array_type] = sym_array_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_parameter_types_repeat1] = aux_sym_parameter_types_repeat1,
  [aux_sym_aggregate_expression_repeat1] = aux_sym_aggregate_expression_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ret] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mov] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_read] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_mul] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_xor] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_shl] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_shr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_eq] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ne] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_lt] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_le] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_gt] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ge] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_at] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_write] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_div] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_rem] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_udiv] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_urem] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_puts] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_put] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_arr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_rec] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fold] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_array_type_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_type_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_types] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_aggregate_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_direct_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_fold_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_text_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_types_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_aggregate_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_count = 2,
  field_element = 3,
  field_function = 4,
  field_id = 5,
  field_init = 6,
  field_name = 7,
  field_operator = 8,
  field_parameters = 9,
  field_path = 10,
  field_predicate = 11,
  field_result = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_count] = "count",
  [field_element] = "element",
  [field_function] = "function",
  [field_id] = "id",
  [field_init] = "init",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_path] = "path",
  [field_predicate] = "predicate",
  [field_result] = "result",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 3},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 2},
  [14] = {.index = 21, .length = 3},
  [15] = {.index = 24, .length = 4},
  [16] = {.index = 28, .length = 3},
  [17] = {.index = 31, .length = 4},
  [18] = {.index = 35, .length = 4},
  [19] = {.index = 39, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_element, 0},
  [2] =
    {field_value, 1},
  [3] =
    {field_id, 0},
  [4] =
    {field_argument, 1},
    {field_operator, 0},
  [6] =
    {field_argument, 0},
  [7] =
    {field_argument, 1, .inherited = true},
    {field_operator, 0},
  [9] =
    {field_function, 1},
  [10] =
    {field_argument, 1, .inherited = true},
    {field_function, 0},
  [12] =
    {field_name, 1},
    {field_result, 3},
  [14] =
    {field_argument, 1},
    {field_argument, 2},
    {field_operator, 0},
  [17] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [19] =
    {field_argument, 2, .inherited = true},
    {field_function, 1},
  [21] =
    {field_name, 1},
    {field_parameters, 2},
    {field_result, 4},
  [24] =
    {field_argument, 1},
    {field_argument, 2},
    {field_argument, 3},
    {field_operator, 0},
  [28] =
    {field_count, 2},
    {field_function, 1},
    {field_init, 3},
  [31] =
    {field_argument, 4, .inherited = true},
    {field_count, 2},
    {field_function, 1},
    {field_init, 3},
  [35] =
    {field_count, 3},
    {field_function, 2},
    {field_init, 4},
    {field_predicate, 1},
  [39] =
    {field_argument, 5, .inherited = true},
    {field_count, 3},
    {field_function, 2},
    {field_init, 4},
    {field_predicate, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 41,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 15,
        '"', 1,
        '#', 14,
        '(', 7,
        ')', 9,
        ',', 8,
        '-', 2,
        '0', 10,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '0') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_integer);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'g', 7,
        'i', 8,
        'l', 9,
        'm', 10,
        'n', 11,
        'o', 12,
        'p', 13,
        'r', 14,
        's', 15,
        't', 16,
        'u', 17,
        'w', 18,
        'x', 19,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20);
      END_STATE();
    case 1:
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == 'q') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(31);
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(39);
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == '0') ADVANCE(43);
      if (lookahead == 'u') ADVANCE(44);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'h') ADVANCE(48);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 17:
      if (lookahead == '3') ADVANCE(52);
      if (lookahead == 'd') ADVANCE(53);
      if (lookahead == 'r') ADVANCE(54);
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 20:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'g', 7,
        'i', 8,
        'l', 9,
        'm', 10,
        'n', 11,
        'o', 12,
        'p', 13,
        'r', 14,
        's', 15,
        't', 16,
        'u', 17,
        'w', 18,
        'x', 59,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(60);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_at);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(63);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 27:
      if (lookahead == 'v') ADVANCE(65);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(66);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_eq);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(68);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_ge);
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_gt);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_primitive_type);
      if (lookahead == 'x') ADVANCE(70);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_le);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_lt);
      END_STATE();
    case 39:
      if (lookahead == 'v') ADVANCE(72);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_ne);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_parameter);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_parameter);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(75);
      if (lookahead == 'c') ADVANCE(76);
      if (lookahead == 'm') ADVANCE(77);
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(79);
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(81);
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 49:
      if (lookahead == 'b') ADVANCE(83);
      END_STATE();
    case 50:
      if (lookahead == 'x') ADVANCE(84);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(85);
      END_STATE();
    case 52:
      if (lookahead == '2') ADVANCE(35);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(86);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 56:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(90);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_array_type_token2);
      if (lookahead == 'x') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_arr);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(92);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_div);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 67:
      if (lookahead == 's') ADVANCE(93);
      END_STATE();
    case 68:
      if (lookahead == 'd') ADVANCE(94);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 71:
      if (lookahead == 'p') ADVANCE(96);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_mov);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_mul);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_put);
      if (lookahead == 's') ADVANCE(97);
      END_STATE();
    case 75:
      if (lookahead == 'd') ADVANCE(98);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_rec);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_rem);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_ret);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_shl);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_shr);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_sub);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 86:
      if (lookahead == 'v') ADVANCE(102);
      END_STATE();
    case 87:
      if (lookahead == 'm') ADVANCE(103);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(104);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_xor);
      END_STATE();
    case 91:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 93:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_fold);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_array_type_token1);
      if (lookahead == 'x') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_puts);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_read);
      END_STATE();
    case 99:
      if (lookahead == 'c') ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_udiv);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_urem);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(108);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_write);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_ret] = ACTIONS(1),
    [anon_sym_mov] = ACTIONS(1),
    [anon_sym_read] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_mul] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_xor] = ACTIONS(1),
    [anon_sym_shl] = ACTIONS(1),
    [anon_sym_shr] = ACTIONS(1),
    [anon_sym_eq] = ACTIONS(1),
    [anon_sym_ne] = ACTIONS(1),
    [anon_sym_lt] = ACTIONS(1),
    [anon_sym_le] = ACTIONS(1),
    [anon_sym_gt] = ACTIONS(1),
    [anon_sym_ge] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_at] = ACTIONS(1),
    [anon_sym_write] = ACTIONS(1),
    [anon_sym_div] = ACTIONS(1),
    [anon_sym_rem] = ACTIONS(1),
    [anon_sym_udiv] = ACTIONS(1),
    [anon_sym_urem] = ACTIONS(1),
    [anon_sym_puts] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_put] = ACTIONS(1),
    [anon_sym_arr] = ACTIONS(1),
    [anon_sym_rec] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_fold] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [sym_primitive_type] = ACTIONS(1),
    [aux_sym_array_type_token1] = ACTIONS(1),
    [aux_sym_array_type_token2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_parameter] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(98),
    [sym_use_declaration] = STATE(85),
    [sym_function_definition] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(26),
    [aux_sym_source_file_repeat2] = STATE(50),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(92),
    [sym_operation] = STATE(92),
    [sym_aggregate_expression] = STATE(92),
    [sym_call_expression] = STATE(92),
    [sym_direct_call_expression] = STATE(92),
    [sym_fold_expression] = STATE(92),
    [sym_loop_expression] = STATE(92),
    [sym_text_expression] = STATE(92),
    [sym__operand] = STATE(94),
    [sym_boolean] = STATE(94),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_mov] = ACTIONS(13),
    [anon_sym_read] = ACTIONS(13),
    [anon_sym_add] = ACTIONS(15),
    [anon_sym_sub] = ACTIONS(15),
    [anon_sym_mul] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_xor] = ACTIONS(15),
    [anon_sym_shl] = ACTIONS(15),
    [anon_sym_shr] = ACTIONS(15),
    [anon_sym_eq] = ACTIONS(15),
    [anon_sym_ne] = ACTIONS(15),
    [anon_sym_lt] = ACTIONS(15),
    [anon_sym_le] = ACTIONS(15),
    [anon_sym_gt] = ACTIONS(15),
    [anon_sym_ge] = ACTIONS(15),
    [anon_sym_get] = ACTIONS(15),
    [anon_sym_at] = ACTIONS(15),
    [anon_sym_write] = ACTIONS(15),
    [anon_sym_div] = ACTIONS(15),
    [anon_sym_rem] = ACTIONS(15),
    [anon_sym_udiv] = ACTIONS(15),
    [anon_sym_urem] = ACTIONS(15),
    [anon_sym_puts] = ACTIONS(15),
    [anon_sym_select] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_put] = ACTIONS(17),
    [anon_sym_arr] = ACTIONS(19),
    [anon_sym_rec] = ACTIONS(19),
    [anon_sym_call] = ACTIONS(21),
    [anon_sym_fold] = ACTIONS(23),
    [anon_sym_loop] = ACTIONS(25),
    [anon_sym_text] = ACTIONS(27),
    [sym_parameter] = ACTIONS(29),
    [sym_integer] = ACTIONS(29),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(96),
    [sym_operation] = STATE(96),
    [sym_aggregate_expression] = STATE(96),
    [sym_call_expression] = STATE(96),
    [sym_direct_call_expression] = STATE(96),
    [sym_fold_expression] = STATE(96),
    [sym_loop_expression] = STATE(96),
    [sym_text_expression] = STATE(96),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_mov] = ACTIONS(13),
    [anon_sym_read] = ACTIONS(13),
    [anon_sym_add] = ACTIONS(15),
    [anon_sym_sub] = ACTIONS(15),
    [anon_sym_mul] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_xor] = ACTIONS(15),
    [anon_sym_shl] = ACTIONS(15),
    [anon_sym_shr] = ACTIONS(15),
    [anon_sym_eq] = ACTIONS(15),
    [anon_sym_ne] = ACTIONS(15),
    [anon_sym_lt] = ACTIONS(15),
    [anon_sym_le] = ACTIONS(15),
    [anon_sym_gt] = ACTIONS(15),
    [anon_sym_ge] = ACTIONS(15),
    [anon_sym_get] = ACTIONS(15),
    [anon_sym_at] = ACTIONS(15),
    [anon_sym_write] = ACTIONS(15),
    [anon_sym_div] = ACTIONS(15),
    [anon_sym_rem] = ACTIONS(15),
    [anon_sym_udiv] = ACTIONS(15),
    [anon_sym_urem] = ACTIONS(15),
    [anon_sym_puts] = ACTIONS(15),
    [anon_sym_select] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_put] = ACTIONS(17),
    [anon_sym_arr] = ACTIONS(19),
    [anon_sym_rec] = ACTIONS(19),
    [anon_sym_call] = ACTIONS(21),
    [anon_sym_fold] = ACTIONS(23),
    [anon_sym_loop] = ACTIONS(25),
    [anon_sym_text] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_DASH_GT,
    ACTIONS(37), 1,
      sym_primitive_type,
    ACTIONS(39), 1,
      aux_sym_array_type_token1,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym_tuple_type,
    STATE(101), 1,
      sym_parameter_types,
    STATE(16), 3,
      sym__type,
      sym_array_type,
      aux_sym_parameter_types_repeat1,
  [27] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(47), 1,
      sym__newline,
    STATE(9), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [52] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [77] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [102] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym__newline,
    STATE(11), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [127] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(55), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [152] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(60), 2,
      sym_parameter,
      sym_integer,
    ACTIONS(63), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [177] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(68), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [202] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(70), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [227] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(72), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [252] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(74), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [277] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_primitive_type,
    ACTIONS(80), 1,
      aux_sym_array_type_token2,
    ACTIONS(76), 6,
      anon_sym_DASH_GT,
      aux_sym_array_type_token1,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__newline,
  [295] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      aux_sym_array_type_token1,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_DASH_GT,
    ACTIONS(84), 1,
      sym_primitive_type,
    STATE(15), 1,
      sym_tuple_type,
    STATE(18), 3,
      sym__type,
      sym_array_type,
      aux_sym_parameter_types_repeat1,
  [319] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_primitive_type,
    ACTIONS(86), 7,
      anon_sym_DASH_GT,
      aux_sym_array_type_token1,
      aux_sym_array_type_token2,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__newline,
  [335] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_DASH_GT,
    ACTIONS(92), 1,
      sym_primitive_type,
    ACTIONS(95), 1,
      aux_sym_array_type_token1,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym_tuple_type,
    STATE(18), 3,
      sym__type,
      sym_array_type,
      aux_sym_parameter_types_repeat1,
  [359] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_primitive_type,
    ACTIONS(101), 7,
      anon_sym_DASH_GT,
      aux_sym_array_type_token1,
      aux_sym_array_type_token2,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__newline,
  [375] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(7), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [397] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(9), 1,
      aux_sym_aggregate_expression_repeat1,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      sym_parameter,
      sym_integer,
    STATE(40), 2,
      sym__operand,
      sym_boolean,
  [419] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(107), 2,
      sym_parameter,
      sym_integer,
    STATE(100), 2,
      sym__operand,
      sym_boolean,
  [438] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(111), 2,
      sym_parameter,
      sym_integer,
    STATE(13), 2,
      sym__operand,
      sym_boolean,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_primitive_type,
    ACTIONS(113), 6,
      anon_sym_DASH_GT,
      aux_sym_array_type_token1,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__newline,
  [472] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_ret,
    ACTIONS(121), 1,
      sym__newline,
    STATE(45), 1,
      aux_sym_function_definition_repeat1,
    STATE(54), 1,
      aux_sym_source_file_repeat1,
    STATE(80), 1,
      sym_instruction,
    STATE(82), 1,
      sym_return_statement,
  [497] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(51), 1,
      aux_sym_source_file_repeat2,
    STATE(59), 1,
      sym_function_definition,
    STATE(85), 1,
      sym_use_declaration,
  [522] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_ret,
    ACTIONS(121), 1,
      sym__newline,
    STATE(48), 1,
      aux_sym_function_definition_repeat1,
    STATE(54), 1,
      aux_sym_source_file_repeat1,
    STATE(80), 1,
      sym_instruction,
    STATE(84), 1,
      sym_return_statement,
  [547] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(127), 2,
      sym_parameter,
      sym_integer,
    STATE(30), 2,
      sym__operand,
      sym_boolean,
  [566] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(131), 2,
      sym_parameter,
      sym_integer,
    STATE(31), 2,
      sym__operand,
      sym_boolean,
  [585] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(135), 2,
      sym_parameter,
      sym_integer,
    STATE(95), 2,
      sym__operand,
      sym_boolean,
  [604] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(139), 2,
      sym_parameter,
      sym_integer,
    STATE(33), 2,
      sym__operand,
      sym_boolean,
  [623] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(143), 2,
      sym_parameter,
      sym_integer,
    STATE(34), 2,
      sym__operand,
      sym_boolean,
  [642] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(147), 2,
      sym_parameter,
      sym_integer,
    STATE(97), 2,
      sym__operand,
      sym_boolean,
  [661] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(151), 2,
      sym_parameter,
      sym_integer,
    STATE(6), 2,
      sym__operand,
      sym_boolean,
  [680] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(155), 2,
      sym_parameter,
      sym_integer,
    STATE(23), 2,
      sym__operand,
      sym_boolean,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_primitive_type,
    ACTIONS(157), 6,
      anon_sym_DASH_GT,
      aux_sym_array_type_token1,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__newline,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(163), 3,
      sym_parameter,
      sym_integer,
      sym__newline,
  [728] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      aux_sym_array_type_token1,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      sym_primitive_type,
    STATE(15), 1,
      sym_tuple_type,
    STATE(68), 2,
      sym__type,
      sym_array_type,
  [748] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      aux_sym_array_type_token1,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(167), 1,
      sym_primitive_type,
    STATE(15), 1,
      sym_tuple_type,
    STATE(79), 2,
      sym__type,
      sym_array_type,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(171), 3,
      sym_parameter,
      sym_integer,
      sym__newline,
  [782] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(173), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_fn,
      anon_sym_end,
  [798] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      aux_sym_array_type_token1,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(178), 1,
      sym_primitive_type,
    STATE(15), 1,
      sym_tuple_type,
    STATE(77), 2,
      sym__type,
      sym_array_type,
  [818] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      aux_sym_array_type_token1,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      sym_primitive_type,
    STATE(15), 1,
      sym_tuple_type,
    STATE(75), 2,
      sym__type,
      sym_array_type,
  [838] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(73), 1,
      sym_function_definition,
  [857] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_ret,
    STATE(55), 1,
      aux_sym_function_definition_repeat1,
    STATE(80), 1,
      sym_instruction,
    STATE(81), 1,
      sym_return_statement,
  [876] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(73), 1,
      sym_function_definition,
  [895] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(73), 1,
      sym_function_definition,
  [914] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_ret,
    STATE(55), 1,
      aux_sym_function_definition_repeat1,
    STATE(76), 1,
      sym_return_statement,
    STATE(80), 1,
      sym_instruction,
  [933] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(73), 1,
      sym_function_definition,
  [952] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_fn,
    STATE(59), 1,
      sym_function_definition,
    STATE(63), 1,
      aux_sym_source_file_repeat2,
    STATE(85), 1,
      sym_use_declaration,
  [971] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_fn,
    STATE(53), 1,
      sym_function_definition,
    STATE(63), 1,
      aux_sym_source_file_repeat2,
    STATE(85), 1,
      sym_use_declaration,
  [990] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 1,
      sym__newline,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(64), 1,
      aux_sym_source_file_repeat3,
  [1006] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 1,
      sym__newline,
    STATE(46), 1,
      aux_sym_source_file_repeat1,
    STATE(60), 1,
      aux_sym_source_file_repeat3,
  [1022] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym__newline,
    STATE(54), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(194), 2,
      anon_sym_ret,
      sym_identifier,
  [1036] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym_identifier,
    ACTIONS(202), 1,
      anon_sym_ret,
    STATE(55), 1,
      aux_sym_function_definition_repeat1,
    STATE(80), 1,
      sym_instruction,
  [1052] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym__newline,
    STATE(54), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(202), 2,
      anon_sym_ret,
      sym_identifier,
  [1066] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(123), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(73), 1,
      sym_function_definition,
  [1082] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(204), 2,
      anon_sym_use,
      anon_sym_fn,
  [1096] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 1,
      sym__newline,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_source_file_repeat3,
  [1112] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(206), 1,
      sym__newline,
    STATE(49), 1,
      aux_sym_source_file_repeat1,
    STATE(64), 1,
      aux_sym_source_file_repeat3,
  [1128] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
    ACTIONS(210), 1,
      sym__newline,
    STATE(47), 1,
      aux_sym_source_file_repeat1,
    STATE(52), 1,
      aux_sym_source_file_repeat3,
  [1144] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 1,
      sym__newline,
    STATE(46), 1,
      aux_sym_source_file_repeat1,
    STATE(64), 1,
      aux_sym_source_file_repeat3,
  [1160] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_fn,
    ACTIONS(212), 1,
      anon_sym_use,
    STATE(63), 1,
      aux_sym_source_file_repeat2,
    STATE(85), 1,
      sym_use_declaration,
  [1176] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 1,
      sym__newline,
    STATE(57), 1,
      aux_sym_source_file_repeat1,
    STATE(64), 1,
      aux_sym_source_file_repeat3,
  [1192] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(220), 1,
      anon_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
  [1205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(222), 1,
      anon_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
  [1218] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(224), 1,
      anon_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
  [1231] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_tuple_type_repeat1,
  [1244] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(230), 1,
      anon_sym_end,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
  [1257] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_tuple_type_repeat1,
  [1270] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_tuple_type_repeat1,
  [1283] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym__newline,
    STATE(69), 1,
      aux_sym_source_file_repeat1,
  [1325] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym__newline,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
  [1335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1343] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__newline,
    STATE(27), 1,
      aux_sym_source_file_repeat1,
  [1353] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym__newline,
    STATE(56), 1,
      aux_sym_source_file_repeat1,
  [1363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym__newline,
    STATE(66), 1,
      aux_sym_source_file_repeat1,
  [1373] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym__newline,
    STATE(65), 1,
      aux_sym_source_file_repeat1,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      ts_builtin_sym_end,
      sym__newline,
  [1391] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym__newline,
    STATE(67), 1,
      aux_sym_source_file_repeat1,
  [1401] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym__newline,
    STATE(58), 1,
      aux_sym_source_file_repeat1,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_string,
  [1418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_identifier,
  [1425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym_identifier,
  [1432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym__newline,
  [1439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_identifier,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
  [1453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym__newline,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym__newline,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym__newline,
  [1474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym__newline,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym__newline,
  [1488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym__newline,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
  [1502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_string,
  [1509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym__newline,
  [1516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DASH_GT,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 27,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 152,
  [SMALL_STATE(11)] = 177,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 227,
  [SMALL_STATE(14)] = 252,
  [SMALL_STATE(15)] = 277,
  [SMALL_STATE(16)] = 295,
  [SMALL_STATE(17)] = 319,
  [SMALL_STATE(18)] = 335,
  [SMALL_STATE(19)] = 359,
  [SMALL_STATE(20)] = 375,
  [SMALL_STATE(21)] = 397,
  [SMALL_STATE(22)] = 419,
  [SMALL_STATE(23)] = 438,
  [SMALL_STATE(24)] = 457,
  [SMALL_STATE(25)] = 472,
  [SMALL_STATE(26)] = 497,
  [SMALL_STATE(27)] = 522,
  [SMALL_STATE(28)] = 547,
  [SMALL_STATE(29)] = 566,
  [SMALL_STATE(30)] = 585,
  [SMALL_STATE(31)] = 604,
  [SMALL_STATE(32)] = 623,
  [SMALL_STATE(33)] = 642,
  [SMALL_STATE(34)] = 661,
  [SMALL_STATE(35)] = 680,
  [SMALL_STATE(36)] = 699,
  [SMALL_STATE(37)] = 714,
  [SMALL_STATE(38)] = 728,
  [SMALL_STATE(39)] = 748,
  [SMALL_STATE(40)] = 768,
  [SMALL_STATE(41)] = 782,
  [SMALL_STATE(42)] = 798,
  [SMALL_STATE(43)] = 818,
  [SMALL_STATE(44)] = 838,
  [SMALL_STATE(45)] = 857,
  [SMALL_STATE(46)] = 876,
  [SMALL_STATE(47)] = 895,
  [SMALL_STATE(48)] = 914,
  [SMALL_STATE(49)] = 933,
  [SMALL_STATE(50)] = 952,
  [SMALL_STATE(51)] = 971,
  [SMALL_STATE(52)] = 990,
  [SMALL_STATE(53)] = 1006,
  [SMALL_STATE(54)] = 1022,
  [SMALL_STATE(55)] = 1036,
  [SMALL_STATE(56)] = 1052,
  [SMALL_STATE(57)] = 1066,
  [SMALL_STATE(58)] = 1082,
  [SMALL_STATE(59)] = 1096,
  [SMALL_STATE(60)] = 1112,
  [SMALL_STATE(61)] = 1128,
  [SMALL_STATE(62)] = 1144,
  [SMALL_STATE(63)] = 1160,
  [SMALL_STATE(64)] = 1176,
  [SMALL_STATE(65)] = 1192,
  [SMALL_STATE(66)] = 1205,
  [SMALL_STATE(67)] = 1218,
  [SMALL_STATE(68)] = 1231,
  [SMALL_STATE(69)] = 1244,
  [SMALL_STATE(70)] = 1257,
  [SMALL_STATE(71)] = 1270,
  [SMALL_STATE(72)] = 1283,
  [SMALL_STATE(73)] = 1291,
  [SMALL_STATE(74)] = 1299,
  [SMALL_STATE(75)] = 1307,
  [SMALL_STATE(76)] = 1315,
  [SMALL_STATE(77)] = 1325,
  [SMALL_STATE(78)] = 1335,
  [SMALL_STATE(79)] = 1343,
  [SMALL_STATE(80)] = 1353,
  [SMALL_STATE(81)] = 1363,
  [SMALL_STATE(82)] = 1373,
  [SMALL_STATE(83)] = 1383,
  [SMALL_STATE(84)] = 1391,
  [SMALL_STATE(85)] = 1401,
  [SMALL_STATE(86)] = 1411,
  [SMALL_STATE(87)] = 1418,
  [SMALL_STATE(88)] = 1425,
  [SMALL_STATE(89)] = 1432,
  [SMALL_STATE(90)] = 1439,
  [SMALL_STATE(91)] = 1446,
  [SMALL_STATE(92)] = 1453,
  [SMALL_STATE(93)] = 1460,
  [SMALL_STATE(94)] = 1467,
  [SMALL_STATE(95)] = 1474,
  [SMALL_STATE(96)] = 1481,
  [SMALL_STATE(97)] = 1488,
  [SMALL_STATE(98)] = 1495,
  [SMALL_STATE(99)] = 1502,
  [SMALL_STATE(100)] = 1509,
  [SMALL_STATE(101)] = 1516,
  [SMALL_STATE(102)] = 1523,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operand, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fold_expression, 4, 0, 16),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aggregate_expression, 2, 0, 7),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, 0, 8),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_call_expression, 2, 0, 9),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_aggregate_expression_repeat1, 2, 0, 12), SHIFT_REPEAT(40),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_aggregate_expression_repeat1, 2, 0, 12), SHIFT_REPEAT(40),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_aggregate_expression_repeat1, 2, 0, 12), SHIFT_REPEAT(37),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_aggregate_expression_repeat1, 2, 0, 12),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 13),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fold_expression, 5, 0, 17),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_expression, 5, 0, 18),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_expression, 6, 0, 19),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_types, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_types_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameter_types_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_types_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_types_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_type, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 2, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_aggregate_expression_repeat1, 1, 0, 6),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_aggregate_expression_repeat1, 1, 0, 6),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(99),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(57),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 14),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 10),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 10),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, 0, 14),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_expression, 2, 0, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 1),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 3, 0, 11),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 4, 0, 15),
  [287] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 2, 0, 5),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_a0(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "a0",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
