import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

// `a0 check` starts a process and validates a program; it must not pay to load the backends, the
// MCP and language servers, the proof encoder or the toolchain wrapper. src/cli.ts loads those on
// demand (dynamic import), so the static import closure of the CLI must stay free of them.

const dist = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'src');

/** Modules reachable from `entry` through static imports and re-exports only (not `import()`). */
function staticClosure(entry: string): Set<string> {
  const seen = new Set<string>();
  const todo = [entry];
  while (todo.length > 0) {
    const file = todo.pop() as string;
    if (seen.has(file)) continue;
    seen.add(file);
    const text = readFileSync(join(dist, file), 'utf8');
    for (const m of text.matchAll(/^(?:import|export)\s[^;]*?from\s+['"]\.\/([\w.-]+\.js)['"]/gm)) {
      const dep = m[1] as string;
      if (existsSync(join(dist, dep))) todo.push(dep);
    }
  }
  return seen;
}

const HEAVY = [
  'backends.js',
  'cache.js',
  'toolchain.js',
  'parallel.js',
  'wasm.js',
  'lsp.js',
  'mcp.js',
  'prove.js',
  'z3enc.js',
  'agents.js',
  'explain.js',
];

test('the CLI statically imports none of the heavy modules', () => {
  const closure = staticClosure('cli.js');
  for (const m of HEAVY) assert.ok(!closure.has(m), `cli.js statically reaches ${m}`);
});

test('check, version and a lazily loaded command still work', () => {
  const cli = join(dist, 'cli.js');
  const v = spawnSync(process.execPath, [cli, '--version'], { encoding: 'utf8' });
  assert.equal(v.status, 0);
  assert.match(v.stdout, /^a0 \S+ \(compiler a0c-/);
  const file = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', 'compiler', 'lex.a0');
  const c = spawnSync(process.execPath, [cli, 'check', file], { encoding: 'utf8' });
  assert.equal(c.status, 0, c.stderr);
  const e = spawnSync(process.execPath, [cli, 'emit', 'c', file], { encoding: 'utf8' });
  assert.equal(e.status, 0, e.stderr);
  assert.match(e.stdout, /Generated by A0 a0c-/);
  const x = spawnSync(process.execPath, [cli, 'explain'], { encoding: 'utf8' });
  assert.equal(x.status, 0, x.stderr);
});
