import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { findClang } from '../src/toolchain.js';
import { buildGenerator, generate } from '../tools/site-gen.js';

// The site pages are generated by an A0 program (site/gen/sitegen.a0). Its output must be the
// committed page programs byte for byte: they were produced by the Python generator it replaced
// (integer arithmetic, the same templates), and `bun run site` regenerates them with it.
test('the A0 site generator reproduces site/page.a0 and site/docs.a0', {
  skip: findClang().path === undefined ? 'clang not found' : false,
  timeout: 1_800_000,
}, async () => {
  const bin = await buildGenerator();
  for (const [tpl, out] of [
    ['site/gen/page.tpl', 'site/page.a0'],
    ['site/gen/docs.tpl', 'site/docs.a0'],
  ] as const) {
    assert.equal(await generate(bin, tpl), await readFile(out, 'utf8'), `${tpl} -> ${out}`);
  }
});
