import assert from 'node:assert/strict';
import { copyFile, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { makeIo, run, type TypedFunc } from '../src/core.js';
import { link } from '../src/link.js';
import { findClang } from '../src/toolchain.js';
import {
  checkOperandBudget,
  functionBudgets,
  NODE_LIMIT,
  OPERAND_LIMIT,
} from '../tools/site-budget.js';
import { buildGenerator, generate } from '../tools/site-gen.js';
import { prerender, renderWords } from '../tools/site-render.js';

// The site pages are generated by an A0 program (site/gen/sitegen.a0). Its output must be the
// committed page programs byte for byte: `bun run site` regenerates them with it, so a template,
// stylesheet or results change is committed together with the pages it produces.
test('the A0 site generator reproduces site/page.a0, site/docs.a0 and site/bench.a0', {
  skip: findClang().path === undefined ? 'clang not found' : false,
  timeout: 1_800_000,
}, async () => {
  const bin = await buildGenerator();
  for (const [tpl, out] of [
    ['site/gen/page.tpl', 'site/page.a0'],
    ['site/gen/docs.tpl', 'site/docs.a0'],
    ['site/gen/bench.tpl', 'site/bench.a0'],
  ] as const) {
    assert.equal(await generate(bin, tpl), await readFile(out, 'utf8'), `${tpl} -> ${out}`);
  }
});

// The benchmark sections are written to be read at a glance: each chart or table has a one-sentence
// takeaway computed from results/*.json (numbers only), terms are defined in plain words, and the
// long many-language lists sit behind a disclosure that is present in the prerendered HTML.
test('the benchmarks page explains every benchmark in plain words', {
  timeout: 600_000,
}, async () => {
  const program = (await link('site/bench.a0', (f) => readFile(f, 'utf8'), { root: '.' })).program;
  const { html, text } = prerender(program);
  const takeaways: readonly RegExp[] = [
    /The slowest test program is \d+\.\d\dx slower on \w+ against baselines with the same calling convention, and \d+\.\d\dx slower on \w+ against each language's own inlined driver\. Same calling convention \(A0 and the best of C, Rust and Zig, both called out of line\): \d+ wins, \d+ ties, \d+ losses of \d+\. Inlined drivers: \d+ wins, \d+ ties, \d+ losses\. Against hand-written C alone, A0 takes \d+\.\d\dx as long/,
    /Baseline: each language's own driver, inlined\./,
    /Speedup = the baseline's time divided by A0's: below 1\.00x A0 is slower/,
    /Every loss under either baseline is in bold\. A0's code is called out of line from a C driver while the other languages' drivers are inlined/,
    /Two baselines, because they answer different questions\. Same calling convention: A0 and the best of C, Rust and Zig are all called out of line from a C driver\. Inlined: each language/,
    /Native speed: one Apple M3, 2026-09-30 and 2026-10-01\. WebAssembly: one Windows x64 PC/,
    /First of the languages that ran each program on \d+ of \d+ test programs \(a language is timed only on the programs it has source for, so fewer languages ran the later programs\); on every one, A0 takes at most \d+\.\d\dx as long as the fastest language/,
    /Writing the \d+ token test programs, A0 \(canonical\)/,
    /The dense totals are over the same \d+ programs/,
    /Up to \d+\.\d\dx behind the best of C, Rust and Zig \(\w+\), and up to \d+\.\d\dx behind each language's own inlined driver/,
    /\d+ paths \(.*\) ran all \d+ generated cases; the native assembly targets ran the \d+ cases that need no io \(\d+ targets\); SystemVerilog is simulated separately on \d+ cases and is unverified in this run/,
    /fewer than TypeScript shown the whole numbered file \(A0's scoped view against a whole-file workflow, not both with scoped views\)/,
    /of the other \d+ languages are more than 5% faster than A0/,
    /A0 takes \d+\.\d\d ms from launch to first result: place \d+ of \d+ languages \(1 = fastest\)/,
    /A0 \(canonical\) takes \d+ tokens: place \d+ of \d+ \(1 = fewest\), fewer than \d+ of the other \d+ languages, equal to \d+ and more than \d+\. A0 \(dense\) takes \d+: place \d+, fewer than \d+, equal to \d+, more than \d+; its lossless form, with the same ids and node order, takes \d+: place \d+/,
    /Over a session of 10 edits, A0 \(canonical\) costs \d+ tokens per task: place \d+ of \d+ \(1 = fewest\), cheaper than \d+ of the other \d+ languages, equal to \d+, dearer than \d+\. A0 \(dense, lean view with callee bodies\) costs \d+: place \d+, cheaper than \d+, equal to \d+, dearer than \d+/,
    /the dense primer is larger \(\d+ tokens against \d+ for canonical\)/,
    /At 4000 functions an A0 edit costs \d+ tokens against \d+ for TypeScript, which is \d+\.\dx fewer than TypeScript/,
    /A0 \(native\) checks in \d+\.\d\d ms: place \d+ of \d+ \(1 = fastest\)\..*A0 \(Node CLI\), the previous path, took \d+\.\d\d ms/,
    /A0 --parallel is the fastest implementation on \d+ of \d+ test programs/,
  ];
  for (const re of takeaways) assert.match(text, re);
  // Plain labels: "test program" is defined, the table says what a place and a ratio are.
  for (const needle of [
    'A test program is one small function',
    "A0's place (1 = fastest)",
    'Fastest language other than A0',
    'A0 takes this many times as long',
    'How long each language takes, as a multiple of A0',
  ])
    assert.ok(text.includes(needle), `missing: ${needle}`);
  for (const gone of ['A0 rank', 'A0 vs fastest other', 'fastest other\n'])
    assert.ok(!text.includes(gone), `unexplained label is back: ${gone}`);
  // One disclosure per many-language chart (speed, startup, tokens, edit cost, check), closed
  // by default, and the fold hides no language: every row is still in the document.
  const disclosures = html.match(
    /<details class="more"><summary>Show all \d+ (languages|rows \(\d+ languages, A0 in two forms\))<\/summary>/g,
  );
  assert.equal(disclosures?.length, 5);
  // A0 is plotted in both forms, never only the dense one: each token and edit-cost chart has the
  // canonical and the dense subject as separate highlighted rows, and dense is defined in one line.
  for (const label of ['A0 (canonical)', 'A0 (dense)'])
    assert.ok(
      (
        html.match(
          new RegExp(`lrow me"><span class="lbl">${label.replace(/[()]/g, '\\$&')}<`, 'g'),
        ) ?? []
      ).length >= 4,
      `${label} is a highlighted subject in the token and edit-cost charts`,
    );
  assert.ok(
    text.includes('Dense is the same program in a shorter surface form; it converts losslessly'),
  );
  const speed =
    /<details class="more"><summary>Show all (\d+) languages<\/summary>(.*?)<\/details>/s.exec(
      html,
    );
  assert.equal((speed?.[2]?.match(/class="lrow/g) ?? []).length, Number(speed?.[1]));
  assert.ok(!html.includes('<details class="more" open'));
  // The section rail and the "where A0 loses" list live on this page only.
  assert.match(html, /<nav class="rail"/);
  assert.match(
    text,
    /Native speed — Up to \d+\.\d\dx behind[^\n]*\n[\s\S]*The language — No floating point, no heap, no recursion/,
  );
});

// The home page is short: a pitch with the install line and a checked edit, the token figure, how
// an edit is checked, the losses, install; every number computed from results/*.json, the rest on /benchmarks.
test('the home page is short: a pitch, the token figure, how it works, the losses, install', {
  timeout: 600_000,
}, async () => {
  const program = (await link('site/page.a0', (f) => readFile(f, 'utf8'), { root: '.' })).program;
  const { html, text } = prerender(program);
  assert.ok(text.split(/s+/).length < 1500, 'the home page stays under 1500 words');
  assert.ok(!html.includes('<details'), 'no hidden lists on the home page');
  assert.ok(!html.includes('class="rail"'), 'the section rail is on /benchmarks only');
  for (const h of [
    'A language for agents to edit.',
    'How it works.',
    'Where it loses.',
    'Install A0.',
  ])
    assert.ok(text.includes(h), `missing: ${h}`);
  const answers: readonly RegExp[] = [
    /\$ a0 run examples\/kernels\.a0 affine 3 4 5\n\s*17/,
    /refused\s+p3: affine takes 3 parameters/,
    /On a one-function file, a whole edit costs \d+\.\d\d× TypeScript's tokens\./,
    /Slower than the best of C, Rust and Zig on \d+ of \d+ programs\./,
  ];
  for (const re of answers) assert.match(text, re);
  // the token figure is read from results/lang-axes.json and results/dense-tokens.json, never typed
  const axes = JSON.parse(await readFile('results/lang-axes.json', 'utf8'));
  const dense = JSON.parse(await readFile('results/dense-tokens.json', 'utf8'));
  const tok = (id: string): number => axes.tokens[id].sumKernelTokens;
  assert.ok(
    text.includes(`${dense.kernelTotals.dense} tokens. Forth takes ${tok('forth')}.`),
    'the token headline is A0 dense against Forth',
  );
  assert.ok(text.includes(`written in ${axes.tokens.a0.dense.vsBest.languagesRanked} languages`));
  for (const [label, v] of [
    ['A0', dense.kernelTotals.dense],
    ['Forth', tok('forth')],
    ['Python', tok('python')],
    ['TypeScript', tok('typescript')],
    ['Rust', tok('rust')],
  ] as const) {
    const pct = Math.floor((v * 100) / tok('rust'));
    assert.ok(
      html.includes(
        `<span class="lbl">${label}</span><div class="htrack"><div class="fill grown" style="width:${pct}%"></div></div><span class="n">${v}</span>`,
      ),
      `${label} bar is ${v} tokens, ${pct}% of Rust`,
    );
  }
  // both install commands carry the COPY protocol; the terminal's final state is in the page without JS
  assert.ok(
    html.includes(
      'data-copy="curl -fsSL https://raw.githubusercontent.com/Joe-Simo/a0/main/install.sh | sh"',
    ),
  );
  assert.ok(
    html.includes(
      'data-copy="irm https://raw.githubusercontent.com/Joe-Simo/a0/main/install.ps1 | iex"',
    ),
  );
  assert.match(
    html,
    /<pre[^>]*class="typing"[^>]*>[\s\S]*written to kernels\.a0[\s\S]*17\n<\/pre>/,
  );
  assert.ok(html.includes('<code>claude mcp add a0 -- a0 mcp .</code>'));
});

// A page program must fit the A0 toolchain: a function holds at most 32768 operand pairs and a text
// literal is one per byte, so the stylesheet is spread over several functions. Splitting changes the
// program, never the page: the unsplit program (one `s 9 css` line) renders identically.
test('splitting the stylesheet over functions leaves the rendered page unchanged', {
  skip: findClang().path === undefined ? 'clang not found' : false,
  timeout: 1_800_000,
}, async () => {
  const bin = await buildGenerator();
  const dir = await mkdtemp(join(tmpdir(), 'a0-sitegen-'));
  try {
    for (const name of ['page', 'docs', 'bench'] as const) {
      const tpl = await readFile(`site/gen/${name}.tpl`, 'utf8');
      const unsplit = tpl.replace(/\{css_a\n[\s\S]*?\ns 9 css \d+\n\}\n/, 's 9 css\n');
      assert.notEqual(unsplit, tpl, `${name}.tpl has the css section functions`);
      const file = join(dir, `${name}.tpl`);
      await writeFile(file, unsplit);
      const whole = await generate(bin, file, { budget: false });
      const split = await generate(bin, `site/gen/${name}.tpl`);
      assert.ok(
        functionBudgets(whole).some((f) => f.operands > OPERAND_LIMIT),
        `${name}: the unsplit program is over the budget`,
      );
      assert.ok(functionBudgets(split).every((f) => f.operands <= OPERAND_LIMIT / 1.5));
      const a = await rendered(whole);
      const b = await rendered(split);
      assert.deepEqual(b.words, a.words, `${name}: protocol stream`);
      assert.equal(b.html, a.html, `${name}: prerendered HTML`);
      assert.equal(b.text, a.text, `${name}: prerendered text`);
      assert.equal(b.css, a.css, `${name}: stylesheet`);
      // the program must carry the whole stylesheet: a chunk that runs out of room silently drops the tail
      const cssSource = await readFile('site/gen/style.css', 'utf8');
      const expected = scopeThemes(cssSource);
      assert.ok(
        Math.abs(b.css.length - expected.length) <= 2,
        `${name}: the program's stylesheet (${b.css.length}) is the whole of style.css, theme-scoped (${expected.length})`,
      );
      assert.equal(b.css.trimEnd(), expected.trimEnd(), `${name}: stylesheet text`);
    }
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('the generator refuses a function above 75% of the operand table, naming it', () => {
  const big = `fn session io -> u32\nx text "${'a'.repeat(OPERAND_LIMIT + 1)}"\nret 0\nend\n`;
  assert.throws(
    () => checkOperandBudget(big, 'page.tpl'),
    /page\.tpl: session has \d+ operand pairs, above 24576/,
  );
  checkOperandBudget(
    `fn session io -> u32\nx text "${'a'.repeat(1000)}"\nret 0\nend\n`,
    'page.tpl',
  );
});

test('the generator refuses a function above the node table, naming it', () => {
  const lines = Array.from({ length: NODE_LIMIT + 1 }, (_, i) => `x${i} add p0 1`).join('\n');
  assert.throws(
    () => checkOperandBudget(`fn session io -> u32\n${lines}\nret x0\nend\n`, 'page.tpl'),
    /page\.tpl: session has 2777 nodes, above 2776/,
  );
  checkOperandBudget(
    `fn session io -> u32\n${lines.split('\n').slice(0, 100).join('\n')}\nret x0\nend\n`,
    'page.tpl',
  );
});

// The theme scoping site/gen/sgcss.a0 documents, written independently: each
// `@media (prefers-color-scheme:X){R}` block keeps R with each selector limited to `:root` without the
// opposite forced theme, and is followed by R limited to `[data-theme=X]`.
function scopeThemes(css: string): string {
  const scope = (rules: string, cond: string): string =>
    rules.replace(/([^{}]+)\{([^{}]*)\}/g, (_, sels: string, body: string) => {
      const out = sels.split(',').map((raw) => {
        const sel = raw.replace(/\s+/g, ' ').trim();
        return sel.startsWith(':root')
          ? `:root:where(${cond})${sel.slice(5)}`
          : `:where(:root${cond}) ${sel}`;
      });
      return `${out.join(',')}{${body}}`;
    });
  return css.replace(
    /@media \(prefers-color-scheme:(light|dark)\)\{((?:[^{}]*\{[^{}]*\})*)\}/g,
    (_, x: string, rules: string) => {
      const other = x === 'light' ? 'dark' : 'light';
      return `@media (prefers-color-scheme:${x}){${scope(rules, `:not([data-theme=${other}])`)}}${scope(rules, `[data-theme=${x}]`)}`;
    },
  );
}

async function rendered(
  source: string,
): Promise<{ words: number[]; html: string; text: string; css: string }> {
  const dir = await mkdtemp(join(tmpdir(), 'a0-sitegen-'));
  try {
    await writeFile(join(dir, 'p.a0'), source);
    await copyFile('site/ui.a0', join(dir, 'ui.a0'));
    const program = (await link(join(dir, 'p.a0'), (f) => readFile(f, 'utf8'), { root: dir }))
      .program;
    const io = makeIo([0, 0, 0, 0, 0]);
    run(program.byName.get('session') as TypedFunc, [io]);
    return { words: [...io.output], ...renderWords(io.output) };
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}
