import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { link } from '../src/link.js';
import { findClang } from '../src/toolchain.js';
import { buildGenerator, generate } from '../tools/site-gen.js';
import { prerender } from '../tools/site-render.js';

// The site pages are generated by an A0 program (site/gen/sitegen.a0). Its output must be the
// committed page programs byte for byte: `bun run site` regenerates them with it, so a template,
// stylesheet or results change is committed together with the pages it produces.
test('the A0 site generator reproduces site/page.a0 and site/docs.a0', {
  skip: findClang().path === undefined ? 'clang not found' : false,
  timeout: 1_800_000,
}, async () => {
  const bin = await buildGenerator();
  for (const [tpl, out] of [
    ['site/gen/page.tpl', 'site/page.a0'],
    ['site/gen/docs.tpl', 'site/docs.a0'],
  ] as const) {
    assert.equal(await generate(bin, tpl), await readFile(out, 'utf8'), `${tpl} -> ${out}`);
  }
});

// The benchmark sections are written to be read at a glance: each chart or table has a one-sentence
// takeaway computed from results/*.json (numbers only), terms are defined in plain words, and the
// long many-language lists sit behind a disclosure that is present in the prerendered HTML.
test('the home page explains every benchmark in plain words', { timeout: 600_000 }, async () => {
  const program = (await link('site/page.a0', (f) => readFile(f, 'utf8'), { root: '.' })).program;
  const { html, text } = prerender(program);
  const takeaways: readonly RegExp[] = [
    /A0 takes \d+\.\d\dx as long as hand-written C, a geometric mean over \d+ test programs/,
    /Fastest on \d+ of \d+ test programs; on every one, A0 takes at most \d+\.\d\dx as long as the fastest language/,
    /of the other \d+ languages are more than 5% faster than A0/,
    /A0 takes \d+\.\d\d ms from launch to first result: place \d+ of \d+ languages \(1 = fastest\)/,
    /Writing the \d+ test programs takes A0 \d+ tokens: place \d+ of \d+ languages \(1 = fewest\)/,
    /At 4000 functions an A0 edit costs \d+ tokens against \d+ for TypeScript, which is \d+\.\dx fewer than TypeScript/,
    /A0's checker takes \d+\.\d\d ms: place \d+ of \d+ \(1 = fastest\)/,
    /Checking and running takes A0 \d+\.\d\d ms: place \d+ of \d+ \(1 = fastest\)/,
    /A0 --parallel is the fastest implementation on \d+ of \d+ test programs/,
    /A0's scoped view is \d+\.\dx fewer tokens than reading the whole life\.a0 file in A0/,
  ];
  for (const re of takeaways) assert.match(text, re);
  // Plain labels: "test program" is defined, the table says what a place and a ratio are.
  for (const needle of [
    'A test program is one small function',
    "A0's place (1 = fastest)",
    'Fastest language other than A0',
    'A0 takes this many times as long',
    'How long each language takes, as a multiple of A0',
  ])
    assert.ok(text.includes(needle), `missing: ${needle}`);
  for (const gone of ['A0 rank', 'A0 vs fastest other', 'fastest other\n'])
    assert.ok(!text.includes(gone), `unexplained label is back: ${gone}`);
  // One disclosure per many-language chart (speed, startup, tokens, check, check and run), closed
  // by default, and the fold hides no language: every row is still in the document.
  const disclosures = html.match(
    /<details class="more"><summary>Show all \d+ languages<\/summary>/g,
  );
  assert.equal(disclosures?.length, 5);
  const speed =
    /<details class="more"><summary>Show all (\d+) languages<\/summary>(.*?)<\/details>/s.exec(
      html,
    );
  assert.equal((speed?.[2]?.match(/class="lrow/g) ?? []).length, Number(speed?.[1]));
  assert.ok(!html.includes('<details class="more" open'));
});
