/**
 * merge-plan: given branches, compute textual conflicts (merge-tree), shared-file coupling and
 * shared gate-step coupling, group independent branches into batches that merge together under one
 * combined gate run, and order coupled ones with the riskiest first. Prints a plan; merges nothing.
 *
 *   node dist/tools/dev/merge-plan.js [--base=<ref>] [--json] [--couple=a:b,...] <branch> <branch> ...
 *
 * Coupling kinds, strongest first:
 *   conflict  merge-tree reports a textual conflict in a code file (hard: never in one batch)
 *   files     both branches touch the same code file (hard)
 *   core      both branches change shared emitter/checker/optimizer code (hard: a failure could not
 *             be attributed to one of them)
 *   steps     both need the same gate step (soft: they SHARE one run of it, which is the saving)
 *   docs      conflict only in STATUS.md or results/ (soft: results are regenerated by the combined
 *             gate run; STATUS.md needs a hand merge)
 * A caller may declare extra coupling the rules cannot see (`--couple=a:b,c:d`); a declared pair is
 * treated as hard. `--json` prints branches, pairs and batches.
 */

import { pathToFileURL } from 'node:url';
import { computeScope, type Scope, SHARED_CORE, STEPS, type StepId } from './gate-scope.js';
import { WEIGHT } from './order.js';
import { branchFiles, defaultBase, defaultRepo, lines, refExists, vcs } from './repo.js';

export interface BranchInfo {
  readonly name: string;
  readonly files: readonly string[];
  readonly scope: Scope;
  readonly subjects: readonly string[];
  readonly risk: number;
}

export interface Pair {
  readonly a: string;
  readonly b: string;
  readonly conflicts: readonly string[];
  readonly softConflicts: readonly string[];
  readonly sharedFiles: readonly string[];
  readonly sharedCore: readonly string[];
  readonly sharedSteps: readonly StepId[];
  readonly declared?: true;
  readonly hard: boolean;
}

export interface Batch {
  readonly branches: readonly string[];
  readonly steps: readonly StepId[];
}

const isSoftFile = (f: string): boolean => f === 'STATUS.md' || f.startsWith('results/');

export function riskOf(scope: Scope, files: readonly string[]): number {
  const w = scope.steps.reduce((n, s) => n + (WEIGHT[s.step] ?? 3), 0);
  const core = files.filter((f) => SHARED_CORE.includes(f)).length * 10;
  return w + core + Math.min(files.length, 40) / 4;
}

/** Textual conflicts when merging b into a, from `merge-tree`. Empty when the merge is clean. */
export function conflictFiles(repo: string, a: string, b: string): string[] {
  const r = vcs(repo, ['merge-tree', '--write-tree', '--name-only', '--no-messages', a, b]);
  if (r.ok) return [];
  // First line is the tree id, then the conflicted file names, then a blank line and messages.
  const all = lines(r.stdout);
  return all.slice(1);
}

export function buildPair(repo: string, a: BranchInfo, b: BranchInfo): Pair {
  const rawConflicts = conflictFiles(repo, a.name, b.name);
  const conflicts = rawConflicts.filter((f) => !isSoftFile(f));
  const softConflicts = rawConflicts.filter(isSoftFile);
  const sharedFiles = a.files.filter((f) => b.files.includes(f) && !isSoftFile(f));
  const sharedCore = sharedFiles.filter((f) => SHARED_CORE.includes(f));
  const bothCore =
    a.files.some((f) => SHARED_CORE.includes(f)) && b.files.some((f) => SHARED_CORE.includes(f));
  const sa = new Set(a.scope.steps.map((s) => s.step));
  const sharedSteps = b.scope.steps
    .map((s) => s.step)
    .filter((s) => sa.has(s) && s !== 'lint' && s !== 'typecheck');
  const hard = conflicts.length > 0 || sharedFiles.length > 0 || bothCore;
  return {
    a: a.name,
    b: b.name,
    conflicts,
    softConflicts,
    sharedFiles,
    sharedCore: bothCore
      ? [...a.files, ...b.files].filter((f) => SHARED_CORE.includes(f))
      : sharedCore,
    sharedSteps,
    hard,
  };
}

export function loadBranch(repo: string, base: string, name: string): BranchInfo {
  const files = branchFiles(repo, base, name);
  const scope = computeScope(repo, files);
  const subjects = lines(vcs(repo, ['log', '--format=%s', `${base}..${name}`]).stdout).slice(0, 20);
  return { name, files, scope, subjects, risk: riskOf(scope, files) };
}

/**
 * Greedy batching: riskiest first, each branch joins the first batch where it has no hard edge to
 * any member. The batch order is by risk, riskiest first, so the batch that can fail the most runs
 * (and is fixed) first.
 */
export function planBatches(branches: readonly BranchInfo[], pairs: readonly Pair[]): Batch[] {
  const hard = (x: string, y: string): boolean =>
    pairs.some((p) => p.hard && ((p.a === x && p.b === y) || (p.a === y && p.b === x)));
  const order = [...branches].sort((p, q) => q.risk - p.risk || p.name.localeCompare(q.name));
  const groups: BranchInfo[][] = [];
  for (const br of order) {
    const home = groups.find((g) => g.every((m) => !hard(m.name, br.name)));
    if (home) home.push(br);
    else groups.push([br]);
  }
  return groups.map((g) => {
    const steps = new Set<StepId>();
    for (const m of g) for (const s of m.scope.steps) steps.add(s.step);
    return {
      branches: g.map((m) => m.name),
      steps: STEPS.map((s) => s.id).filter((s) => steps.has(s)),
    };
  });
}

export function renderPlan(
  base: string,
  branches: readonly BranchInfo[],
  pairs: readonly Pair[],
  batches: readonly Batch[],
): string {
  const out: string[] = [
    `merge-plan against ${base}: ${branches.length} branches, nothing is merged`,
  ];
  for (const b of branches) {
    out.push(
      `  ${b.name}: ${b.files.length} files, scope ${b.scope.class} [${b.scope.steps.map((s) => s.step).join(' ')}], risk ${b.risk.toFixed(1)}`,
    );
  }
  for (const p of pairs) {
    const bits: string[] = [];
    if (p.conflicts.length) bits.push(`CONFLICT in ${p.conflicts.join(', ')}`);
    if (p.softConflicts.length)
      bits.push(
        `doc/results conflict in ${p.softConflicts.join(', ')} (results regenerate; STATUS.md by hand)`,
      );
    if (p.sharedFiles.length && !p.conflicts.length)
      bits.push(`both edit ${p.sharedFiles.join(', ')}`);
    if (p.sharedCore.length && !p.sharedFiles.length)
      bits.push('both change shared core code, failures would not attribute');
    if (p.declared) bits.push('coupling declared by the caller');
    if (p.sharedSteps.length) bits.push(`share steps ${p.sharedSteps.join(', ')}`);
    out.push(
      `  ${p.a} x ${p.b}: ${p.hard ? 'COUPLED' : 'independent'}${bits.length ? ` (${bits.join('; ')})` : ''}`,
    );
  }
  out.push('plan, riskiest first (merge in this order; one combined gate run per batch):');
  batches.forEach((b, i) => {
    out.push(
      `  batch ${i + 1}: ${b.branches.join(' + ')}  ->  gate steps: ${b.steps.join(' ') || 'lint'}`,
    );
  });
  return out.join('\n');
}

function arg(args: readonly string[], name: string): string | undefined {
  return args.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const repo = arg(args, 'repo') ?? defaultRepo();
  const base = arg(args, 'base') ?? defaultBase(repo);
  const names = args.filter((a) => !a.startsWith('--'));
  if (names.length === 0) {
    process.stderr.write(
      'usage: merge-plan [--base=<ref>] [--json] [--couple=a:b,...] <branch> <branch> ...\n',
    );
    process.exit(2);
  }
  const missing = names.filter((n) => !refExists(repo, n));
  if (missing.length) {
    process.stderr.write(`merge-plan: unknown branch ${missing.join(', ')}\n`);
    process.exit(2);
  }
  const declared = (arg(args, 'couple') ?? '')
    .split(',')
    .filter(Boolean)
    .map((x) => x.split(':'));
  const branches = names.map((n) => loadBranch(repo, base, n));
  const pairs: Pair[] = [];
  for (let i = 0; i < branches.length; i += 1) {
    for (let j = i + 1; j < branches.length; j += 1) {
      const a = branches[i] as BranchInfo;
      const b = branches[j] as BranchInfo;
      let pair = buildPair(repo, a, b);
      if (
        declared.some(([x, y]) => (x === a.name && y === b.name) || (x === b.name && y === a.name))
      )
        pair = { ...pair, declared: true, hard: true };
      pairs.push(pair);
    }
  }
  const batches = planBatches(branches, pairs);
  if (args.includes('--json')) {
    process.stdout.write(`${JSON.stringify({ base, branches, pairs, batches }, null, 2)}\n`);
    return;
  }
  process.stdout.write(`${renderPlan(base, branches, pairs, batches)}\n`);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e: unknown) => {
    process.stderr.write(`${e instanceof Error ? e.message : String(e)}\n`);
    process.exit(1);
  });
}
