/**
 * Held-out task set K (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-k/k-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-k.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskK {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_K: readonly TaskK[] = [
  {
    id: 'k-nibble-swap',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Start shifts by 3 instead of 4. Wrongs drop the upper bits, or mask 8 bits before shifting left.',
    instruction:
      'Swap the two 4-bit groups of the lowest byte of the input and leave every bit above the lowest byte unchanged.',
    a0Source:
      'fn f u32 -> u32\na and p0 15\nb shl a 4\nc shr p0 3\nd and c 15\ne and p0 4294967040\nf or b d\ng or f e\nret g\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [18], expected: 33 },
      { fn: 'f', args: [171], expected: 186 },
      { fn: 'f', args: [240], expected: 15 },
      { fn: 'f', args: [15], expected: 240 },
      { fn: 'f', args: [305419896], expected: 305419911 },
      { fn: 'f', args: [4294967295], expected: 4294967295 },
      { fn: 'f', args: [256], expected: 256 },
      { fn: 'f', args: [128], expected: 8 },
    ],
    reference: {
      a0: 'fn f u32 -> u32\na and p0 15\nb shl a 4\nc shr p0 4\nd and c 15\ne and p0 4294967040\nf or b d\ng or f e\nret g\nend\n',
    },
    wrongEdits: [
      'fn f u32 -> u32\na and p0 15\nb shl a 4\nc shr p0 4\nd and c 15\ne and p0 4294967040\nf or b d\ng mov f\nret g\nend\n',
      'fn f u32 -> u32\na and p0 255\nb shl a 4\nc shr p0 4\nd and c 15\ne and p0 4294967040\nf or b d\ng or f e\nret g\nend\n',
    ],
  },
  {
    id: 'k-lowest-bit',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'wrapping',
    note: 'Start clears the lowest set bit instead; the fix relies on 0 minus the input wrapping.',
    instruction:
      'Return a value with only the lowest set bit of the input kept (zero when the input is zero).',
    a0Source: 'fn f u32 -> u32\na sub p0 1\nb and p0 a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [1], expected: 1 },
      { fn: 'f', args: [2], expected: 2 },
      { fn: 'f', args: [6], expected: 2 },
      { fn: 'f', args: [12], expected: 4 },
      { fn: 'f', args: [2147483648], expected: 2147483648 },
      { fn: 'f', args: [4294967295], expected: 1 },
      { fn: 'f', args: [2147483649], expected: 1 },
      { fn: 'f', args: [4096], expected: 4096 },
    ],
    reference: { a0: 'fn f u32 -> u32\na sub 0 p0\nb and p0 a\nret b\nend\n' },
    wrongEdits: [
      'fn f u32 -> u32\na sub p0 1\nb xor p0 a\nret b\nend\n',
      'fn f u32 -> u32\na sub 0 p0\nb xor p0 a\nret b\nend\n',
    ],
  },
  {
    id: 'k-late-fee',
    kind: 'targeted-edit',
    target: 'late',
    wrongEditKind: 'comparison',
    note: 'Start treats the last grace day as late.',
    instruction:
      'Return true only when the days elapsed (first input) are strictly more than the grace days (second input) and the amount owed (third input) is not zero.',
    a0Source: 'fn late u32 u32 u32 -> bool\na ge p0 p1\nb ne p2 0\nc and a b\nret c\nend\n',
    tests: [
      { fn: 'late', args: [5, 5, 1], expected: false },
      { fn: 'late', args: [6, 5, 1], expected: true },
      { fn: 'late', args: [4, 5, 1], expected: false },
      { fn: 'late', args: [6, 5, 0], expected: false },
      { fn: 'late', args: [0, 0, 1], expected: false },
      { fn: 'late', args: [4294967295, 0, 7], expected: true },
      { fn: 'late', args: [0, 4294967295, 7], expected: false },
      { fn: 'late', args: [4294967295, 4294967295, 1], expected: false },
      { fn: 'late', args: [10, 3, 4294967295], expected: true },
    ],
    reference: {
      a0: 'fn late u32 u32 u32 -> bool\na gt p0 p1\nb ne p2 0\nc and a b\nret c\nend\n',
    },
    wrongEdits: [
      'fn late u32 u32 u32 -> bool\na gt p0 p1\nb ne p2 0\nc or a b\nret c\nend\n',
      'fn late u32 u32 u32 -> bool\na ge p0 p1\nb gt p2 0\nc and a b\nret c\nend\n',
    ],
  },
  {
    id: 'k-majority',
    kind: 'targeted-edit',
    target: 'maj',
    wrongEditKind: 'missing-case',
    note: 'Start ignores the pair of second and third inputs; the wrong edit pairs the second and third inputs with xor, which fails when only those two are true.',
    instruction: 'Return true when at least two of the three boolean inputs are true.',
    a0Source: 'fn maj bool bool bool -> bool\na and p0 p1\nb and p0 p2\nc or a b\nret c\nend\n',
    tests: [
      { fn: 'maj', args: [false, false, false], expected: false },
      { fn: 'maj', args: [false, false, true], expected: false },
      { fn: 'maj', args: [false, true, false], expected: false },
      { fn: 'maj', args: [false, true, true], expected: true },
      { fn: 'maj', args: [true, false, false], expected: false },
      { fn: 'maj', args: [true, false, true], expected: true },
      { fn: 'maj', args: [true, true, false], expected: true },
      { fn: 'maj', args: [true, true, true], expected: true },
    ],
    reference: {
      a0: 'fn maj bool bool bool -> bool\na and p0 p1\nb and p0 p2\nc or a b\nd and p1 p2\ne or c d\nret e\nend\n',
    },
    wrongEdits: [
      'fn maj bool bool bool -> bool\na and p0 p1\nb and p0 p2\nc or a b\nd xor p1 p2\ne or c d\nret e\nend\n',
    ],
  },
  {
    id: 'k-prefix-sums',
    kind: 'targeted-edit',
    target: 'prefix',
    wrongEditKind: 'off-by-one',
    note: "Start's third sum omits the first element.",
    instruction:
      'Return an array whose element k is the wrapping sum of input elements 0 through k.',
    a0Source:
      'fn prefix u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ns1 add a b\ns2 add b c\ns3 add s2 d\nr arr a s1 s2 s3\nret r\nend\n',
    tests: [
      { fn: 'prefix', args: [[0, 0, 0, 0]], expected: [0, 0, 0, 0] },
      { fn: 'prefix', args: [[1, 2, 3, 4]], expected: [1, 3, 6, 10] },
      { fn: 'prefix', args: [[5, 0, 0, 0]], expected: [5, 5, 5, 5] },
      { fn: 'prefix', args: [[0, 0, 0, 9]], expected: [0, 0, 0, 9] },
      { fn: 'prefix', args: [[4294967295, 1, 0, 0]], expected: [4294967295, 0, 0, 0] },
      { fn: 'prefix', args: [[1, 4294967295, 1, 4294967295]], expected: [1, 0, 1, 0] },
      { fn: 'prefix', args: [[10, 20, 30, 40]], expected: [10, 30, 60, 100] },
      { fn: 'prefix', args: [[0, 7, 0, 0]], expected: [0, 7, 7, 7] },
    ],
    reference: {
      a0: 'fn prefix u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ns1 add a b\ns2 add s1 c\ns3 add s2 d\nr arr a s1 s2 s3\nret r\nend\n',
    },
    wrongEdits: [
      'fn prefix u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ns1 add a b\ns2 add s1 c\ns3 add s2 d\nr arr 0 a s1 s2\nret r\nend\n',
      'fn prefix u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ns1 add a b\ns2 add s1 c\ns3 add s2 c\nr arr a s1 s2 s3\nret r\nend\n',
    ],
  },
  {
    id: 'k-borrow-sub',
    kind: 'targeted-edit',
    target: 'csub',
    wrongEditKind: 'comparison',
    note: 'Start has the comparison reversed. Record results are written as JSON arrays [field0, field1].',
    instruction:
      'Return the wrapping difference first minus second, paired with a flag that is true exactly when the subtraction borrowed (second input larger than the first).',
    a0Source: 'fn csub u32 u32 -> (u32,bool)\nd sub p0 p1\nb lt p1 p0\nr rec d b\nret r\nend\n',
    tests: [
      { fn: 'csub', args: [5, 3], expected: [2, false] },
      { fn: 'csub', args: [3, 5], expected: [4294967294, true] },
      { fn: 'csub', args: [4, 4], expected: [0, false] },
      { fn: 'csub', args: [0, 0], expected: [0, false] },
      { fn: 'csub', args: [0, 1], expected: [4294967295, true] },
      { fn: 'csub', args: [4294967295, 0], expected: [4294967295, false] },
      { fn: 'csub', args: [0, 4294967295], expected: [1, true] },
      { fn: 'csub', args: [4294967295, 4294967295], expected: [0, false] },
      { fn: 'csub', args: [100, 99], expected: [1, false] },
    ],
    reference: {
      a0: 'fn csub u32 u32 -> (u32,bool)\nd sub p0 p1\nb lt p0 p1\nr rec d b\nret r\nend\n',
    },
    wrongEdits: ['fn csub u32 u32 -> (u32,bool)\nd sub p0 p1\nb le p0 p1\nr rec d b\nret r\nend\n'],
  },
  {
    id: 'k-low-bit-histogram',
    kind: 'targeted-edit',
    target: 'hist',
    wrongEditKind: 'fold-bound',
    note: 'Start stops one element early; a count of 5 wraps around and counts the first element twice.',
    instruction:
      'Count, for each value 0 to 3, how many of the four input elements have that value in their lowest two bits; every element must be counted exactly once.',
    a0Source:
      'fn step u32x4 u32 u32x4 -> u32x4\nx get p2 p1\nk and x 3\nc get p0 k\nd add c 1\nn set p0 k d\nret n\nend\nfn hist u32x4 -> u32x4\nz arr 0 0 0 0\nh fold step 3 z p0\nret h\nend\n',
    tests: [
      { fn: 'hist', args: [[0, 0, 0, 0]], expected: [4, 0, 0, 0] },
      { fn: 'hist', args: [[0, 1, 2, 3]], expected: [1, 1, 1, 1] },
      { fn: 'hist', args: [[3, 3, 3, 3]], expected: [0, 0, 0, 4] },
      { fn: 'hist', args: [[4, 8, 12, 1]], expected: [3, 1, 0, 0] },
      { fn: 'hist', args: [[4294967295, 0, 0, 7]], expected: [2, 0, 0, 2] },
      { fn: 'hist', args: [[1, 1, 1, 2]], expected: [0, 3, 1, 0] },
      { fn: 'hist', args: [[0, 0, 0, 3]], expected: [3, 0, 0, 1] },
      { fn: 'hist', args: [[5, 6, 7, 8]], expected: [1, 1, 1, 1] },
    ],
    reference: {
      a0: 'fn step u32x4 u32 u32x4 -> u32x4\nx get p2 p1\nk and x 3\nc get p0 k\nd add c 1\nn set p0 k d\nret n\nend\nfn hist u32x4 -> u32x4\nz arr 0 0 0 0\nh fold step 4 z p0\nret h\nend\n',
    },
    wrongEdits: [
      'fn step u32x4 u32 u32x4 -> u32x4\nx get p2 p1\nk and x 3\nc get p0 k\nd add c 1\nn set p0 k d\nret n\nend\nfn hist u32x4 -> u32x4\nz arr 0 0 0 0\nh fold step 5 z p0\nret h\nend\n',
      'fn step u32x4 u32 u32x4 -> u32x4\nx get p2 p1\nk and x 4\nc get p0 k\nd add c 1\nn set p0 k d\nret n\nend\nfn hist u32x4 -> u32x4\nz arr 0 0 0 0\nh fold step 4 z p0\nret h\nend\n',
    ],
  },
  {
    id: 'k-over-budget',
    kind: 'targeted-edit',
    target: 'budget',
    wrongEditKind: 'comparison',
    note: 'Start flags a total equal to the budget. Record results are written as JSON arrays.',
    instruction:
      'Return the wrapping total of the four elements together with a flag that is true only when the total is strictly greater than the budget (second input).',
    a0Source:
      'fn acc u32 u32 u32x4 -> u32\nx get p2 p1\ns add p0 x\nret s\nend\nfn budget u32x4 u32 -> (u32,bool)\nt fold acc 4 0 p0\no ge t p1\nr rec t o\nret r\nend\n',
    tests: [
      { fn: 'budget', args: [[1, 2, 3, 4], 10], expected: [10, false] },
      { fn: 'budget', args: [[1, 2, 3, 4], 9], expected: [10, true] },
      { fn: 'budget', args: [[1, 2, 3, 4], 11], expected: [10, false] },
      { fn: 'budget', args: [[0, 0, 0, 0], 0], expected: [0, false] },
      { fn: 'budget', args: [[4294967295, 1, 0, 0], 0], expected: [0, false] },
      { fn: 'budget', args: [[0, 0, 0, 5], 4], expected: [5, true] },
      { fn: 'budget', args: [[2, 2, 2, 2], 8], expected: [8, false] },
      { fn: 'budget', args: [[4294967295, 0, 0, 0], 4294967294], expected: [4294967295, true] },
    ],
    reference: {
      a0: 'fn acc u32 u32 u32x4 -> u32\nx get p2 p1\ns add p0 x\nret s\nend\nfn budget u32x4 u32 -> (u32,bool)\nt fold acc 4 0 p0\no gt t p1\nr rec t o\nret r\nend\n',
    },
    wrongEdits: [
      'fn acc u32 u32 u32x4 -> u32\nx get p2 p1\ns add p0 x\nret s\nend\nfn budget u32x4 u32 -> (u32,bool)\nt fold acc 3 0 p0\no gt t p1\nr rec t o\nret r\nend\n',
    ],
  },
  {
    id: 'k-tiered-price',
    kind: 'multi-node-edit',
    target: 'price',
    wrongEditKind: 'off-by-one',
    note: 'Start charges 5 for all units.',
    instruction:
      'Units up to and including 10 cost 5 each; every unit beyond the tenth costs 3, so the price above 10 units is 50 plus 3 per extra unit (wrapping).',
    a0Source: 'fn price u32 -> u32\na mul p0 5\nr mov a\nret r\nend\n',
    tests: [
      { fn: 'price', args: [0], expected: 0 },
      { fn: 'price', args: [1], expected: 5 },
      { fn: 'price', args: [9], expected: 45 },
      { fn: 'price', args: [10], expected: 50 },
      { fn: 'price', args: [11], expected: 53 },
      { fn: 'price', args: [12], expected: 56 },
      { fn: 'price', args: [100], expected: 320 },
      { fn: 'price', args: [1000], expected: 3020 },
      { fn: 'price', args: [4294967295], expected: 17 },
    ],
    reference: {
      a0: 'fn price u32 -> u32\na mul p0 5\no gt p0 10\ne sub p0 10\nm mul e 3\nt add m 50\nr select o t a\nret r\nend\n',
    },
    wrongEdits: [
      'fn price u32 -> u32\na mul p0 5\no gt p0 10\ne sub p0 9\nm mul e 3\nt add m 50\nr select o t a\nret r\nend\n',
    ],
  },
  {
    id: 'k-pack-channels',
    kind: 'multi-node-edit',
    target: 'pack',
    wrongEditKind: 'changed-constant',
    note: 'Start does not mask.',
    instruction:
      'Pack three channels into one value as first<<16 | second<<8 | third, using only the low 8 bits of each input so that oversized inputs cannot spill into neighbouring channels.',
    a0Source:
      'fn pack u32 u32 u32 -> u32\nr mov p0\ng mov p1\nbl mov p2\nrs shl r 16\ngs shl g 8\nx or rs gs\ny or x bl\nret y\nend\n',
    tests: [
      { fn: 'pack', args: [0, 0, 0], expected: 0 },
      { fn: 'pack', args: [255, 255, 255], expected: 16777215 },
      { fn: 'pack', args: [1, 2, 3], expected: 66051 },
      { fn: 'pack', args: [256, 0, 0], expected: 0 },
      { fn: 'pack', args: [0, 256, 0], expected: 0 },
      { fn: 'pack', args: [0, 0, 256], expected: 0 },
      { fn: 'pack', args: [4294967295, 4294967295, 4294967295], expected: 16777215 },
      { fn: 'pack', args: [18, 52, 86], expected: 1193046 },
      { fn: 'pack', args: [0, 511, 0], expected: 65280 },
    ],
    reference: {
      a0: 'fn pack u32 u32 u32 -> u32\nr and p0 255\ng and p1 255\nbl and p2 255\nrs shl r 16\ngs shl g 8\nx or rs gs\ny or x bl\nret y\nend\n',
    },
    wrongEdits: [
      'fn pack u32 u32 u32 -> u32\nr and p0 127\ng and p1 127\nbl and p2 127\nrs shl r 16\ngs shl g 8\nx or rs gs\ny or x bl\nret y\nend\n',
      'fn pack u32 u32 u32 -> u32\nr and p0 511\ng and p1 511\nbl and p2 511\nrs shl r 16\ngs shl g 8\nx or rs gs\ny or x bl\nret y\nend\n',
    ],
  },
  {
    id: 'k-pair-swap',
    kind: 'multi-node-edit',
    target: 'pairs',
    wrongEditKind: 'swapped-argument',
    note: 'Start swaps only the first pair; the wrong edit writes the same value into both slots.',
    instruction: 'Swap elements 0 and 1 and also swap elements 2 and 3, returning the new array.',
    a0Source:
      'fn pairs u32x4 -> u32x4\na get p0 0\nb get p0 1\ns set p0 0 b\nt set s 1 a\nret t\nend\n',
    tests: [
      { fn: 'pairs', args: [[1, 2, 3, 4]], expected: [2, 1, 4, 3] },
      { fn: 'pairs', args: [[0, 0, 0, 0]], expected: [0, 0, 0, 0] },
      { fn: 'pairs', args: [[5, 5, 6, 7]], expected: [5, 5, 7, 6] },
      { fn: 'pairs', args: [[1, 2, 3, 3]], expected: [2, 1, 3, 3] },
      {
        fn: 'pairs',
        args: [[4294967295, 0, 1, 4294967295]],
        expected: [0, 4294967295, 4294967295, 1],
      },
      { fn: 'pairs', args: [[9, 8, 7, 6]], expected: [8, 9, 6, 7] },
      { fn: 'pairs', args: [[0, 0, 1, 2]], expected: [0, 0, 2, 1] },
      { fn: 'pairs', args: [[4, 3, 2, 1]], expected: [3, 4, 1, 2] },
    ],
    reference: {
      a0: 'fn pairs u32x4 -> u32x4\na get p0 0\nb get p0 1\ns set p0 0 b\nt set s 1 a\nc get p0 2\nd get p0 3\nu set t 2 d\nv set u 3 c\nret v\nend\n',
    },
    wrongEdits: [
      'fn pairs u32x4 -> u32x4\na get p0 0\nb get p0 1\ns set p0 0 b\nt set s 1 a\nc get p0 2\nd get p0 3\nu set t 2 d\nv set u 3 d\nret v\nend\n',
    ],
  },
  {
    id: 'k-scaled-diff',
    kind: 'multi-node-edit',
    target: 'diff',
    wrongEditKind: 'swapped-argument',
    note: 'Start adds the raw second input.',
    instruction:
      'Apply the existing scale helper to both inputs and return the scaled first input minus the scaled second input (wrapping).',
    a0Source:
      'fn scale u32 -> u32\na mul p0 3\nb add a 1\nret b\nend\nfn diff u32 u32 -> u32\nx call scale p0\nr add x p1\nret r\nend\n',
    tests: [
      { fn: 'diff', args: [0, 0], expected: 0 },
      { fn: 'diff', args: [1, 0], expected: 3 },
      { fn: 'diff', args: [0, 1], expected: 4294967293 },
      { fn: 'diff', args: [5, 2], expected: 9 },
      { fn: 'diff', args: [2, 5], expected: 4294967287 },
      { fn: 'diff', args: [4294967295, 0], expected: 4294967293 },
      { fn: 'diff', args: [1431655765, 0], expected: 4294967295 },
      { fn: 'diff', args: [7, 7], expected: 0 },
    ],
    reference: {
      a0: 'fn scale u32 -> u32\na mul p0 3\nb add a 1\nret b\nend\nfn diff u32 u32 -> u32\nx call scale p0\ny call scale p1\nr sub x y\nret r\nend\n',
    },
    wrongEdits: [
      'fn scale u32 -> u32\na mul p0 3\nb add a 1\nret b\nend\nfn diff u32 u32 -> u32\nx call scale p0\ny call scale p1\nr sub y x\nret r\nend\n',
    ],
  },
  {
    id: 'k-index-checksum',
    kind: 'comprehension-edit',
    target: 'check',
    wrongEditKind: 'changed-constant',
    note: 'Start uses the old seed and no position mixing; the edit touches both functions.',
    instruction:
      "The checksum must start from 17 instead of 7, and every step must also add the element's position to the running value.",
    a0Source:
      'fn mix u32 u32 u32x4 -> u32\nx get p2 p1\nm mul p0 31\ns add m x\nret s\nend\nfn check u32x4 -> u32\nh fold mix 4 7 p0\nr mov h\nret r\nend\n',
    tests: [
      { fn: 'check', args: [[0, 0, 0, 0]], expected: 15700883 },
      { fn: 'check', args: [[1, 2, 3, 4]], expected: 15732693 },
      { fn: 'check', args: [[4294967295, 4294967295, 4294967295, 4294967295]], expected: 15670099 },
      { fn: 'check', args: [[0, 0, 0, 1]], expected: 15700884 },
      { fn: 'check', args: [[100, 0, 0, 0]], expected: 18679983 },
      { fn: 'check', args: [[5, 4, 3, 2]], expected: 15853777 },
      { fn: 'check', args: [[0, 4294967295, 0, 0]], expected: 15699922 },
      { fn: 'check', args: [[31, 31, 31, 31]], expected: 16655187 },
    ],
    reference: {
      a0: 'fn mix u32 u32 u32x4 -> u32\nx get p2 p1\nm mul p0 31\ns add m x\nt add s p1\nret t\nend\nfn check u32x4 -> u32\nh fold mix 4 17 p0\nr mov h\nret r\nend\n',
    },
    wrongEdits: [
      'fn mix u32 u32 u32x4 -> u32\nx get p2 p1\nm mul p0 31\ns add m x\nt add s p1\nret t\nend\nfn check u32x4 -> u32\nh fold mix 4 7 p0\nr mov h\nret r\nend\n',
      'fn mix u32 u32 u32x4 -> u32\nx get p2 p1\nm mul p0 31\ns add m x\nret s\nend\nfn check u32x4 -> u32\nh fold mix 4 17 p0\nr mov h\nret r\nend\n',
    ],
  },
  {
    id: 'k-bit-length',
    kind: 'comprehension-edit',
    target: 'bitlen',
    wrongEditKind: 'off-by-one',
    note: 'Start returns the index of the highest set bit; the greater-than-1 wrong is off by one; fold count 31 misses the top bit.',
    instruction:
      'Return how many bits are needed to write the input in binary: 0 for 0, 1 for 1, 2 for 2 and 3, up to 32 for values with the top bit set.',
    a0Source:
      'fn bstep u32 u32 u32 -> u32\na shr p2 p1\nn ne a 0\nr select n p1 p0\nret r\nend\nfn bitlen u32 -> u32\nh fold bstep 32 0 p0\nr mov h\nret r\nend\n',
    tests: [
      { fn: 'bitlen', args: [0], expected: 0 },
      { fn: 'bitlen', args: [1], expected: 1 },
      { fn: 'bitlen', args: [2], expected: 2 },
      { fn: 'bitlen', args: [3], expected: 2 },
      { fn: 'bitlen', args: [4], expected: 3 },
      { fn: 'bitlen', args: [255], expected: 8 },
      { fn: 'bitlen', args: [256], expected: 9 },
      { fn: 'bitlen', args: [2147483648], expected: 32 },
      { fn: 'bitlen', args: [4294967295], expected: 32 },
      { fn: 'bitlen', args: [1073741824], expected: 31 },
    ],
    reference: {
      a0: 'fn bstep u32 u32 u32 -> u32\na shr p2 p1\nn ne a 0\nk add p1 1\nr select n k p0\nret r\nend\nfn bitlen u32 -> u32\nh fold bstep 32 0 p0\nr mov h\nret r\nend\n',
    },
    wrongEdits: [
      'fn bstep u32 u32 u32 -> u32\na shr p2 p1\nn gt a 1\nk add p1 1\nr select n k p0\nret r\nend\nfn bitlen u32 -> u32\nh fold bstep 32 0 p0\nr mov h\nret r\nend\n',
      'fn bstep u32 u32 u32 -> u32\na shr p2 p1\nn ne a 0\nk add p1 1\nr select n k p0\nret r\nend\nfn bitlen u32 -> u32\nh fold bstep 31 0 p0\nr mov h\nret r\nend\n',
    ],
  },
  {
    id: 'k-adjacent-equal',
    kind: 'comprehension-edit',
    target: 'pairs_eq',
    wrongEditKind: 'fold-bound',
    note: "Start's fold also compares element 3 with element 0 because the index wraps.",
    instruction:
      'Count the neighbouring positions (0,1), (1,2) and (2,3) whose elements are equal; the last element must not be compared with the first.',
    a0Source:
      'fn pstep u32 u32 u32x4 -> u32\na get p2 p1\nj add p1 1\nb get p2 j\ne eq a b\ni add p0 1\nr select e i p0\nret r\nend\nfn pairs_eq u32x4 -> u32\nh fold pstep 4 0 p0\nr mov h\nret r\nend\n',
    tests: [
      { fn: 'pairs_eq', args: [[0, 0, 0, 0]], expected: 3 },
      { fn: 'pairs_eq', args: [[1, 2, 3, 4]], expected: 0 },
      { fn: 'pairs_eq', args: [[1, 2, 3, 1]], expected: 0 },
      { fn: 'pairs_eq', args: [[5, 5, 6, 6]], expected: 2 },
      { fn: 'pairs_eq', args: [[7, 8, 8, 9]], expected: 1 },
      { fn: 'pairs_eq', args: [[1, 2, 3, 3]], expected: 1 },
      { fn: 'pairs_eq', args: [[4294967295, 0, 0, 4294967295]], expected: 1 },
      { fn: 'pairs_eq', args: [[4, 4, 4, 5]], expected: 2 },
    ],
    reference: {
      a0: 'fn pstep u32 u32 u32x4 -> u32\na get p2 p1\nj add p1 1\nb get p2 j\ne eq a b\ni add p0 1\nr select e i p0\nret r\nend\nfn pairs_eq u32x4 -> u32\nh fold pstep 3 0 p0\nr mov h\nret r\nend\n',
    },
    wrongEdits: [
      'fn pstep u32 u32 u32x4 -> u32\na get p2 p1\nj add p1 1\nb get p2 j\ne eq a b\ni add p0 1\nr select e i p0\nret r\nend\nfn pairs_eq u32x4 -> u32\nh fold pstep 2 0 p0\nr mov h\nret r\nend\n',
    ],
  },
  {
    id: 'k-strictly-ascending',
    kind: 'comprehension-edit',
    target: 'ascending',
    wrongEditKind: 'comparison',
    note: 'Start accepts equal neighbours; the edit is in the step helper.',
    instruction:
      'Return true only when every element is strictly smaller than the next one; equal neighbours make the result false.',
    a0Source:
      'fn istep bool u32 u32x4 -> bool\na get p2 p1\nj add p1 1\nb get p2 j\nc le a b\nr and p0 c\nret r\nend\nfn ascending u32x4 -> bool\nh fold istep 3 true p0\nr mov h\nret r\nend\n',
    tests: [
      { fn: 'ascending', args: [[1, 2, 3, 4]], expected: true },
      { fn: 'ascending', args: [[1, 1, 2, 3]], expected: false },
      { fn: 'ascending', args: [[1, 2, 3, 3]], expected: false },
      { fn: 'ascending', args: [[0, 0, 0, 0]], expected: false },
      { fn: 'ascending', args: [[4, 3, 2, 1]], expected: false },
      { fn: 'ascending', args: [[0, 1, 2, 4294967295]], expected: true },
      { fn: 'ascending', args: [[0, 5, 5, 9]], expected: false },
      { fn: 'ascending', args: [[1, 2, 2, 3]], expected: false },
      { fn: 'ascending', args: [[4294967295, 0, 1, 2]], expected: false },
    ],
    reference: {
      a0: 'fn istep bool u32 u32x4 -> bool\na get p2 p1\nj add p1 1\nb get p2 j\nc lt a b\nr and p0 c\nret r\nend\nfn ascending u32x4 -> bool\nh fold istep 3 true p0\nr mov h\nret r\nend\n',
    },
    wrongEdits: [
      'fn istep bool u32 u32x4 -> bool\na get p2 p1\nj add p1 1\nb get p2 j\nc lt a b\nr and p0 c\nret r\nend\nfn ascending u32x4 -> bool\nh fold istep 2 true p0\nr mov h\nret r\nend\n',
      'fn istep bool u32 u32x4 -> bool\na get p2 p1\nj add p1 1\nb get p2 j\nc lt a b\nr and p0 c\nret r\nend\nfn ascending u32x4 -> bool\nh fold istep 4 true p0\nr mov h\nret r\nend\n',
    ],
  },
];
