/**
 * Held-out task set T (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-t/t-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-t.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskT {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_T: readonly TaskT[] = [
  {
    id: 't-covers-mask',
    kind: 'targeted-edit',
    target: 'covers',
    wrongEditKind: 'swapped-argument',
    note: 'Start returns the negation; the wrong edit compares the masked value with the first argument (the reverse containment).',
    instruction:
      'The function should return true exactly when every bit set in the second argument is also set in the first argument.',
    a0Source: 'fn covers u32 u32 -> bool\na and p0 p1\nb ne a p1\nret b\nend\n',
    tests: [
      { fn: 'covers', args: [15, 5], expected: true },
      { fn: 'covers', args: [15, 16], expected: false },
      { fn: 'covers', args: [0, 0], expected: true },
      { fn: 'covers', args: [8, 12], expected: false },
      { fn: 'covers', args: [4294967295, 4294967295], expected: true },
      { fn: 'covers', args: [0, 1], expected: false },
      { fn: 'covers', args: [6, 6], expected: true },
      { fn: 'covers', args: [2147483648, 2147483649], expected: false },
      { fn: 'covers', args: [1, 0], expected: true },
    ],
    reference: { a0: 'fn covers u32 u32 -> bool\na and p0 p1\nb eq a p1\nret b\nend\n' },
    wrongEdits: ['fn covers u32 u32 -> bool\na and p0 p1\nb eq a p0\nret b\nend\n'],
  },
  {
    id: 't-triangle-sides',
    kind: 'targeted-edit',
    target: 'tri',
    wrongEditKind: 'comparison',
    note: 'Lengths kept small so no addition wraps; a degenerate case on each side.',
    instruction:
      'Return true when the three lengths form a non-degenerate triangle: each pair of sides must sum to strictly more than the third side.',
    a0Source:
      'fn tri u32 u32 u32 -> bool\na add p0 p1\nb add p0 p2\nc add p1 p2\nd gt a p2\ne ge b p1\ng gt c p0\nh and d e\nk and h g\nret k\nend\n',
    tests: [
      { fn: 'tri', args: [3, 4, 5], expected: true },
      { fn: 'tri', args: [1, 2, 3], expected: false },
      { fn: 'tri', args: [1, 3, 2], expected: false },
      { fn: 'tri', args: [2, 1, 3], expected: false },
      { fn: 'tri', args: [5, 5, 5], expected: true },
      { fn: 'tri', args: [0, 0, 0], expected: false },
      { fn: 'tri', args: [1, 1, 1], expected: true },
      { fn: 'tri', args: [2, 9, 7], expected: false },
      { fn: 'tri', args: [10, 1, 1], expected: false },
      { fn: 'tri', args: [4, 7, 3], expected: false },
      { fn: 'tri', args: [4, 1, 3], expected: false },
    ],
    reference: {
      a0: 'fn tri u32 u32 u32 -> bool\na add p0 p1\nb add p0 p2\nc add p1 p2\nd gt a p2\ne gt b p1\ng gt c p0\nh and d e\nk and h g\nret k\nend\n',
    },
    wrongEdits: [
      'fn tri u32 u32 u32 -> bool\na add p0 p1\nb add p0 p2\nc add p1 p2\nd ge a p2\ne gt b p1\ng gt c p0\nh and d e\nk and h g\nret k\nend\n',
      'fn tri u32 u32 u32 -> bool\na add p0 p1\nb add p0 p2\nc add p1 p2\nd gt a p2\ne gt b p1\ng ge c p0\nh and d e\nk and h g\nret k\nend\n',
    ],
  },
  {
    id: 't-two-of-three',
    kind: 'targeted-edit',
    target: 'maj',
    wrongEditKind: 'logic-operator',
    note: 'Start uses exclusive or for the final combine, wrong when all three are true.',
    instruction: 'Return true when at least two of the three flags are true.',
    a0Source:
      'fn maj bool bool bool -> bool\na and p0 p1\nb and p0 p2\nc and p1 p2\nd or a b\ne xor d c\nret e\nend\n',
    tests: [
      { fn: 'maj', args: [false, false, false], expected: false },
      { fn: 'maj', args: [false, false, true], expected: false },
      { fn: 'maj', args: [false, true, false], expected: false },
      { fn: 'maj', args: [false, true, true], expected: true },
      { fn: 'maj', args: [true, false, false], expected: false },
      { fn: 'maj', args: [true, false, true], expected: true },
      { fn: 'maj', args: [true, true, false], expected: true },
      { fn: 'maj', args: [true, true, true], expected: true },
    ],
    reference: {
      a0: 'fn maj bool bool bool -> bool\na and p0 p1\nb and p0 p2\nc and p1 p2\nd or a b\ne or d c\nret e\nend\n',
    },
    wrongEdits: [
      'fn maj bool bool bool -> bool\na and p0 p1\nb and p0 p2\nc and p1 p2\nd or a b\ne and d c\nret e\nend\n',
    ],
  },
  {
    id: 't-offset-series',
    kind: 'targeted-edit',
    target: 'run',
    wrongEditKind: 'fold-bound',
    note: 'Seven terms; large inputs wrap.',
    instruction:
      'The function should add up p0+i for every i from 0 through 6 inclusive (seven terms), with wrapping addition.',
    a0Source:
      'fn step u32 u32 u32 -> u32\na add p2 p1\nb add p0 a\nret b\nend\nfn run u32 -> u32\na fold step 6 0 p0\nret a\nend\n',
    tests: [
      { fn: 'run', args: [0], expected: 21 },
      { fn: 'run', args: [1], expected: 28 },
      { fn: 'run', args: [10], expected: 91 },
      { fn: 'run', args: [100], expected: 721 },
      { fn: 'run', args: [4294967295], expected: 14 },
      { fn: 'run', args: [4294967292], expected: 4294967289 },
      { fn: 'run', args: [613566756], expected: 17 },
      { fn: 'run', args: [613566757], expected: 24 },
      { fn: 'run', args: [2147483648], expected: 2147483669 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32 -> u32\na add p2 p1\nb add p0 a\nret b\nend\nfn run u32 -> u32\na fold step 7 0 p0\nret a\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32 -> u32\na add p2 p1\nb add p0 a\nret b\nend\nfn run u32 -> u32\na fold step 8 0 p0\nret a\nend\n',
    ],
  },
  {
    id: 't-first-largest-index',
    kind: 'comprehension-edit',
    target: 'argmax',
    wrongEditKind: 'comparison',
    note: 'Ties expose ge versus gt.',
    instruction:
      'The function returns the position of the largest element; when the largest value occurs more than once it must return the earliest such position.',
    a0Source:
      'fn pick u32 u32 u32x4 -> u32\na get p2 p1\nb get p2 p0\nc ge a b\nd select c p1 p0\nret d\nend\nfn argmax u32x4 -> u32\na fold pick 4 0 p0\nret a\nend\n',
    tests: [
      { fn: 'argmax', args: [[1, 2, 3, 4]], expected: 3 },
      { fn: 'argmax', args: [[4, 3, 2, 1]], expected: 0 },
      { fn: 'argmax', args: [[5, 5, 5, 5]], expected: 0 },
      { fn: 'argmax', args: [[0, 7, 7, 1]], expected: 1 },
      { fn: 'argmax', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'argmax', args: [[2, 9, 3, 9]], expected: 1 },
      { fn: 'argmax', args: [[4294967295, 1, 4294967295, 0]], expected: 0 },
      { fn: 'argmax', args: [[1, 2, 2, 1]], expected: 1 },
    ],
    reference: {
      a0: 'fn pick u32 u32 u32x4 -> u32\na get p2 p1\nb get p2 p0\nc gt a b\nd select c p1 p0\nret d\nend\nfn argmax u32x4 -> u32\na fold pick 4 0 p0\nret a\nend\n',
    },
    wrongEdits: [
      'fn pick u32 u32 u32x4 -> u32\na get p2 p1\nb get p2 p0\nc lt a b\nd select c p1 p0\nret d\nend\nfn argmax u32x4 -> u32\na fold pick 4 0 p0\nret a\nend\n',
    ],
  },
  {
    id: 't-fill-two',
    kind: 'multi-node-edit',
    target: 'fill2',
    wrongEditKind: 'off-by-one',
    note: 'Positions are taken modulo 4, which handles the wrap.',
    instruction:
      'Besides writing the value at the given position, also write it at the next position (wrapping from the last position back to the first).',
    a0Source: 'fn fill2 u32x4 u32 u32 -> u32x4\na set p0 p1 p2\nret a\nend\n',
    tests: [
      { fn: 'fill2', args: [[1, 2, 3, 4], 0, 9], expected: [9, 9, 3, 4] },
      { fn: 'fill2', args: [[1, 2, 3, 4], 3, 9], expected: [9, 2, 3, 9] },
      { fn: 'fill2', args: [[0, 0, 0, 0], 1, 5], expected: [0, 5, 5, 0] },
      { fn: 'fill2', args: [[5, 6, 7, 8], 2, 0], expected: [5, 6, 0, 0] },
      { fn: 'fill2', args: [[1, 1, 1, 1], 4, 2], expected: [2, 2, 1, 1] },
      {
        fn: 'fill2',
        args: [[9, 8, 7, 6], 7, 4294967295],
        expected: [4294967295, 8, 7, 4294967295],
      },
      { fn: 'fill2', args: [[1, 2, 3, 4], 5, 0], expected: [1, 0, 0, 4] },
      { fn: 'fill2', args: [[0, 0, 0, 0], 2, 3], expected: [0, 0, 3, 3] },
    ],
    reference: {
      a0: 'fn fill2 u32x4 u32 u32 -> u32x4\na set p0 p1 p2\nb add p1 1\nc set a b p2\nret c\nend\n',
    },
    wrongEdits: [
      'fn fill2 u32x4 u32 u32 -> u32x4\na set p0 p1 p2\nb add p1 2\nc set a b p2\nret c\nend\n',
    ],
  },
  {
    id: 't-matching-slots',
    kind: 'comprehension-edit',
    target: 'same',
    wrongEditKind: 'fold-bound',
    note: 'The last slot matters for the fold count.',
    instruction:
      'The function should count the positions at which the two arrays hold equal values.',
    a0Source:
      'fn tally u32 u32 u32x4 u32x4 -> u32\na get p2 p1\nb get p3 p1\nc ne a b\nd add p0 1\ne select c d p0\nret e\nend\nfn same u32x4 u32x4 -> u32\na fold tally 4 0 p0 p1\nret a\nend\n',
    tests: [
      {
        fn: 'same',
        args: [
          [1, 2, 3, 4],
          [1, 2, 3, 4],
        ],
        expected: 4,
      },
      {
        fn: 'same',
        args: [
          [1, 2, 3, 4],
          [4, 3, 2, 1],
        ],
        expected: 0,
      },
      {
        fn: 'same',
        args: [
          [0, 0, 0, 0],
          [0, 0, 0, 1],
        ],
        expected: 3,
      },
      {
        fn: 'same',
        args: [
          [5, 6, 7, 8],
          [5, 0, 7, 0],
        ],
        expected: 2,
      },
      {
        fn: 'same',
        args: [
          [1, 1, 1, 1],
          [2, 2, 2, 2],
        ],
        expected: 0,
      },
      {
        fn: 'same',
        args: [
          [4294967295, 0, 4294967295, 0],
          [4294967295, 1, 4294967295, 1],
        ],
        expected: 2,
      },
      {
        fn: 'same',
        args: [
          [1, 2, 3, 9],
          [0, 2, 0, 9],
        ],
        expected: 2,
      },
      {
        fn: 'same',
        args: [
          [3, 3, 3, 3],
          [3, 3, 3, 3],
        ],
        expected: 4,
      },
    ],
    reference: {
      a0: 'fn tally u32 u32 u32x4 u32x4 -> u32\na get p2 p1\nb get p3 p1\nc eq a b\nd add p0 1\ne select c d p0\nret e\nend\nfn same u32x4 u32x4 -> u32\na fold tally 4 0 p0 p1\nret a\nend\n',
    },
    wrongEdits: [
      'fn tally u32 u32 u32x4 u32x4 -> u32\na get p2 p1\nb get p3 p1\nc eq a b\nd add p0 1\ne select c d p0\nret e\nend\nfn same u32x4 u32x4 -> u32\na fold tally 3 0 p0 p1\nret a\nend\n',
    ],
  },
  {
    id: 't-keep-low-bits',
    kind: 'multi-node-edit',
    target: 'low',
    wrongEditKind: 'wrapping',
    note: 'Shift distance wraps at 32, so the start yields 0 for 32 and wrong masks above.',
    instruction:
      'Keep only the lowest p1 bits of p0; when p1 is 32 or more the whole value must be kept.',
    a0Source: 'fn low u32 u32 -> u32\nb shl 1 p1\nc sub b 1\nd and p0 c\nret d\nend\n',
    tests: [
      { fn: 'low', args: [4294967295, 0], expected: 0 },
      { fn: 'low', args: [4294967295, 1], expected: 1 },
      { fn: 'low', args: [4294967295, 31], expected: 2147483647 },
      { fn: 'low', args: [4294967295, 32], expected: 4294967295 },
      { fn: 'low', args: [4294967295, 33], expected: 4294967295 },
      { fn: 'low', args: [255, 4], expected: 15 },
      { fn: 'low', args: [2147483653, 40], expected: 2147483653 },
      { fn: 'low', args: [12345, 64], expected: 12345 },
      { fn: 'low', args: [6, 2], expected: 2 },
    ],
    reference: {
      a0: 'fn low u32 u32 -> u32\nb shl 1 p1\nc sub b 1\nd and p0 c\na ge p1 32\ne select a p0 d\nret e\nend\n',
    },
    wrongEdits: [
      'fn low u32 u32 -> u32\nb shl 1 p1\nc sub b 1\nd and p0 c\na gt p1 32\ne select a p0 d\nret e\nend\n',
    ],
  },
  {
    id: 't-checked-product',
    kind: 'multi-node-edit',
    target: 'mulchk',
    wrongEditKind: 'logic-operator',
    note: 'Division by zero gives all ones, which wrongly flagged zero factors.',
    instruction:
      'Return the wrapped product and a flag that is true only when the true product does not fit in 32 bits; a zero first factor must never report overflow.',
    a0Source:
      'fn mulchk u32 u32 -> (u32,bool)\na mul p0 p1\nb div a p0\nc ne b p1\ng rec a c\nret g\nend\n',
    tests: [
      { fn: 'mulchk', args: [0, 5], expected: [0, false] },
      { fn: 'mulchk', args: [0, 0], expected: [0, false] },
      { fn: 'mulchk', args: [3, 4], expected: [12, false] },
      { fn: 'mulchk', args: [65536, 65536], expected: [0, true] },
      { fn: 'mulchk', args: [65535, 65537], expected: [4294967295, false] },
      { fn: 'mulchk', args: [65536, 65535], expected: [4294901760, false] },
      { fn: 'mulchk', args: [4294967295, 2], expected: [4294967294, true] },
      { fn: 'mulchk', args: [1, 4294967295], expected: [4294967295, false] },
      { fn: 'mulchk', args: [2, 2147483648], expected: [0, true] },
      { fn: 'mulchk', args: [0, 4294967295], expected: [0, false] },
    ],
    reference: {
      a0: 'fn mulchk u32 u32 -> (u32,bool)\na mul p0 p1\nb div a p0\nc ne b p1\nd ne p0 0\ne and d c\ng rec a e\nret g\nend\n',
    },
    wrongEdits: [
      'fn mulchk u32 u32 -> (u32,bool)\na mul p0 p1\nb div a p0\nc ne b p1\nd ne p0 0\ne or d c\ng rec a e\nret g\nend\n',
    ],
  },
  {
    id: 't-tick-millis',
    kind: 'targeted-edit',
    target: 'ms',
    wrongEditKind: 'changed-constant',
    note: 'The product wraps for large tick counts, matching the stated arithmetic.',
    instruction:
      'The timer now runs at 1024 ticks per second instead of 1000; convert a tick count to whole milliseconds (multiply first, with wrapping, then round down).',
    a0Source: 'fn ms u32 -> u32\na mul p0 1000\nb div a 1000\nret b\nend\n',
    tests: [
      { fn: 'ms', args: [0], expected: 0 },
      { fn: 'ms', args: [1], expected: 0 },
      { fn: 'ms', args: [1024], expected: 1000 },
      { fn: 'ms', args: [2048], expected: 2000 },
      { fn: 'ms', args: [1023], expected: 999 },
      { fn: 'ms', args: [5000], expected: 4882 },
      { fn: 'ms', args: [4294967], expected: 4194303 },
      { fn: 'ms', args: [4294968], expected: 0 },
      { fn: 'ms', args: [100], expected: 97 },
    ],
    reference: { a0: 'fn ms u32 -> u32\na mul p0 1000\nb div a 1024\nret b\nend\n' },
    wrongEdits: ['fn ms u32 -> u32\na mul p0 1024\nb div a 1000\nret b\nend\n'],
  },
  {
    id: 't-binary-digits',
    kind: 'comprehension-edit',
    target: 'digits',
    wrongEditKind: 'swapped-argument',
    note: 'The helper is one Horner step.',
    instruction:
      'The function should read the array as four base-2 digits with the first element most significant, returning 8*a0 + 4*a1 + 2*a2 + a3 (wrapping).',
    a0Source:
      'fn h u32 u32 -> u32\na mul p0 2\nb add a p1\nret b\nend\nfn digits u32x4 -> u32\ng0 get p0 0\ng1 get p0 1\ng2 get p0 2\ng3 get p0 3\nc0 call h 0 g0\nc1 call h c0 g1\nc2 call h g2 c1\nc3 call h c2 g3\nret c3\nend\n',
    tests: [
      { fn: 'digits', args: [[1, 0, 0, 0]], expected: 8 },
      { fn: 'digits', args: [[0, 0, 0, 1]], expected: 1 },
      { fn: 'digits', args: [[1, 0, 1, 1]], expected: 11 },
      { fn: 'digits', args: [[0, 1, 0, 0]], expected: 4 },
      { fn: 'digits', args: [[0, 0, 1, 0]], expected: 2 },
      { fn: 'digits', args: [[1, 1, 1, 1]], expected: 15 },
      { fn: 'digits', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'digits', args: [[3, 0, 5, 2]], expected: 36 },
      { fn: 'digits', args: [[2147483648, 0, 0, 1]], expected: 1 },
    ],
    reference: {
      a0: 'fn h u32 u32 -> u32\na mul p0 2\nb add a p1\nret b\nend\nfn digits u32x4 -> u32\ng0 get p0 0\ng1 get p0 1\ng2 get p0 2\ng3 get p0 3\nc0 call h 0 g0\nc1 call h c0 g1\nc2 call h c1 g2\nc3 call h c2 g3\nret c3\nend\n',
    },
    wrongEdits: [
      'fn h u32 u32 -> u32\na mul p0 2\nb add a p1\nret b\nend\nfn digits u32x4 -> u32\ng0 get p0 0\ng1 get p0 1\ng2 get p0 2\ng3 get p0 3\nc0 call h 0 g3\nc1 call h c0 g2\nc2 call h c1 g1\nc3 call h c2 g0\nret c3\nend\n',
    ],
  },
  {
    id: 't-hailstone-five',
    kind: 'comprehension-edit',
    target: 'hops',
    wrongEditKind: 'changed-constant',
    note: 'Start multiplies odd values by 2.',
    instruction:
      'Apply the hailstone step five times: halve an even value, otherwise replace it with three times the value plus one (wrapping).',
    a0Source:
      'fn hop u32 u32 -> u32\na and p0 1\nb eq a 0\nc shr p0 1\nd mul p0 2\ne add d 1\ng select b c e\nret g\nend\nfn hops u32 -> u32\na fold hop 5 p0\nret a\nend\n',
    tests: [
      { fn: 'hops', args: [1], expected: 2 },
      { fn: 'hops', args: [2], expected: 4 },
      { fn: 'hops', args: [3], expected: 4 },
      { fn: 'hops', args: [7], expected: 52 },
      { fn: 'hops', args: [27], expected: 31 },
      { fn: 'hops', args: [16], expected: 4 },
      { fn: 'hops', args: [0], expected: 0 },
      { fn: 'hops', args: [1431655765], expected: 0 },
      { fn: 'hops', args: [4294967295], expected: 3221225470 },
    ],
    reference: {
      a0: 'fn hop u32 u32 -> u32\na and p0 1\nb eq a 0\nc shr p0 1\nd mul p0 3\ne add d 1\ng select b c e\nret g\nend\nfn hops u32 -> u32\na fold hop 5 p0\nret a\nend\n',
    },
    wrongEdits: [
      'fn hop u32 u32 -> u32\na and p0 1\nb eq a 0\nc shr p0 1\nd mul p0 3\ne add d 1\ng select b c e\nret g\nend\nfn hops u32 -> u32\na fold hop 4 p0\nret a\nend\n',
    ],
  },
  {
    id: 't-neighbour-sum',
    kind: 'targeted-edit',
    target: 'pairsum',
    wrongEditKind: 'logic-operator',
    note: 'Each neighbour pair is the only match in some test.',
    instruction:
      'Return true when any two neighbouring elements of the array add up (with wrapping) to the target.',
    a0Source:
      'fn pairsum u32x4 u32 -> bool\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ne add a b\ng add b c\nh add c d\nk eq e p1\nm eq g p1\nn eq h p1\nq or k m\nr and q n\nret r\nend\n',
    tests: [
      { fn: 'pairsum', args: [[1, 2, 3, 4], 3], expected: true },
      { fn: 'pairsum', args: [[1, 2, 3, 4], 5], expected: true },
      { fn: 'pairsum', args: [[1, 2, 3, 4], 7], expected: true },
      { fn: 'pairsum', args: [[1, 2, 3, 4], 4], expected: false },
      { fn: 'pairsum', args: [[0, 0, 0, 0], 0], expected: true },
      { fn: 'pairsum', args: [[4294967295, 1, 5, 5], 0], expected: true },
      { fn: 'pairsum', args: [[2, 2, 2, 2], 5], expected: false },
      { fn: 'pairsum', args: [[1, 1, 9, 9], 18], expected: true },
      { fn: 'pairsum', args: [[9, 9, 1, 1], 18], expected: true },
    ],
    reference: {
      a0: 'fn pairsum u32x4 u32 -> bool\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ne add a b\ng add b c\nh add c d\nk eq e p1\nm eq g p1\nn eq h p1\nq or k m\nr or q n\nret r\nend\n',
    },
    wrongEdits: [
      'fn pairsum u32x4 u32 -> bool\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\ne add a b\ng add b c\nh add c d\nk eq e p1\nm eq g p1\nn eq h p1\nq and k m\nr or q n\nret r\nend\n',
    ],
  },
  {
    id: 't-signed-less',
    kind: 'multi-node-edit',
    target: 'sless',
    wrongEditKind: 'bit-manipulation',
    note: 'Flipping the sign bit of both operands maps signed order onto unsigned order.',
    instruction:
      "Compare the two values as two's-complement signed numbers: return true when the first is less than the second.",
    a0Source: 'fn sless u32 u32 -> bool\na mov p0\nb mov p1\nc lt a b\nret c\nend\n',
    tests: [
      { fn: 'sless', args: [1, 2], expected: true },
      { fn: 'sless', args: [2, 1], expected: false },
      { fn: 'sless', args: [4294967295, 0], expected: true },
      { fn: 'sless', args: [0, 4294967295], expected: false },
      { fn: 'sless', args: [2147483648, 2147483647], expected: true },
      { fn: 'sless', args: [2147483647, 2147483648], expected: false },
      { fn: 'sless', args: [4294967295, 4294967295], expected: false },
      { fn: 'sless', args: [2147483648, 0], expected: true },
      { fn: 'sless', args: [5, 5], expected: false },
      { fn: 'sless', args: [0, 1], expected: true },
    ],
    reference: {
      a0: 'fn sless u32 u32 -> bool\na xor p0 2147483648\nb xor p1 2147483648\nc lt a b\nret c\nend\n',
    },
    wrongEdits: ['fn sless u32 u32 -> bool\na xor p0 2147483648\nb mov p1\nc lt a b\nret c\nend\n'],
  },
  {
    id: 't-nibble-field',
    kind: 'targeted-edit',
    target: 'field',
    wrongEditKind: 'changed-constant',
    note: 'Shift distance uses the low five bits.',
    instruction:
      'Return the four-bit field of p0 that starts at bit position p1 (bits p1 to p1+3), using only the low five bits of p1.',
    a0Source: 'fn field u32 u32 -> u32\na shr p0 p1\nb and a 7\nret b\nend\n',
    tests: [
      { fn: 'field', args: [240, 4], expected: 15 },
      { fn: 'field', args: [240, 0], expected: 0 },
      { fn: 'field', args: [255, 0], expected: 15 },
      { fn: 'field', args: [2147483648, 28], expected: 8 },
      { fn: 'field', args: [4294967295, 31], expected: 1 },
      { fn: 'field', args: [4660, 8], expected: 2 },
      { fn: 'field', args: [8, 0], expected: 8 },
      { fn: 'field', args: [165, 36], expected: 10 },
      { fn: 'field', args: [0, 5], expected: 0 },
    ],
    reference: { a0: 'fn field u32 u32 -> u32\na shr p0 p1\nb and a 15\nret b\nend\n' },
    wrongEdits: ['fn field u32 u32 -> u32\na shl p0 p1\nb and a 15\nret b\nend\n'],
  },
  {
    id: 't-split-top-bit',
    kind: 'targeted-edit',
    target: 'split',
    wrongEditKind: 'off-by-one',
    note: 'Exactly 2^31 is the boundary.',
    instruction:
      'Return the value with its top bit cleared, together with a flag telling whether the top bit was set.',
    a0Source:
      'fn split u32 -> (u32,bool)\na and p0 2147483647\nb gt p0 2147483648\nc rec a b\nret c\nend\n',
    tests: [
      { fn: 'split', args: [0], expected: [0, false] },
      { fn: 'split', args: [1], expected: [1, false] },
      { fn: 'split', args: [2147483647], expected: [2147483647, false] },
      { fn: 'split', args: [2147483648], expected: [0, true] },
      { fn: 'split', args: [2147483649], expected: [1, true] },
      { fn: 'split', args: [4294967295], expected: [2147483647, true] },
      { fn: 'split', args: [12345], expected: [12345, false] },
      { fn: 'split', args: [2147495993], expected: [12345, true] },
    ],
    reference: {
      a0: 'fn split u32 -> (u32,bool)\na and p0 2147483647\nb ge p0 2147483648\nc rec a b\nret c\nend\n',
    },
    wrongEdits: [
      'fn split u32 -> (u32,bool)\na and p0 2147483647\nb eq p0 2147483648\nc rec a b\nret c\nend\n',
    ],
  },
];
