/**
 * Held-out task set R (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-r/r-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-r.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskR {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_R: readonly TaskR[] = [
  {
    id: 'r-bucket-index',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'zero-divisor',
    note: 'Zero divisor in div yields all ones; the edit must map it to 0.',
    instruction:
      'Return the bucket number of value p0 for buckets of width p1 (p0 divided by p1, rounded down). When the width p1 is 0, return 0 instead.',
    a0Source: 'fn f u32 u32 -> u32\nq div p0 p1\nr mov q\nret r\nend\n',
    tests: [
      { fn: 'f', args: [10, 3], expected: 3 },
      { fn: 'f', args: [9, 3], expected: 3 },
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [7, 0], expected: 0 },
      { fn: 'f', args: [4294967295, 0], expected: 0 },
      { fn: 'f', args: [4294967295, 1], expected: 4294967295 },
      { fn: 'f', args: [2, 5], expected: 0 },
      { fn: 'f', args: [5, 5], expected: 1 },
      { fn: 'f', args: [0, 7], expected: 0 },
      { fn: 'f', args: [100, 1], expected: 100 },
    ],
    reference: { a0: 'fn f u32 u32 -> u32\nz eq p1 0\nq div p0 p1\nr select z 0 q\nret r\nend\n' },
    wrongEdits: [
      'fn f u32 u32 -> u32\nz eq p1 0\nq div p0 p1\nr select z p0 q\nret r\nend\n',
      'fn f u32 u32 -> u32\nz eq p0 0\nq div p0 p1\nr select z 0 q\nret r\nend\n',
    ],
  },
  {
    id: 'r-field-extract',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Mask must be 15; start keeps only 3 bits.',
    instruction:
      'Return the 4-bit field held in bits 4 to 7 of p0 (bit 0 is the lowest), as a number from 0 to 15.',
    a0Source: 'fn f u32 -> u32\ns shr p0 4\nm and s 7\nret m\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [15], expected: 0 },
      { fn: 'f', args: [16], expected: 1 },
      { fn: 'f', args: [240], expected: 15 },
      { fn: 'f', args: [255], expected: 15 },
      { fn: 'f', args: [128], expected: 8 },
      { fn: 'f', args: [4294967295], expected: 15 },
      { fn: 'f', args: [305419896], expected: 7 },
      { fn: 'f', args: [128], expected: 8 },
      { fn: 'f', args: [256], expected: 0 },
    ],
    reference: { a0: 'fn f u32 -> u32\ns shr p0 4\nm and s 15\nret m\nend\n' },
    wrongEdits: [
      'fn f u32 -> u32\ns shr p0 3\nm and s 15\nret m\nend\n',
      'fn f u32 -> u32\ns shr p0 4\nm and s 16\nret m\nend\n',
    ],
  },
  {
    id: 'r-is-multiple',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'rem with zero divisor gives the dividend.',
    instruction:
      'Return true when p0 is an exact multiple of p1 (p0 leaves no remainder when divided by p1). With p1 equal to 0, remainder of p0 is p0 itself, so only p0 = 0 counts.',
    a0Source: 'fn f u32 u32 -> bool\nr rem p0 p1\nb ne r 0\nret b\nend\n',
    tests: [
      { fn: 'f', args: [6, 3], expected: true },
      { fn: 'f', args: [7, 3], expected: false },
      { fn: 'f', args: [0, 0], expected: true },
      { fn: 'f', args: [5, 0], expected: false },
      { fn: 'f', args: [0, 5], expected: true },
      { fn: 'f', args: [3, 6], expected: false },
      { fn: 'f', args: [4294967295, 5], expected: true },
      { fn: 'f', args: [4294967295, 4294967295], expected: true },
      { fn: 'f', args: [1, 1], expected: true },
      { fn: 'f', args: [12, 4], expected: true },
    ],
    reference: { a0: 'fn f u32 u32 -> bool\nr rem p0 p1\nb eq r 0\nret b\nend\n' },
    wrongEdits: ['fn f u32 u32 -> bool\nr rem p1 p0\nb eq r 0\nret b\nend\n'],
  },
  {
    id: 'r-slot-write',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Index wraps modulo 4.',
    instruction:
      'Return a copy of the array p0 with the element at position p1 (taken modulo 4) replaced by the value p2.',
    a0Source: 'fn f u32x4 u32 u32 -> u32x4\ni add p1 1\na set p0 i p2\nret a\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 0, 9], expected: [9, 2, 3, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 3, 9], expected: [1, 2, 3, 9] },
      { fn: 'f', args: [[1, 2, 3, 4], 4, 7], expected: [7, 2, 3, 4] },
      { fn: 'f', args: [[0, 0, 0, 0], 1, 5], expected: [0, 5, 0, 0] },
      { fn: 'f', args: [[5, 6, 7, 8], 2, 0], expected: [5, 6, 0, 8] },
      { fn: 'f', args: [[1, 1, 1, 1], 7, 2], expected: [1, 1, 1, 2] },
      { fn: 'f', args: [[9, 9, 9, 9], 4294967295, 1], expected: [9, 9, 9, 1] },
      { fn: 'f', args: [[1, 2, 3, 4], 1, 1], expected: [1, 1, 3, 4] },
    ],
    reference: { a0: 'fn f u32x4 u32 u32 -> u32x4\ni mov p1\na set p0 i p2\nret a\nend\n' },
    wrongEdits: ['fn f u32x4 u32 u32 -> u32x4\ni mov p2\na set p0 i p1\nret a\nend\n'],
  },
  {
    id: 'r-product-all',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Fold count must cover all four elements; init must be 1.',
    instruction:
      'The function should return the product of all four elements of the array p0 (wrapping modulo 2^32); currently it misses one element.',
    a0Source:
      'fn step u32 u32 u32x4 -> u32\ne get p2 p1\nm mul p0 e\nret m\nend\nfn f u32x4 -> u32\nq fold step 3 1 p0\nr mov q\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4]], expected: 24 },
      { fn: 'f', args: [[2, 2, 2, 2]], expected: 16 },
      { fn: 'f', args: [[5, 5, 5, 0]], expected: 0 },
      { fn: 'f', args: [[0, 1, 1, 1]], expected: 0 },
      { fn: 'f', args: [[1, 1, 1, 1]], expected: 1 },
      { fn: 'f', args: [[65536, 65536, 1, 1]], expected: 0 },
      { fn: 'f', args: [[3, 1, 1, 7]], expected: 21 },
      { fn: 'f', args: [[4294967295, 2, 1, 3]], expected: 4294967290 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32x4 -> u32\ne get p2 p1\nm mul p0 e\nret m\nend\nfn f u32x4 -> u32\nq fold step 4 1 p0\nr mov q\nret r\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32x4 -> u32\ne get p2 p1\nm mul p0 e\nret m\nend\nfn f u32x4 -> u32\nq fold step 4 0 p0\nr mov q\nret r\nend\n',
      'fn step u32 u32 u32x4 -> u32\ne get p2 p1\nm mul p0 e\nret m\nend\nfn f u32x4 -> u32\nq fold step 5 1 p0\nr mov q\nret r\nend\n',
    ],
  },
  {
    id: 'r-quorum',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Inputs kept small so doubling does not wrap.',
    instruction:
      'Return true when p0 yes-votes out of p1 total votes form a strict majority, that is twice p0 is greater than p1. A tie is not a majority.',
    a0Source: 'fn f u32 u32 -> bool\nd mul p0 2\nb ge d p1\nret b\nend\n',
    tests: [
      { fn: 'f', args: [2, 4], expected: false },
      { fn: 'f', args: [3, 4], expected: true },
      { fn: 'f', args: [1, 2], expected: false },
      { fn: 'f', args: [0, 0], expected: false },
      { fn: 'f', args: [1, 0], expected: true },
      { fn: 'f', args: [0, 1], expected: false },
      { fn: 'f', args: [5, 9], expected: true },
      { fn: 'f', args: [4, 9], expected: false },
      { fn: 'f', args: [1000, 1999], expected: true },
      { fn: 'f', args: [1000, 2000], expected: false },
    ],
    reference: { a0: 'fn f u32 u32 -> bool\nd mul p0 2\nb gt d p1\nret b\nend\n' },
    wrongEdits: ['fn f u32 u32 -> bool\nd mul p1 2\nb gt p0 d\nret b\nend\n'],
  },
  {
    id: 'r-pack-bytes',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'mask',
    note: 'Both masks needed.',
    instruction:
      'Pack the low byte of p0 into bits 8 to 15 and the low byte of p1 into bits 0 to 7; all other bits of the result must be 0. Mask both inputs to their low 8 bits.',
    a0Source: 'fn f u32 u32 -> u32\nh shl p0 8\nr or h p1\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [1, 2], expected: 258 },
      { fn: 'f', args: [255, 255], expected: 65535 },
      { fn: 'f', args: [256, 0], expected: 0 },
      { fn: 'f', args: [0, 256], expected: 0 },
      { fn: 'f', args: [4660, 22136], expected: 13432 },
      { fn: 'f', args: [4294967295, 4294967295], expected: 65535 },
      { fn: 'f', args: [128, 128], expected: 32896 },
      { fn: 'f', args: [171, 205], expected: 43981 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\na and p0 255\nb and p1 255\nh shl a 8\nr or h b\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\na and p0 255\nh shl a 8\nr or h p1\nret r\nend\n',
      'fn f u32 u32 -> u32\na and p0 127\nb and p1 127\nh shl a 8\nr or h b\nret r\nend\n',
    ],
  },
  {
    id: 'r-page-of',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'wrong-quantity',
    note: 'Zero page size: div gives all ones, rem gives p0.',
    instruction:
      "Return a record (page, starts): page is item p0's page number for pages of p1 items (p0 divided by p1), and starts is true when item p0 is the first item on its page (p0 leaves remainder 0 when divided by p1).",
    a0Source: 'fn f u32 u32 -> (u32,bool)\npg div p0 p1\ns eq p0 0\nr rec pg s\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 10], expected: [0, true] },
      { fn: 'f', args: [10, 10], expected: [1, true] },
      { fn: 'f', args: [11, 10], expected: [1, false] },
      { fn: 'f', args: [9, 10], expected: [0, false] },
      { fn: 'f', args: [25, 5], expected: [5, true] },
      { fn: 'f', args: [7, 0], expected: [4294967295, false] },
      { fn: 'f', args: [0, 0], expected: [4294967295, true] },
      { fn: 'f', args: [3, 1], expected: [3, true] },
      { fn: 'f', args: [4294967295, 4294967295], expected: [1, true] },
    ],
    reference: {
      a0: 'fn f u32 u32 -> (u32,bool)\npg div p0 p1\no rem p0 p1\ns eq o 0\nr rec pg s\nret r\nend\n',
    },
    wrongEdits: ['fn f u32 u32 -> (u32,bool)\npg div p0 p1\ns eq pg 0\nr rec pg s\nret r\nend\n'],
  },
  {
    id: 'r-both-flags',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'mask',
    note: 'Any vs both.',
    instruction: 'Return true only when both bit 0 (value 1) and bit 2 (value 4) of p0 are set.',
    a0Source: 'fn f u32 -> bool\nm and p0 5\nb ne m 0\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: false },
      { fn: 'f', args: [1], expected: false },
      { fn: 'f', args: [4], expected: false },
      { fn: 'f', args: [5], expected: true },
      { fn: 'f', args: [7], expected: true },
      { fn: 'f', args: [13], expected: true },
      { fn: 'f', args: [2], expected: false },
      { fn: 'f', args: [4294967295], expected: true },
      { fn: 'f', args: [4294967290], expected: false },
      { fn: 'f', args: [21], expected: true },
    ],
    reference: { a0: 'fn f u32 -> bool\nm and p0 5\nb eq m 5\nret b\nend\n' },
    wrongEdits: ['fn f u32 -> bool\nm and p0 5\nb ge m 4\nret b\nend\n'],
  },
  {
    id: 'r-tally-two',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: "Second bump must use the first's result and index p2.",
    instruction:
      'The function should add one to the counter at position p1 and one to the counter at position p2 of array p0 (positions modulo 4; if they are the same position it gets two). Currently it counts the wrong positions.',
    a0Source:
      'fn bump u32x4 u32 -> u32x4\nv get p0 p1\nw add v 1\na set p0 p1 w\nret a\nend\nfn f u32x4 u32 u32 -> u32x4\nx call bump p0 p1\ny call bump x p1\nret y\nend\n',
    tests: [
      { fn: 'f', args: [[0, 0, 0, 0], 0, 1], expected: [1, 1, 0, 0] },
      { fn: 'f', args: [[0, 0, 0, 0], 2, 2], expected: [0, 0, 2, 0] },
      { fn: 'f', args: [[1, 2, 3, 4], 3, 0], expected: [2, 2, 3, 5] },
      { fn: 'f', args: [[0, 0, 0, 0], 4, 5], expected: [1, 1, 0, 0] },
      { fn: 'f', args: [[4294967295, 0, 0, 0], 0, 3], expected: [0, 0, 0, 1] },
      { fn: 'f', args: [[5, 5, 5, 5], 1, 3], expected: [5, 6, 5, 6] },
      { fn: 'f', args: [[0, 0, 0, 0], 7, 7], expected: [0, 0, 0, 2] },
      { fn: 'f', args: [[9, 8, 7, 6], 2, 1], expected: [9, 9, 8, 6] },
    ],
    reference: {
      a0: 'fn bump u32x4 u32 -> u32x4\nv get p0 p1\nw add v 1\na set p0 p1 w\nret a\nend\nfn f u32x4 u32 u32 -> u32x4\nx call bump p0 p1\ny call bump x p2\nret y\nend\n',
    },
    wrongEdits: [
      'fn bump u32x4 u32 -> u32x4\nv get p0 p1\nw add v 1\na set p0 p1 w\nret a\nend\nfn f u32x4 u32 u32 -> u32x4\nx call bump p0 p1\ny call bump p0 p2\nret y\nend\n',
    ],
  },
  {
    id: 'r-percent-of',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: '42949673*100 wraps to 4.',
    instruction:
      "Return p0 as a whole-number percentage of p1: p0 times 100 (wrapping modulo 2^32), divided by p1 and rounded down; a zero p1 gives the division's all-ones result.",
    a0Source: 'fn f u32 u32 -> u32\nm mul p0 10\nq div m p1\nret q\nend\n',
    tests: [
      { fn: 'f', args: [1, 2], expected: 50 },
      { fn: 'f', args: [1, 3], expected: 33 },
      { fn: 'f', args: [50, 200], expected: 25 },
      { fn: 'f', args: [0, 5], expected: 0 },
      { fn: 'f', args: [5, 0], expected: 4294967295 },
      { fn: 'f', args: [0, 0], expected: 4294967295 },
      { fn: 'f', args: [3, 3], expected: 100 },
      { fn: 'f', args: [7, 8], expected: 87 },
      { fn: 'f', args: [42949673, 1], expected: 4 },
      { fn: 'f', args: [2, 3], expected: 66 },
    ],
    reference: { a0: 'fn f u32 u32 -> u32\nm mul p0 100\nq div m p1\nret q\nend\n' },
    wrongEdits: ['fn f u32 u32 -> u32\nd div p0 p1\nq mul d 100\nret q\nend\n'],
  },
  {
    id: 'r-mean-four',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'shift-amount',
    note: 'Sum wraps; shift by 2.',
    instruction:
      'The function should return the average of the four elements of p0, rounded down (the wrapped sum shifted right by 2 bits). Currently the divide step is wrong.',
    a0Source:
      'fn acc u32 u32 u32x4 -> u32\ne get p2 p1\ns add p0 e\nret s\nend\nfn f u32x4 -> u32\nt fold acc 4 0 p0\nr shr t 1\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'f', args: [[4, 4, 4, 4]], expected: 4 },
      { fn: 'f', args: [[1, 2, 3, 4]], expected: 2 },
      { fn: 'f', args: [[1, 1, 1, 0]], expected: 0 },
      { fn: 'f', args: [[100, 0, 0, 0]], expected: 25 },
      { fn: 'f', args: [[4294967295, 1, 0, 0]], expected: 0 },
      { fn: 'f', args: [[7, 7, 7, 7]], expected: 7 },
      { fn: 'f', args: [[8, 0, 0, 0]], expected: 2 },
    ],
    reference: {
      a0: 'fn acc u32 u32 u32x4 -> u32\ne get p2 p1\ns add p0 e\nret s\nend\nfn f u32x4 -> u32\nt fold acc 4 0 p0\nr shr t 2\nret r\nend\n',
    },
    wrongEdits: [
      'fn acc u32 u32 u32x4 -> u32\ne get p2 p1\ns add p0 e\nret s\nend\nfn f u32x4 -> u32\nt fold acc 4 0 p0\nr shr t 4\nret r\nend\n',
    ],
  },
  {
    id: 'r-larger-pick',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Start picks the smaller.',
    instruction:
      'Return whichever of the elements at positions p1 and p2 of array p0 is larger (positions modulo 4); if they are equal return that value.',
    a0Source:
      'fn f u32x4 u32 u32 -> u32\nx get p0 p1\ny get p0 p2\nc lt x y\nr select c x y\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 0, 3], expected: 4 },
      { fn: 'f', args: [[1, 2, 3, 4], 3, 0], expected: 4 },
      { fn: 'f', args: [[5, 5, 5, 5], 1, 2], expected: 5 },
      { fn: 'f', args: [[0, 4294967295, 0, 0], 0, 1], expected: 4294967295 },
      { fn: 'f', args: [[9, 1, 1, 1], 4, 1], expected: 9 },
      { fn: 'f', args: [[1, 8, 2, 3], 5, 6], expected: 8 },
      { fn: 'f', args: [[3, 3, 1, 1], 0, 1], expected: 3 },
      { fn: 'f', args: [[2, 7, 7, 2], 1, 2], expected: 7 },
    ],
    reference: {
      a0: 'fn f u32x4 u32 u32 -> u32\nx get p0 p1\ny get p0 p2\nc gt x y\nr select c x y\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32x4 u32 u32 -> u32\nx get p0 p1\ny get p0 p2\nc gt x y\nr select c y x\nret r\nend\n',
    ],
  },
  {
    id: 'r-all-under',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'fold-init',
    note: 'and with init true.',
    instruction:
      'Return true when every element of array p0 is strictly less than p1 (currently it returns true when any element is). Fix both the per-element combination and the starting value.',
    a0Source:
      'fn chk bool u32 u32x4 u32 -> bool\ne get p2 p1\nl lt e p3\ns or p0 l\nret s\nend\nfn f u32x4 u32 -> bool\nq fold chk 4 false p0 p1\nr mov q\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 5], expected: true },
      { fn: 'f', args: [[1, 2, 3, 4], 4], expected: false },
      { fn: 'f', args: [[1, 2, 3, 4], 0], expected: false },
      { fn: 'f', args: [[0, 0, 0, 0], 1], expected: true },
      { fn: 'f', args: [[0, 0, 0, 0], 0], expected: false },
      { fn: 'f', args: [[9, 1, 1, 1], 5], expected: false },
      { fn: 'f', args: [[1, 1, 1, 9], 9], expected: false },
      { fn: 'f', args: [[4294967294, 0, 0, 0], 4294967295], expected: true },
    ],
    reference: {
      a0: 'fn chk bool u32 u32x4 u32 -> bool\ne get p2 p1\nl lt e p3\ns and p0 l\nret s\nend\nfn f u32x4 u32 -> bool\nq fold chk 4 true p0 p1\nr mov q\nret r\nend\n',
    },
    wrongEdits: [
      'fn chk bool u32 u32x4 u32 -> bool\ne get p2 p1\nl lt e p3\ns and p0 l\nret s\nend\nfn f u32x4 u32 -> bool\nq fold chk 4 false p0 p1\nr mov q\nret r\nend\n',
      'fn chk bool u32 u32x4 u32 -> bool\ne get p2 p1\nl le e p3\ns and p0 l\nret s\nend\nfn f u32x4 u32 -> bool\nq fold chk 4 true p0 p1\nr mov q\nret r\nend\n',
    ],
  },
  {
    id: 'r-mod-diff',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'wrapping',
    note: 'Start fails because 2^32 is not a multiple of p2.',
    instruction:
      'Return (p0 - p1) modulo p2 as true modular arithmetic: reduce p0 and p1 modulo p2 first, add p2 to the reduced p0, subtract the reduced p1 and reduce modulo p2 again (all wrapping). When p2 is 0 this gives the wrapped p0 - p1.',
    a0Source: 'fn f u32 u32 u32 -> u32\nd sub p0 p1\nr rem d p2\nret r\nend\n',
    tests: [
      { fn: 'f', args: [1, 2, 5], expected: 4 },
      { fn: 'f', args: [7, 3, 5], expected: 4 },
      { fn: 'f', args: [3, 3, 5], expected: 0 },
      { fn: 'f', args: [0, 9, 7], expected: 5 },
      { fn: 'f', args: [2, 1, 0], expected: 1 },
      { fn: 'f', args: [1, 2, 0], expected: 4294967295 },
      { fn: 'f', args: [100, 1, 10], expected: 9 },
      { fn: 'f', args: [0, 0, 1], expected: 0 },
      { fn: 'f', args: [4, 13, 6], expected: 3 },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 -> u32\na rem p0 p2\nb rem p1 p2\nc add a p2\nd sub c b\nr rem d p2\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 u32 -> u32\na rem p0 p2\nc add a p2\nd sub c p1\nr rem d p2\nret r\nend\n',
    ],
  },
  {
    id: 'r-header-ok',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Version from shr 28.',
    instruction:
      'A header word p0 is valid when its version (the top four bits, read by the helper) is exactly 3 and its low byte is not 0. The function currently accepts any version of 3 or more; make it require exactly 3.',
    a0Source:
      'fn ver u32 -> u32\ns shr p0 28\nv and s 15\nret v\nend\nfn f u32 -> bool\nv call ver p0\na ge v 3\nl and p0 255\nn ne l 0\nr and a n\nret r\nend\n',
    tests: [
      { fn: 'f', args: [805306369], expected: true },
      { fn: 'f', args: [805306624], expected: false },
      { fn: 'f', args: [1073741825], expected: false },
      { fn: 'f', args: [536870913], expected: false },
      { fn: 'f', args: [1073741823], expected: true },
      { fn: 'f', args: [4026532095], expected: false },
      { fn: 'f', args: [0], expected: false },
      { fn: 'f', args: [1], expected: false },
      { fn: 'f', args: [805306623], expected: true },
    ],
    reference: {
      a0: 'fn ver u32 -> u32\ns shr p0 28\nv and s 15\nret v\nend\nfn f u32 -> bool\nv call ver p0\na eq v 3\nl and p0 255\nn ne l 0\nr and a n\nret r\nend\n',
    },
    wrongEdits: [
      'fn ver u32 -> u32\ns shr p0 28\nv and s 15\nret v\nend\nfn f u32 -> bool\nv call ver p0\na eq v 3\nl and p0 255\nn ne l 0\nr or a n\nret r\nend\n',
    ],
  },
];
