/**
 * Held-out task set Q (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-q/q-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-q.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskQ {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_Q: readonly TaskQ[] = [
  {
    id: 'q-tank-refill',
    kind: 'targeted-edit',
    target: 'refill',
    wrongEditKind: 'wrapping',
    note: 'le versus lt at exactly one tenth; adding 1 to the capacity wraps at the maximum.',
    instruction:
      'Refill is needed when ten times the level is at most the capacity; a level of exactly one tenth must also trigger a refill.',
    a0Source: 'fn refill u32 u32 -> bool\nt mul p0 10\nc mov p1\nr lt t c\nret r\nend\n',
    tests: [
      { fn: 'refill', args: [1, 10], expected: true },
      { fn: 'refill', args: [1, 11], expected: true },
      { fn: 'refill', args: [2, 10], expected: false },
      { fn: 'refill', args: [0, 0], expected: true },
      { fn: 'refill', args: [5, 50], expected: true },
      { fn: 'refill', args: [5, 49], expected: false },
      { fn: 'refill', args: [1, 4294967295], expected: true },
      { fn: 'refill', args: [0, 4294967295], expected: true },
      { fn: 'refill', args: [3, 31], expected: true },
    ],
    reference: { a0: 'fn refill u32 u32 -> bool\nt mul p0 10\nc mov p1\nr le t c\nret r\nend\n' },
    wrongEdits: ['fn refill u32 u32 -> bool\nt mul p0 10\nc add p1 1\nr lt t c\nret r\nend\n'],
  },
  {
    id: 'q-ladder-sum',
    kind: 'targeted-edit',
    target: 'ladder',
    wrongEditKind: 'fold-bound',
    note: 'weights 1..4; the wrong edit runs 5 steps.',
    instruction:
      'The function should return k times (1 + 2 + 3 + 4): the step weights must run from 1 to 4, not from 0 to 3.',
    a0Source:
      'fn rung u32 u32 u32 -> u32\nj mov p1\nm mul j p2\ns add p0 m\nret s\nend\nfn ladder u32 -> u32\nf fold rung 4 0 p0\nr mov f\nret r\nend\n',
    tests: [
      { fn: 'ladder', args: [0], expected: 0 },
      { fn: 'ladder', args: [1], expected: 10 },
      { fn: 'ladder', args: [2], expected: 20 },
      { fn: 'ladder', args: [7], expected: 70 },
      { fn: 'ladder', args: [100], expected: 1000 },
      { fn: 'ladder', args: [429496729], expected: 4294967290 },
      { fn: 'ladder', args: [429496730], expected: 4 },
      { fn: 'ladder', args: [4294967295], expected: 4294967286 },
    ],
    reference: {
      a0: 'fn rung u32 u32 u32 -> u32\nj add p1 1\nm mul j p2\ns add p0 m\nret s\nend\nfn ladder u32 -> u32\nf fold rung 4 0 p0\nr mov f\nret r\nend\n',
    },
    wrongEdits: [
      'fn rung u32 u32 u32 -> u32\nj add p1 1\nm mul j p2\ns add p0 m\nret s\nend\nfn ladder u32 -> u32\nf fold rung 5 0 p0\nr mov f\nret r\nend\n',
    ],
  },
  {
    id: 'q-hue-field',
    kind: 'targeted-edit',
    target: 'hue',
    wrongEditKind: 'off-by-one',
    note: 'mask should be 15, not 7.',
    instruction:
      'Return the 4-bit field held in bits 4 through 7 of the input (bit 0 is the lowest).',
    a0Source: 'fn hue u32 -> u32\ns shr p0 4\nm and s 7\nret m\nend\n',
    tests: [
      { fn: 'hue', args: [0], expected: 0 },
      { fn: 'hue', args: [240], expected: 15 },
      { fn: 'hue', args: [128], expected: 8 },
      { fn: 'hue', args: [255], expected: 15 },
      { fn: 'hue', args: [16], expected: 1 },
      { fn: 'hue', args: [4294967295], expected: 15 },
      { fn: 'hue', args: [143], expected: 8 },
      { fn: 'hue', args: [4660], expected: 3 },
      { fn: 'hue', args: [8], expected: 0 },
    ],
    reference: { a0: 'fn hue u32 -> u32\ns shr p0 4\nm and s 15\nret m\nend\n' },
    wrongEdits: ['fn hue u32 -> u32\ns shr p0 3\nm and s 15\nret m\nend\n'],
  },
  {
    id: 'q-seal-last',
    kind: 'targeted-edit',
    target: 'seal',
    wrongEditKind: 'off-by-one',
    note: 'source index 0, destination 3; index 4 wraps to 0.',
    instruction:
      'Return the array with its last slot overwritten by the value from its first slot.',
    a0Source: 'fn seal u32x4 -> u32x4\nv get p0 1\nr set p0 3 v\nret r\nend\n',
    tests: [
      { fn: 'seal', args: [[1, 2, 3, 4]], expected: [1, 2, 3, 1] },
      { fn: 'seal', args: [[0, 0, 0, 0]], expected: [0, 0, 0, 0] },
      { fn: 'seal', args: [[9, 8, 7, 6]], expected: [9, 8, 7, 9] },
      { fn: 'seal', args: [[5, 5, 5, 1]], expected: [5, 5, 5, 5] },
      { fn: 'seal', args: [[4294967295, 0, 1, 2]], expected: [4294967295, 0, 1, 4294967295] },
      { fn: 'seal', args: [[7, 7, 7, 7]], expected: [7, 7, 7, 7] },
      { fn: 'seal', args: [[1, 0, 0, 0]], expected: [1, 0, 0, 1] },
      { fn: 'seal', args: [[0, 1, 2, 3]], expected: [0, 1, 2, 0] },
    ],
    reference: { a0: 'fn seal u32x4 -> u32x4\nv get p0 0\nr set p0 3 v\nret r\nend\n' },
    wrongEdits: ['fn seal u32x4 -> u32x4\nv get p0 0\nr set p0 4 v\nret r\nend\n'],
  },
  {
    id: 'q-vote-pass',
    kind: 'targeted-edit',
    target: 'passes',
    wrongEditKind: 'comparison',
    note: 'three yes votes are enough.',
    instruction: 'A motion passes when at least three of the four votes are nonzero.',
    a0Source:
      'fn tally u32 u32 u32x4 -> u32\nx get p2 p1\ny ne x 0\nd select y 1 0\ns add p0 d\nret s\nend\nfn passes u32x4 -> bool\nc fold tally 4 0 p0\nr gt c 3\nret r\nend\n',
    tests: [
      { fn: 'passes', args: [[1, 1, 1, 1]], expected: true },
      { fn: 'passes', args: [[1, 1, 1, 0]], expected: true },
      { fn: 'passes', args: [[0, 1, 1, 0]], expected: false },
      { fn: 'passes', args: [[0, 0, 0, 0]], expected: false },
      { fn: 'passes', args: [[5, 0, 9, 4294967295]], expected: true },
      { fn: 'passes', args: [[0, 0, 1, 1]], expected: false },
      { fn: 'passes', args: [[1, 0, 1, 1]], expected: true },
      { fn: 'passes', args: [[0, 0, 0, 7]], expected: false },
    ],
    reference: {
      a0: 'fn tally u32 u32 u32x4 -> u32\nx get p2 p1\ny ne x 0\nd select y 1 0\ns add p0 d\nret s\nend\nfn passes u32x4 -> bool\nc fold tally 4 0 p0\nr ge c 3\nret r\nend\n',
    },
    wrongEdits: [
      'fn tally u32 u32 u32x4 -> u32\nx get p2 p1\ny ne x 0\nd select y 1 0\ns add p0 d\nret s\nend\nfn passes u32x4 -> bool\nc fold tally 4 0 p0\nr ge c 2\nret r\nend\n',
    ],
  },
  {
    id: 'q-heater-on',
    kind: 'targeted-edit',
    target: 'heater',
    wrongEditKind: 'logic',
    note: 'needs the negated night flag.',
    instruction: 'The heater should run only when it is cold and it is not night.',
    a0Source:
      'fn cold u32 u32 -> bool\nc lt p0 p1\nk mov c\nret k\nend\nfn night u32 -> bool\nn ge p0 22\nk mov n\nret k\nend\nfn heater u32 u32 u32 -> bool\na call cold p0 p1\nb call night p2\nr and a b\nret r\nend\n',
    tests: [
      { fn: 'heater', args: [10, 18, 12], expected: true },
      { fn: 'heater', args: [10, 18, 23], expected: false },
      { fn: 'heater', args: [20, 18, 12], expected: false },
      { fn: 'heater', args: [18, 18, 21], expected: false },
      { fn: 'heater', args: [17, 18, 22], expected: false },
      { fn: 'heater', args: [17, 18, 21], expected: true },
      { fn: 'heater', args: [25, 18, 23], expected: false },
      { fn: 'heater', args: [0, 1, 0], expected: true },
    ],
    reference: {
      a0: 'fn cold u32 u32 -> bool\nc lt p0 p1\nk mov c\nret k\nend\nfn night u32 -> bool\nn ge p0 22\nk mov n\nret k\nend\nfn heater u32 u32 u32 -> bool\na call cold p0 p1\nb call night p2\nnb xor b true\nr and a nb\nret r\nend\n',
    },
    wrongEdits: [
      'fn cold u32 u32 -> bool\nc lt p0 p1\nk mov c\nret k\nend\nfn night u32 -> bool\nn ge p0 22\nk mov n\nret k\nend\nfn heater u32 u32 u32 -> bool\na call cold p0 p1\nb call night p2\nnb xor b true\nr or a nb\nret r\nend\n',
    ],
  },
  {
    id: 'q-odometer',
    kind: 'targeted-edit',
    target: 'odo',
    wrongEditKind: 'wrapping',
    note: 'reading modulo 100000.',
    instruction:
      'The odometer shows five digits, so the new reading must roll over to 0 when it reaches 100000.',
    a0Source: 'fn odo u32 u32 -> u32\ns add p0 p1\nr mov s\nret r\nend\n',
    tests: [
      { fn: 'odo', args: [0, 0], expected: 0 },
      { fn: 'odo', args: [99999, 1], expected: 0 },
      { fn: 'odo', args: [99998, 1], expected: 99999 },
      { fn: 'odo', args: [50000, 50000], expected: 0 },
      { fn: 'odo', args: [12345, 10], expected: 12355 },
      { fn: 'odo', args: [99999, 99999], expected: 99998 },
      { fn: 'odo', args: [1, 2], expected: 3 },
      { fn: 'odo', args: [0, 99999], expected: 99999 },
    ],
    reference: { a0: 'fn odo u32 u32 -> u32\ns add p0 p1\nr rem s 100000\nret r\nend\n' },
    wrongEdits: ['fn odo u32 u32 -> u32\ns add p0 p1\nr rem s 99999\nret r\nend\n'],
  },
  {
    id: 'q-level-up',
    kind: 'targeted-edit',
    target: 'gain',
    wrongEditKind: 'comparison',
    note: 'reaching means at least 100.',
    instruction:
      'Experience levels up when the total reaches 100: return the total minus 100 and true, otherwise the total and false.',
    a0Source:
      'fn gain u32 u32 -> (u32,bool)\nt add p0 p1\nu gt t 100\nd sub t 100\nx select u d t\nr rec x u\nret r\nend\n',
    tests: [
      { fn: 'gain', args: [0, 0], expected: [0, false] },
      { fn: 'gain', args: [50, 50], expected: [0, true] },
      { fn: 'gain', args: [99, 1], expected: [0, true] },
      { fn: 'gain', args: [99, 2], expected: [1, true] },
      { fn: 'gain', args: [0, 99], expected: [99, false] },
      { fn: 'gain', args: [150, 30], expected: [80, true] },
      { fn: 'gain', args: [10, 20], expected: [30, false] },
      { fn: 'gain', args: [100, 0], expected: [0, true] },
    ],
    reference: {
      a0: 'fn gain u32 u32 -> (u32,bool)\nt add p0 p1\nu ge t 100\nd sub t 100\nx select u d t\nr rec x u\nret r\nend\n',
    },
    wrongEdits: [
      'fn gain u32 u32 -> (u32,bool)\nt add p0 p1\nu ge t 100\nd sub t 99\nx select u d t\nr rec x u\nret r\nend\n',
    ],
  },
  {
    id: 'q-off-day',
    kind: 'multi-node-edit',
    target: 'offday',
    wrongEditKind: 'comparison',
    note: 'the weekend helper is rewritten.',
    instruction:
      'Days are now numbered with 0 as Sunday and 6 as Saturday; the result should be true only for those two days.',
    a0Source:
      'fn wrap7 u32 -> u32\nr rem p0 7\nk mov r\nret k\nend\nfn weekend u32 -> bool\nt mov p0\nw ge t 5\nret w\nend\nfn offday u32 u32 -> bool\ns add p0 p1\nd call wrap7 s\nw call weekend d\nret w\nend\n',
    tests: [
      { fn: 'offday', args: [0, 0], expected: true },
      { fn: 'offday', args: [0, 5], expected: false },
      { fn: 'offday', args: [0, 6], expected: true },
      { fn: 'offday', args: [3, 4], expected: true },
      { fn: 'offday', args: [1, 3], expected: false },
      { fn: 'offday', args: [2, 2], expected: false },
      { fn: 'offday', args: [6, 7], expected: true },
      { fn: 'offday', args: [100, 0], expected: false },
      { fn: 'offday', args: [4, 1], expected: false },
    ],
    reference: {
      a0: 'fn wrap7 u32 -> u32\nr rem p0 7\nk mov r\nret k\nend\nfn weekend u32 -> bool\na eq p0 0\nb eq p0 6\nw or a b\nret w\nend\nfn offday u32 u32 -> bool\ns add p0 p1\nd call wrap7 s\nw call weekend d\nret w\nend\n',
    },
    wrongEdits: [
      'fn wrap7 u32 -> u32\nr rem p0 7\nk mov r\nret k\nend\nfn weekend u32 -> bool\na eq p0 0\nb eq p0 5\nw or a b\nret w\nend\nfn offday u32 u32 -> bool\ns add p0 p1\nd call wrap7 s\nw call weekend d\nret w\nend\n',
    ],
  },
  {
    id: 'q-shift-in',
    kind: 'multi-node-edit',
    target: 'push',
    wrongEditKind: 'swapped-argument',
    note: 'three indices each shift by one.',
    instruction:
      'Drop the oldest (first) sample, move the others one place toward the front, and put the new value in the last slot.',
    a0Source:
      'fn push u32x4 u32 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nr arr a b c p1\nret r\nend\n',
    tests: [
      { fn: 'push', args: [[1, 2, 3, 4], 5], expected: [2, 3, 4, 5] },
      { fn: 'push', args: [[0, 0, 0, 0], 0], expected: [0, 0, 0, 0] },
      { fn: 'push', args: [[9, 8, 7, 6], 1], expected: [8, 7, 6, 1] },
      { fn: 'push', args: [[1, 1, 1, 1], 1], expected: [1, 1, 1, 1] },
      { fn: 'push', args: [[0, 0, 0, 7], 3], expected: [0, 0, 7, 3] },
      { fn: 'push', args: [[4, 3, 2, 1], 0], expected: [3, 2, 1, 0] },
      { fn: 'push', args: [[5, 6, 7, 8], 9], expected: [6, 7, 8, 9] },
      { fn: 'push', args: [[1, 0, 0, 0], 2], expected: [0, 0, 0, 2] },
    ],
    reference: {
      a0: 'fn push u32x4 u32 -> u32x4\na get p0 1\nb get p0 2\nc get p0 3\nr arr a b c p1\nret r\nend\n',
    },
    wrongEdits: [
      'fn push u32x4 u32 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nr arr p1 a b c\nret r\nend\n',
    ],
  },
  {
    id: 'q-ledger-overdraw',
    kind: 'multi-node-edit',
    target: 'overdrawn',
    wrongEditKind: 'off-by-one',
    note: 'parity and initial balance both change.',
    instruction:
      'Entries at odd positions are withdrawals and entries at even positions are deposits, and the account opens with the second argument as its balance; return whether it ever went below zero.',
    a0Source:
      'fn post (u32,bool) u32 u32x4 -> (u32,bool)\nb at p0 0\no at p0 1\nx get p2 p1\nq and p1 1\nw eq q 0\nu lt b x\ndn sub b x\nup add b x\nnb select w dn up\nov and w u\nno or o ov\nr rec nb no\nret r\nend\nfn overdrawn u32x4 u32 -> bool\nz rec 0 false\nf fold post 4 z p0\nr at f 1\nret r\nend\n',
    tests: [
      { fn: 'overdrawn', args: [[5, 3, 0, 0], 0], expected: false },
      { fn: 'overdrawn', args: [[0, 1, 0, 0], 0], expected: true },
      { fn: 'overdrawn', args: [[0, 1, 0, 0], 1], expected: false },
      { fn: 'overdrawn', args: [[10, 10, 0, 1], 0], expected: true },
      { fn: 'overdrawn', args: [[0, 0, 0, 0], 0], expected: false },
      { fn: 'overdrawn', args: [[3, 4, 0, 0], 0], expected: true },
      { fn: 'overdrawn', args: [[0, 5, 0, 0], 5], expected: false },
      { fn: 'overdrawn', args: [[0, 5, 0, 0], 4], expected: true },
      { fn: 'overdrawn', args: [[2, 1, 1, 3], 0], expected: true },
    ],
    reference: {
      a0: 'fn post (u32,bool) u32 u32x4 -> (u32,bool)\nb at p0 0\no at p0 1\nx get p2 p1\nq and p1 1\nw eq q 1\nu lt b x\ndn sub b x\nup add b x\nnb select w dn up\nov and w u\nno or o ov\nr rec nb no\nret r\nend\nfn overdrawn u32x4 u32 -> bool\nz rec p1 false\nf fold post 4 z p0\nr at f 1\nret r\nend\n',
    },
    wrongEdits: [
      'fn post (u32,bool) u32 u32x4 -> (u32,bool)\nb at p0 0\no at p0 1\nx get p2 p1\nq and p1 1\nw eq q 1\nu lt b x\ndn sub b x\nup add b x\nnb select w dn up\nov and w u\nno or o ov\nr rec nb no\nret r\nend\nfn overdrawn u32x4 u32 -> bool\nz rec 0 false\nf fold post 4 z p0\nr at f 1\nret r\nend\n',
      'fn post (u32,bool) u32 u32x4 -> (u32,bool)\nb at p0 0\no at p0 1\nx get p2 p1\nq and p1 1\nw eq q 0\nu lt b x\ndn sub b x\nup add b x\nnb select w dn up\nov and w u\nno or o ov\nr rec nb no\nret r\nend\nfn overdrawn u32x4 u32 -> bool\nz rec p1 false\nf fold post 4 z p0\nr at f 1\nret r\nend\n',
    ],
  },
  {
    id: 'q-pack565',
    kind: 'multi-node-edit',
    target: 'pack',
    wrongEditKind: 'bit-overlap',
    note: 'red shift and green width both change.',
    instruction:
      'Pack the colour as 5-6-5: red in bits 11-15, a 6-bit green in bits 5-10, blue in bits 0-4.',
    a0Source:
      'fn pack u32 u32 u32 -> u32\nr and p0 31\nrs shl r 10\ng and p1 31\ngs shl g 5\nb and p2 31\no or rs gs\nx or o b\nret x\nend\n',
    tests: [
      { fn: 'pack', args: [0, 0, 0], expected: 0 },
      { fn: 'pack', args: [31, 0, 0], expected: 63488 },
      { fn: 'pack', args: [0, 63, 0], expected: 2016 },
      { fn: 'pack', args: [0, 0, 31], expected: 31 },
      { fn: 'pack', args: [31, 63, 31], expected: 65535 },
      { fn: 'pack', args: [1, 1, 1], expected: 2081 },
      { fn: 'pack', args: [255, 255, 255], expected: 65535 },
      { fn: 'pack', args: [16, 32, 16], expected: 33808 },
      { fn: 'pack', args: [0, 32, 0], expected: 1024 },
    ],
    reference: {
      a0: 'fn pack u32 u32 u32 -> u32\nr and p0 31\nrs shl r 11\ng and p1 63\ngs shl g 5\nb and p2 31\no or rs gs\nx or o b\nret x\nend\n',
    },
    wrongEdits: [
      'fn pack u32 u32 u32 -> u32\nr and p0 31\nrs shl r 10\ng and p1 63\ngs shl g 5\nb and p2 31\no or rs gs\nx or o b\nret x\nend\n',
    ],
  },
  {
    id: 'q-grow-tenths',
    kind: 'comprehension-edit',
    target: 'grow',
    wrongEditKind: 'changed-constant',
    note: 'divisor 1000.',
    instruction:
      'The rate argument is now given in tenths of a percent (so 25 means 2.5 per cent per period); keep the three periods and the rounding down.',
    a0Source:
      'fn credit u32 u32 u32 -> u32\nm mul p0 p2\nq div m 100\ns add p0 q\nret s\nend\nfn grow u32 u32 -> u32\nf fold credit 3 p0 p1\nr mov f\nret r\nend\n',
    tests: [
      { fn: 'grow', args: [1000, 0], expected: 1000 },
      { fn: 'grow', args: [1000, 10], expected: 1030 },
      { fn: 'grow', args: [1000, 25], expected: 1076 },
      { fn: 'grow', args: [0, 50], expected: 0 },
      { fn: 'grow', args: [100000, 5], expected: 101507 },
      { fn: 'grow', args: [999, 1000], expected: 7992 },
      { fn: 'grow', args: [12345, 7], expected: 12605 },
      { fn: 'grow', args: [1, 1000], expected: 8 },
    ],
    reference: {
      a0: 'fn credit u32 u32 u32 -> u32\nm mul p0 p2\nq div m 1000\ns add p0 q\nret s\nend\nfn grow u32 u32 -> u32\nf fold credit 3 p0 p1\nr mov f\nret r\nend\n',
    },
    wrongEdits: [
      'fn credit u32 u32 u32 -> u32\nm mul p0 p2\nq div m 10\ns add p0 q\nret s\nend\nfn grow u32 u32 -> u32\nf fold credit 3 p0 p1\nr mov f\nret r\nend\n',
    ],
  },
  {
    id: 'q-calibrate',
    kind: 'comprehension-edit',
    target: 'calib',
    wrongEditKind: 'swapped-argument',
    note: 'apply scale before bias.',
    instruction: 'The calibrated reading should be four times the raw reading plus three.',
    a0Source:
      'fn bias u32 -> u32\nr add p0 3\nk mov r\nret k\nend\nfn scale u32 -> u32\nr mul p0 4\nk mov r\nret k\nend\nfn calib u32 -> u32\nx call bias p0\ny call scale x\nret y\nend\n',
    tests: [
      { fn: 'calib', args: [0], expected: 3 },
      { fn: 'calib', args: [1], expected: 7 },
      { fn: 'calib', args: [2], expected: 11 },
      { fn: 'calib', args: [10], expected: 43 },
      { fn: 'calib', args: [1073741823], expected: 4294967295 },
      { fn: 'calib', args: [1073741824], expected: 3 },
      { fn: 'calib', args: [4294967295], expected: 4294967295 },
      { fn: 'calib', args: [100], expected: 403 },
    ],
    reference: {
      a0: 'fn bias u32 -> u32\nr add p0 3\nk mov r\nret k\nend\nfn scale u32 -> u32\nr mul p0 4\nk mov r\nret k\nend\nfn calib u32 -> u32\nx call scale p0\ny call bias x\nret y\nend\n',
    },
    wrongEdits: [
      'fn bias u32 -> u32\nr add p0 3\nk mov r\nret k\nend\nfn scale u32 -> u32\nr mul p0 4\nk mov r\nret k\nend\nfn calib u32 -> u32\nx call scale p0\ny call bias x\nz call bias y\nret z\nend\n',
    ],
  },
  {
    id: 'q-door-lockout',
    kind: 'comprehension-edit',
    target: 'unlock',
    wrongEditKind: 'comparison',
    note: 'lockout at 3 attempts.',
    instruction:
      'The door must stay shut once three or more failed attempts have been recorded, even with the right code.',
    a0Source:
      'fn codeok u32 -> bool\nc eq p0 4321\nk mov c\nret k\nend\nfn fresh u32 -> bool\nf le p0 3\nk mov f\nret k\nend\nfn unlock u32 u32 -> bool\na call codeok p0\nb call fresh p1\nr and a b\nret r\nend\n',
    tests: [
      { fn: 'unlock', args: [4321, 0], expected: true },
      { fn: 'unlock', args: [4321, 2], expected: true },
      { fn: 'unlock', args: [4321, 3], expected: false },
      { fn: 'unlock', args: [4321, 4], expected: false },
      { fn: 'unlock', args: [1234, 0], expected: false },
      { fn: 'unlock', args: [4320, 1], expected: false },
      { fn: 'unlock', args: [4321, 4294967295], expected: false },
      { fn: 'unlock', args: [4322, 2], expected: false },
    ],
    reference: {
      a0: 'fn codeok u32 -> bool\nc eq p0 4321\nk mov c\nret k\nend\nfn fresh u32 -> bool\nf lt p0 3\nk mov f\nret k\nend\nfn unlock u32 u32 -> bool\na call codeok p0\nb call fresh p1\nr and a b\nret r\nend\n',
    },
    wrongEdits: [
      'fn codeok u32 -> bool\nc eq p0 4321\nk mov c\nret k\nend\nfn fresh u32 -> bool\nf lt p0 4\nk mov f\nret k\nend\nfn unlock u32 u32 -> bool\na call codeok p0\nb call fresh p1\nr and a b\nret r\nend\n',
    ],
  },
  {
    id: 'q-echo-count',
    kind: 'comprehension-edit',
    target: 'echoes',
    wrongEditKind: 'fold-bound',
    note: 'skip index 0, three steps.',
    instruction:
      'Count how many of the elements after the first are equal to the first element; the first element itself must not be counted.',
    a0Source:
      'fn same u32 u32 u32x4 -> u32\nj mov p1\nx get p2 j\nh get p2 0\ne eq x h\nd select e 1 0\ns add p0 d\nret s\nend\nfn echoes u32x4 -> u32\nc fold same 4 0 p0\nr mov c\nret r\nend\n',
    tests: [
      { fn: 'echoes', args: [[1, 1, 1, 1]], expected: 3 },
      { fn: 'echoes', args: [[1, 2, 3, 4]], expected: 0 },
      { fn: 'echoes', args: [[0, 0, 0, 0]], expected: 3 },
      { fn: 'echoes', args: [[5, 5, 6, 5]], expected: 2 },
      { fn: 'echoes', args: [[7, 1, 7, 1]], expected: 1 },
      { fn: 'echoes', args: [[2, 3, 3, 3]], expected: 0 },
      { fn: 'echoes', args: [[9, 9, 0, 0]], expected: 1 },
      { fn: 'echoes', args: [[4294967295, 0, 4294967295, 0]], expected: 1 },
    ],
    reference: {
      a0: 'fn same u32 u32 u32x4 -> u32\nj add p1 1\nx get p2 j\nh get p2 0\ne eq x h\nd select e 1 0\ns add p0 d\nret s\nend\nfn echoes u32x4 -> u32\nc fold same 3 0 p0\nr mov c\nret r\nend\n',
    },
    wrongEdits: [
      'fn same u32 u32 u32x4 -> u32\nj add p1 1\nx get p2 j\nh get p2 0\ne eq x h\nd select e 1 0\ns add p0 d\nret s\nend\nfn echoes u32x4 -> u32\nc fold same 4 0 p0\nr mov c\nret r\nend\n',
    ],
  },
];
