/**
 * Held-out task set H (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-h/h-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-h.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskH {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_H: readonly TaskH[] = [
  {
    id: 'h-at-most-100',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Boundary comparison; start excludes 100, wrong edit includes 101.',
    instruction: 'Return true when the argument is at most 100, with 100 itself included.',
    a0Source: 'fn f u32 -> bool\na lt p0 100\nb mov a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: true },
      { fn: 'f', args: [1], expected: true },
      { fn: 'f', args: [50], expected: true },
      { fn: 'f', args: [99], expected: true },
      { fn: 'f', args: [100], expected: true },
      { fn: 'f', args: [101], expected: false },
      { fn: 'f', args: [1000], expected: false },
      { fn: 'f', args: [4294967295], expected: false },
    ],
    reference: { a0: 'fn f u32 -> bool\na le p0 100\nb mov a\nret b\nend\n' },
    wrongEdits: ['fn f u32 -> bool\na le p0 101\nb mov a\nret b\nend\n'],
  },
  {
    id: 'h-low-byte',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'Bit mask constant; 127 drops bit 7, 256 is a single bit.',
    instruction: 'Return the lowest 8 bits of the argument.',
    a0Source: 'fn f u32 -> u32\nm and p0 127\nr mov m\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [127], expected: 127 },
      { fn: 'f', args: [128], expected: 128 },
      { fn: 'f', args: [255], expected: 255 },
      { fn: 'f', args: [256], expected: 0 },
      { fn: 'f', args: [300], expected: 44 },
      { fn: 'f', args: [511], expected: 255 },
      { fn: 'f', args: [4294967295], expected: 255 },
    ],
    reference: { a0: 'fn f u32 -> u32\nm and p0 255\nr mov m\nret r\nend\n' },
    wrongEdits: ['fn f u32 -> u32\nm and p0 256\nr mov m\nret r\nend\n'],
  },
  {
    id: 'h-last-elem',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Index 4 wraps to 0 under modulo indexing.',
    instruction: 'Return the last element of the array.',
    a0Source: 'fn f u32x4 -> u32\ne get p0 4\nr mov e\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4]], expected: 4 },
      { fn: 'f', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'f', args: [[9, 8, 7, 6]], expected: 6 },
      { fn: 'f', args: [[5, 5, 5, 5]], expected: 5 },
      { fn: 'f', args: [[4294967295, 0, 0, 1]], expected: 1 },
      { fn: 'f', args: [[0, 0, 0, 4294967295]], expected: 4294967295 },
      { fn: 'f', args: [[1, 0, 0, 0]], expected: 0 },
      { fn: 'f', args: [[7, 1, 2, 3]], expected: 3 },
    ],
    reference: { a0: 'fn f u32x4 -> u32\ne get p0 3\nr mov e\nret r\nend\n' },
    wrongEdits: ['fn f u32x4 -> u32\ne get p0 2\nr mov e\nret r\nend\n'],
  },
  {
    id: 'h-saturating-add',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'wrapping',
    note: 'Overflow detected by wrapped sum < first operand; wrong edit uses <= and misfires when p1 is 0.',
    instruction:
      'Return the sum of the two arguments, but when the true sum does not fit in 32 bits return 4294967295 instead of a wrapped value.',
    a0Source: 'fn f u32 u32 -> u32\ns add p0 p1\no lt s p0\nr select o 0 s\nret r\nend\n',
    tests: [
      { fn: 'f', args: [1, 2], expected: 3 },
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [5, 0], expected: 5 },
      { fn: 'f', args: [4294967295, 0], expected: 4294967295 },
      { fn: 'f', args: [4294967295, 1], expected: 4294967295 },
      { fn: 'f', args: [2147483648, 2147483648], expected: 4294967295 },
      { fn: 'f', args: [4294967290, 5], expected: 4294967295 },
      { fn: 'f', args: [4294967290, 6], expected: 4294967295 },
      { fn: 'f', args: [100, 4294967200], expected: 4294967295 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\ns add p0 p1\no lt s p0\nr select o 4294967295 s\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\ns add p0 p1\no le s p0\nr select o 4294967295 s\nret r\nend\n',
    ],
  },
  {
    id: 'h-set-second',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Start swaps index and value; wrong edit writes position 2.',
    instruction:
      'Return a copy of the array with the element at position 1 (the second element) replaced by the second argument.',
    a0Source: 'fn f u32x4 u32 -> u32x4\nn set p0 p1 1\nr mov n\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[0, 0, 0, 0], 7], expected: [0, 7, 0, 0] },
      { fn: 'f', args: [[1, 2, 3, 4], 9], expected: [1, 9, 3, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 2], expected: [1, 2, 3, 4] },
      { fn: 'f', args: [[5, 6, 7, 8], 0], expected: [5, 0, 7, 8] },
      { fn: 'f', args: [[0, 0, 0, 0], 4294967295], expected: [0, 4294967295, 0, 0] },
      { fn: 'f', args: [[9, 9, 9, 9], 1], expected: [9, 1, 9, 9] },
      { fn: 'f', args: [[1, 1, 1, 1], 5], expected: [1, 5, 1, 1] },
      { fn: 'f', args: [[4, 3, 2, 1], 3], expected: [4, 3, 2, 1] },
    ],
    reference: { a0: 'fn f u32x4 u32 -> u32x4\nn set p0 1 p1\nr mov n\nret r\nend\n' },
    wrongEdits: ['fn f u32x4 u32 -> u32x4\nn set p0 2 p1\nr mov n\nret r\nend\n'],
  },
  {
    id: 'h-is-even',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'bit-mask',
    note: 'Bool result; start tests odd.',
    instruction: 'Return true when the argument is even.',
    a0Source: 'fn f u32 -> bool\nlo and p0 1\nt eq lo 1\nret t\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: true },
      { fn: 'f', args: [1], expected: false },
      { fn: 'f', args: [2], expected: true },
      { fn: 'f', args: [3], expected: false },
      { fn: 'f', args: [6], expected: true },
      { fn: 'f', args: [7], expected: false },
      { fn: 'f', args: [4294967294], expected: true },
      { fn: 'f', args: [4294967295], expected: false },
    ],
    reference: { a0: 'fn f u32 -> bool\nlo and p0 1\nt eq lo 0\nret t\nend\n' },
    wrongEdits: ['fn f u32 -> bool\nlo and p0 2\nt eq lo 0\nret t\nend\n'],
  },
  {
    id: 'h-abs-diff',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Helper call; start picks the wrapped (negative) difference.',
    instruction: 'Return the absolute difference between the two arguments.',
    a0Source:
      'fn d u32 u32 -> u32\nx sub p0 p1\ny mov x\nret y\nend\nfn f u32 u32 -> u32\na lt p0 p1\nb call d p1 p0\nc call d p0 p1\nr select a c b\nret r\nend\n',
    tests: [
      { fn: 'f', args: [3, 5], expected: 2 },
      { fn: 'f', args: [5, 3], expected: 2 },
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [10, 10], expected: 0 },
      { fn: 'f', args: [0, 4294967295], expected: 4294967295 },
      { fn: 'f', args: [4294967295, 0], expected: 4294967295 },
      { fn: 'f', args: [1, 2], expected: 1 },
      { fn: 'f', args: [100, 1], expected: 99 },
    ],
    reference: {
      a0: 'fn d u32 u32 -> u32\nx sub p0 p1\ny mov x\nret y\nend\nfn f u32 u32 -> u32\na lt p0 p1\nb call d p1 p0\nc call d p0 p1\nr select a b c\nret r\nend\n',
    },
    wrongEdits: [
      'fn d u32 u32 -> u32\nx sub p0 p1\ny mov x\nret y\nend\nfn f u32 u32 -> u32\na gt p0 p1\nb call d p1 p0\nc call d p0 p1\nr select a b c\nret r\nend\n',
    ],
  },
  {
    id: 'h-times-eight',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'Shift distance is log2 of the factor, not the factor.',
    instruction: 'Return the argument multiplied by 8 (wrapping modulo 2^32).',
    a0Source: 'fn f u32 -> u32\ns shl p0 2\nr mov s\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [1], expected: 8 },
      { fn: 'f', args: [2], expected: 16 },
      { fn: 'f', args: [5], expected: 40 },
      { fn: 'f', args: [100], expected: 800 },
      { fn: 'f', args: [536870911], expected: 4294967288 },
      { fn: 'f', args: [536870912], expected: 0 },
      { fn: 'f', args: [4294967295], expected: 4294967288 },
    ],
    reference: { a0: 'fn f u32 -> u32\ns shl p0 3\nr mov s\nret r\nend\n' },
    wrongEdits: ['fn f u32 -> u32\ns shl p0 8\nr mov s\nret r\nend\n'],
  },
  {
    id: 'h-sum-squares',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Needs both squaring in the helper and the fold count raised to 4.',
    instruction: 'Return the sum of the squares of all four array elements (wrapping modulo 2^32).',
    a0Source:
      'fn step u32 u32 u32x4 -> u32\ng get p2 p1\ns add p0 g\nret s\nend\nfn f u32x4 -> u32\nt fold step 3 0 p0\nr mov t\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4]], expected: 30 },
      { fn: 'f', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'f', args: [[0, 0, 0, 5]], expected: 25 },
      { fn: 'f', args: [[1, 1, 1, 1]], expected: 4 },
      { fn: 'f', args: [[65536, 0, 0, 0]], expected: 0 },
      { fn: 'f', args: [[65535, 0, 0, 0]], expected: 4294836225 },
      { fn: 'f', args: [[2, 0, 0, 3]], expected: 13 },
      { fn: 'f', args: [[10, 10, 10, 10]], expected: 400 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32x4 -> u32\ng get p2 p1\nq mul g g\ns add p0 q\nret s\nend\nfn f u32x4 -> u32\nt fold step 4 0 p0\nr mov t\nret r\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32x4 -> u32\ng get p2 p1\nq mul g g\ns add p0 q\nret s\nend\nfn f u32x4 -> u32\nt fold step 3 0 p0\nr mov t\nret r\nend\n',
    ],
  },
  {
    id: 'h-in-range',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Both bounds must become inclusive; wrong edit fixes only the lower.',
    instruction:
      'Return true when the first argument lies between the second and third arguments, with both ends included.',
    a0Source: 'fn f u32 u32 u32 -> bool\nlo gt p0 p1\nhi lt p0 p2\nboth and lo hi\nret both\nend\n',
    tests: [
      { fn: 'f', args: [5, 1, 10], expected: true },
      { fn: 'f', args: [1, 1, 10], expected: true },
      { fn: 'f', args: [10, 1, 10], expected: true },
      { fn: 'f', args: [0, 1, 10], expected: false },
      { fn: 'f', args: [11, 1, 10], expected: false },
      { fn: 'f', args: [5, 5, 5], expected: true },
      { fn: 'f', args: [0, 0, 4294967295], expected: true },
      { fn: 'f', args: [4294967295, 0, 4294967295], expected: true },
      { fn: 'f', args: [3, 5, 2], expected: false },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 -> bool\nlo ge p0 p1\nhi le p0 p2\nboth and lo hi\nret both\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 u32 -> bool\nlo ge p0 p1\nhi lt p0 p2\nboth and lo hi\nret both\nend\n',
    ],
  },
  {
    id: 'h-second-byte',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'Shift and mask both change; wrong edit keeps the 4-bit mask.',
    instruction:
      'Change the function to return bits 8 through 15 of the argument (its second-lowest byte) instead of bits 4 through 7.',
    a0Source: 'fn f u32 -> u32\nsh shr p0 4\nm and sh 15\nret m\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [255], expected: 0 },
      { fn: 'f', args: [256], expected: 1 },
      { fn: 'f', args: [4096], expected: 16 },
      { fn: 'f', args: [4660], expected: 18 },
      { fn: 'f', args: [43981], expected: 171 },
      { fn: 'f', args: [65280], expected: 255 },
      { fn: 'f', args: [65535], expected: 255 },
      { fn: 'f', args: [4294967295], expected: 255 },
    ],
    reference: { a0: 'fn f u32 -> u32\nsh shr p0 8\nm and sh 255\nret m\nend\n' },
    wrongEdits: ['fn f u32 -> u32\nsh shr p0 8\nm and sh 15\nret m\nend\n'],
  },
  {
    id: 'h-swap-ends',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Read index and write index both change; wrong edit writes the wrong saved value.',
    instruction:
      'Change the function so it swaps the first and last elements of the array instead of the first two.',
    a0Source:
      'fn f u32x4 -> u32x4\nx get p0 0\ny get p0 1\nu set p0 0 y\nv set u 1 x\nret v\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4]], expected: [4, 2, 3, 1] },
      { fn: 'f', args: [[0, 0, 0, 0]], expected: [0, 0, 0, 0] },
      { fn: 'f', args: [[5, 6, 7, 5]], expected: [5, 6, 7, 5] },
      { fn: 'f', args: [[9, 0, 0, 1]], expected: [1, 0, 0, 9] },
      { fn: 'f', args: [[4294967295, 1, 2, 0]], expected: [0, 1, 2, 4294967295] },
      { fn: 'f', args: [[1, 1, 2, 2]], expected: [2, 1, 2, 1] },
      { fn: 'f', args: [[7, 8, 9, 10]], expected: [10, 8, 9, 7] },
      { fn: 'f', args: [[3, 3, 3, 4]], expected: [4, 3, 3, 3] },
    ],
    reference: {
      a0: 'fn f u32x4 -> u32x4\nx get p0 0\ny get p0 3\nu set p0 0 y\nv set u 3 x\nret v\nend\n',
    },
    wrongEdits: [
      'fn f u32x4 -> u32x4\nx get p0 0\ny get p0 3\nu set p0 0 y\nv set u 3 y\nret v\nend\n',
    ],
  },
  {
    id: 'h-count-above',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Fold skips the last element; a count of 5 revisits index 0 via modulo indexing.',
    instruction:
      'Return how many of the four array elements are strictly greater than the second argument.',
    a0Source:
      'fn cnt u32 u32 u32x4 u32 -> u32\ng get p2 p1\nc gt g p3\none select c 1 0\ns add p0 one\nret s\nend\nfn f u32x4 u32 -> u32\nn fold cnt 3 0 p0 p1\nr mov n\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 2], expected: 2 },
      { fn: 'f', args: [[0, 0, 0, 0], 0], expected: 0 },
      { fn: 'f', args: [[5, 5, 5, 5], 4], expected: 4 },
      { fn: 'f', args: [[5, 5, 5, 5], 5], expected: 0 },
      { fn: 'f', args: [[4294967295, 0, 0, 0], 4294967294], expected: 1 },
      { fn: 'f', args: [[0, 0, 0, 9], 8], expected: 1 },
      { fn: 'f', args: [[1, 2, 3, 4], 0], expected: 4 },
      { fn: 'f', args: [[1, 2, 3, 4], 4294967295], expected: 0 },
      { fn: 'f', args: [[5, 0, 0, 0], 1], expected: 1 },
    ],
    reference: {
      a0: 'fn cnt u32 u32 u32x4 u32 -> u32\ng get p2 p1\nc gt g p3\none select c 1 0\ns add p0 one\nret s\nend\nfn f u32x4 u32 -> u32\nn fold cnt 4 0 p0 p1\nr mov n\nret r\nend\n',
    },
    wrongEdits: [
      'fn cnt u32 u32 u32x4 u32 -> u32\ng get p2 p1\nc gt g p3\none select c 1 0\ns add p0 one\nret s\nend\nfn f u32x4 u32 -> u32\nn fold cnt 5 0 p0 p1\nr mov n\nret r\nend\n',
    ],
  },
  {
    id: 'h-array-min',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'The helper already keeps the minimum; the starting state 0 makes the result always 0.',
    instruction: 'Return the smallest element of the array.',
    a0Source:
      'fn mn u32 u32 u32x4 -> u32\ng get p2 p1\nc lt g p0\ns select c g p0\nret s\nend\nfn f u32x4 -> u32\nm fold mn 4 0 p0\nr mov m\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4]], expected: 1 },
      { fn: 'f', args: [[4, 3, 2, 1]], expected: 1 },
      { fn: 'f', args: [[0, 5, 5, 5]], expected: 0 },
      { fn: 'f', args: [[7, 7, 7, 7]], expected: 7 },
      { fn: 'f', args: [[4294967295, 4294967295, 4294967295, 4294967295]], expected: 4294967295 },
      { fn: 'f', args: [[9, 8, 10, 11]], expected: 8 },
      { fn: 'f', args: [[100, 0, 100, 100]], expected: 0 },
      { fn: 'f', args: [[3, 9, 9, 2]], expected: 2 },
    ],
    reference: {
      a0: 'fn mn u32 u32 u32x4 -> u32\ng get p2 p1\nc lt g p0\ns select c g p0\nret s\nend\nfn f u32x4 -> u32\nm fold mn 4 4294967295 p0\nr mov m\nret r\nend\n',
    },
    wrongEdits: [
      'fn mn u32 u32 u32x4 -> u32\ng get p2 p1\nc lt g p0\ns select c g p0\nret s\nend\nfn f u32x4 -> u32\nm fold mn 3 4294967295 p0\nr mov m\nret r\nend\n',
    ],
  },
  {
    id: 'h-one-low-bit',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'bit-mask',
    note: "Start computes 'both bits equal'; wrong edit compares bit 0 against unshifted bit 1 (value 2).",
    instruction: 'Return true when exactly one of the two lowest bits of the argument is set.',
    a0Source: 'fn f u32 -> bool\na and p0 1\nb shr p0 1\nc and b 1\nd eq a c\nret d\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: false },
      { fn: 'f', args: [1], expected: true },
      { fn: 'f', args: [2], expected: true },
      { fn: 'f', args: [3], expected: false },
      { fn: 'f', args: [4], expected: false },
      { fn: 'f', args: [5], expected: true },
      { fn: 'f', args: [6], expected: true },
      { fn: 'f', args: [7], expected: false },
      { fn: 'f', args: [4294967294], expected: true },
      { fn: 'f', args: [4294967295], expected: false },
    ],
    reference: {
      a0: 'fn f u32 -> bool\na and p0 1\nb shr p0 1\nc and b 1\nd ne a c\nret d\nend\n',
    },
    wrongEdits: ['fn f u32 -> bool\na and p0 1\nb shr p0 1\nc and p0 2\nd ne a c\nret d\nend\n'],
  },
  {
    id: 'h-clamp-range',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'order',
    note: 'Helper only caps from above; lower bound must be applied before calling it.',
    instruction:
      'Return the first argument clamped to the range from 10 up to the second argument: raise it to 10 if smaller, then lower it to the second argument if larger (the upper limit wins when it is below 10).',
    a0Source:
      'fn cap u32 u32 -> u32\no gt p0 p1\nv select o p1 p0\nret v\nend\nfn f u32 u32 -> u32\nk call cap p0 p1\nr mov k\nret r\nend\n',
    tests: [
      { fn: 'f', args: [5, 100], expected: 10 },
      { fn: 'f', args: [9, 100], expected: 10 },
      { fn: 'f', args: [10, 100], expected: 10 },
      { fn: 'f', args: [50, 100], expected: 50 },
      { fn: 'f', args: [100, 100], expected: 100 },
      { fn: 'f', args: [150, 100], expected: 100 },
      { fn: 'f', args: [5, 3], expected: 3 },
      { fn: 'f', args: [20, 3], expected: 3 },
      { fn: 'f', args: [0, 4294967295], expected: 10 },
      { fn: 'f', args: [4294967295, 4294967295], expected: 4294967295 },
    ],
    reference: {
      a0: 'fn cap u32 u32 -> u32\no gt p0 p1\nv select o p1 p0\nret v\nend\nfn f u32 u32 -> u32\nsmall lt p0 10\nup select small 10 p0\nk call cap up p1\nr mov k\nret r\nend\n',
    },
    wrongEdits: [
      'fn cap u32 u32 -> u32\no gt p0 p1\nv select o p1 p0\nret v\nend\nfn f u32 u32 -> u32\nk call cap p0 p1\nsmall lt k 10\nr select small 10 k\nret r\nend\n',
    ],
  },
];
