/**
 * Held-out task set S (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-s/s-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-s.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskS {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_S: readonly TaskS[] = [
  {
    id: 's-overtime-pay',
    kind: 'targeted-edit',
    target: 'pay',
    wrongEditKind: 'off-by-one',
    note: 'Changed constant inside a comparison chained with select.',
    instruction:
      'Overtime pay (15 per hour instead of 10) should start after 38 hours instead of after 40.',
    a0Source:
      'fn pay u32 -> u32\no gt p0 40\nb mul p0 10\nx sub p0 40\ny mul x 15\nz mul 40 10\nw add z y\nr select o w b\nret r\nend\n',
    tests: [
      { fn: 'pay', args: [0], expected: 0 },
      { fn: 'pay', args: [37], expected: 370 },
      { fn: 'pay', args: [38], expected: 380 },
      { fn: 'pay', args: [39], expected: 395 },
      { fn: 'pay', args: [40], expected: 410 },
      { fn: 'pay', args: [41], expected: 425 },
      { fn: 'pay', args: [50], expected: 560 },
      { fn: 'pay', args: [1], expected: 10 },
    ],
    reference: {
      a0: 'fn pay u32 -> u32\no gt p0 38\nb mul p0 10\nx sub p0 38\ny mul x 15\nz mul 38 10\nw add z y\nr select o w b\nret r\nend\n',
    },
    wrongEdits: [
      'fn pay u32 -> u32\no gt p0 37\nb mul p0 10\nx sub p0 37\ny mul x 15\nz mul 37 10\nw add z y\nr select o w b\nret r\nend\n',
    ],
  },
  {
    id: 's-speed-ticket',
    kind: 'targeted-edit',
    target: 'ticket',
    wrongEditKind: 'comparison',
    note: 'Boundary at equality in the first of two chained selects.',
    instruction:
      'Return 0 when the speed (first argument) is at or below the limit (second argument), 1 when it is at most 10 over the limit, and 2 otherwise; a speed exactly equal to the limit currently gets the wrong code.',
    a0Source:
      'fn ticket u32 u32 -> u32\nl2 add p1 10\na lt p0 p1\nb le p0 l2\nm select b 1 2\nr select a 0 m\nret r\nend\n',
    tests: [
      { fn: 'ticket', args: [50, 50], expected: 0 },
      { fn: 'ticket', args: [49, 50], expected: 0 },
      { fn: 'ticket', args: [51, 50], expected: 1 },
      { fn: 'ticket', args: [60, 50], expected: 1 },
      { fn: 'ticket', args: [61, 50], expected: 2 },
      { fn: 'ticket', args: [0, 0], expected: 0 },
      { fn: 'ticket', args: [10, 0], expected: 1 },
      { fn: 'ticket', args: [11, 0], expected: 2 },
      { fn: 'ticket', args: [100, 30], expected: 2 },
    ],
    reference: {
      a0: 'fn ticket u32 u32 -> u32\nl2 add p1 10\na le p0 p1\nb le p0 l2\nm select b 1 2\nr select a 0 m\nret r\nend\n',
    },
    wrongEdits: [
      'fn ticket u32 u32 -> u32\nl2 add p1 10\na le p0 p1\nb lt p0 l2\nm select b 1 2\nr select a 0 m\nret r\nend\n',
    ],
  },
  {
    id: 's-middle-nibble',
    kind: 'targeted-edit',
    target: 'field',
    wrongEditKind: 'wrapping',
    note: 'Mask is one bit too narrow; the wrong edit is one bit too wide.',
    instruction: 'Return bits 4 through 7 of the argument as a number from 0 to 15.',
    a0Source: 'fn field u32 -> u32\ns shr p0 4\nr and s 7\nret r\nend\n',
    tests: [
      { fn: 'field', args: [0], expected: 0 },
      { fn: 'field', args: [240], expected: 15 },
      { fn: 'field', args: [128], expected: 8 },
      { fn: 'field', args: [112], expected: 7 },
      { fn: 'field', args: [255], expected: 15 },
      { fn: 'field', args: [496], expected: 15 },
      { fn: 'field', args: [4294967295], expected: 15 },
      { fn: 'field', args: [16], expected: 1 },
      { fn: 'field', args: [256], expected: 0 },
    ],
    reference: { a0: 'fn field u32 -> u32\ns shr p0 4\nr and s 15\nret r\nend\n' },
    wrongEdits: ['fn field u32 -> u32\ns shr p0 4\nr and s 31\nret r\nend\n'],
  },
  {
    id: 's-fits-24-bits',
    kind: 'targeted-edit',
    target: 'fits24',
    wrongEditKind: 'off-by-one',
    note: 'Bool result; shift distance off by one.',
    instruction: 'Return true exactly when the value fits in 24 bits (is below 16777216).',
    a0Source: 'fn fits24 u32 -> bool\nh shr p0 23\nr eq h 0\nret r\nend\n',
    tests: [
      { fn: 'fits24', args: [0], expected: true },
      { fn: 'fits24', args: [8388607], expected: true },
      { fn: 'fits24', args: [8388608], expected: true },
      { fn: 'fits24', args: [16777215], expected: true },
      { fn: 'fits24', args: [16777216], expected: false },
      { fn: 'fits24', args: [33554431], expected: false },
      { fn: 'fits24', args: [33554432], expected: false },
      { fn: 'fits24', args: [4294967295], expected: false },
    ],
    reference: { a0: 'fn fits24 u32 -> bool\nh shr p0 24\nr eq h 0\nret r\nend\n' },
    wrongEdits: ['fn fits24 u32 -> bool\nh shr p0 25\nr eq h 0\nret r\nend\n'],
  },
  {
    id: 's-clear-next-slot',
    kind: 'targeted-edit',
    target: 'clearnext',
    wrongEditKind: 'off-by-one',
    note: 'Array update with modulo index.',
    instruction:
      'Set to zero the slot just after the given index, wrapping from the last slot back to the first; the other slots stay unchanged.',
    a0Source: 'fn clearnext u32x4 u32 -> u32x4\nj add p1 0\nr set p0 j 0\nret r\nend\n',
    tests: [
      { fn: 'clearnext', args: [[1, 2, 3, 4], 0], expected: [1, 0, 3, 4] },
      { fn: 'clearnext', args: [[1, 2, 3, 4], 1], expected: [1, 2, 0, 4] },
      { fn: 'clearnext', args: [[1, 2, 3, 4], 2], expected: [1, 2, 3, 0] },
      { fn: 'clearnext', args: [[1, 2, 3, 4], 3], expected: [0, 2, 3, 4] },
      { fn: 'clearnext', args: [[5, 6, 7, 8], 4], expected: [5, 0, 7, 8] },
      { fn: 'clearnext', args: [[9, 9, 9, 9], 7], expected: [0, 9, 9, 9] },
      { fn: 'clearnext', args: [[0, 1, 0, 1], 0], expected: [0, 0, 0, 1] },
      { fn: 'clearnext', args: [[7, 0, 7, 0], 2], expected: [7, 0, 7, 0] },
    ],
    reference: { a0: 'fn clearnext u32x4 u32 -> u32x4\nj add p1 1\nr set p0 j 0\nret r\nend\n' },
    wrongEdits: ['fn clearnext u32x4 u32 -> u32x4\nj sub p1 1\nr set p0 j 0\nret r\nend\n'],
  },
  {
    id: 's-count-descents',
    kind: 'targeted-edit',
    target: 'descents',
    wrongEditKind: 'fold-bound',
    note: 'Fold count includes the wrap-around pair in start.',
    instruction:
      'Count the places where an element is smaller than the element just before it, looking only at the three neighbouring pairs (no wrap from the last element back to the first).',
    a0Source:
      'fn step u32 u32 u32x4 -> u32\nn add p1 1\na get p2 p1\nb get p2 n\nd lt b a\ni select d 1 0\nr add p0 i\nret r\nend\nfn descents u32x4 -> u32\nc fold step 4 0 p0\nr mov c\nret r\nend\n',
    tests: [
      { fn: 'descents', args: [[1, 2, 3, 4]], expected: 0 },
      { fn: 'descents', args: [[4, 3, 2, 1]], expected: 3 },
      { fn: 'descents', args: [[1, 2, 3, 0]], expected: 1 },
      { fn: 'descents', args: [[5, 1, 5, 1]], expected: 2 },
      { fn: 'descents', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'descents', args: [[2, 1, 1, 1]], expected: 1 },
      { fn: 'descents', args: [[1, 1, 1, 2]], expected: 0 },
      { fn: 'descents', args: [[3, 4, 1, 2]], expected: 1 },
      { fn: 'descents', args: [[9, 8, 9, 8]], expected: 2 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32x4 -> u32\nn add p1 1\na get p2 p1\nb get p2 n\nd lt b a\ni select d 1 0\nr add p0 i\nret r\nend\nfn descents u32x4 -> u32\nc fold step 3 0 p0\nr mov c\nret r\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32x4 -> u32\nn add p1 1\na get p2 p1\nb get p2 n\nd lt b a\ni select d 1 0\nr add p0 i\nret r\nend\nfn descents u32x4 -> u32\nc fold step 2 0 p0\nr mov c\nret r\nend\n',
    ],
  },
  {
    id: 's-member-price',
    kind: 'targeted-edit',
    target: 'price',
    wrongEditKind: 'changed-constant',
    note: 'Record parameter and helper call.',
    instruction:
      "Members (the record's flag) should get ten per cent off (the discount rounded down) instead of twenty per cent; non-members pay the full price.",
    a0Source:
      'fn cut u32 -> u32\nq div p0 5\nr mov q\nret r\nend\nfn price (u32,bool) -> u32\nv at p0 0\nm at p0 1\nc call cut v\nd sub v c\nr select m d v\nret r\nend\n',
    tests: [
      { fn: 'price', args: [[100, true]], expected: 90 },
      { fn: 'price', args: [[100, false]], expected: 100 },
      { fn: 'price', args: [[0, true]], expected: 0 },
      { fn: 'price', args: [[9, true]], expected: 9 },
      { fn: 'price', args: [[10, true]], expected: 9 },
      { fn: 'price', args: [[95, true]], expected: 86 },
      { fn: 'price', args: [[999, true]], expected: 900 },
      { fn: 'price', args: [[50, false]], expected: 50 },
      { fn: 'price', args: [[4294967295, true]], expected: 3865470566 },
    ],
    reference: {
      a0: 'fn cut u32 -> u32\nq div p0 10\nr mov q\nret r\nend\nfn price (u32,bool) -> u32\nv at p0 0\nm at p0 1\nc call cut v\nd sub v c\nr select m d v\nret r\nend\n',
    },
    wrongEdits: [
      'fn cut u32 -> u32\nq div p0 9\nr mov q\nret r\nend\nfn price (u32,bool) -> u32\nv at p0 0\nm at p0 1\nc call cut v\nd sub v c\nr select m d v\nret r\nend\n',
    ],
  },
  {
    id: 's-two-thirds-quorum',
    kind: 'targeted-edit',
    target: 'quorum',
    wrongEditKind: 'comparison',
    note: 'Bool result; swapped constants in the wrong edit.',
    instruction:
      'Return true when the yes votes (first argument) are at least two thirds of the total (second argument); exactly two thirds should pass.',
    a0Source: 'fn quorum u32 u32 -> bool\nx mul p0 3\ny mul p1 2\nr gt x y\nret r\nend\n',
    tests: [
      { fn: 'quorum', args: [2, 3], expected: true },
      { fn: 'quorum', args: [1, 3], expected: false },
      { fn: 'quorum', args: [3, 3], expected: true },
      { fn: 'quorum', args: [0, 0], expected: true },
      { fn: 'quorum', args: [4, 6], expected: true },
      { fn: 'quorum', args: [3, 6], expected: false },
      { fn: 'quorum', args: [7, 10], expected: true },
      { fn: 'quorum', args: [6, 10], expected: false },
      { fn: 'quorum', args: [0, 1], expected: false },
    ],
    reference: { a0: 'fn quorum u32 u32 -> bool\nx mul p0 3\ny mul p1 2\nr ge x y\nret r\nend\n' },
    wrongEdits: ['fn quorum u32 u32 -> bool\nx mul p0 2\ny mul p1 3\nr ge x y\nret r\nend\n'],
  },
  {
    id: 's-tank-refill',
    kind: 'multi-node-edit',
    target: 'refill',
    wrongEditKind: 'comparison',
    note: 'Record result built from a comparison chained with select.',
    instruction:
      'Adding 25 to the level (first argument) must not go over the capacity (second argument): when it would, return the capacity and true, otherwise the new level and false.',
    a0Source: 'fn refill u32 u32 -> (u32,bool)\ns add p0 25\nr rec s false\nret r\nend\n',
    tests: [
      { fn: 'refill', args: [0, 100], expected: [25, false] },
      { fn: 'refill', args: [75, 100], expected: [100, false] },
      { fn: 'refill', args: [76, 100], expected: [100, true] },
      { fn: 'refill', args: [74, 100], expected: [99, false] },
      { fn: 'refill', args: [100, 100], expected: [100, true] },
      { fn: 'refill', args: [0, 25], expected: [25, false] },
      { fn: 'refill', args: [0, 24], expected: [24, true] },
      { fn: 'refill', args: [10, 0], expected: [0, true] },
    ],
    reference: {
      a0: 'fn refill u32 u32 -> (u32,bool)\ns add p0 25\no gt s p1\nl select o p1 s\nr rec l o\nret r\nend\n',
    },
    wrongEdits: [
      'fn refill u32 u32 -> (u32,bool)\ns add p0 25\no ge s p1\nl select o p1 s\nr rec l o\nret r\nend\n',
    ],
  },
  {
    id: 's-bonus-both',
    kind: 'multi-node-edit',
    target: 'total',
    wrongEditKind: 'swapped-argument',
    note: 'Helper call must be applied twice, not to the sum.',
    instruction:
      'Apply the bonus helper to each of the two scores separately and return the sum of the two bonused scores.',
    a0Source:
      'fn bonus u32 -> u32\nd mul p0 2\nr add d 1\nret r\nend\nfn total u32 u32 -> u32\na call bonus p0\nr add a p1\nret r\nend\n',
    tests: [
      { fn: 'total', args: [0, 0], expected: 2 },
      { fn: 'total', args: [1, 0], expected: 4 },
      { fn: 'total', args: [0, 1], expected: 4 },
      { fn: 'total', args: [3, 4], expected: 16 },
      { fn: 'total', args: [10, 10], expected: 42 },
      { fn: 'total', args: [2147483647, 0], expected: 0 },
      { fn: 'total', args: [2147483648, 1], expected: 4 },
      { fn: 'total', args: [100, 5], expected: 212 },
    ],
    reference: {
      a0: 'fn bonus u32 -> u32\nd mul p0 2\nr add d 1\nret r\nend\nfn total u32 u32 -> u32\na call bonus p0\nb call bonus p1\nr add a b\nret r\nend\n',
    },
    wrongEdits: [
      'fn bonus u32 -> u32\nd mul p0 2\nr add d 1\nret r\nend\nfn total u32 u32 -> u32\ns add p0 p1\nr call bonus s\nret r\nend\n',
    ],
  },
  {
    id: 's-shift-in',
    kind: 'multi-node-edit',
    target: 'pushback',
    wrongEditKind: 'swapped-argument',
    note: 'Array rebuilt with every element moving.',
    instruction:
      'Drop the first element, move the others one place towards the front, and put the new value (second argument) in the last slot.',
    a0Source: 'fn pushback u32x4 u32 -> u32x4\nr set p0 3 p1\no mov r\nret o\nend\n',
    tests: [
      { fn: 'pushback', args: [[1, 2, 3, 4], 9], expected: [2, 3, 4, 9] },
      { fn: 'pushback', args: [[0, 0, 0, 0], 0], expected: [0, 0, 0, 0] },
      { fn: 'pushback', args: [[1, 2, 3, 4], 4], expected: [2, 3, 4, 4] },
      { fn: 'pushback', args: [[5, 5, 5, 5], 1], expected: [5, 5, 5, 1] },
      { fn: 'pushback', args: [[7, 8, 9, 10], 0], expected: [8, 9, 10, 0] },
      { fn: 'pushback', args: [[1, 1, 1, 2], 2], expected: [1, 1, 2, 2] },
      { fn: 'pushback', args: [[4, 3, 2, 1], 5], expected: [3, 2, 1, 5] },
      { fn: 'pushback', args: [[0, 1, 2, 3], 3], expected: [1, 2, 3, 3] },
    ],
    reference: {
      a0: 'fn pushback u32x4 u32 -> u32x4\ne0 get p0 0\ne1 get p0 1\ne2 get p0 2\ne3 get p0 3\nr arr e1 e2 e3 p1\nret r\nend\n',
    },
    wrongEdits: [
      'fn pushback u32x4 u32 -> u32x4\ne0 get p0 0\ne1 get p0 1\ne2 get p0 2\ne3 get p0 3\nr arr p1 e0 e1 e2\nret r\nend\n',
    ],
  },
  {
    id: 's-window-ok',
    kind: 'multi-node-edit',
    target: 'window',
    wrongEditKind: 'off-by-one',
    note: 'Bool result with a new conjunct.',
    instruction:
      'Return true when the start (first argument) is below the end (second argument) and the end is below 100.',
    a0Source: 'fn window u32 u32 -> bool\na lt p0 p1\nr mov a\nret r\nend\n',
    tests: [
      { fn: 'window', args: [0, 1], expected: true },
      { fn: 'window', args: [1, 0], expected: false },
      { fn: 'window', args: [5, 5], expected: false },
      { fn: 'window', args: [0, 99], expected: true },
      { fn: 'window', args: [0, 100], expected: false },
      { fn: 'window', args: [0, 101], expected: false },
      { fn: 'window', args: [99, 100], expected: false },
      { fn: 'window', args: [50, 4294967295], expected: false },
      { fn: 'window', args: [98, 99], expected: true },
    ],
    reference: {
      a0: 'fn window u32 u32 -> bool\na lt p0 p1\nb lt p1 100\nr and a b\nret r\nend\n',
    },
    wrongEdits: ['fn window u32 u32 -> bool\na lt p0 p1\nb le p1 100\nr and a b\nret r\nend\n'],
  },
  {
    id: 's-equal-kind',
    kind: 'comprehension-edit',
    target: 'kind',
    wrongEditKind: 'comparison',
    note: 'Comparisons chained through two selects.',
    instruction:
      'The function should return 2 when all three values are equal, 1 when exactly two are equal, and 0 when all differ; it currently misses one pair.',
    a0Source:
      'fn kind u32 u32 u32 -> u32\nx eq p0 p1\ny eq p1 p2\nany or x y\nall and x y\nm select any 1 0\nr select all 2 m\nret r\nend\n',
    tests: [
      { fn: 'kind', args: [1, 1, 1], expected: 2 },
      { fn: 'kind', args: [1, 2, 3], expected: 0 },
      { fn: 'kind', args: [1, 1, 2], expected: 1 },
      { fn: 'kind', args: [2, 1, 1], expected: 1 },
      { fn: 'kind', args: [1, 2, 1], expected: 1 },
      { fn: 'kind', args: [0, 0, 5], expected: 1 },
      { fn: 'kind', args: [5, 0, 5], expected: 1 },
      { fn: 'kind', args: [7, 8, 7], expected: 1 },
      { fn: 'kind', args: [3, 3, 3], expected: 2 },
    ],
    reference: {
      a0: 'fn kind u32 u32 u32 -> u32\nx eq p0 p1\ny eq p1 p2\nz eq p0 p2\nw or x y\nany or w z\nall and x y\nm select any 1 0\nr select all 2 m\nret r\nend\n',
    },
    wrongEdits: [
      'fn kind u32 u32 u32 -> u32\nx eq p0 p1\ny eq p1 p2\nz eq p0 p2\nw and x y\nany or w z\nall and x y\nm select any 1 0\nr select all 2 m\nret r\nend\n',
    ],
  },
  {
    id: 's-first-largest-index',
    kind: 'comprehension-edit',
    target: 'argmax',
    wrongEditKind: 'comparison',
    note: 'Fold over a record state; ge picks the last tie.',
    instruction:
      'Return the position of the largest element; when the largest value appears more than once, return its first position.',
    a0Source:
      'fn better (u32,u32) u32 u32x4 -> (u32,u32)\nbv at p0 0\ne get p2 p1\ng ge e bv\nnv select g e bv\nbi at p0 1\nni select g p1 bi\nr rec nv ni\nret r\nend\nfn argmax u32x4 -> u32\ni get p0 0\ns rec i 0\nf fold better 4 s p0\nr at f 1\nret r\nend\n',
    tests: [
      { fn: 'argmax', args: [[1, 2, 3, 4]], expected: 3 },
      { fn: 'argmax', args: [[4, 3, 2, 1]], expected: 0 },
      { fn: 'argmax', args: [[5, 5, 5, 5]], expected: 0 },
      { fn: 'argmax', args: [[1, 7, 7, 0]], expected: 1 },
      { fn: 'argmax', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'argmax', args: [[2, 9, 1, 9]], expected: 1 },
      { fn: 'argmax', args: [[3, 1, 3, 2]], expected: 0 },
      { fn: 'argmax', args: [[0, 0, 0, 1]], expected: 3 },
      { fn: 'argmax', args: [[8, 1, 1, 8]], expected: 0 },
    ],
    reference: {
      a0: 'fn better (u32,u32) u32 u32x4 -> (u32,u32)\nbv at p0 0\ne get p2 p1\ng gt e bv\nnv select g e bv\nbi at p0 1\nni select g p1 bi\nr rec nv ni\nret r\nend\nfn argmax u32x4 -> u32\ni get p0 0\ns rec i 0\nf fold better 4 s p0\nr at f 1\nret r\nend\n',
    },
    wrongEdits: [
      'fn better (u32,u32) u32 u32x4 -> (u32,u32)\nbv at p0 0\ne get p2 p1\ng gt e bv\nnv select g e bv\nbi at p0 1\nni select g p1 bi\nr rec nv ni\nret r\nend\nfn argmax u32x4 -> u32\ni get p0 0\ns rec i 0\nf fold better 4 s p0\nr at f 0\nret r\nend\n',
    ],
  },
  {
    id: 's-alternating-sum',
    kind: 'comprehension-edit',
    target: 'altsum',
    wrongEditKind: 'swapped-argument',
    note: 'Wrapping results such as 0 minus 1.',
    instruction:
      'Return the first element minus the second plus the third minus the fourth, with u32 wrapping.',
    a0Source:
      'fn acc u32 u32 u32x4 -> u32\ne get p2 p1\nr add p0 e\nret r\nend\nfn altsum u32x4 -> u32\nt fold acc 4 0 p0\nr mov t\nret r\nend\n',
    tests: [
      { fn: 'altsum', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'altsum', args: [[5, 3, 2, 1]], expected: 3 },
      { fn: 'altsum', args: [[1, 2, 0, 0]], expected: 4294967295 },
      { fn: 'altsum', args: [[0, 1, 0, 0]], expected: 4294967295 },
      { fn: 'altsum', args: [[10, 1, 10, 1]], expected: 18 },
      { fn: 'altsum', args: [[4294967295, 4294967295, 0, 0]], expected: 0 },
      { fn: 'altsum', args: [[1, 0, 0, 0]], expected: 1 },
      { fn: 'altsum', args: [[0, 0, 0, 5]], expected: 4294967291 },
      { fn: 'altsum', args: [[3, 3, 3, 3]], expected: 0 },
    ],
    reference: {
      a0: 'fn acc u32 u32 u32x4 -> u32\ne get p2 p1\no and p1 1\nodd eq o 1\na add p0 e\ns sub p0 e\nr select odd s a\nret r\nend\nfn altsum u32x4 -> u32\nt fold acc 4 0 p0\nr mov t\nret r\nend\n',
    },
    wrongEdits: [
      'fn acc u32 u32 u32x4 -> u32\ne get p2 p1\no and p1 1\nodd eq o 1\na add p0 e\ns sub p0 e\nr select odd a s\nret r\nend\nfn altsum u32x4 -> u32\nt fold acc 4 0 p0\nr mov t\nret r\nend\n',
    ],
  },
  {
    id: 's-pack-flag',
    kind: 'comprehension-edit',
    target: 'pack',
    wrongEditKind: 'wrapping',
    note: 'Shift by 32 is a shift by 0 under the low-five-bits rule.',
    instruction:
      "Return the record's number with its top bit (bit 31) replaced by the record's flag: set when the flag is true, cleared when it is false.",
    a0Source:
      'fn pack (u32,bool) -> u32\nv at p0 0\nf at p0 1\nt select f 1 0\nh shl t 31\nr or v h\nret r\nend\n',
    tests: [
      { fn: 'pack', args: [[0, false]], expected: 0 },
      { fn: 'pack', args: [[0, true]], expected: 2147483648 },
      { fn: 'pack', args: [[5, true]], expected: 2147483653 },
      { fn: 'pack', args: [[5, false]], expected: 5 },
      { fn: 'pack', args: [[2147483648, false]], expected: 0 },
      { fn: 'pack', args: [[2147483648, true]], expected: 2147483648 },
      { fn: 'pack', args: [[4294967295, false]], expected: 2147483647 },
      { fn: 'pack', args: [[4294967295, true]], expected: 4294967295 },
      { fn: 'pack', args: [[2147483647, true]], expected: 4294967295 },
    ],
    reference: {
      a0: 'fn pack (u32,bool) -> u32\nv at p0 0\nf at p0 1\nt select f 1 0\nh shl t 31\nl and v 2147483647\nr or l h\nret r\nend\n',
    },
    wrongEdits: [
      'fn pack (u32,bool) -> u32\nv at p0 0\nf at p0 1\nt select f 1 0\nh shl t 32\nl and v 2147483647\nr or l h\nret r\nend\n',
    ],
  },
];
