/**
 * Held-out task set U (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-u/u-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-u.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskU {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_U: readonly TaskU[] = [
  {
    id: 'u-same-top-byte',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'Second shift amount wrong; the wrong edit shifts by 23 and so also compares bit 23.',
    instruction:
      "Return true when both values have the same top 8 bits (bits 24 to 31) and the first value's lowest byte is not zero.",
    a0Source:
      'fn f u32 u32 -> bool\na shr p0 24\nb shr p1 16\nc eq a b\nd and p0 255\ne ne d 0\ng and c e\nret g\nend\n',
    tests: [
      { fn: 'f', args: [301989889, 301989888], expected: true },
      { fn: 'f', args: [305419777, 318767103], expected: true },
      { fn: 'f', args: [301990144, 301989888], expected: false },
      { fn: 'f', args: [4278190081, 4261412865], expected: false },
      { fn: 'f', args: [1, 0], expected: true },
      { fn: 'f', args: [2147483653, 2164260863], expected: true },
      { fn: 'f', args: [318767105, 301989888], expected: false },
      { fn: 'f', args: [4294967295, 4294967295], expected: true },
      { fn: 'f', args: [16777217, 8388608], expected: false },
    ],
    reference: {
      a0: 'fn f u32 u32 -> bool\na shr p0 24\nb shr p1 24\nc eq a b\nd and p0 255\ne ne d 0\ng and c e\nret g\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> bool\na shr p0 24\nb shr p1 23\nc eq a b\nd and p0 255\ne ne d 0\ng and c e\nret g\nend\n',
    ],
  },
  {
    id: 'u-window-of-three',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Third element offset wrong (3 instead of 2); wrong edit repeats the second element.',
    instruction:
      'Return the sum of three consecutive elements starting at the given index, where positions past the end wrap around to the start.',
    a0Source:
      'fn f u32x4 u32 -> u32\na get p0 p1\nb add p1 1\nc get p0 b\nd add p1 3\ne get p0 d\ng add a c\nh add g e\nret h\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 0], expected: 6 },
      { fn: 'f', args: [[1, 2, 3, 4], 1], expected: 9 },
      { fn: 'f', args: [[1, 2, 3, 4], 2], expected: 8 },
      { fn: 'f', args: [[1, 2, 3, 4], 3], expected: 7 },
      { fn: 'f', args: [[10, 20, 30, 40], 5], expected: 90 },
      { fn: 'f', args: [[0, 0, 0, 7], 0], expected: 0 },
      { fn: 'f', args: [[4294967295, 1, 0, 0], 0], expected: 0 },
      { fn: 'f', args: [[5, 6, 7, 8], 4294967295], expected: 19 },
      { fn: 'f', args: [[1, 10, 100, 1000], 7], expected: 1011 },
    ],
    reference: {
      a0: 'fn f u32x4 u32 -> u32\na get p0 p1\nb add p1 1\nc get p0 b\nd add p1 2\ne get p0 d\ng add a c\nh add g e\nret h\nend\n',
    },
    wrongEdits: [
      'fn f u32x4 u32 -> u32\na get p0 p1\nb add p1 1\nc get p0 b\nd add p1 1\ne get p0 d\ng add a c\nh add g e\nret h\nend\n',
    ],
  },
  {
    id: 'u-tie-break-winner',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Equal entrant numbers must not win; wrong edit lets every score tie win.',
    instruction:
      'Given scores p0, p1 and entrant numbers p2, p3, return true when the first entrant wins: a higher score wins, and on equal scores the strictly lower entrant number wins.',
    a0Source:
      'fn f u32 u32 u32 u32 -> bool\na gt p0 p1\nb eq p0 p1\nc le p2 p3\nd and b c\ne or a d\ng mov e\nret g\nend\n',
    tests: [
      { fn: 'f', args: [5, 4, 9, 1], expected: true },
      { fn: 'f', args: [4, 5, 1, 9], expected: false },
      { fn: 'f', args: [5, 5, 1, 2], expected: true },
      { fn: 'f', args: [5, 5, 2, 1], expected: false },
      { fn: 'f', args: [5, 5, 3, 3], expected: false },
      { fn: 'f', args: [0, 0, 0, 0], expected: false },
      { fn: 'f', args: [4294967295, 4294967295, 0, 4294967295], expected: true },
      { fn: 'f', args: [4294967295, 0, 4294967295, 0], expected: true },
      { fn: 'f', args: [0, 4294967295, 0, 1], expected: false },
      { fn: 'f', args: [7, 7, 4294967295, 4294967295], expected: false },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 u32 -> bool\na gt p0 p1\nb eq p0 p1\nc lt p2 p3\nd and b c\ne or a d\ng mov e\nret g\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 u32 u32 -> bool\na ge p0 p1\nb eq p0 p1\nc lt p2 p3\nd and b c\ne or a d\ng mov e\nret g\nend\n',
    ],
  },
  {
    id: 'u-pack-four-bytes',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'bit-position',
    note: "Third byte shifted into the second byte's place; wrong edit drops the mask on the third argument.",
    instruction:
      'Pack the low bytes of the four arguments into one word: the first argument in bits 0 to 7, the second in bits 8 to 15, the third in bits 16 to 23 and the fourth in bits 24 to 31.',
    a0Source:
      'fn f u32 u32 u32 u32 -> u32\na and p0 255\nb and p1 255\nc shl b 8\nd and p2 255\ne shl d 8\ng shl p3 24\nh or a c\ni or h e\nj or i g\nret j\nend\n',
    tests: [
      { fn: 'f', args: [1, 2, 3, 4], expected: 67305985 },
      { fn: 'f', args: [0, 0, 0, 0], expected: 0 },
      { fn: 'f', args: [255, 255, 255, 255], expected: 4294967295 },
      { fn: 'f', args: [0, 0, 1, 0], expected: 65536 },
      { fn: 'f', args: [0, 0, 511, 0], expected: 16711680 },
      { fn: 'f', args: [4660, 22136, 39612, 57072], expected: 4038883380 },
      { fn: 'f', args: [0, 0, 256, 0], expected: 0 },
      { fn: 'f', args: [4294967295, 4294967295, 4294967295, 4294967295], expected: 4294967295 },
      { fn: 'f', args: [0, 0, 128, 0], expected: 8388608 },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 u32 -> u32\na and p0 255\nb and p1 255\nc shl b 8\nd and p2 255\ne shl d 16\ng shl p3 24\nh or a c\ni or h e\nj or i g\nret j\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 u32 u32 -> u32\na and p0 255\nb and p1 255\nc shl b 8\nd mov p2\ne shl d 16\ng shl p3 24\nh or a c\ni or h e\nj or i g\nret j\nend\n',
    ],
  },
  {
    id: 'u-fifteen-percent',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'wrapping',
    note: 'Both rate constants must change; a direct multiply-then-divide wraps for large amounts.',
    instruction:
      'The function returns 10 per cent of the amount rounded down; change it to return 15 per cent rounded down, exact for every amount without overflow.',
    a0Source:
      'fn f u32 -> u32\na div p0 100\nb mul a 10\nc rem p0 100\nd mul c 10\ne div d 100\ng add b e\nret g\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [99], expected: 14 },
      { fn: 'f', args: [100], expected: 15 },
      { fn: 'f', args: [150], expected: 22 },
      { fn: 'f', args: [199], expected: 29 },
      { fn: 'f', args: [1000], expected: 150 },
      { fn: 'f', args: [4294967295], expected: 644245094 },
      { fn: 'f', args: [400000000], expected: 60000000 },
      { fn: 'f', args: [286331153], expected: 42949672 },
      { fn: 'f', args: [7], expected: 1 },
    ],
    reference: {
      a0: 'fn f u32 -> u32\na div p0 100\nb mul a 15\nc rem p0 100\nd mul c 15\ne div d 100\ng add b e\nret g\nend\n',
    },
    wrongEdits: [
      'fn f u32 -> u32\na div p0 100\nb mul a 15\nc rem p0 100\nd mul c 10\ne div d 100\ng add b e\nret g\nend\n',
      'fn f u32 -> u32\na mul p0 15\nb div a 100\nret b\nend\n',
    ],
  },
  {
    id: 'u-max-position',
    kind: 'comprehension-edit',
    target: 'step',
    wrongEditKind: 'comparison',
    note: 'Ties must not replace the stored position; one wrong edit inverts the test, the other compares with the stored position.',
    instruction:
      'f folds step over the array to find the position of the largest element. Change step so that when an element equals the best so far, the earlier position is kept.',
    a0Source:
      'fn step (u32,u32) u32 u32x4 -> (u32,u32)\nv get p2 p1\nb at p0 0\nk at p0 1\nbetter ge v b\nnb select better v b\nni select better p1 k\nr rec nb ni\nret r\nend\nfn f u32x4 -> u32\na get p0 0\ns rec a 0\nr fold step 4 s p0\ni at r 1\nret i\nend\n',
    tests: [
      { fn: 'step', args: [[5, 1], 2, [1, 2, 5, 0]], expected: [5, 1] },
      { fn: 'step', args: [[5, 1], 2, [1, 2, 6, 0]], expected: [6, 2] },
      { fn: 'step', args: [[5, 1], 2, [1, 2, 4, 0]], expected: [5, 1] },
      { fn: 'step', args: [[0, 0], 0, [0, 0, 0, 0]], expected: [0, 0] },
      { fn: 'step', args: [[4294967295, 3], 1, [0, 4294967295, 0, 0]], expected: [4294967295, 3] },
      { fn: 'step', args: [[0, 0], 3, [0, 0, 0, 1]], expected: [1, 3] },
      { fn: 'step', args: [[7, 0], 3, [7, 7, 7, 7]], expected: [7, 0] },
      { fn: 'step', args: [[2, 0], 1, [2, 3, 1, 1]], expected: [3, 1] },
      { fn: 'step', args: [[9, 2], 6, [1, 1, 9, 1]], expected: [9, 2] },
    ],
    reference: {
      a0: 'fn step (u32,u32) u32 u32x4 -> (u32,u32)\nv get p2 p1\nb at p0 0\nk at p0 1\nbetter gt v b\nnb select better v b\nni select better p1 k\nr rec nb ni\nret r\nend\nfn f u32x4 -> u32\na get p0 0\ns rec a 0\nr fold step 4 s p0\ni at r 1\nret i\nend\n',
    },
    wrongEdits: [
      'fn step (u32,u32) u32 u32x4 -> (u32,u32)\nv get p2 p1\nb at p0 0\nk at p0 1\nbetter ge b v\nnb select better v b\nni select better p1 k\nr rec nb ni\nret r\nend\nfn f u32x4 -> u32\na get p0 0\ns rec a 0\nr fold step 4 s p0\ni at r 1\nret i\nend\n',
      'fn step (u32,u32) u32 u32x4 -> (u32,u32)\nv get p2 p1\nb at p0 0\nk at p0 1\nbetter gt v k\nnb select better v b\nni select better p1 k\nr rec nb ni\nret r\nend\nfn f u32x4 -> u32\na get p0 0\ns rec a 0\nr fold step 4 s p0\ni at r 1\nret i\nend\n',
    ],
  },
  {
    id: 'u-signed-half',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Boundary at 32768 (the most negative value) must count as negative; wrong edit is off by one in the magnitude.',
    instruction:
      "Read the low 16 bits as a two's-complement signed number and return its magnitude and whether it is negative; bit 15 set means negative.",
    a0Source:
      'fn f u32 -> (u32,bool)\na and p0 65535\nn gt a 32768\nm sub 65536 a\ng select n m a\nr rec g n\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: [0, false] },
      { fn: 'f', args: [1], expected: [1, false] },
      { fn: 'f', args: [32767], expected: [32767, false] },
      { fn: 'f', args: [32768], expected: [32768, true] },
      { fn: 'f', args: [32769], expected: [32767, true] },
      { fn: 'f', args: [65535], expected: [1, true] },
      { fn: 'f', args: [65536], expected: [0, false] },
      { fn: 'f', args: [4294934528], expected: [32768, true] },
      { fn: 'f', args: [305397765], expected: [5, false] },
      { fn: 'f', args: [4294967295], expected: [1, true] },
    ],
    reference: {
      a0: 'fn f u32 -> (u32,bool)\na and p0 65535\nn ge a 32768\nm sub 65536 a\ng select n m a\nr rec g n\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 -> (u32,bool)\na and p0 65535\nn ge a 32768\nm sub 65535 a\ng select n m a\nr rec g n\nret r\nend\n',
    ],
  },
  {
    id: 'u-mirror-write',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Mirror index is 3 minus the position; wrong edit subtracts the other way.',
    instruction:
      'Write the value into the given position and also into the mirrored position counted from the other end (position 0 mirrors 3, 1 mirrors 2), positions taken modulo 4.',
    a0Source: 'fn f u32x4 u32 u32 -> u32x4\na set p0 p1 p2\nb sub 4 p1\nc set a b p2\nret c\nend\n',
    tests: [
      { fn: 'f', args: [[0, 0, 0, 0], 0, 9], expected: [9, 0, 0, 9] },
      { fn: 'f', args: [[0, 0, 0, 0], 1, 9], expected: [0, 9, 9, 0] },
      { fn: 'f', args: [[0, 0, 0, 0], 2, 9], expected: [0, 9, 9, 0] },
      { fn: 'f', args: [[0, 0, 0, 0], 3, 9], expected: [9, 0, 0, 9] },
      { fn: 'f', args: [[1, 2, 3, 4], 4, 0], expected: [0, 2, 3, 0] },
      { fn: 'f', args: [[1, 2, 3, 4], 5, 7], expected: [1, 7, 7, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 4294967295, 8], expected: [8, 2, 3, 8] },
      { fn: 'f', args: [[5, 5, 5, 5], 2, 4294967295], expected: [5, 4294967295, 4294967295, 5] },
    ],
    reference: {
      a0: 'fn f u32x4 u32 u32 -> u32x4\na set p0 p1 p2\nb sub 3 p1\nc set a b p2\nret c\nend\n',
    },
    wrongEdits: [
      'fn f u32x4 u32 u32 -> u32x4\na set p0 p1 p2\nb sub p1 3\nc set a b p2\nret c\nend\n',
    ],
  },
  {
    id: 'u-sticky-shift',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Sticky bit set when shifting back does not restore the value; wrong edits invert the test or test the result instead.',
    instruction:
      'Shift the value right by the distance as now, but also set bit 0 of the result whenever any 1 bit was shifted out.',
    a0Source: 'fn f u32 u32 -> u32\na shr p0 p1\nret a\nend\n',
    tests: [
      { fn: 'f', args: [8, 2], expected: 2 },
      { fn: 'f', args: [9, 2], expected: 3 },
      { fn: 'f', args: [12, 3], expected: 1 },
      { fn: 'f', args: [0, 5], expected: 0 },
      { fn: 'f', args: [4294967295, 31], expected: 1 },
      { fn: 'f', args: [2147483648, 31], expected: 1 },
      { fn: 'f', args: [2147483649, 31], expected: 1 },
      { fn: 'f', args: [5, 0], expected: 5 },
      { fn: 'f', args: [6, 1], expected: 3 },
      { fn: 'f', args: [7, 32], expected: 7 },
      { fn: 'f', args: [16, 4], expected: 1 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\na shr p0 p1\nb shl a p1\nc ne b p0\nd select c 1 0\ne or a d\nret e\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\na shr p0 p1\nb shl a p1\nc eq b p0\nd select c 1 0\ne or a d\nret e\nend\n',
      'fn f u32 u32 -> u32\na shr p0 p1\nb shl a p1\nc ne a 0\nd select c 1 0\ne or a d\nret e\nend\n',
    ],
  },
  {
    id: 'u-larger-half-wins',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Second call must use the second argument; wrong edit swaps the comparison.',
    instruction:
      "Using the helper, which gives the larger of a value's two 16-bit halves, return true when the first value's larger half is strictly greater than the second value's.",
    a0Source:
      'fn h u32 -> u32\na shr p0 16\nb and p0 65535\nc gt a b\nd select c a b\nret d\nend\nfn f u32 u32 -> bool\nx call h p0\ny call h p0\nz gt x y\nret z\nend\n',
    tests: [
      { fn: 'f', args: [327683, 262148], expected: true },
      { fn: 'f', args: [262148, 327683], expected: false },
      { fn: 'f', args: [65536, 1], expected: false },
      { fn: 'f', args: [1, 65536], expected: false },
      { fn: 'f', args: [0, 0], expected: false },
      { fn: 'f', args: [4294967295, 4294901760], expected: false },
      { fn: 'f', args: [65535, 4294836224], expected: true },
      { fn: 'f', args: [7, 6], expected: true },
      { fn: 'f', args: [196608, 4], expected: false },
    ],
    reference: {
      a0: 'fn h u32 -> u32\na shr p0 16\nb and p0 65535\nc gt a b\nd select c a b\nret d\nend\nfn f u32 u32 -> bool\nx call h p0\ny call h p1\nz gt x y\nret z\nend\n',
    },
    wrongEdits: [
      'fn h u32 -> u32\na shr p0 16\nb and p0 65535\nc gt a b\nd select c a b\nret d\nend\nfn f u32 u32 -> bool\nx call h p0\ny call h p1\nz gt y x\nret z\nend\n',
    ],
  },
  {
    id: 'u-all-under-limit',
    kind: 'targeted-edit',
    target: 'ok',
    wrongEditKind: 'comparison',
    note: 'Strict bound; wrong edit reverses the comparison.',
    instruction:
      'f returns true when every element of the array is strictly below the limit. Fix the per-element check, which currently accepts an element equal to the limit.',
    a0Source:
      'fn ok bool u32 u32x4 u32 -> bool\nv get p2 p1\nc le v p3\nr and p0 c\nret r\nend\nfn f u32x4 u32 -> bool\nr fold ok 4 true p0 p1\nret r\nend\n',
    tests: [
      { fn: 'ok', args: [true, 0, [5, 0, 0, 0], 5], expected: false },
      { fn: 'ok', args: [true, 0, [4, 0, 0, 0], 5], expected: true },
      { fn: 'ok', args: [false, 0, [4, 0, 0, 0], 5], expected: false },
      { fn: 'ok', args: [true, 5, [1, 2, 3, 4], 2], expected: false },
      { fn: 'ok', args: [true, 3, [0, 0, 0, 0], 0], expected: false },
      { fn: 'ok', args: [true, 0, [4294967295, 0, 0, 0], 4294967295], expected: false },
      { fn: 'ok', args: [true, 1, [0, 4294967294, 0, 0], 4294967295], expected: true },
      { fn: 'ok', args: [false, 2, [0, 0, 9, 0], 1], expected: false },
      { fn: 'ok', args: [true, 2, [0, 0, 9, 0], 10], expected: true },
    ],
    reference: {
      a0: 'fn ok bool u32 u32x4 u32 -> bool\nv get p2 p1\nc lt v p3\nr and p0 c\nret r\nend\nfn f u32x4 u32 -> bool\nr fold ok 4 true p0 p1\nret r\nend\n',
    },
    wrongEdits: [
      'fn ok bool u32 u32x4 u32 -> bool\nv get p2 p1\nc lt p3 v\nr and p0 c\nret r\nend\nfn f u32x4 u32 -> bool\nr fold ok 4 true p0 p1\nret r\nend\n',
    ],
  },
  {
    id: 'u-celsius-to-fahrenheit',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'Two constants swapped and the offset wrong; dividing first loses the remainder.',
    instruction:
      'Convert a Celsius temperature to Fahrenheit: multiply by 9, divide by 5 rounding down, then add 32.',
    a0Source: 'fn f u32 -> u32\na mul p0 5\nb div a 9\nc add b 30\nret c\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 32 },
      { fn: 'f', args: [100], expected: 212 },
      { fn: 'f', args: [37], expected: 98 },
      { fn: 'f', args: [1], expected: 33 },
      { fn: 'f', args: [3], expected: 37 },
      { fn: 'f', args: [40], expected: 104 },
      { fn: 'f', args: [4294967295], expected: 858993489 },
      { fn: 'f', args: [477218588], expected: 858993490 },
      { fn: 'f', args: [7], expected: 44 },
    ],
    reference: { a0: 'fn f u32 -> u32\na mul p0 9\nb div a 5\nc add b 32\nret c\nend\n' },
    wrongEdits: [
      'fn f u32 -> u32\na div p0 5\nb mul a 9\nc add b 32\nret c\nend\n',
      'fn f u32 -> u32\na mul p0 9\nb div a 5\nc add b 30\nret c\nend\n',
    ],
  },
  {
    id: 'u-version-compatible',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Equal minor must be accepted; wrong edits mask too few bits or accept a newer major.',
    instruction:
      'Versions are packed as major in the top 16 bits and minor in the low 16. Return true when the installed version (first) has the same major as the required one (second) and a minor at least as high.',
    a0Source:
      'fn f u32 u32 -> bool\na shr p0 16\nb shr p1 16\nc eq a b\nd and p0 65535\ne and p1 65535\ng gt d e\nh and c g\nret h\nend\n',
    tests: [
      { fn: 'f', args: [65538, 65538], expected: true },
      { fn: 'f', args: [65539, 65538], expected: true },
      { fn: 'f', args: [65537, 65538], expected: false },
      { fn: 'f', args: [131072, 65541], expected: false },
      { fn: 'f', args: [131071, 131071], expected: true },
      { fn: 'f', args: [65792, 65793], expected: false },
      { fn: 'f', args: [0, 0], expected: true },
      { fn: 'f', args: [4294967295, 4294967295], expected: true },
      { fn: 'f', args: [66048, 65793], expected: true },
      { fn: 'f', args: [131077, 65538], expected: false },
    ],
    reference: {
      a0: 'fn f u32 u32 -> bool\na shr p0 16\nb shr p1 16\nc eq a b\nd and p0 65535\ne and p1 65535\ng ge d e\nh and c g\nret h\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> bool\na shr p0 16\nb shr p1 16\nc eq a b\nd and p0 65535\ne and p1 255\ng ge d e\nh and c g\nret h\nend\n',
      'fn f u32 u32 -> bool\na shr p0 16\nb shr p1 16\nc ge a b\nd and p0 65535\ne and p1 65535\ng ge d e\nh and c g\nret h\nend\n',
    ],
  },
  {
    id: 'u-alarm-due',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'wrapping',
    note: 'Adding alarm and delay wraps to a small value; the wrong edit forgets that the current time may be before the alarm.',
    instruction:
      'Return true when the current time (first) has reached the alarm time (second) plus the snooze delay (third); the sum may exceed the u32 range, so do not add them.',
    a0Source: 'fn f u32 u32 u32 -> bool\ne add p1 p2\ng ge p0 e\nret g\nend\n',
    tests: [
      { fn: 'f', args: [10, 5, 5], expected: true },
      { fn: 'f', args: [9, 5, 5], expected: false },
      { fn: 'f', args: [11, 5, 5], expected: true },
      { fn: 'f', args: [5, 10, 0], expected: false },
      { fn: 'f', args: [4294967295, 4294967292, 3], expected: true },
      { fn: 'f', args: [4294967295, 4294967292, 4], expected: false },
      { fn: 'f', args: [2, 4294967295, 5], expected: false },
      { fn: 'f', args: [0, 0, 0], expected: true },
      { fn: 'f', args: [100, 1, 4294967295], expected: false },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 -> bool\na ge p0 p1\nb sub p0 p1\nc ge b p2\nd and a c\nret d\nend\n',
    },
    wrongEdits: ['fn f u32 u32 u32 -> bool\nb sub p0 p1\nc ge b p2\nret c\nend\n'],
  },
  {
    id: 'u-swap-neighbours',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Only the first pair was swapped; wrong edit reverses the whole array.',
    instruction:
      'Return the array with each neighbouring pair exchanged: elements 0 and 1 trade places, and elements 2 and 3 trade places.',
    a0Source:
      'fn f u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\nr arr b a c d\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4]], expected: [2, 1, 4, 3] },
      { fn: 'f', args: [[0, 0, 0, 0]], expected: [0, 0, 0, 0] },
      { fn: 'f', args: [[5, 5, 6, 6]], expected: [5, 5, 6, 6] },
      { fn: 'f', args: [[1, 1, 2, 3]], expected: [1, 1, 3, 2] },
      { fn: 'f', args: [[4294967295, 0, 4294967295, 0]], expected: [0, 4294967295, 0, 4294967295] },
      { fn: 'f', args: [[9, 8, 7, 6]], expected: [8, 9, 6, 7] },
      { fn: 'f', args: [[0, 1, 0, 1]], expected: [1, 0, 1, 0] },
      { fn: 'f', args: [[4, 3, 2, 1]], expected: [3, 4, 1, 2] },
    ],
    reference: {
      a0: 'fn f u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\nr arr b a d c\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32x4 -> u32x4\na get p0 0\nb get p0 1\nc get p0 2\nd get p0 3\nr arr d c b a\nret r\nend\n',
    ],
  },
  {
    id: 'u-trailing-ones',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'All 32 bits must be examined; 33 steps wraps the shift and rereads bit 0.',
    instruction:
      'Return how many consecutive 1 bits the value has starting from bit 0 (for example 0b0111 gives 3 and all ones gives 32).',
    a0Source:
      'fn step (u32,bool) u32 u32 -> (u32,bool)\nx shr p2 p1\nb and x 1\none eq b 1\ns at p0 1\ncont and s one\ninc select cont 1 0\nn0 at p0 0\nn add n0 inc\nr rec n cont\nret r\nend\nfn f u32 -> u32\ns rec 0 true\nr fold step 31 s p0\nc at r 0\nret c\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [1], expected: 1 },
      { fn: 'f', args: [2], expected: 0 },
      { fn: 'f', args: [3], expected: 2 },
      { fn: 'f', args: [7], expected: 3 },
      { fn: 'f', args: [11], expected: 2 },
      { fn: 'f', args: [4294967295], expected: 32 },
      { fn: 'f', args: [2147483647], expected: 31 },
      { fn: 'f', args: [4294967294], expected: 0 },
      { fn: 'f', args: [65535], expected: 16 },
    ],
    reference: {
      a0: 'fn step (u32,bool) u32 u32 -> (u32,bool)\nx shr p2 p1\nb and x 1\none eq b 1\ns at p0 1\ncont and s one\ninc select cont 1 0\nn0 at p0 0\nn add n0 inc\nr rec n cont\nret r\nend\nfn f u32 -> u32\ns rec 0 true\nr fold step 32 s p0\nc at r 0\nret c\nend\n',
    },
    wrongEdits: [
      'fn step (u32,bool) u32 u32 -> (u32,bool)\nx shr p2 p1\nb and x 1\none eq b 1\ns at p0 1\ncont and s one\ninc select cont 1 0\nn0 at p0 0\nn add n0 inc\nr rec n cont\nret r\nend\nfn f u32 -> u32\ns rec 0 true\nr fold step 33 s p0\nc at r 0\nret c\nend\n',
    ],
  },
];
