/**
 * Held-out task set M (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-m/m-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-m.sha256 before any subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

export interface TaskM {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly Value[];
    readonly expected: Value;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_M: readonly TaskM[] = [
  {
    id: 'm-field-extract',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'Start masks only 5 bits; the wrong edit shifts by 5.',
    instruction: 'Return the 6-bit field stored in bits 4 through 9 of the input.',
    a0Source: 'fn f u32 -> u32\na shr p0 4\nb and a 31\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [1008], expected: 63 },
      { fn: 'f', args: [496], expected: 31 },
      { fn: 'f', args: [512], expected: 32 },
      { fn: 'f', args: [1024], expected: 0 },
      { fn: 'f', args: [4294967295], expected: 63 },
      { fn: 'f', args: [16], expected: 1 },
      { fn: 'f', args: [1023], expected: 63 },
      { fn: 'f', args: [527], expected: 32 },
    ],
    reference: { a0: 'fn f u32 -> u32\na shr p0 4\nb and a 63\nret b\nend\n' },
    wrongEdits: ['fn f u32 -> u32\na shr p0 5\nb and a 63\nret b\nend\n'],
  },
  {
    id: 'm-pack-bytes',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'changed-constant',
    note: 'The helper masks to a byte; the shift amount is the bug.',
    instruction:
      'Pack the low byte of the first argument into bits 8 to 15 and the low byte of the second argument into bits 0 to 7.',
    a0Source:
      'fn lo8 u32 -> u32\na and p0 255\nb mov a\nret b\nend\nfn f u32 u32 -> u32\na call lo8 p0\nb call lo8 p1\nc shl a 4\nd or c b\nret d\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [1, 0], expected: 256 },
      { fn: 'f', args: [0, 1], expected: 1 },
      { fn: 'f', args: [255, 255], expected: 65535 },
      { fn: 'f', args: [4660, 22136], expected: 13432 },
      { fn: 'f', args: [4294967295, 0], expected: 65280 },
      { fn: 'f', args: [0, 4294967295], expected: 255 },
      { fn: 'f', args: [128, 1], expected: 32769 },
      { fn: 'f', args: [256, 256], expected: 0 },
    ],
    reference: {
      a0: 'fn lo8 u32 -> u32\na and p0 255\nb mov a\nret b\nend\nfn f u32 u32 -> u32\na call lo8 p0\nb call lo8 p1\nc shl a 8\nd or c b\nret d\nend\n',
    },
    wrongEdits: [
      'fn lo8 u32 -> u32\na and p0 255\nb mov a\nret b\nend\nfn f u32 u32 -> u32\na call lo8 p0\nb call lo8 p1\nc shl a 16\nd or c b\nret d\nend\n',
    ],
  },
  {
    id: 'm-nonzero-nibbles',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Start skips the top nibble; the wrong edit runs nine steps and re-counts nibble 0 because shifts use the low five bits.',
    instruction: 'Count how many of the eight 4-bit nibbles of the input are nonzero.',
    a0Source:
      'fn step u32 u32 u32 -> u32\na mul p1 4\nb shr p2 a\nc and b 15\nd ne c 0\ne select d 1 0\ng add p0 e\nret g\nend\nfn f u32 -> u32\na fold step 7 0 p0\nb mov a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [4294967295], expected: 8 },
      { fn: 'f', args: [4026531840], expected: 1 },
      { fn: 'f', args: [1], expected: 1 },
      { fn: 'f', args: [268435456], expected: 1 },
      { fn: 'f', args: [252645135], expected: 4 },
      { fn: 'f', args: [2147483649], expected: 2 },
      { fn: 'f', args: [1048576], expected: 1 },
      { fn: 'f', args: [286331153], expected: 8 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32 -> u32\na mul p1 4\nb shr p2 a\nc and b 15\nd ne c 0\ne select d 1 0\ng add p0 e\nret g\nend\nfn f u32 -> u32\na fold step 8 0 p0\nb mov a\nret b\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32 -> u32\na mul p1 4\nb shr p2 a\nc and b 15\nd ne c 0\ne select d 1 0\ng add p0 e\nret g\nend\nfn f u32 -> u32\na fold step 9 0 p0\nb mov a\nret b\nend\n',
    ],
  },
  {
    id: 'm-header-valid',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Start reads the nibble at bit 24; the wrong edit reads at bit 27.',
    instruction:
      'Return true when bits 28 to 31 of the input hold the value 5 and bits 0 to 7 are not all zero.',
    a0Source:
      'fn nib u32 u32 -> u32\na shr p0 p1\nb and a 15\nret b\nend\nfn f u32 -> bool\na call nib p0 24\nb eq a 5\nc and p0 255\nd ne c 0\ne and b d\nret e\nend\n',
    tests: [
      { fn: 'f', args: [1342177281], expected: true },
      { fn: 'f', args: [1342177280], expected: false },
      { fn: 'f', args: [83886081], expected: false },
      { fn: 'f', args: [1593835775], expected: true },
      { fn: 'f', args: [1073741825], expected: false },
      { fn: 'f', args: [2684354561], expected: false },
      { fn: 'f', args: [1342177535], expected: true },
      { fn: 'f', args: [1342177536], expected: false },
      { fn: 'f', args: [0], expected: false },
      { fn: 'f', args: [4294967295], expected: false },
    ],
    reference: {
      a0: 'fn nib u32 u32 -> u32\na shr p0 p1\nb and a 15\nret b\nend\nfn f u32 -> bool\na call nib p0 28\nb eq a 5\nc and p0 255\nd ne c 0\ne and b d\nret e\nend\n',
    },
    wrongEdits: [
      'fn nib u32 u32 -> u32\na shr p0 p1\nb and a 15\nret b\nend\nfn f u32 -> bool\na call nib p0 27\nb eq a 5\nc and p0 255\nd ne c 0\ne and b d\nret e\nend\n',
    ],
  },
  {
    id: 'm-copy-next',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Indexes wrap modulo 4.',
    instruction:
      'Return the array with slot k (the second argument) replaced by the element that follows it; the slot after the last one is the first.',
    a0Source: 'fn f u32x4 u32 -> u32x4\ng get p0 p1\ns set p0 p1 g\nret s\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 0], expected: [2, 2, 3, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 1], expected: [1, 3, 3, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 2], expected: [1, 2, 4, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 3], expected: [1, 2, 3, 1] },
      { fn: 'f', args: [[1, 2, 3, 4], 4], expected: [2, 2, 3, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 4294967295], expected: [1, 2, 3, 1] },
      { fn: 'f', args: [[9, 9, 9, 9], 2], expected: [9, 9, 9, 9] },
      { fn: 'f', args: [[5, 0, 7, 0], 1], expected: [5, 7, 7, 0] },
      { fn: 'f', args: [[10, 20, 30, 40], 7], expected: [10, 20, 30, 10] },
    ],
    reference: {
      a0: 'fn f u32x4 u32 -> u32x4\nn add p1 1\ng get p0 n\ns set p0 p1 g\nret s\nend\n',
    },
    wrongEdits: ['fn f u32x4 u32 -> u32x4\nn sub p1 1\ng get p0 n\ns set p0 p1 g\nret s\nend\n'],
  },
  {
    id: 'm-low-bits-tally',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'partial-fix',
    note: 'Both the element and the key need masking.',
    instruction:
      'Count the elements whose two lowest bits equal the two lowest bits of the second argument, comparing only those two bits on both sides.',
    a0Source:
      'fn step u32 u32 u32x4 u32 -> u32\na get p2 p1\nd eq a p3\ne select d 1 0\ng add p0 e\nret g\nend\nfn f u32x4 u32 -> u32\na fold step 4 0 p0 p1\nb mov a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [[0, 1, 2, 3], 0], expected: 1 },
      { fn: 'f', args: [[0, 1, 2, 3], 1], expected: 1 },
      { fn: 'f', args: [[4, 5, 6, 7], 1], expected: 1 },
      { fn: 'f', args: [[4, 8, 12, 0], 0], expected: 4 },
      { fn: 'f', args: [[4, 8, 12, 0], 4], expected: 4 },
      { fn: 'f', args: [[7, 7, 7, 7], 3], expected: 4 },
      { fn: 'f', args: [[7, 7, 7, 7], 7], expected: 4 },
      { fn: 'f', args: [[1, 5, 9, 13], 5], expected: 4 },
      { fn: 'f', args: [[4294967295, 3, 0, 2], 4294967295], expected: 2 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32x4 u32 -> u32\na get p2 p1\nb and a 3\nc and p3 3\nd eq b c\ne select d 1 0\ng add p0 e\nret g\nend\nfn f u32x4 u32 -> u32\na fold step 4 0 p0 p1\nb mov a\nret b\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32x4 u32 -> u32\na get p2 p1\nb and a 3\nd eq b p3\ne select d 1 0\ng add p0 e\nret g\nend\nfn f u32x4 u32 -> u32\na fold step 4 0 p0 p1\nb mov a\nret b\nend\n',
    ],
  },
  {
    id: 'm-split-word',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Start misses a high half equal to exactly 1.',
    instruction:
      'Return a record of the low 16 bits of the input and whether any of the high 16 bits are set.',
    a0Source:
      'fn f u32 -> (u32,bool)\na and p0 65535\nb shr p0 16\nc gt b 1\nr rec a c\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: [0, false] },
      { fn: 'f', args: [65536], expected: [0, true] },
      { fn: 'f', args: [131072], expected: [0, true] },
      { fn: 'f', args: [65535], expected: [65535, false] },
      { fn: 'f', args: [4294967295], expected: [65535, true] },
      { fn: 'f', args: [305419896], expected: [22136, true] },
      { fn: 'f', args: [2147483648], expected: [0, true] },
      { fn: 'f', args: [131071], expected: [65535, true] },
      { fn: 'f', args: [5], expected: [5, false] },
    ],
    reference: {
      a0: 'fn f u32 -> (u32,bool)\na and p0 65535\nb shr p0 16\nc ne b 0\nr rec a c\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 -> (u32,bool)\na and p0 65535\nb shr p0 16\nc ge b 0\nr rec a c\nret r\nend\n',
    ],
  },
  {
    id: 'm-bit-window',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'order-of-operations',
    note: 'n = 32 shifts by 0 under the five-bit rule, so that mask is 0.',
    instruction:
      'The function should return a mask with n bits set starting at bit lo (lo is the first argument, n the second), but it sets only the single bit just above that window. Fix it.',
    a0Source: 'fn f u32 u32 -> u32\na shl 1 p1\nb shl a p0\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [0, 1], expected: 1 },
      { fn: 'f', args: [0, 4], expected: 15 },
      { fn: 'f', args: [4, 4], expected: 240 },
      { fn: 'f', args: [8, 8], expected: 65280 },
      { fn: 'f', args: [31, 1], expected: 2147483648 },
      { fn: 'f', args: [0, 31], expected: 2147483647 },
      { fn: 'f', args: [16, 16], expected: 4294901760 },
      { fn: 'f', args: [3, 2], expected: 24 },
      { fn: 'f', args: [0, 32], expected: 0 },
    ],
    reference: { a0: 'fn f u32 u32 -> u32\na shl 1 p1\nc sub a 1\nb shl c p0\nret b\nend\n' },
    wrongEdits: ['fn f u32 u32 -> u32\na shl 1 p1\nb shl a p0\nc sub b 1\nret c\nend\n'],
  },
  {
    id: 'm-shift-xor-check',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'wrong-operator',
    note: 'or and add agree with xor only when the shifted values share no bits.',
    instruction:
      'Combine the four elements with exclusive-or, after shifting each element left by its index.',
    a0Source:
      'fn step u32 u32 u32x4 -> u32\na get p2 p1\nb shl a p1\nc or p0 b\nret c\nend\nfn f u32x4 -> u32\na fold step 4 0 p0\nb mov a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [[0, 0, 0, 0]], expected: 0 },
      { fn: 'f', args: [[1, 0, 0, 0]], expected: 1 },
      { fn: 'f', args: [[1, 1, 1, 1]], expected: 15 },
      { fn: 'f', args: [[1, 2, 4, 8]], expected: 85 },
      { fn: 'f', args: [[3, 0, 0, 0]], expected: 3 },
      { fn: 'f', args: [[4294967295, 4294967295, 0, 0]], expected: 1 },
      { fn: 'f', args: [[2, 1, 0, 0]], expected: 0 },
      { fn: 'f', args: [[8, 4, 2, 1]], expected: 0 },
      { fn: 'f', args: [[5, 5, 5, 5]], expected: 51 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32x4 -> u32\na get p2 p1\nb shl a p1\nc xor p0 b\nret c\nend\nfn f u32x4 -> u32\na fold step 4 0 p0\nb mov a\nret b\nend\n',
    },
    wrongEdits: [
      'fn step u32 u32 u32x4 -> u32\na get p2 p1\nb shl a p1\nc add p0 b\nret c\nend\nfn f u32x4 -> u32\na fold step 4 0 p0\nb mov a\nret b\nend\n',
    ],
  },
  {
    id: 'm-flag-write',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'wrong-operator',
    note: 'Start toggles instead of clearing.',
    instruction:
      'Set flag k (the second argument, taken modulo 8) in the flags word when the third argument is true, and clear it when it is false.',
    a0Source:
      'fn bit u32 -> u32\na and p0 7\nb shl 1 a\nret b\nend\nfn f u32 u32 bool -> u32\nb call bit p1\ns or p0 b\nc xor p0 b\nr select p2 s c\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 0, true], expected: 1 },
      { fn: 'f', args: [0, 0, false], expected: 0 },
      { fn: 'f', args: [1, 0, false], expected: 0 },
      { fn: 'f', args: [255, 3, false], expected: 247 },
      { fn: 'f', args: [255, 3, true], expected: 255 },
      { fn: 'f', args: [0, 11, true], expected: 8 },
      { fn: 'f', args: [4294967295, 7, false], expected: 4294967167 },
      { fn: 'f', args: [16, 4, false], expected: 0 },
      { fn: 'f', args: [16, 5, false], expected: 16 },
    ],
    reference: {
      a0: 'fn bit u32 -> u32\na and p0 7\nb shl 1 a\nret b\nend\nfn f u32 u32 bool -> u32\nb call bit p1\ns or p0 b\nn xor b 4294967295\nc and p0 n\nr select p2 s c\nret r\nend\n',
    },
    wrongEdits: [
      'fn bit u32 -> u32\na and p0 7\nb shl 1 a\nret b\nend\nfn f u32 u32 bool -> u32\nb call bit p1\ns or p0 b\nc and p0 b\nr select p2 s c\nret r\nend\n',
    ],
  },
  {
    id: 'm-decade-counter',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Values above 10 keep counting (wrapping); the wrong edit resets them.',
    instruction:
      'Advance the counter by one; when the advanced value is exactly 10 it becomes 0, any other value is kept. Right now the counter resets one step too early.',
    a0Source: 'fn f u32 -> u32\na add p0 1\nb eq a 9\nc select b 0 a\nret c\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 1 },
      { fn: 'f', args: [8], expected: 9 },
      { fn: 'f', args: [9], expected: 0 },
      { fn: 'f', args: [10], expected: 11 },
      { fn: 'f', args: [15], expected: 16 },
      { fn: 'f', args: [4294967295], expected: 0 },
      { fn: 'f', args: [5], expected: 6 },
      { fn: 'f', args: [100], expected: 101 },
    ],
    reference: { a0: 'fn f u32 -> u32\na add p0 1\nb eq a 10\nc select b 0 a\nret c\nend\n' },
    wrongEdits: ['fn f u32 -> u32\na add p0 1\nb ge a 10\nc select b 0 a\nret c\nend\n'],
  },
  {
    id: 'm-unpack-channels',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'partial-fix',
    note: 'All three masks must widen.',
    instruction:
      "Return the input's bytes as an array: bits 16-23, bits 8-15, bits 0-7, then bits 24-31, each field a full 8 bits wide.",
    a0Source:
      'fn f u32 -> u32x4\na shr p0 16\nb and a 15\nc shr p0 8\nd and c 15\ne and p0 15\ng shr p0 24\nr arr b d e g\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: [0, 0, 0, 0] },
      { fn: 'f', args: [4294967295], expected: [255, 255, 255, 255] },
      { fn: 'f', args: [305419896], expected: [52, 86, 120, 18] },
      { fn: 'f', args: [15728640], expected: [240, 0, 0, 0] },
      { fn: 'f', args: [61440], expected: [0, 240, 0, 0] },
      { fn: 'f', args: [240], expected: [0, 0, 240, 0] },
      { fn: 'f', args: [2864434397], expected: [187, 204, 221, 170] },
      { fn: 'f', args: [252645135], expected: [15, 15, 15, 15] },
    ],
    reference: {
      a0: 'fn f u32 -> u32x4\na shr p0 16\nb and a 255\nc shr p0 8\nd and c 255\ne and p0 255\ng shr p0 24\nr arr b d e g\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 -> u32x4\na shr p0 16\nb and a 255\nc shr p0 8\nd and c 255\ne and p0 15\ng shr p0 24\nr arr b d e g\nret r\nend\n',
    ],
  },
  {
    id: 'm-adjacent-repeat',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Index i+1 wraps modulo 4 at the last step.',
    instruction:
      'The function should report whether two neighbouring elements are equal, but it also compares the last element with the first. Make it compare only true neighbours.',
    a0Source:
      'fn same u32 u32 -> bool\na eq p0 p1\nb mov a\nret b\nend\nfn step bool u32 u32x4 -> bool\na get p2 p1\nn add p1 1\nb get p2 n\nc call same a b\nd or p0 c\nret d\nend\nfn f u32x4 -> bool\na fold step 4 false p0\nb mov a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 1]], expected: false },
      { fn: 'f', args: [[1, 1, 2, 3]], expected: true },
      { fn: 'f', args: [[1, 2, 2, 3]], expected: true },
      { fn: 'f', args: [[1, 2, 3, 3]], expected: true },
      { fn: 'f', args: [[1, 2, 3, 4]], expected: false },
      { fn: 'f', args: [[5, 5, 5, 5]], expected: true },
      { fn: 'f', args: [[0, 1, 0, 1]], expected: false },
      { fn: 'f', args: [[7, 8, 9, 7]], expected: false },
    ],
    reference: {
      a0: 'fn same u32 u32 -> bool\na eq p0 p1\nb mov a\nret b\nend\nfn step bool u32 u32x4 -> bool\na get p2 p1\nn add p1 1\nb get p2 n\nc call same a b\nd or p0 c\nret d\nend\nfn f u32x4 -> bool\na fold step 3 false p0\nb mov a\nret b\nend\n',
    },
    wrongEdits: [
      'fn same u32 u32 -> bool\na eq p0 p1\nb mov a\nret b\nend\nfn step bool u32 u32x4 -> bool\na get p2 p1\nn add p1 1\nb get p2 n\nc call same a b\nd or p0 c\nret d\nend\nfn f u32x4 -> bool\na fold step 2 false p0\nb mov a\nret b\nend\n',
    ],
  },
  {
    id: 'm-scaled-pack',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'partial-fix',
    note: 'The helper is x*3>>2 with a wrapping multiply.',
    instruction:
      'Scale both arguments with the helper, then put the scaled first value in the upper 16 bits and the scaled second value, cut to 16 bits, in the lower 16 bits.',
    a0Source:
      'fn scale u32 -> u32\na mul p0 3\nb shr a 2\nret b\nend\nfn f u32 u32 -> u32\na call scale p0\nb call scale p1\nc shl a 8\nr or c b\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [4, 0], expected: 196608 },
      { fn: 'f', args: [0, 4], expected: 3 },
      { fn: 'f', args: [4, 4], expected: 196611 },
      { fn: 'f', args: [100, 200], expected: 4915350 },
      { fn: 'f', args: [0, 131072], expected: 32768 },
      { fn: 'f', args: [65536, 1], expected: 3221225472 },
      { fn: 'f', args: [4294967295, 4294967295], expected: 4294967295 },
      { fn: 'f', args: [1, 1], expected: 0 },
    ],
    reference: {
      a0: 'fn scale u32 -> u32\na mul p0 3\nb shr a 2\nret b\nend\nfn f u32 u32 -> u32\na call scale p0\nb call scale p1\nc shl a 16\nd and b 65535\nr or c d\nret r\nend\n',
    },
    wrongEdits: [
      'fn scale u32 -> u32\na mul p0 3\nb shr a 2\nret b\nend\nfn f u32 u32 -> u32\na call scale p0\nb call scale p1\nc shl a 8\nd and b 65535\nr or c d\nret r\nend\n',
    ],
  },
  {
    id: 'm-set-pair-count',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'shift-scale',
    note: 'Pairs overlap; position 7 looks at bit 8.',
    instruction:
      'The function currently counts set bits among bits 0 to 7, but it should count the positions i from 0 to 7 where bits i and i+1 are both set. Change the helper accordingly.',
    a0Source:
      'fn pair u32 u32 -> bool\na shr p0 p1\nb and a 1\nc eq b 1\nret c\nend\nfn step u32 u32 u32 -> u32\na call pair p2 p1\nb select a 1 0\nc add p0 b\nret c\nend\nfn f u32 -> u32\na fold step 8 0 p0\nb mov a\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [1], expected: 0 },
      { fn: 'f', args: [3], expected: 1 },
      { fn: 'f', args: [511], expected: 8 },
      { fn: 'f', args: [255], expected: 7 },
      { fn: 'f', args: [341], expected: 0 },
      { fn: 'f', args: [6], expected: 1 },
      { fn: 'f', args: [384], expected: 1 },
      { fn: 'f', args: [4294967295], expected: 8 },
      { fn: 'f', args: [768], expected: 0 },
    ],
    reference: {
      a0: 'fn pair u32 u32 -> bool\na shr p0 p1\nb and a 3\nc eq b 3\nret c\nend\nfn step u32 u32 u32 -> u32\na call pair p2 p1\nb select a 1 0\nc add p0 b\nret c\nend\nfn f u32 -> u32\na fold step 8 0 p0\nb mov a\nret b\nend\n',
    },
    wrongEdits: [
      'fn pair u32 u32 -> bool\ns mul p1 2\na shr p0 s\nb and a 3\nc eq b 3\nret c\nend\nfn step u32 u32 u32 -> u32\na call pair p2 p1\nb select a 1 0\nc add p0 b\nret c\nend\nfn f u32 -> u32\na fold step 8 0 p0\nb mov a\nret b\nend\n',
    ],
  },
  {
    id: 'm-byte-insert',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'missing-mask',
    note: 'Start keeps only the field instead of clearing it, and does not mask the value.',
    instruction:
      'Return the word with bits 8 to 15 replaced by the low 8 bits of the second argument; all other bits of the word stay unchanged.',
    a0Source: 'fn f u32 u32 -> u32\na and p0 65280\nc shl p1 8\nr or a c\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [4294967295, 0], expected: 4294902015 },
      { fn: 'f', args: [0, 255], expected: 65280 },
      { fn: 'f', args: [0, 511], expected: 65280 },
      { fn: 'f', args: [305419896, 171], expected: 305441656 },
      { fn: 'f', args: [4294902015, 4294967295], expected: 4294967295 },
      { fn: 'f', args: [65280, 0], expected: 0 },
      { fn: 'f', args: [2882400001, 256], expected: 2882338817 },
      { fn: 'f', args: [1, 1], expected: 257 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\nn xor 65280 4294967295\na and p0 n\nb and p1 255\nc shl b 8\nr or a c\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\nn xor 65280 4294967295\na and p0 n\nc shl p1 8\nr or a c\nret r\nend\n',
    ],
  },
];
