/**
 * Held-out task set G for the spec-line experiment (results/spec-lines.json): twelve or more
 * tasks in which a plausible wrong edit exists. Generated by tools/ai-edit-tasks-g-gen.ts from two
 * language-neutral files (the tasks and hidden tests by an author who never saw the language or
 * the other sets; the examples and post properties by a second author who never saw the hidden
 * tests, the reference or the wrong edits). SHA-256 sealed in ai-edit-tasks-g.sha256 before any
 * subject ran: never alter this file.
 */

import type { Value } from '../src/core.js';

interface AcceptanceCase {
  readonly fn: string;
  readonly args: readonly Value[];
  readonly expected: Value;
}

interface SpecExample {
  readonly args: readonly Value[];
  readonly result: Value;
}

export interface TaskG {
  readonly id: string;
  readonly kind: 'targeted-edit' | 'multi-node-edit' | 'comprehension-edit' | 'create';
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tsSource: string;
  readonly rustSource: string;
  readonly tests: readonly AcceptanceCase[];
  readonly reference: { readonly a0: string; readonly ts: string; readonly rust: string };
  /** Plausible wrong edits (whole programs): each fails a hidden test; used for the catch analysis only. */
  readonly wrongEdits: readonly string[];
  readonly specs: {
    /** True of the starting program and of the reference; not a hidden test. In the author's order. */
    readonly preserved: readonly SpecExample[];
    /** True of the starting program, false of the reference (what the change alters). */
    readonly stale: SpecExample | null;
    /** A bool operation over the parameters and `r` that holds on the starting program and the reference. */
    readonly post: string;
    readonly candidates: {
      readonly preserved: number;
      readonly stale: number;
      readonly post: number;
      readonly droppedCandidates: number;
    };
  };
}

export const TASKS_G: readonly TaskG[] = [
  {
    id: 'g-range-inclusive-upper',
    kind: 'targeted-edit',
    target: 'in_range',
    wrongEditKind: 'comparison',
    note: 'Flipping the lower bound to strict as well looks symmetric but rejects x equal to lo.',
    instruction:
      'in_range(x, lo, hi) should report whether x lies between lo and hi with both ends included; currently a value equal to hi is rejected.',
    a0Source: 'fn in_range u32 u32 u32 -> bool\na ge p0 p1\nb lt p0 p2\nc and a b\nret c\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'in_range', args: [5, 3, 9], expected: true },
      { fn: 'in_range', args: [9, 3, 9], expected: true },
      { fn: 'in_range', args: [10, 3, 9], expected: false },
      { fn: 'in_range', args: [3, 3, 9], expected: true },
      { fn: 'in_range', args: [2, 3, 9], expected: false },
      { fn: 'in_range', args: [0, 0, 0], expected: true },
      { fn: 'in_range', args: [4294967295, 0, 4294967295], expected: true },
      { fn: 'in_range', args: [4294967295, 1, 4294967294], expected: false },
      { fn: 'in_range', args: [1234567, 1000, 1234567], expected: true },
      { fn: 'in_range', args: [77, 100, 200], expected: false },
    ],
    reference: {
      a0: 'fn in_range u32 u32 u32 -> bool\na ge p0 p1\nb le p0 p2\nc and a b\nret c\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn in_range u32 u32 u32 -> bool\na gt p0 p1\nb le p0 p2\nc and a b\nret c\nend\n',
    ],
    specs: {
      preserved: [
        { args: [9, 5, 10], result: true },
        { args: [5, 5, 10], result: true },
        { args: [4, 5, 10], result: false },
        { args: [11, 5, 10], result: false },
        { args: [2, 1, 3], result: true },
        { args: [0, 3, 12], result: false },
      ],
      stale: { args: [10, 5, 10], result: false },
      post: 'or r true',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 2 },
    },
  },
  {
    id: 'g-saturating-add',
    kind: 'multi-node-edit',
    target: 'sat_add',
    wrongEditKind: 'wrapping',
    note: 'Testing the wrapped sum with <= instead of < saturates whenever b is zero.',
    instruction:
      'sat_add(a, b) should return a + b, but when the true sum does not fit it should return the largest representable value instead of wrapping around.',
    a0Source: 'fn sat_add u32 u32 -> u32\ns add p0 p1\nret s\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'sat_add', args: [3, 4], expected: 7 },
      { fn: 'sat_add', args: [0, 0], expected: 0 },
      { fn: 'sat_add', args: [4294967295, 0], expected: 4294967295 },
      { fn: 'sat_add', args: [0, 4294967295], expected: 4294967295 },
      { fn: 'sat_add', args: [4294967295, 1], expected: 4294967295 },
      { fn: 'sat_add', args: [4000000000, 294967295], expected: 4294967295 },
      { fn: 'sat_add', args: [4000000000, 294967296], expected: 4294967295 },
      { fn: 'sat_add', args: [2147483648, 2147483648], expected: 4294967295 },
      { fn: 'sat_add', args: [123456, 654321], expected: 777777 },
      { fn: 'sat_add', args: [4294967295, 4294967295], expected: 4294967295 },
    ],
    reference: {
      a0: 'fn sat_add u32 u32 -> u32\ns add p0 p1\no lt s p0\nr select o 4294967295 s\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn sat_add u32 u32 -> u32\ns add p0 p1\no le s p0\nr select o 4294967295 s\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [4294967294, 1], result: 4294967295 },
        { args: [2147483647, 2147483648], result: 4294967295 },
        { args: [100, 200], result: 300 },
        { args: [0, 7], result: 7 },
        { args: [65535, 1], result: 65536 },
      ],
      stale: { args: [4294967290, 10], result: 4 },
      post: 'le r 4294967295',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 4 },
    },
  },
  {
    id: 'g-average-no-overflow',
    kind: 'multi-node-edit',
    target: 'avg',
    wrongEditKind: 'wrapping',
    note: 'Halving each operand separately avoids the overflow but drops the carry when both are odd.',
    instruction:
      'avg(a, b) should return the average of a and b rounded down, and must stay correct even when a + b is larger than the largest representable value.',
    a0Source: 'fn avg u32 u32 -> u32\ns add p0 p1\nr div s 2\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'avg', args: [10, 20], expected: 15 },
      { fn: 'avg', args: [7, 8], expected: 7 },
      { fn: 'avg', args: [0, 0], expected: 0 },
      { fn: 'avg', args: [1, 1], expected: 1 },
      { fn: 'avg', args: [4294967295, 4294967295], expected: 4294967295 },
      { fn: 'avg', args: [4294967295, 4294967294], expected: 4294967294 },
      { fn: 'avg', args: [3000000000, 2000000000], expected: 2500000000 },
      { fn: 'avg', args: [4294967293, 7], expected: 2147483650 },
      { fn: 'avg', args: [99, 100], expected: 99 },
      { fn: 'avg', args: [5, 5], expected: 5 },
    ],
    reference: {
      a0: 'fn avg u32 u32 -> u32\nha shr p0 1\nhb shr p1 1\nh add ha hb\nc and p0 p1\nc1 and c 1\nr add h c1\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: ['fn avg u32 u32 -> u32\nha shr p0 1\nhb shr p1 1\nh add ha hb\nret h\nend\n'],
    specs: {
      preserved: [
        { args: [4294967294, 1], result: 2147483647 },
        { args: [3, 4], result: 3 },
        { args: [2147483647, 2147483648], result: 2147483647 },
        { args: [7, 7], result: 7 },
        { args: [0, 9], result: 4 },
      ],
      stale: { args: [4294967295, 1], result: 0 },
      post: 'le r 4294967295',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 2 },
    },
  },
  {
    id: 'g-page-count-ceiling',
    kind: 'targeted-edit',
    target: 'page_count',
    wrongEditKind: 'off-by-one',
    note: 'Adding per_page instead of per_page minus one gives an extra page whenever items divide evenly.',
    instruction:
      'page_count(items, per_page) should return how many pages are needed to show all items (per_page is at least 1), counting a partially filled last page as a page.',
    a0Source: 'fn page_count u32 u32 -> u32\nr div p0 p1\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'page_count', args: [100, 10], expected: 10 },
      { fn: 'page_count', args: [101, 10], expected: 11 },
      { fn: 'page_count', args: [99, 10], expected: 10 },
      { fn: 'page_count', args: [0, 10], expected: 0 },
      { fn: 'page_count', args: [1, 10], expected: 1 },
      { fn: 'page_count', args: [25, 7], expected: 4 },
      { fn: 'page_count', args: [28, 7], expected: 4 },
      { fn: 'page_count', args: [1, 1], expected: 1 },
      { fn: 'page_count', args: [1000000, 3], expected: 333334 },
      { fn: 'page_count', args: [999999, 3], expected: 333333 },
    ],
    reference: {
      a0: 'fn page_count u32 u32 -> u32\nm sub p1 1\na add p0 m\nr div a p1\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: ['fn page_count u32 u32 -> u32\na add p0 p1\nr div a p1\nret r\nend\n'],
    specs: {
      preserved: [
        { args: [10, 5], result: 2 },
        { args: [20, 4], result: 5 },
        { args: [0, 3], result: 0 },
        { args: [9, 9], result: 1 },
        { args: [6, 1], result: 6 },
      ],
      stale: { args: [11, 5], result: 2 },
      post: 'le r p0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 1 },
    },
  },
  {
    id: 'g-ring-prev-slot',
    kind: 'targeted-edit',
    target: 'prev_slot',
    wrongEditKind: 'off-by-one',
    note: 'Wrapping with a remainder of i-1 looks right but i-1 wraps to the maximum value first, which only lands on n-1 for powers of two.',
    instruction:
      'prev_slot(i, n) gives the slot before i in a ring of n slots numbered 0 to n-1; stepping back from slot 0 should land on the last slot.',
    a0Source: 'fn prev_slot u32 u32 -> u32\nz eq p0 0\nd sub p0 1\nr select z p1 d\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'prev_slot', args: [3, 5], expected: 2 },
      { fn: 'prev_slot', args: [1, 5], expected: 0 },
      { fn: 'prev_slot', args: [0, 5], expected: 4 },
      { fn: 'prev_slot', args: [0, 10], expected: 9 },
      { fn: 'prev_slot', args: [0, 8], expected: 7 },
      { fn: 'prev_slot', args: [4, 5], expected: 3 },
      { fn: 'prev_slot', args: [0, 1], expected: 0 },
      { fn: 'prev_slot', args: [0, 7], expected: 6 },
      { fn: 'prev_slot', args: [123, 1000], expected: 122 },
      { fn: 'prev_slot', args: [0, 1000], expected: 999 },
    ],
    reference: {
      a0: 'fn prev_slot u32 u32 -> u32\nz eq p0 0\nd sub p0 1\nl sub p1 1\nr select z l d\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: ['fn prev_slot u32 u32 -> u32\nd sub p0 1\nr rem d p1\nret r\nend\n'],
    specs: {
      preserved: [
        { args: [2, 3], result: 1 },
        { args: [7, 10], result: 6 },
        { args: [1, 2], result: 0 },
        { args: [3, 8], result: 2 },
        { args: [2, 5], result: 1 },
        { args: [3, 4], result: 2 },
        { args: [5, 6], result: 4 },
        { args: [9, 12], result: 8 },
        { args: [1, 3], result: 0 },
        { args: [15, 16], result: 14 },
        { args: [6, 7], result: 5 },
        { args: [2, 2], result: 1 },
      ],
      stale: { args: [0, 2], result: 2 },
      post: 'ge r 0',
      candidates: { preserved: 14, stale: 8, post: 3, droppedCandidates: 7 },
    },
  },
  {
    id: 'g-clamp-index',
    kind: 'targeted-edit',
    target: 'clamp_index',
    wrongEditKind: 'off-by-one',
    note: 'Also relaxing the guard to i <= len lets i equal to len through unchanged.',
    instruction:
      'clamp_index(i, len) should return i when it is a valid index of a list of len elements (len at least 1), and otherwise the last valid index.',
    a0Source:
      'fn clamp_index u32 u32 -> u32\nl sub p1 1\nc lt p0 p1\nr select c p0 p1\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'clamp_index', args: [2, 5], expected: 2 },
      { fn: 'clamp_index', args: [4, 5], expected: 4 },
      { fn: 'clamp_index', args: [5, 5], expected: 4 },
      { fn: 'clamp_index', args: [6, 5], expected: 4 },
      { fn: 'clamp_index', args: [0, 1], expected: 0 },
      { fn: 'clamp_index', args: [1, 1], expected: 0 },
      { fn: 'clamp_index', args: [4294967295, 10], expected: 9 },
      { fn: 'clamp_index', args: [0, 10], expected: 0 },
      { fn: 'clamp_index', args: [9, 10], expected: 9 },
      { fn: 'clamp_index', args: [10, 10], expected: 9 },
    ],
    reference: {
      a0: 'fn clamp_index u32 u32 -> u32\nl sub p1 1\nc lt p0 p1\nr select c p0 l\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn clamp_index u32 u32 -> u32\nl sub p1 1\nc le p0 p1\nr select c p0 l\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [0, 5], result: 0 },
        { args: [2, 3], result: 2 },
        { args: [6, 8], result: 6 },
      ],
      stale: { args: [7, 3], result: 3 },
      post: 'le r p0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 5 },
    },
  },
  {
    id: 'g-grade-threshold',
    kind: 'targeted-edit',
    target: 'grade',
    wrongEditKind: 'comparison',
    note: 'Making both thresholds use the same strictness, or lowering the constant, changes the score-80 or score-89 boundary.',
    instruction:
      'grade(score) returns 3 for scores of 90 and above, 2 for scores of 80 and above, otherwise 1; a score of exactly 90 currently gets the wrong grade.',
    a0Source:
      'fn grade u32 -> u32\na gt p0 90\nb ge p0 80\nm select b 2 1\nr select a 3 m\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'grade', args: [90], expected: 3 },
      { fn: 'grade', args: [91], expected: 3 },
      { fn: 'grade', args: [89], expected: 2 },
      { fn: 'grade', args: [80], expected: 2 },
      { fn: 'grade', args: [79], expected: 1 },
      { fn: 'grade', args: [0], expected: 1 },
      { fn: 'grade', args: [100], expected: 3 },
      { fn: 'grade', args: [4294967295], expected: 3 },
      { fn: 'grade', args: [85], expected: 2 },
      { fn: 'grade', args: [81], expected: 2 },
    ],
    reference: {
      a0: 'fn grade u32 -> u32\na ge p0 90\nb ge p0 80\nm select b 2 1\nr select a 3 m\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn grade u32 -> u32\na ge p0 90\nb gt p0 80\nm select b 2 1\nr select a 3 m\nret r\nend\n',
      'fn grade u32 -> u32\na ge p0 89\nb ge p0 80\nm select b 2 1\nr select a 3 m\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [95], result: 3 },
        { args: [92], result: 3 },
        { args: [88], result: 2 },
        { args: [78], result: 1 },
        { args: [50], result: 1 },
        { args: [1000], result: 3 },
      ],
      stale: null,
      post: 'ge r 1',
      candidates: { preserved: 14, stale: 3, post: 3, droppedCandidates: 11 },
    },
  },
  {
    id: 'g-count-strictly-above',
    kind: 'targeted-edit',
    target: 'count_above',
    wrongEditKind: 'comparison',
    note: 'Writing the comparison as t > value counts entries below the threshold instead.',
    instruction:
      'count_above(values, t) should count the entries of values that are strictly greater than t; entries equal to t must not be counted.',
    a0Source:
      'fn step u32 u32 u32x4 u32 -> u32\ne get p2 p1\nt mov p3\nc ge e t\nk select c 1 0\ns add p0 k\nret s\nend\nfn count_above u32x4 u32 -> u32\nn fold step 4 0 p0 p1\nret n\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'count_above', args: [[1, 5, 9, 12], 4], expected: 3 },
      { fn: 'count_above', args: [[1, 5, 9, 12], 5], expected: 2 },
      { fn: 'count_above', args: [[7, 7, 7, 7], 7], expected: 0 },
      { fn: 'count_above', args: [[7, 7, 7, 8], 7], expected: 1 },
      { fn: 'count_above', args: [[0, 0, 0, 0], 0], expected: 0 },
      { fn: 'count_above', args: [[4294967295, 4294967295, 0, 1], 4294967295], expected: 0 },
      { fn: 'count_above', args: [[4294967295, 3, 2, 1], 0], expected: 4 },
      { fn: 'count_above', args: [[10, 20, 30, 40], 100], expected: 0 },
      { fn: 'count_above', args: [[100, 200, 300, 400], 250], expected: 2 },
    ],
    reference: {
      a0: 'fn step u32 u32 u32x4 u32 -> u32\ne get p2 p1\nt mov p3\nc gt e t\nk select c 1 0\ns add p0 k\nret s\nend\nfn count_above u32x4 u32 -> u32\nn fold step 4 0 p0 p1\nret n\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn step u32 u32 u32x4 u32 -> u32\ne get p2 p1\nt mov p3\nc gt t e\nk select c 1 0\ns add p0 k\nret s\nend\nfn count_above u32x4 u32 -> u32\nn fold step 4 0 p0 p1\nret n\nend\n',
    ],
    specs: {
      preserved: [
        { args: [[6, 7, 1, 2], 5], result: 2 },
        { args: [[1, 2, 3, 4], 9], result: 0 },
        { args: [[9, 9, 9, 9], 8], result: 4 },
        { args: [[10, 0, 3, 20], 4], result: 2 },
        { args: [[6, 4, 8, 2], 5], result: 2 },
        { args: [[1, 2, 3, 4], 0], result: 4 },
      ],
      stale: { args: [[5, 6, 5, 1], 5], result: 3 },
      post: 'le r 4',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 0 },
    },
  },
  {
    id: 'g-remaining-floor-zero',
    kind: 'multi-node-edit',
    target: 'remaining',
    wrongEditKind: 'swapped-argument',
    note: 'Writing the overflow test as total > used swaps the operands and zeroes every normal case.',
    instruction:
      'remaining(total, used) returns how much of total is left after used; when used exceeds total the answer should be 0 rather than a huge wrapped number.',
    a0Source: 'fn remaining u32 u32 -> u32\nd sub p0 p1\nret d\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'remaining', args: [100, 30], expected: 70 },
      { fn: 'remaining', args: [100, 100], expected: 0 },
      { fn: 'remaining', args: [100, 101], expected: 0 },
      { fn: 'remaining', args: [0, 1], expected: 0 },
      { fn: 'remaining', args: [0, 0], expected: 0 },
      { fn: 'remaining', args: [4294967295, 4294967295], expected: 0 },
      { fn: 'remaining', args: [5, 4294967295], expected: 0 },
      { fn: 'remaining', args: [4294967295, 0], expected: 4294967295 },
      { fn: 'remaining', args: [42, 17], expected: 25 },
      { fn: 'remaining', args: [17, 42], expected: 0 },
    ],
    reference: {
      a0: 'fn remaining u32 u32 -> u32\nd sub p0 p1\no gt p1 p0\nr select o 0 d\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn remaining u32 u32 -> u32\nd sub p0 p1\no gt p0 p1\nr select o 0 d\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [10, 9], result: 1 },
        { args: [10, 10], result: 0 },
        { args: [100, 1], result: 99 },
        { args: [5, 0], result: 5 },
        { args: [50, 25], result: 25 },
        { args: [4294967295, 1], result: 4294967294 },
      ],
      stale: { args: [9, 10], result: 4294967295 },
      post: 'ge r 0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 2 },
    },
  },
  {
    id: 'g-ring-distance',
    kind: 'targeted-edit',
    target: 'ring_distance',
    wrongEditKind: 'swapped-argument',
    note: 'Computing tail minus head reads naturally as a distance but measures the opposite direction.',
    instruction:
      'ring_distance(head, tail, n) gives how many steps forward from tail reach head in a ring of n slots (head and tail are below n); it is wrong when head is behind tail.',
    a0Source: 'fn ring_distance u32 u32 u32 -> u32\nd sub p0 p1\nr rem d p2\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'ring_distance', args: [7, 3, 10], expected: 4 },
      { fn: 'ring_distance', args: [3, 3, 10], expected: 0 },
      { fn: 'ring_distance', args: [2, 7, 10], expected: 5 },
      { fn: 'ring_distance', args: [0, 9, 10], expected: 1 },
      { fn: 'ring_distance', args: [9, 0, 10], expected: 9 },
      { fn: 'ring_distance', args: [1, 4, 6], expected: 3 },
      { fn: 'ring_distance', args: [4, 1, 6], expected: 3 },
      { fn: 'ring_distance', args: [0, 1, 3], expected: 2 },
      { fn: 'ring_distance', args: [999, 0, 1000], expected: 999 },
      { fn: 'ring_distance', args: [0, 999, 1000], expected: 1 },
    ],
    reference: {
      a0: 'fn ring_distance u32 u32 u32 -> u32\nd sub p0 p1\ne add d p2\nr rem e p2\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn ring_distance u32 u32 u32 -> u32\nd sub p1 p0\ne add d p2\nr rem e p2\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [5, 4, 8], result: 1 },
        { args: [4, 4, 8], result: 0 },
        { args: [7, 0, 8], result: 7 },
        { args: [3, 1, 5], result: 2 },
        { args: [9, 2, 10], result: 7 },
        { args: [1, 0, 2], result: 1 },
      ],
      stale: { args: [0, 1, 5], result: 0 },
      post: 'lt r p2',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 1 },
    },
  },
  {
    id: 'g-bit-field-extract',
    kind: 'multi-node-edit',
    target: 'bit_field',
    wrongEditKind: 'swapped-argument',
    note: 'Shifting width left by one instead of one left by width builds a wrong mask.',
    instruction:
      'bit_field(x, pos, width) should return the width bits of x starting at bit position pos as a small number (width between 1 and 31); it currently also returns all the bits above the field.',
    a0Source: 'fn bit_field u32 u32 u32 -> u32\ns shr p0 p1\nret s\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'bit_field', args: [2882343476, 4, 8], expected: 35 },
      { fn: 'bit_field', args: [2882343476, 0, 16], expected: 4660 },
      { fn: 'bit_field', args: [4294967295, 28, 4], expected: 15 },
      { fn: 'bit_field', args: [2882343476, 24, 8], expected: 171 },
      { fn: 'bit_field', args: [2147483648, 31, 1], expected: 1 },
      { fn: 'bit_field', args: [0, 5, 3], expected: 0 },
      { fn: 'bit_field', args: [4294967295, 0, 31], expected: 2147483647 },
      { fn: 'bit_field', args: [123456789, 7, 5], expected: 26 },
      { fn: 'bit_field', args: [4042322160, 16, 16], expected: 61680 },
    ],
    reference: {
      a0: 'fn bit_field u32 u32 u32 -> u32\ns shr p0 p1\no shl 1 p2\nm sub o 1\nr and s m\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn bit_field u32 u32 u32 -> u32\ns shr p0 p1\no shl p2 1\nm sub o 1\nr and s m\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [15, 0, 4], result: 15 },
        { args: [171, 4, 4], result: 10 },
        { args: [3, 0, 2], result: 3 },
        { args: [16, 4, 1], result: 1 },
        { args: [255, 1, 7], result: 127 },
        { args: [0, 3, 5], result: 0 },
      ],
      stale: { args: [31, 0, 4], result: 31 },
      post: 'le r p0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 1 },
    },
  },
  {
    id: 'g-budget-with-refund',
    kind: 'targeted-edit',
    target: 'budget_left',
    wrongEditKind: 'swapped-argument',
    note: 'Passing the spent amount as the first argument of the saturating helper subtracts in the wrong direction.',
    instruction:
      'budget_left(limit, spent, refund) returns what remains of limit after spending, never going below 0; the refund amount should be added to the limit before spending is taken off.',
    a0Source:
      'fn sat_sub u32 u32 -> u32\nu gt p1 p0\nd sub p0 p1\nr select u 0 d\nret r\nend\nfn budget_left u32 u32 u32 -> u32\nr call sat_sub p0 p1\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'budget_left', args: [100, 40, 0], expected: 60 },
      { fn: 'budget_left', args: [100, 40, 10], expected: 70 },
      { fn: 'budget_left', args: [100, 105, 10], expected: 5 },
      { fn: 'budget_left', args: [100, 120, 10], expected: 0 },
      { fn: 'budget_left', args: [0, 0, 0], expected: 0 },
      { fn: 'budget_left', args: [50, 50, 0], expected: 0 },
      { fn: 'budget_left', args: [0, 5, 0], expected: 0 },
      { fn: 'budget_left', args: [1000, 1500, 600], expected: 100 },
      { fn: 'budget_left', args: [7, 3, 0], expected: 4 },
    ],
    reference: {
      a0: 'fn sat_sub u32 u32 -> u32\nu gt p1 p0\nd sub p0 p1\nr select u 0 d\nret r\nend\nfn budget_left u32 u32 u32 -> u32\nl add p0 p2\nr call sat_sub l p1\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn sat_sub u32 u32 -> u32\nu gt p1 p0\nd sub p0 p1\nr select u 0 d\nret r\nend\nfn budget_left u32 u32 u32 -> u32\nl add p0 p2\nr call sat_sub p1 l\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [10, 3, 0], result: 7 },
        { args: [5, 5, 0], result: 0 },
        { args: [5, 6, 0], result: 0 },
        { args: [100, 20, 0], result: 80 },
        { args: [0, 1, 0], result: 0 },
        { args: [8, 0, 0], result: 8 },
      ],
      stale: { args: [10, 12, 5], result: 0 },
      post: 'ge r 0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 0 },
    },
  },
  {
    id: 'g-saturating-multiply',
    kind: 'multi-node-edit',
    target: 'sat_mul',
    wrongEditKind: 'wrapping',
    note: 'Reusing the addition overflow check (result smaller than an operand) misses many wrapped products.',
    instruction:
      'sat_mul(a, b) should return a times b, or the largest representable value when the true product does not fit.',
    a0Source: 'fn sat_mul u32 u32 -> u32\np mul p0 p1\nret p\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'sat_mul', args: [6, 7], expected: 42 },
      { fn: 'sat_mul', args: [0, 4294967295], expected: 0 },
      { fn: 'sat_mul', args: [4294967295, 0], expected: 0 },
      { fn: 'sat_mul', args: [1, 4294967295], expected: 4294967295 },
      { fn: 'sat_mul', args: [65536, 65536], expected: 4294967295 },
      { fn: 'sat_mul', args: [65535, 65537], expected: 4294967295 },
      { fn: 'sat_mul', args: [65536, 65537], expected: 4294967295 },
      { fn: 'sat_mul', args: [100000, 100000], expected: 4294967295 },
      { fn: 'sat_mul', args: [3, 1431655765], expected: 4294967295 },
      { fn: 'sat_mul', args: [3, 1431655766], expected: 4294967295 },
      { fn: 'sat_mul', args: [0, 0], expected: 0 },
    ],
    reference: {
      a0: 'fn sat_mul u32 u32 -> u32\np mul p0 p1\nq div p p0\nbad ne q p1\nnz ne p0 0\no and bad nz\nr select o 4294967295 p\nret r\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn sat_mul u32 u32 -> u32\np mul p0 p1\no lt p p0\nr select o 4294967295 p\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [65536, 65535], result: 4294901760 },
        { args: [3, 4], result: 12 },
        { args: [1000, 1000], result: 1000000 },
        { args: [1, 123], result: 123 },
      ],
      stale: { args: [2, 2147483648], result: 0 },
      post: 'ge r 0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 3 },
    },
  },
  {
    id: 'g-elapsed-counter-wrap',
    kind: 'targeted-edit',
    target: 'elapsed',
    wrongEditKind: 'wrapping',
    note: 'Adding the distance to the top and the distance from zero forgets the tick from the maximum value to 0.',
    instruction:
      'elapsed(start, now) returns ticks passed on a free-running counter that wraps from the largest value back to 0; when now is below start the counter has wrapped and the result should be the ticks actually passed, not 0.',
    a0Source: 'fn elapsed u32 u32 -> u32\nc ge p1 p0\nd sub p1 p0\nr select c d 0\nret r\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'elapsed', args: [100, 250], expected: 150 },
      { fn: 'elapsed', args: [5, 5], expected: 0 },
      { fn: 'elapsed', args: [0, 4294967295], expected: 4294967295 },
      { fn: 'elapsed', args: [4294967295, 0], expected: 1 },
      { fn: 'elapsed', args: [4294967295, 4], expected: 5 },
      { fn: 'elapsed', args: [4294967000, 300], expected: 596 },
      { fn: 'elapsed', args: [1, 0], expected: 4294967295 },
      { fn: 'elapsed', args: [123, 456789], expected: 456666 },
      { fn: 'elapsed', args: [3000000000, 3000000001], expected: 1 },
    ],
    reference: { a0: 'fn elapsed u32 u32 -> u32\nr sub p1 p0\nret r\nend\n', ts: '', rust: '' },
    wrongEdits: [
      'fn elapsed u32 u32 -> u32\nc ge p1 p0\nd sub p1 p0\nx sub 4294967295 p0\ny add x p1\nr select c d y\nret r\nend\n',
    ],
    specs: {
      preserved: [
        { args: [5, 6], result: 1 },
        { args: [0, 100], result: 100 },
        { args: [10, 30], result: 20 },
        { args: [7, 8], result: 1 },
        { args: [1, 4294967295], result: 4294967294 },
      ],
      stale: { args: [10, 5], result: 0 },
      post: 'ge r 0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 2 },
    },
  },
  {
    id: 'g-weighted-checksum-length',
    kind: 'targeted-edit',
    target: 'checksum',
    wrongEditKind: 'fold-bound',
    note: 'Raising the count one past the length re-reads the first entry because indexes wrap around.',
    instruction:
      'checksum(v) should be the wrapping sum of each entry times its position plus one, over all six entries; the last entry is currently left out.',
    a0Source:
      'fn wstep u32 u32 u32x6 -> u32\ne get p2 p1\nw add p1 1\nm mul e w\ns add p0 m\nret s\nend\nfn checksum u32x6 -> u32\nc fold wstep 5 0 p0\nret c\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'checksum', args: [[1, 2, 3, 4, 5, 0]], expected: 55 },
      { fn: 'checksum', args: [[1, 2, 3, 4, 5, 6]], expected: 91 },
      { fn: 'checksum', args: [[0, 0, 0, 0, 0, 9]], expected: 54 },
      { fn: 'checksum', args: [[0, 0, 0, 0, 0, 0]], expected: 0 },
      { fn: 'checksum', args: [[10, 0, 0, 0, 0, 0]], expected: 10 },
      {
        fn: 'checksum',
        args: [[4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295]],
        expected: 4294967275,
      },
      { fn: 'checksum', args: [[7, 11, 13, 17, 19, 23]], expected: 369 },
      { fn: 'checksum', args: [[1000, 2000, 3000, 4000, 5000, 0]], expected: 55000 },
      { fn: 'checksum', args: [[5, 0, 0, 0, 0, 1]], expected: 11 },
    ],
    reference: {
      a0: 'fn wstep u32 u32 u32x6 -> u32\ne get p2 p1\nw add p1 1\nm mul e w\ns add p0 m\nret s\nend\nfn checksum u32x6 -> u32\nc fold wstep 6 0 p0\nret c\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn wstep u32 u32 u32x6 -> u32\ne get p2 p1\nw add p1 1\nm mul e w\ns add p0 m\nret s\nend\nfn checksum u32x6 -> u32\nc fold wstep 7 0 p0\nret c\nend\n',
    ],
    specs: {
      preserved: [
        { args: [[1, 1, 1, 1, 1, 0]], result: 15 },
        { args: [[3, 0, 0, 0, 2, 0]], result: 13 },
        { args: [[0, 0, 0, 0, 2, 0]], result: 10 },
        { args: [[7, 0, 1, 0, 0, 0]], result: 10 },
      ],
      stale: { args: [[0, 0, 0, 0, 0, 1]], result: 0 },
      post: 'ge r 0',
      candidates: { preserved: 6, stale: 2, post: 3, droppedCandidates: 3 },
    },
  },
  {
    id: 'g-low-byte-popcount',
    kind: 'targeted-edit',
    target: 'low_byte_bits',
    wrongEditKind: 'fold-bound',
    note: 'Counting nine positions includes bit 8, which lies outside the low byte.',
    instruction:
      'low_byte_bits(x) should count how many of the eight lowest bits of x are set; the highest of those eight bits is currently ignored.',
    a0Source:
      'fn bstep u32 u32 u32 -> u32\ns shr p2 p1\nb and s 1\nr add p0 b\nret r\nend\nfn low_byte_bits u32 -> u32\nc fold bstep 7 0 p0\nret c\nend\n',
    tsSource: '',
    rustSource: '',
    tests: [
      { fn: 'low_byte_bits', args: [0], expected: 0 },
      { fn: 'low_byte_bits', args: [1], expected: 1 },
      { fn: 'low_byte_bits', args: [127], expected: 7 },
      { fn: 'low_byte_bits', args: [128], expected: 1 },
      { fn: 'low_byte_bits', args: [255], expected: 8 },
      { fn: 'low_byte_bits', args: [511], expected: 8 },
      { fn: 'low_byte_bits', args: [256], expected: 0 },
      { fn: 'low_byte_bits', args: [4294967295], expected: 8 },
      { fn: 'low_byte_bits', args: [165], expected: 4 },
      { fn: 'low_byte_bits', args: [55], expected: 5 },
    ],
    reference: {
      a0: 'fn bstep u32 u32 u32 -> u32\ns shr p2 p1\nb and s 1\nr add p0 b\nret r\nend\nfn low_byte_bits u32 -> u32\nc fold bstep 8 0 p0\nret c\nend\n',
      ts: '',
      rust: '',
    },
    wrongEdits: [
      'fn bstep u32 u32 u32 -> u32\ns shr p2 p1\nb and s 1\nr add p0 b\nret r\nend\nfn low_byte_bits u32 -> u32\nc fold bstep 9 0 p0\nret c\nend\n',
    ],
    specs: {
      preserved: [
        { args: [85], result: 4 },
        { args: [3], result: 2 },
        { args: [383], result: 7 },
        { args: [63], result: 6 },
        { args: [130816], result: 0 },
        { args: [126], result: 6 },
        { args: [64], result: 1 },
        { args: [512], result: 0 },
        { args: [96], result: 2 },
      ],
      stale: { args: [129], result: 1 },
      post: 'le r 8',
      candidates: { preserved: 14, stale: 8, post: 3, droppedCandidates: 7 },
    },
  },
];
