/**
 * Held-out task set DL (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts
 * from experiments/set-dl/dl-tasks.neutral.json (an author who never saw the language, the other sets or any
 * model answer). SHA-256 sealed in ai-edit-tasks-dl.sha256 before any subject ran: never alter this file.
 */

export interface TaskDL {
  readonly id: string;
  readonly kind: string;
  readonly target: string;
  readonly wrongEditKind: string;
  readonly note: string;
  readonly instruction: string;
  readonly a0Source: string;
  readonly tests: readonly {
    readonly fn: string;
    readonly args: readonly unknown[];
    readonly expected: unknown;
  }[];
  readonly reference: { readonly a0: string };
  readonly wrongEdits: readonly string[];
}

export const TASKS_DL: readonly TaskDL[] = [
  {
    id: 'dl-shot-clock',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Ceiling division; adding 10 instead of 9 overshoots on exact multiples.',
    instruction:
      'Given tenths of a second elapsed on a 24-second shot clock, return the whole seconds remaining, rounded up.',
    a0Source: 'fn f u32 -> u32\na sub 240 p0\nb div a 10\nret b\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 24 },
      { fn: 'f', args: [5], expected: 24 },
      { fn: 'f', args: [240], expected: 0 },
      { fn: 'f', args: [239], expected: 1 },
      { fn: 'f', args: [231], expected: 1 },
      { fn: 'f', args: [230], expected: 1 },
      { fn: 'f', args: [100], expected: 14 },
      { fn: 'f', args: [101], expected: 14 },
    ],
    reference: { a0: 'fn f u32 -> u32\na sub 240 p0\nb add a 9\nc div b 10\nret c\nend\n' },
    wrongEdits: ['fn f u32 -> u32\na sub 240 p0\nb add a 10\nc div b 10\nret c\nend\n'],
  },
  {
    id: 'dl-tempo-table',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Index shift by one; the wrong edit reverses the table instead.',
    instruction:
      'Tempo modes are numbered from 1, and mode 1 is the first tempo in the table; return that tempo times the number of bars.',
    a0Source: 'fn f u32 u32 -> u32\ntab arr 60 90 120 168\nt get tab p0\nr mul t p1\nret r\nend\n',
    tests: [
      { fn: 'f', args: [1, 2], expected: 120 },
      { fn: 'f', args: [2, 1], expected: 90 },
      { fn: 'f', args: [3, 3], expected: 360 },
      { fn: 'f', args: [4, 1], expected: 168 },
      { fn: 'f', args: [4, 0], expected: 0 },
      { fn: 'f', args: [1, 0], expected: 0 },
      { fn: 'f', args: [2, 10], expected: 900 },
      { fn: 'f', args: [3, 1], expected: 120 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\ntab arr 60 90 120 168\nk sub p0 1\nt get tab k\nr mul t p1\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\ntab arr 60 90 120 168\nk sub 4 p0\nt get tab k\nr mul t p1\nret r\nend\n',
    ],
  },
  {
    id: 'dl-discount-tax',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'order-of-operations',
    note: 'Billing: tax must be on the discounted amount; the wrong edit still taxes the full subtotal.',
    instruction:
      'Subtract the discount from the subtotal first, then add the tax percentage computed on the discounted amount.',
    a0Source:
      'fn f u32 u32 u32 -> u32\nt mul p0 p2\nu div t 100\nv add p0 u\nw sub v p1\nret w\nend\n',
    tests: [
      { fn: 'f', args: [1000, 0, 10], expected: 1100 },
      { fn: 'f', args: [1000, 200, 10], expected: 880 },
      { fn: 'f', args: [500, 500, 20], expected: 0 },
      { fn: 'f', args: [999, 99, 5], expected: 945 },
      { fn: 'f', args: [100, 0, 0], expected: 100 },
      { fn: 'f', args: [0, 0, 50], expected: 0 },
      { fn: 'f', args: [250, 50, 8], expected: 216 },
      { fn: 'f', args: [10, 1, 100], expected: 18 },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 -> u32\nn sub p0 p1\nt mul n p2\nu div t 100\nv add n u\nret v\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 u32 -> u32\nn sub p0 p1\nt mul p0 p2\nu div t 100\nv add n u\nret v\nend\n',
    ],
  },
  {
    id: 'dl-hit-flags',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'wrong-bit',
    note: 'Shift distance selects the flag bit; value 8 is bit 3, not bit 4.',
    instruction:
      'A player can be hit when neither the shield (bit 0) nor invisibility is set; invisibility is bit 3 (value 8).',
    a0Source:
      'fn f u32 -> bool\na and p0 1\ns ne a 0\nb shr p0 2\nc and b 1\nv ne c 0\nx or s v\nr eq x false\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: true },
      { fn: 'f', args: [1], expected: false },
      { fn: 'f', args: [8], expected: false },
      { fn: 'f', args: [4], expected: true },
      { fn: 'f', args: [16], expected: true },
      { fn: 'f', args: [9], expected: false },
      { fn: 'f', args: [12], expected: false },
      { fn: 'f', args: [2], expected: true },
    ],
    reference: {
      a0: 'fn f u32 -> bool\na and p0 1\ns ne a 0\nb shr p0 3\nc and b 1\nv ne c 0\nx or s v\nr eq x false\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 -> bool\na and p0 1\ns ne a 0\nb shr p0 4\nc and b 1\nv ne c 0\nx or s v\nr eq x false\nret r\nend\n',
    ],
  },
  {
    id: 'dl-recipe-scale',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'order-of-operations',
    note: 'Cooking: half the divisor is added after multiplying, not before.',
    instruction:
      'Scale grams from the old number of servings (third argument) to the new one (second argument), rounding to the nearest gram with halves rounded up.',
    a0Source: 'fn f u32 u32 u32 -> u32\na mul p0 p1\nb div a p2\nret b\nend\n',
    tests: [
      { fn: 'f', args: [100, 3, 2], expected: 150 },
      { fn: 'f', args: [10, 1, 3], expected: 3 },
      { fn: 'f', args: [10, 2, 3], expected: 7 },
      { fn: 'f', args: [5, 1, 2], expected: 3 },
      { fn: 'f', args: [7, 3, 4], expected: 5 },
      { fn: 'f', args: [0, 5, 4], expected: 0 },
      { fn: 'f', args: [250, 4, 4], expected: 250 },
      { fn: 'f', args: [1, 1, 1], expected: 1 },
    ],
    reference: {
      a0: 'fn f u32 u32 u32 -> u32\nh shr p2 1\na mul p0 p1\nc add a h\nb div c p2\nret b\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 u32 -> u32\nh shr p2 1\nc add p0 h\na mul c p1\nb div a p2\nret b\nend\n',
    ],
  },
  {
    id: 'dl-window-seat',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Travel: the last column is 5; comparing the raw seat number only works in row 0.',
    instruction:
      'Seats are numbered from 0 with six seats per row (columns 0 to 5); return true for window seats, the first and last column.',
    a0Source: 'fn f u32 -> bool\nc rem p0 6\na eq c 0\nb eq c 6\nr ne a b\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: true },
      { fn: 'f', args: [5], expected: true },
      { fn: 'f', args: [11], expected: true },
      { fn: 'f', args: [6], expected: true },
      { fn: 'f', args: [3], expected: false },
      { fn: 'f', args: [2], expected: false },
      { fn: 'f', args: [17], expected: true },
      { fn: 'f', args: [4], expected: false },
    ],
    reference: { a0: 'fn f u32 -> bool\nc rem p0 6\na eq c 0\nb eq c 5\nr ne a b\nret r\nend\n' },
    wrongEdits: ['fn f u32 -> bool\nc rem p0 6\na eq c 0\nb eq p0 5\nr ne a b\nret r\nend\n'],
  },
  {
    id: 'dl-score-bonus',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Games: read-modify-write of an array element; index wraps modulo 4.',
    instruction:
      'Add the bonus (third argument) to the score at the given position instead of overwriting it, and return the updated scores.',
    a0Source: 'fn f u32x4 u32 u32 -> u32x4\ng get p0 p1\nr set p0 p1 p2\nret r\nend\n',
    tests: [
      { fn: 'f', args: [[1, 2, 3, 4], 0, 10], expected: [11, 2, 3, 4] },
      { fn: 'f', args: [[1, 2, 3, 4], 2, 2], expected: [1, 2, 5, 4] },
      { fn: 'f', args: [[0, 0, 0, 0], 3, 0], expected: [0, 0, 0, 0] },
      { fn: 'f', args: [[5, 5, 5, 5], 5, 1], expected: [5, 6, 5, 5] },
      { fn: 'f', args: [[9, 8, 7, 6], 1, 3], expected: [9, 11, 7, 6] },
      { fn: 'f', args: [[4294967295, 0, 0, 0], 0, 1], expected: [0, 0, 0, 0] },
      { fn: 'f', args: [[2, 4, 6, 8], 3, 0], expected: [2, 4, 6, 8] },
      { fn: 'f', args: [[1, 1, 1, 1], 0, 4], expected: [5, 1, 1, 1] },
    ],
    reference: {
      a0: 'fn f u32x4 u32 u32 -> u32x4\ng get p0 p1\nn add g p2\nr set p0 p1 n\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32x4 u32 u32 -> u32x4\ng get p0 p1\nn add g p2\nr set p0 p2 n\nret r\nend\n',
    ],
  },
  {
    id: 'dl-damage-ticks',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Fold count is the number of ticks.',
    instruction:
      'The damage-over-time effect lasts four ticks, halving each tick; return the total damage over all four ticks.',
    a0Source:
      'fn tick u32 u32 u32 -> u32\na shr p2 p1\nb add p0 a\nret b\nend\nfn f u32 -> u32\nr fold tick 3 0 p0\no mov r\nret o\nend\n',
    tests: [
      { fn: 'f', args: [8], expected: 15 },
      { fn: 'f', args: [16], expected: 30 },
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [1], expected: 1 },
      { fn: 'f', args: [7], expected: 11 },
      { fn: 'f', args: [100], expected: 187 },
      { fn: 'f', args: [15], expected: 26 },
      { fn: 'f', args: [32], expected: 60 },
    ],
    reference: {
      a0: 'fn tick u32 u32 u32 -> u32\na shr p2 p1\nb add p0 a\nret b\nend\nfn f u32 -> u32\nr fold tick 4 0 p0\no mov r\nret o\nend\n',
    },
    wrongEdits: [
      'fn tick u32 u32 u32 -> u32\na shr p2 p1\nb add p0 a\nret b\nend\nfn f u32 -> u32\nr fold tick 5 0 p0\no mov r\nret o\nend\n',
    ],
  },
  {
    id: 'dl-quarter-change',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Loop cap was 3 quarters; inputs up to a few dollars need a larger cap.',
    instruction:
      'The machine should keep handing out quarters for as long as at least 25 cents remain, then return the cents left over.',
    a0Source:
      'fn more u32 u32 u32 -> bool\nu lt p0 p2\nk ne u true\nret k\nend\nfn give u32 u32 u32 -> u32\nn sub p0 p2\nm mov n\nret m\nend\nfn f u32 -> u32\nr loop more give 3 p0 25\no mov r\nret o\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 0 },
      { fn: 'f', args: [25], expected: 0 },
      { fn: 'f', args: [100], expected: 0 },
      { fn: 'f', args: [99], expected: 24 },
      { fn: 'f', args: [130], expected: 5 },
      { fn: 'f', args: [200], expected: 0 },
      { fn: 'f', args: [76], expected: 1 },
      { fn: 'f', args: [101], expected: 1 },
    ],
    reference: {
      a0: 'fn more u32 u32 u32 -> bool\nu lt p0 p2\nk ne u true\nret k\nend\nfn give u32 u32 u32 -> u32\nn sub p0 p2\nm mov n\nret m\nend\nfn f u32 -> u32\nr loop more give 100 p0 25\no mov r\nret o\nend\n',
    },
    wrongEdits: [
      'fn more u32 u32 u32 -> bool\nu lt p0 p2\nk ne u true\nret k\nend\nfn give u32 u32 u32 -> u32\nn sub p0 p2\nm mov n\nret m\nend\nfn f u32 -> u32\nr loop more give 4 p0 25\no mov r\nret o\nend\n',
    ],
  },
  {
    id: 'dl-overbooked-slot',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'start-state',
    note: 'Scheduling: the scan started at slot 1; the wrong edit also treats a full slot as overbooked.',
    instruction:
      'Return the index of the first time slot whose bookings exceed the capacity, scanning from slot 0; return 6 if none does.',
    a0Source:
      'fn fits u32 u32 u32x6 u32 -> bool\ng get p2 p0\nover gt g p3\nk eq over false\nret k\nend\nfn next u32 u32 u32x6 u32 -> u32\nn add p0 1\nm mov n\nret m\nend\nfn f u32x6 u32 -> u32\nr loop fits next 6 1 p0 p1\no mov r\nret o\nend\n',
    tests: [
      { fn: 'f', args: [[5, 5, 5, 5, 5, 5], 5], expected: 6 },
      { fn: 'f', args: [[9, 1, 1, 1, 1, 1], 5], expected: 0 },
      { fn: 'f', args: [[1, 2, 8, 1, 1, 1], 5], expected: 2 },
      { fn: 'f', args: [[1, 1, 1, 1, 1, 6], 5], expected: 5 },
      { fn: 'f', args: [[0, 0, 0, 0, 0, 0], 0], expected: 6 },
      { fn: 'f', args: [[3, 4, 5, 6, 7, 8], 5], expected: 3 },
      { fn: 'f', args: [[7, 7, 7, 7, 7, 7], 10], expected: 6 },
      { fn: 'f', args: [[2, 10, 2, 2, 2, 2], 9], expected: 1 },
    ],
    reference: {
      a0: 'fn fits u32 u32 u32x6 u32 -> bool\ng get p2 p0\nover gt g p3\nk eq over false\nret k\nend\nfn next u32 u32 u32x6 u32 -> u32\nn add p0 1\nm mov n\nret m\nend\nfn f u32x6 u32 -> u32\nr loop fits next 6 0 p0 p1\no mov r\nret o\nend\n',
    },
    wrongEdits: [
      'fn fits u32 u32 u32x6 u32 -> bool\ng get p2 p0\nover ge g p3\nk eq over false\nret k\nend\nfn next u32 u32 u32x6 u32 -> u32\nn add p0 1\nm mov n\nret m\nend\nfn f u32x6 u32 -> u32\nr loop fits next 6 0 p0 p1\no mov r\nret o\nend\n',
    ],
  },
  {
    id: 'dl-dough-rise',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'start-state',
    note: 'Record state (volume, hours); the hour counter started at 1.',
    instruction:
      'Return how many hourly doublings the dough needs to reach at least the goal volume; dough already at the goal needs zero hours.',
    a0Source:
      'fn short (u32,u32) u32 u32 -> bool\nv at p0 0\nk lt v p2\nret k\nend\nfn grow (u32,u32) u32 u32 -> (u32,u32)\nv at p0 0\nd shl v 1\nh at p0 1\nh2 add h 1\nr1 put p0 0 d\nr2 put r1 1 h2\nret r2\nend\nfn f u32 u32 -> u32\ninit rec p0 1\nr loop short grow 20 init p1\no at r 1\nret o\nend\n',
    tests: [
      { fn: 'f', args: [1, 8], expected: 3 },
      { fn: 'f', args: [8, 8], expected: 0 },
      { fn: 'f', args: [10, 5], expected: 0 },
      { fn: 'f', args: [3, 10], expected: 2 },
      { fn: 'f', args: [5, 20], expected: 2 },
      { fn: 'f', args: [0, 1], expected: 20 },
      { fn: 'f', args: [1, 1], expected: 0 },
      { fn: 'f', args: [7, 100], expected: 4 },
    ],
    reference: {
      a0: 'fn short (u32,u32) u32 u32 -> bool\nv at p0 0\nk lt v p2\nret k\nend\nfn grow (u32,u32) u32 u32 -> (u32,u32)\nv at p0 0\nd shl v 1\nh at p0 1\nh2 add h 1\nr1 put p0 0 d\nr2 put r1 1 h2\nret r2\nend\nfn f u32 u32 -> u32\ninit rec p0 0\nr loop short grow 20 init p1\no at r 1\nret o\nend\n',
    },
    wrongEdits: [
      'fn short (u32,u32) u32 u32 -> bool\nv at p0 0\nk le v p2\nret k\nend\nfn grow (u32,u32) u32 u32 -> (u32,u32)\nv at p0 0\nd shl v 1\nh at p0 1\nh2 add h 1\nr1 put p0 0 d\nr2 put r1 1 h2\nret r2\nend\nfn f u32 u32 -> u32\ninit rec p0 0\nr loop short grow 20 init p1\no at r 1\nret o\nend\n',
    ],
  },
  {
    id: 'dl-playlist-fit',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'Music: loop cap must equal the playlist length; a song that exactly fills the budget still fits.',
    instruction:
      'Count how many of the five songs, taken in order, fit into the time budget; all five songs must be considered.',
    a0Source:
      'fn fit (u32,u32) u32 u32x5 u32 -> bool\ns0 at p0 0\ng get p2 p1\nt add s0 g\nk le t p3\nret k\nend\nfn take (u32,u32) u32 u32x5 u32 -> (u32,u32)\ns0 at p0 0\ng get p2 p1\nt add s0 g\nc at p0 1\nc2 add c 1\nr1 put p0 0 t\nr2 put r1 1 c2\nret r2\nend\nfn f u32x5 u32 -> u32\ninit rec 0 0\nr loop fit take 4 init p0 p1\no at r 1\nret o\nend\n',
    tests: [
      { fn: 'f', args: [[1, 1, 1, 1, 1], 5], expected: 5 },
      { fn: 'f', args: [[1, 1, 1, 1, 1], 10], expected: 5 },
      { fn: 'f', args: [[3, 3, 3, 3, 3], 10], expected: 3 },
      { fn: 'f', args: [[0, 0, 0, 0, 0], 0], expected: 5 },
      { fn: 'f', args: [[10, 1, 1, 1, 1], 9], expected: 0 },
      { fn: 'f', args: [[2, 2, 2, 2, 2], 8], expected: 4 },
      { fn: 'f', args: [[4, 4, 4, 4, 1], 17], expected: 5 },
      { fn: 'f', args: [[5, 5, 5, 5, 5], 100], expected: 5 },
    ],
    reference: {
      a0: 'fn fit (u32,u32) u32 u32x5 u32 -> bool\ns0 at p0 0\ng get p2 p1\nt add s0 g\nk le t p3\nret k\nend\nfn take (u32,u32) u32 u32x5 u32 -> (u32,u32)\ns0 at p0 0\ng get p2 p1\nt add s0 g\nc at p0 1\nc2 add c 1\nr1 put p0 0 t\nr2 put r1 1 c2\nret r2\nend\nfn f u32x5 u32 -> u32\ninit rec 0 0\nr loop fit take 5 init p0 p1\no at r 1\nret o\nend\n',
    },
    wrongEdits: [
      'fn fit (u32,u32) u32 u32x5 u32 -> bool\ns0 at p0 0\ng get p2 p1\nt add s0 g\nk lt t p3\nret k\nend\nfn take (u32,u32) u32 u32x5 u32 -> (u32,u32)\ns0 at p0 0\ng get p2 p1\nt add s0 g\nc at p0 1\nc2 add c 1\nr1 put p0 0 t\nr2 put r1 1 c2\nret r2\nend\nfn f u32x5 u32 -> u32\ninit rec 0 0\nr loop fit take 5 init p0 p1\no at r 1\nret o\nend\n',
    ],
  },
  {
    id: 'dl-light-phases',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'State machine; the phase count passed to the step was 4. Ticks are at most 50.',
    instruction:
      'The traffic light has three phases (0, 1, 2) and wraps from 2 back to 0; return the phase after the given number of ticks.',
    a0Source:
      'fn going u32 u32 u32 u32 -> bool\nk lt p1 p2\nok mov k\nret ok\nend\nfn tick u32 u32 u32 u32 -> u32\na add p0 1\nm rem a p3\nret m\nend\nfn f u32 u32 -> u32\nr loop going tick 50 p0 p1 4\no mov r\nret o\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 0 },
      { fn: 'f', args: [0, 1], expected: 1 },
      { fn: 'f', args: [0, 3], expected: 0 },
      { fn: 'f', args: [2, 1], expected: 0 },
      { fn: 'f', args: [1, 2], expected: 0 },
      { fn: 'f', args: [0, 4], expected: 1 },
      { fn: 'f', args: [2, 5], expected: 1 },
      { fn: 'f', args: [1, 0], expected: 1 },
    ],
    reference: {
      a0: 'fn going u32 u32 u32 u32 -> bool\nk lt p1 p2\nok mov k\nret ok\nend\nfn tick u32 u32 u32 u32 -> u32\na add p0 1\nm rem a p3\nret m\nend\nfn f u32 u32 -> u32\nr loop going tick 50 p0 p1 3\no mov r\nret o\nend\n',
    },
    wrongEdits: [
      'fn going u32 u32 u32 u32 -> bool\nk lt p1 p2\nok mov k\nret ok\nend\nfn tick u32 u32 u32 u32 -> u32\na add p0 1\nm rem a p3\nret m\nend\nfn f u32 u32 -> u32\ne add p1 1\nr loop going tick 50 p0 e 3\no mov r\nret o\nend\n',
    ],
  },
  {
    id: 'dl-pin-unlock',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'The loop result is the count of leading matching digits; a full match is 4.',
    instruction: 'The lock should open only when all four entered digits match the code.',
    a0Source:
      'fn same u32 u32 u32x4 u32x4 -> bool\nx get p2 p0\ny get p3 p0\nk eq x y\nret k\nend\nfn adv u32 u32 u32x4 u32x4 -> u32\nn add p0 1\nm mov n\nret m\nend\nfn f u32x4 u32x4 -> bool\nr loop same adv 4 0 p0 p1\nok eq r 3\nret ok\nend\n',
    tests: [
      {
        fn: 'f',
        args: [
          [1, 2, 3, 4],
          [1, 2, 3, 4],
        ],
        expected: true,
      },
      {
        fn: 'f',
        args: [
          [1, 2, 3, 5],
          [1, 2, 3, 4],
        ],
        expected: false,
      },
      {
        fn: 'f',
        args: [
          [0, 2, 3, 4],
          [1, 2, 3, 4],
        ],
        expected: false,
      },
      {
        fn: 'f',
        args: [
          [1, 0, 3, 4],
          [1, 2, 3, 4],
        ],
        expected: false,
      },
      {
        fn: 'f',
        args: [
          [7, 7, 7, 7],
          [7, 7, 7, 7],
        ],
        expected: true,
      },
      {
        fn: 'f',
        args: [
          [1, 2, 0, 4],
          [1, 2, 3, 4],
        ],
        expected: false,
      },
      {
        fn: 'f',
        args: [
          [9, 9, 9, 0],
          [9, 9, 9, 1],
        ],
        expected: false,
      },
      {
        fn: 'f',
        args: [
          [0, 0, 0, 0],
          [0, 0, 0, 0],
        ],
        expected: true,
      },
    ],
    reference: {
      a0: 'fn same u32 u32 u32x4 u32x4 -> bool\nx get p2 p0\ny get p3 p0\nk eq x y\nret k\nend\nfn adv u32 u32 u32x4 u32x4 -> u32\nn add p0 1\nm mov n\nret m\nend\nfn f u32x4 u32x4 -> bool\nr loop same adv 4 0 p0 p1\nok eq r 4\nret ok\nend\n',
    },
    wrongEdits: [
      'fn same u32 u32 u32x4 u32x4 -> bool\nx get p2 p0\ny get p3 p0\nk eq x y\nret k\nend\nfn adv u32 u32 u32x4 u32x4 -> u32\nn add p0 1\nm mov n\nret m\nend\nfn f u32x4 u32x4 -> bool\nr loop same adv 4 0 p0 p1\nok ge r 3\nret ok\nend\n',
    ],
  },
  {
    id: 'dl-grade-letter',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'missing-cap',
    note: 'Fixing the table while dropping the cap makes 100 wrap to F.',
    instruction:
      "Scores 0-19 get F, 20-39 D, 40-59 C, 60-79 B and 80 or more A; return the letter's byte. The letter table is in the wrong order.",
    a0Source:
      'fn f u32 -> u32\nt text "ABCDF"\nk div p0 20\nc gt k 4\nj select c 4 k\ng get t j\nret g\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 70 },
      { fn: 'f', args: [100], expected: 65 },
      { fn: 'f', args: [80], expected: 65 },
      { fn: 'f', args: [79], expected: 66 },
      { fn: 'f', args: [40], expected: 67 },
      { fn: 'f', args: [20], expected: 68 },
      { fn: 'f', args: [59], expected: 67 },
      { fn: 'f', args: [200], expected: 65 },
    ],
    reference: {
      a0: 'fn f u32 -> u32\nt text "FDCBA"\nk div p0 20\nc gt k 4\nj select c 4 k\ng get t j\nret g\nend\n',
    },
    wrongEdits: ['fn f u32 -> u32\nt text "FDCBA"\nk div p0 20\ng get t k\nret g\nend\n'],
  },
  {
    id: 'dl-station-code',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'fold-bound',
    note: 'OSLO bytes sum to 317; folding 5 times wraps and counts O twice.',
    instruction:
      'The ticket code is the sum of all letters of the station name plus the seat number, modulo 100; every letter must be included.',
    a0Source:
      'fn addb u32 u32 u32x4 -> u32\ng get p2 p1\nn add p0 g\nret n\nend\nfn f u32 -> u32\nt text "OSLO"\ns fold addb 3 0 t\na add s p0\nr rem a 100\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0], expected: 17 },
      { fn: 'f', args: [83], expected: 0 },
      { fn: 'f', args: [1], expected: 18 },
      { fn: 'f', args: [3], expected: 20 },
      { fn: 'f', args: [4], expected: 21 },
      { fn: 'f', args: [62], expected: 79 },
      { fn: 'f', args: [100], expected: 17 },
      { fn: 'f', args: [99], expected: 16 },
    ],
    reference: {
      a0: 'fn addb u32 u32 u32x4 -> u32\ng get p2 p1\nn add p0 g\nret n\nend\nfn f u32 -> u32\nt text "OSLO"\ns fold addb 4 0 t\na add s p0\nr rem a 100\nret r\nend\n',
    },
    wrongEdits: [
      'fn addb u32 u32 u32x4 -> u32\ng get p2 p1\nn add p0 g\nret n\nend\nfn f u32 -> u32\nt text "OSLO"\ns fold addb 5 0 t\na add s p0\nr rem a 100\nret r\nend\n',
    ],
  },
  {
    id: 'dl-menu-reverse',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'off-by-one',
    note: 'Text processing: reversed index is length minus one minus position.',
    instruction:
      'Read the word from its end: position 0 is the last letter, position 3 the first. Keep the upper-case option as it is.',
    a0Source:
      'fn f u32 bool -> u32\nt text "menu"\ng get t p0\nu sub g 32\nr select p1 u g\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, true], expected: 85 },
      { fn: 'f', args: [1, true], expected: 78 },
      { fn: 'f', args: [2, true], expected: 69 },
      { fn: 'f', args: [3, true], expected: 77 },
      { fn: 'f', args: [0, false], expected: 117 },
      { fn: 'f', args: [1, false], expected: 110 },
      { fn: 'f', args: [2, false], expected: 101 },
      { fn: 'f', args: [3, false], expected: 109 },
    ],
    reference: {
      a0: 'fn f u32 bool -> u32\nt text "menu"\nk sub 3 p0\ng get t k\nu sub g 32\nr select p1 u g\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 bool -> u32\nt text "menu"\nk sub 4 p0\ng get t k\nu sub g 32\nr select p1 u g\nret r\nend\n',
    ],
  },
  {
    id: 'dl-digit-prices',
    kind: 'comprehension-edit',
    target: 'f',
    wrongEditKind: 'order-of-operations',
    note: "Cooking menu: subtract the code of '0' (48) before multiplying.",
    instruction:
      "The menu string stores each item's price as a digit character; return that price in dollars times the quantity.",
    a0Source: 'fn f u32 u32 -> u32\nt text "3125"\ng get t p0\nr mul g p1\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 1], expected: 3 },
      { fn: 'f', args: [0, 2], expected: 6 },
      { fn: 'f', args: [1, 3], expected: 3 },
      { fn: 'f', args: [2, 0], expected: 0 },
      { fn: 'f', args: [3, 4], expected: 20 },
      { fn: 'f', args: [2, 5], expected: 10 },
      { fn: 'f', args: [1, 1], expected: 1 },
      { fn: 'f', args: [3, 1], expected: 5 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\nt text "3125"\ng get t p0\nd sub g 48\nr mul d p1\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\nt text "3125"\ng get t p0\nr mul g p1\nd sub r 48\nret d\nend\n',
    ],
  },
  {
    id: 'dl-note-transpose',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'wrong-operand',
    note: 'Music: octave carry divides the absolute position by the scale length 7.',
    instruction:
      'Transpose the note up by the given steps on the seven-note scale; add 100 for every octave crossed, where an octave is seven steps from C.',
    a0Source:
      'fn f u32 u32 -> u32\nt text "CDEFGAB"\nk add p0 p1\ng get t k\nq div k 8\nh mul q 100\nr add g h\nret r\nend\n',
    tests: [
      { fn: 'f', args: [0, 0], expected: 67 },
      { fn: 'f', args: [6, 1], expected: 167 },
      { fn: 'f', args: [5, 2], expected: 167 },
      { fn: 'f', args: [0, 7], expected: 167 },
      { fn: 'f', args: [3, 4], expected: 167 },
      { fn: 'f', args: [6, 2], expected: 168 },
      { fn: 'f', args: [2, 12], expected: 267 },
      { fn: 'f', args: [1, 1], expected: 69 },
    ],
    reference: {
      a0: 'fn f u32 u32 -> u32\nt text "CDEFGAB"\nk add p0 p1\ng get t k\nq div k 7\nh mul q 100\nr add g h\nret r\nend\n',
    },
    wrongEdits: [
      'fn f u32 u32 -> u32\nt text "CDEFGAB"\nk add p0 p1\ng get t k\nq div p1 7\nh mul q 100\nr add g h\nret r\nend\n',
    ],
  },
  {
    id: 'dl-tip-echo',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'wrong-operand',
    note: 'Billing echo; adding a flat 15 instead of the computed tip is the wrong edit.',
    instruction:
      'Read the bill amount and write the amount plus a 15 percent tip (rounded down), not the tip alone.',
    a0Source:
      'fn f io -> io\nr read p0\nx at r 0\nt at r 1\nm mul x 15\ntp div m 100\nw write t tp\nret w\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [100] }], expected: { out: [115] } },
      { fn: 'f', args: [{ io: [200] }], expected: { out: [230] } },
      { fn: 'f', args: [{ io: [0] }], expected: { out: [0] } },
      { fn: 'f', args: [{ io: [] }], expected: { out: [0] } },
      { fn: 'f', args: [{ io: [7] }], expected: { out: [8] } },
      { fn: 'f', args: [{ io: [1000, 5] }], expected: { out: [1150] } },
      { fn: 'f', args: [{ io: [20] }], expected: { out: [23] } },
      { fn: 'f', args: [{ io: [99] }], expected: { out: [113] } },
    ],
    reference: {
      a0: 'fn f io -> io\nr read p0\nx at r 0\nt at r 1\nm mul x 15\ntp div m 100\ns add x tp\nw write t s\nret w\nend\n',
    },
    wrongEdits: [
      'fn f io -> io\nr read p0\nx at r 0\nt at r 1\nm mul x 15\ntp div m 100\ns add x 15\nw write t s\nret w\nend\n',
    ],
  },
  {
    id: 'dl-goals-ranked',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'token-order',
    note: 'Sports scoreboard; the wrong edit writes the smaller first.',
    instruction:
      "Read the two teams' goals and write the larger count first and the smaller second.",
    a0Source:
      'fn f io -> io\nr1 read p0\na at r1 0\nt1 at r1 1\nr2 read t1\nb at r2 0\nt2 at r2 1\nw1 write t2 a\nw2 write w1 b\nret w2\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [3, 1] }], expected: { out: [3, 1] } },
      { fn: 'f', args: [{ io: [1, 3] }], expected: { out: [3, 1] } },
      { fn: 'f', args: [{ io: [2, 2] }], expected: { out: [2, 2] } },
      { fn: 'f', args: [{ io: [] }], expected: { out: [0, 0] } },
      { fn: 'f', args: [{ io: [5] }], expected: { out: [5, 0] } },
      { fn: 'f', args: [{ io: [0, 9] }], expected: { out: [9, 0] } },
      { fn: 'f', args: [{ io: [10, 20, 30] }], expected: { out: [20, 10] } },
      { fn: 'f', args: [{ io: [7, 6] }], expected: { out: [7, 6] } },
    ],
    reference: {
      a0: 'fn f io -> io\nr1 read p0\na at r1 0\nt1 at r1 1\nr2 read t1\nb at r2 0\nt2 at r2 1\nc gt b a\nhi select c b a\nlo select c a b\nw1 write t2 hi\nw2 write w1 lo\nret w2\nend\n',
    },
    wrongEdits: [
      'fn f io -> io\nr1 read p0\na at r1 0\nt1 at r1 1\nr2 read t1\nb at r2 0\nt2 at r2 1\nc gt b a\nhi select c b a\nlo select c a b\nw1 write t2 lo\nw2 write w1 hi\nret w2\nend\n',
    ],
  },
  {
    id: 'dl-three-bins',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'dropped-term',
    note: 'Inventory; the token must be threaded through the third read.',
    instruction: 'Read the counts of three storage bins (not two) and write their total.',
    a0Source:
      'fn f io -> io\nr1 read p0\na at r1 0\nt1 at r1 1\nr2 read t1\nb at r2 0\nt2 at r2 1\ns add a b\nw write t2 s\nret w\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [1, 2, 3] }], expected: { out: [6] } },
      { fn: 'f', args: [{ io: [] }], expected: { out: [0] } },
      { fn: 'f', args: [{ io: [5] }], expected: { out: [5] } },
      { fn: 'f', args: [{ io: [1, 1] }], expected: { out: [2] } },
      { fn: 'f', args: [{ io: [1, 1, 1] }], expected: { out: [3] } },
      { fn: 'f', args: [{ io: [0, 0, 9] }], expected: { out: [9] } },
      { fn: 'f', args: [{ io: [4294967295, 1, 0] }], expected: { out: [0] } },
      { fn: 'f', args: [{ io: [10, 20, 30, 40] }], expected: { out: [60] } },
    ],
    reference: {
      a0: 'fn f io -> io\nr1 read p0\na at r1 0\nt1 at r1 1\nr2 read t1\nb at r2 0\nt2 at r2 1\nr3 read t2\nc at r3 0\nt3 at r3 1\ns add a b\ns2 add s c\nw write t3 s2\nret w\nend\n',
    },
    wrongEdits: [
      'fn f io -> io\nr1 read p0\na at r1 0\nt1 at r1 1\nr2 read t1\nb at r2 0\nt2 at r2 1\nr3 read t2\nc at r3 0\nt3 at r3 1\ns add a b\nw write t3 s\nret w\nend\n',
    ],
  },
  {
    id: 'dl-hand-total',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'token-order',
    note: 'Card game; puts writes the length 3 first; the total must come after the hand.',
    instruction:
      'After writing the hand of three cards, also write the total of the three card values.',
    a0Source: 'fn f io u32 u32 u32 -> io\na arr p1 p2 p3\nw puts p0 a\nret w\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [] }, 1, 2, 3], expected: { out: [3, 1, 2, 3, 6] } },
      { fn: 'f', args: [{ io: [] }, 0, 0, 0], expected: { out: [3, 0, 0, 0, 0] } },
      { fn: 'f', args: [{ io: [] }, 5, 5, 5], expected: { out: [3, 5, 5, 5, 15] } },
      { fn: 'f', args: [{ io: [] }, 10, 0, 1], expected: { out: [3, 10, 0, 1, 11] } },
      { fn: 'f', args: [{ io: [] }, 4, 4, 1], expected: { out: [3, 4, 4, 1, 9] } },
      { fn: 'f', args: [{ io: [] }, 2, 7, 9], expected: { out: [3, 2, 7, 9, 18] } },
      { fn: 'f', args: [{ io: [] }, 13, 12, 11], expected: { out: [3, 13, 12, 11, 36] } },
      { fn: 'f', args: [{ io: [] }, 1, 0, 0], expected: { out: [3, 1, 0, 0, 1] } },
    ],
    reference: {
      a0: 'fn f io u32 u32 u32 -> io\na arr p1 p2 p3\nw puts p0 a\ns add p1 p2\ns2 add s p3\nw2 write w s2\nret w2\nend\n',
    },
    wrongEdits: [
      'fn f io u32 u32 u32 -> io\na arr p1 p2 p3\ns add p1 p2\ns2 add s p3\nw write p0 s2\nw2 puts w a\nret w2\nend\n',
    ],
  },
  {
    id: 'dl-thermo-emit',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Signals: the offset is added after scaling; the token goes through the helper.',
    instruction:
      'Read a Celsius temperature and emit it in Fahrenheit: multiply by 9, divide by 5, then add 32.',
    a0Source:
      'fn emit io u32 -> io\nm mov p1\nw write p0 m\nret w\nend\nfn f io -> io\nr read p0\nx at r 0\nt at r 1\na add x 32\nm mul a 9\nd div m 5\nw call emit t d\nret w\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [0] }], expected: { out: [32] } },
      { fn: 'f', args: [{ io: [100] }], expected: { out: [212] } },
      { fn: 'f', args: [{ io: [10] }], expected: { out: [50] } },
      { fn: 'f', args: [{ io: [37] }], expected: { out: [98] } },
      { fn: 'f', args: [{ io: [] }], expected: { out: [32] } },
      { fn: 'f', args: [{ io: [5] }], expected: { out: [41] } },
      { fn: 'f', args: [{ io: [1] }], expected: { out: [33] } },
      { fn: 'f', args: [{ io: [20, 99] }], expected: { out: [68] } },
    ],
    reference: {
      a0: 'fn emit io u32 -> io\nm mov p1\nw write p0 m\nret w\nend\nfn f io -> io\nr read p0\nx at r 0\nt at r 1\nm mul x 9\nd div m 5\na add d 32\nw call emit t a\nret w\nend\n',
    },
    wrongEdits: [
      'fn emit io u32 -> io\nm mov p1\nw write p0 m\nret w\nend\nfn f io -> io\nr read p0\nx at r 0\nt at r 1\nm mul x 5\nd div m 9\na add d 32\nw call emit t a\nret w\nend\n',
    ],
  },
  {
    id: 'dl-trip-stamps',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'token-order',
    note: 'Travel log: division operands were swapped; the wrong edit fixes the division but swaps the stamp order.',
    instruction:
      "Log the trip's speed (distance divided by time) first and then the distance, each through the stamp helper.",
    a0Source:
      'fn stamp io u32 -> io\na write p0 7\nb write a p1\nret b\nend\nfn f io u32 u32 -> io\ns div p2 p1\nw1 call stamp p0 s\nw2 call stamp w1 p1\nret w2\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [] }, 100, 2], expected: { out: [7, 50, 7, 100] } },
      { fn: 'f', args: [{ io: [] }, 60, 60], expected: { out: [7, 1, 7, 60] } },
      { fn: 'f', args: [{ io: [] }, 0, 5], expected: { out: [7, 0, 7, 0] } },
      { fn: 'f', args: [{ io: [] }, 10, 0], expected: { out: [7, 4294967295, 7, 10] } },
      { fn: 'f', args: [{ io: [] }, 9, 3], expected: { out: [7, 3, 7, 9] } },
      { fn: 'f', args: [{ io: [] }, 1, 1], expected: { out: [7, 1, 7, 1] } },
      { fn: 'f', args: [{ io: [] }, 7, 2], expected: { out: [7, 3, 7, 7] } },
      { fn: 'f', args: [{ io: [] }, 300, 4], expected: { out: [7, 75, 7, 300] } },
    ],
    reference: {
      a0: 'fn stamp io u32 -> io\na write p0 7\nb write a p1\nret b\nend\nfn f io u32 u32 -> io\ns div p1 p2\nw1 call stamp p0 s\nw2 call stamp w1 p1\nret w2\nend\n',
    },
    wrongEdits: [
      'fn stamp io u32 -> io\na write p0 7\nb write a p1\nret b\nend\nfn f io u32 u32 -> io\ns div p1 p2\nw1 call stamp p0 p1\nw2 call stamp w1 s\nret w2\nend\n',
    ],
  },
  {
    id: 'dl-receipt-line',
    kind: 'targeted-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: 'Billing receipt; product wraps modulo 2^32.',
    instruction:
      'Read a unit price and a quantity and write the receipt line [price, quantity, price times quantity] with puts.',
    a0Source:
      'fn f io -> io\nr1 read p0\np at r1 0\nt1 at r1 1\nr2 read t1\nq at r2 0\nt2 at r2 1\ns add p q\nv arr p q s\nw puts t2 v\nret w\nend\n',
    tests: [
      { fn: 'f', args: [{ io: [3, 4] }], expected: { out: [3, 3, 4, 12] } },
      { fn: 'f', args: [{ io: [0, 5] }], expected: { out: [3, 0, 5, 0] } },
      { fn: 'f', args: [{ io: [2, 2] }], expected: { out: [3, 2, 2, 4] } },
      { fn: 'f', args: [{ io: [] }], expected: { out: [3, 0, 0, 0] } },
      { fn: 'f', args: [{ io: [7] }], expected: { out: [3, 7, 0, 0] } },
      { fn: 'f', args: [{ io: [10, 1] }], expected: { out: [3, 10, 1, 10] } },
      { fn: 'f', args: [{ io: [1, 10] }], expected: { out: [3, 1, 10, 10] } },
      { fn: 'f', args: [{ io: [65536, 65536] }], expected: { out: [3, 65536, 65536, 0] } },
    ],
    reference: {
      a0: 'fn f io -> io\nr1 read p0\np at r1 0\nt1 at r1 1\nr2 read t1\nq at r2 0\nt2 at r2 1\ns mul p q\nv arr p q s\nw puts t2 v\nret w\nend\n',
    },
    wrongEdits: [
      'fn f io -> io\nr1 read p0\np at r1 0\nt1 at r1 1\nr2 read t1\nq at r2 0\nt2 at r2 1\ns mul p q\nv arr q p s\nw puts t2 v\nret w\nend\n',
    ],
  },
  {
    id: 'dl-runner-pace',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'New helper pace; zero metres gives the all-ones pace, which is never the faster one.',
    instruction:
      'Add a helper that turns metres and seconds into seconds per kilometre, and make the target return the faster (smaller) pace of the two runners.',
    a0Source: 'fn f u32 u32 u32 u32 -> u32\na mul p1 1000\nb div a p0\nret b\nend\n',
    tests: [
      { fn: 'f', args: [1000, 300, 1000, 240], expected: 240 },
      { fn: 'f', args: [5000, 1500, 1000, 320], expected: 300 },
      { fn: 'f', args: [2000, 500, 2000, 500], expected: 250 },
      { fn: 'f', args: [1000, 200, 500, 90], expected: 180 },
      { fn: 'f', args: [0, 100, 1000, 250], expected: 250 },
      { fn: 'f', args: [400, 100, 800, 180], expected: 225 },
      { fn: 'f', args: [1000, 1, 1000, 2], expected: 1 },
      { fn: 'f', args: [3000, 600, 1500, 330], expected: 200 },
    ],
    reference: {
      a0: 'fn pace u32 u32 -> u32\na mul p1 1000\nb div a p0\nret b\nend\nfn f u32 u32 u32 u32 -> u32\nx call pace p0 p1\ny call pace p2 p3\nk lt y x\nr select k y x\nret r\nend\n',
    },
    wrongEdits: [
      'fn pace u32 u32 -> u32\na mul p1 1000\nb div a p0\nret b\nend\nfn f u32 u32 u32 u32 -> u32\nx call pace p0 p1\ny call pace p2 p3\nk gt y x\nr select k y x\nret r\nend\n',
    ],
  },
  {
    id: 'dl-cook-minutes',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'swapped-argument',
    note: "Cooking timer; the start ignored the second time's minutes.",
    instruction:
      'Add a helper converting hours and minutes to minutes, and use it for both clock times so the target returns the minutes from the first time to the second.',
    a0Source:
      'fn f u32 u32 u32 u32 -> u32\na mul p0 60\nb add a p1\nc mul p2 60\nd sub c b\nret d\nend\n',
    tests: [
      { fn: 'f', args: [10, 0, 11, 30], expected: 90 },
      { fn: 'f', args: [8, 15, 8, 45], expected: 30 },
      { fn: 'f', args: [0, 0, 0, 0], expected: 0 },
      { fn: 'f', args: [12, 30, 12, 30], expected: 0 },
      { fn: 'f', args: [1, 59, 2, 0], expected: 1 },
      { fn: 'f', args: [6, 0, 18, 0], expected: 720 },
      { fn: 'f', args: [9, 10, 9, 50], expected: 40 },
      { fn: 'f', args: [23, 0, 23, 59], expected: 59 },
    ],
    reference: {
      a0: 'fn mins u32 u32 -> u32\na mul p0 60\nb add a p1\nret b\nend\nfn f u32 u32 u32 u32 -> u32\nx call mins p0 p1\ny call mins p2 p3\nd sub y x\nret d\nend\n',
    },
    wrongEdits: [
      'fn mins u32 u32 -> u32\na mul p0 60\nb add a p1\nret b\nend\nfn f u32 u32 u32 u32 -> u32\nx call mins p0 p1\ny call mins p2 p3\nd sub x y\nret d\nend\n',
    ],
  },
  {
    id: 'dl-one-low-stock',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'comparison',
    note: 'Inventory; a stock equal to the minimum is not below it.',
    instruction:
      'Add a helper that says whether a stock is below the minimum, and make the target return true when exactly one of the two stocks is below it.',
    a0Source: 'fn f u32 u32 u32 -> bool\na lt p0 p2\nr eq a true\nret r\nend\n',
    tests: [
      { fn: 'f', args: [1, 10, 5], expected: true },
      { fn: 'f', args: [10, 1, 5], expected: true },
      { fn: 'f', args: [1, 1, 5], expected: false },
      { fn: 'f', args: [10, 10, 5], expected: false },
      { fn: 'f', args: [5, 1, 5], expected: true },
      { fn: 'f', args: [5, 5, 5], expected: false },
      { fn: 'f', args: [4, 5, 5], expected: true },
      { fn: 'f', args: [0, 0, 0], expected: false },
    ],
    reference: {
      a0: 'fn low u32 u32 -> bool\nk lt p0 p1\no mov k\nret o\nend\nfn f u32 u32 u32 -> bool\nx call low p0 p2\ny call low p1 p2\nr ne x y\nret r\nend\n',
    },
    wrongEdits: [
      'fn low u32 u32 -> bool\nk le p0 p1\no mov k\nret o\nend\nfn f u32 u32 u32 -> bool\nx call low p0 p2\ny call low p1 p2\nr ne x y\nret r\nend\n',
    ],
  },
  {
    id: 'dl-stereo-volume',
    kind: 'multi-node-edit',
    target: 'f',
    wrongEditKind: 'order-of-operations',
    note: 'Signals; dividing before multiplying loses precision.',
    instruction:
      'Add a helper that scales a level by a percentage (multiply, then divide by 100), and use it so both the left and right channels are scaled.',
    a0Source: 'fn f u32 u32 u32 -> u32x2\na mul p0 p2\nb div a 100\nr arr b p1\nret r\nend\n',
    tests: [
      { fn: 'f', args: [200, 100, 50], expected: [100, 50] },
      { fn: 'f', args: [50, 30, 50], expected: [25, 15] },
      { fn: 'f', args: [0, 0, 100], expected: [0, 0] },
      { fn: 'f', args: [1000, 1000, 100], expected: [1000, 1000] },
      { fn: 'f', args: [99, 199, 10], expected: [9, 19] },
      { fn: 'f', args: [100, 250, 0], expected: [0, 0] },
      { fn: 'f', args: [150, 150, 200], expected: [300, 300] },
      { fn: 'f', args: [7, 9, 300], expected: [21, 27] },
    ],
    reference: {
      a0: 'fn scale u32 u32 -> u32\nm mul p0 p1\nd div m 100\nret d\nend\nfn f u32 u32 u32 -> u32x2\nx call scale p0 p2\ny call scale p1 p2\nr arr x y\nret r\nend\n',
    },
    wrongEdits: [
      'fn scale u32 u32 -> u32\nd div p0 100\nm mul d p1\nret m\nend\nfn f u32 u32 u32 -> u32x2\nx call scale p0 p2\ny call scale p1 p2\nr arr x y\nret r\nend\n',
    ],
  },
];
