/**
 * Builds the sealed task set H (tools/ai-edit-tasks-h.ts) from one language-neutral file written by an author
 * who never saw the language, the other sets or any model answer (experiments/set-h/AUTHOR_BRIEF.md,
 * experiments/set-h/h-tasks.neutral.json). This tool only changes the format (JSON program to the language's text)
 * and checks everything with the reference interpreter: the starting program fails a hidden test, the reference
 * passes all of them, every wrong edit fails one. A task that fails a check is listed and dropped; nothing is
 * repaired by hand.
 *
 *   node dist/tools/ai-edit-tasks-h-gen.js [h|i] [--write]   (the set letter selects experiments/set-<letter>/)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { parseAndValidate, run, type TypedFunc, type Value } from '../src/core.js';

type Arg = string | number | boolean;
interface NStmt {
  id: string;
  op: string;
  args: Arg[];
}
interface NFunc {
  name: string;
  params: string[];
  result: string;
  body: NStmt[];
  ret: Arg;
}
interface NProgram {
  functions: NFunc[];
}
interface NTest {
  fn: string;
  args: Value[];
  expected: Value;
}
interface NTask {
  id: string;
  kind: string;
  wrongEditKind: string;
  target: string;
  instruction: string;
  start: NProgram;
  reference: NProgram;
  wrongEdits: NProgram[];
  tests: NTest[];
  note: string;
}

const text = (p: NProgram): string =>
  `${p.functions
    .map((f) =>
      [
        `fn ${f.name}${f.params.length === 0 ? '' : ` ${f.params.join(' ')}`} -> ${f.result}`,
        ...f.body.map((s) => `${s.id} ${s.op} ${s.args.map(String).join(' ')}`.trimEnd()),
        `ret ${String(f.ret)}`,
        'end',
      ].join('\n'),
    )
    .join('\n')}\n`;

const same = (a: unknown, b: unknown): boolean => JSON.stringify(a) === JSON.stringify(b);
const letter = process.argv.find((a) => /^[hij]$/.test(a)) ?? 'h';
const tasks = (
  JSON.parse(readFileSync(`experiments/set-${letter}/${letter}-tasks.neutral.json`, 'utf8')) as {
    tasks: NTask[];
  }
).tasks;
const problems: string[] = [];
const kept: NTask[] = [];
for (const t of tasks) {
  const fail = (m: string): void => void problems.push(`${t.id}: ${m}`);
  try {
    const ts = parseAndValidate(text(t.start));
    const tr = parseAndValidate(text(t.reference));
    const wrongs = t.wrongEdits.map((w) => parseAndValidate(text(w)));
    const ok = (p: ReturnType<typeof parseAndValidate>, x: NTest): boolean => {
      const f = p.byName.get(x.fn) as TypedFunc | undefined;
      if (f === undefined) return false;
      try {
        return same(run(f, x.args), x.expected);
      } catch {
        return false;
      }
    };
    const before = problems.length;
    const refFails = t.tests.filter((x) => !ok(tr, x));
    if (refFails.length > 0) fail(`reference fails ${JSON.stringify(refFails)}`);
    if (t.tests.every((x) => ok(ts, x))) fail('starting program passes every test');
    wrongs.forEach((w, i) => {
      if (t.tests.every((x) => ok(w, x))) fail(`wrong edit ${i} passes every test`);
    });
    if (t.tests.length < 8) fail(`only ${t.tests.length} tests`);
    if (!ts.byName.has(t.target)) fail('target missing');
    if (problems.length === before) kept.push(t);
  } catch (e) {
    fail(`does not validate: ${e instanceof Error ? e.message : String(e)}`);
  }
}
console.log(`${kept.length} of ${tasks.length} tasks kept`);
for (const p of problems) console.log(`dropped: ${p}`);
if (process.argv.includes('--write')) {
  const body = kept
    .map(
      (t) =>
        `  {\n    id: ${JSON.stringify(t.id)},\n    kind: ${JSON.stringify(t.kind)},\n    target: ${JSON.stringify(t.target)},\n    wrongEditKind: ${JSON.stringify(t.wrongEditKind)},\n    note: ${JSON.stringify(t.note)},\n    instruction: ${JSON.stringify(t.instruction)},\n    a0Source: ${JSON.stringify(text(t.start))},\n    tests: ${JSON.stringify(t.tests)},\n    reference: { a0: ${JSON.stringify(text(t.reference))} },\n    wrongEdits: ${JSON.stringify(t.wrongEdits.map(text))},\n  },`,
    )
    .join('\n');
  writeFileSync(
    `tools/ai-edit-tasks-${letter}.ts`,
    `/**\n * Held-out task set ${letter.toUpperCase()} (A0 only) for the dense-against-canonical experiment. Generated by tools/ai-edit-tasks-h-gen.ts\n * from experiments/set-${letter}/${letter}-tasks.neutral.json (an author who never saw the language, the other sets or any\n * model answer). SHA-256 sealed in ai-edit-tasks-${letter}.sha256 before any subject ran: never alter this file.\n */\n\nimport type { Value } from '../src/core.js';\n\nexport interface Task${letter.toUpperCase()} {\n  readonly id: string;\n  readonly kind: string;\n  readonly target: string;\n  readonly wrongEditKind: string;\n  readonly note: string;\n  readonly instruction: string;\n  readonly a0Source: string;\n  readonly tests: readonly { readonly fn: string; readonly args: readonly Value[]; readonly expected: Value }[];\n  readonly reference: { readonly a0: string };\n  readonly wrongEdits: readonly string[];\n}\n\nexport const TASKS_${letter.toUpperCase()}: readonly Task${letter.toUpperCase()}[] = [\n${body}\n];\n`,
  );
}
