#!/bin/sh
# Regenerate packaging/homebrew/a0.rb from a release's checksums file.
# Usage: sh tools/homebrew-formula.sh <version-without-v> <checksums.txt> [out]
set -eu
version=$1
sums=$2
out=${3:-packaging/homebrew/a0.rb}
sha() {
  s=$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  [ -n "$s" ] || { echo "missing checksum for $1 in $sums" >&2; exit 1; }
  printf '%s' "$s"
}
darwin_arm64=$(sha a0-darwin-arm64)
darwin_x64=$(sha a0-darwin-x64)
linux_arm64=$(sha a0-linux-arm64)
linux_x64=$(sha a0-linux-x64)
cat > "$out" <<RUBY
# Homebrew formula for the tap Joe-Simo/homebrew-a0 (brew install joe-simo/a0/a0).
# Generated by tools/homebrew-formula.sh from the release's checksums.txt; do not edit by hand.
class A0 < Formula
  desc "Programming language built for AI, not for people"
  homepage "https://github.com/Joe-Simo/a0"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Joe-Simo/a0/releases/download/v#{version}/a0-darwin-arm64"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "https://github.com/Joe-Simo/a0/releases/download/v#{version}/a0-darwin-x64"
      sha256 "$darwin_x64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Joe-Simo/a0/releases/download/v#{version}/a0-linux-arm64"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "https://github.com/Joe-Simo/a0/releases/download/v#{version}/a0-linux-x64"
      sha256 "$linux_x64"
    end
  end

  def install
    bin.install Dir["a0-*"].first => "a0"
  end

  test do
    (testpath/"sq.a0").write "fn sq u32 -> u32\\na mul p0 p0\\nret a\\nend\\n"
    system bin/"a0", "check", testpath/"sq.a0"
    assert_equal "144", shell_output("#{bin}/a0 run #{testpath}/sq.a0 sq 12").strip
  end
end
RUBY
echo "wrote $out for v$version"
