/**
 * The a0lang.com page programs (site/page.a0, site/docs.a0) are generated by an A0 program,
 * site/gen/sitegen.a0, from the templates site/gen/page.tpl and site/gen/docs.tpl and the files
 * they name. This module runs it natively: the TypeScript C backend compiles the linked
 * generator, clang builds it with a stdin/stdout main, and the binary reads the template and
 * its files as io words. Nothing here knows about the pages: the input is the template, then
 * every file its `f ROLE... PATH` lines name, in order, each as a byte count and its bytes
 * packed four to a little-endian word (a missing file is a count of 0); the output is one byte
 * per io word.
 */

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { compile } from '../src/backends.js';
import { link } from '../src/link.js';
import { findClang, runTool } from '../src/toolchain.js';
import { checkOperandBudget } from './site-budget.js';

export const GENERATOR = join('site', 'gen', 'sitegen.a0');
const BUILD_DIR = join('dist', 'sitegen');
/** io capacities in words: the results files are about 2.3 MB (4 bytes a word); a page is under 1 MB. */
const INPUT_WORDS = 1 << 21;
const OUTPUT_WORDS = 1 << 22;

const MAIN = (entry: string): string => `#include <pthread.h>
#include <stdio.h>
#define A0_IO_INPUT_CAPACITY ${INPUT_WORDS}u
#define A0_IO_OUTPUT_CAPACITY ${OUTPUT_WORDS}u
#include "sitegen.c"
static a0_io io;
static uint32_t code;
static void *run(void *arg) {
  (void)arg;
  code = a0_${entry}(&io);
  return NULL;
}
int main(void) {
  unsigned char b[4];
  uint32_t n = 0;
  while (fread(b, 1, 4, stdin) == 4) {
    if (n == A0_IO_INPUT_CAPACITY) {
      fprintf(stderr, "sitegen: input over %u words\\n", A0_IO_INPUT_CAPACITY);
      return 64;
    }
    io.input[n++] = (uint32_t)b[0] | (uint32_t)b[1] << 8 | (uint32_t)b[2] << 16 | (uint32_t)b[3] << 24;
  }
  io.ninput = n;
  pthread_attr_t attr;
  pthread_t thread;
  pthread_attr_init(&attr);
  pthread_attr_setstacksize(&attr, (size_t)1u << 30);
  if (pthread_create(&thread, &attr, run, NULL) != 0 || pthread_join(thread, NULL) != 0) {
    fprintf(stderr, "sitegen: cannot run the generator thread\\n");
    return 66;
  }
  if (io.noutput >= A0_IO_OUTPUT_CAPACITY) {
    fprintf(stderr, "sitegen: output capacity reached\\n");
    return 65;
  }
  for (uint32_t i = 0; i < io.noutput; i++) putchar((int)(io.output[i] & 255u));
  return (int)code;
}
`;

/** Link the generator, emit C, and build the native binary; returns its path. */
export async function buildGenerator(entry = 'sitegen'): Promise<string> {
  const clang = findClang();
  if (clang.path === undefined)
    throw new Error('clang not found (the site generator runs natively)');
  const program = (await link(GENERATOR, (p) => readFile(p, 'utf8'), { root: '.' })).program;
  const c = compile(program, 'c', {
    ioInputCapacity: INPUT_WORDS,
    ioOutputCapacity: OUTPUT_WORDS,
  }).text;
  await mkdir(BUILD_DIR, { recursive: true });
  await writeFile(join(BUILD_DIR, 'sitegen.c'), c, 'utf8');
  await writeFile(join(BUILD_DIR, 'main.c'), MAIN(entry), 'utf8');
  const r = runTool(
    clang.path,
    ['-std=c11', '-O2', '-Wno-unused-parameter', '-o', 'sitegen', 'main.c'],
    { cwd: BUILD_DIR, timeoutMs: 1_800_000 },
  );
  if (!r.ok) throw new Error(`sitegen build failed:\n${r.stderr.slice(0, 4000)}`);
  return join(BUILD_DIR, 'sitegen');
}

/** A byte count and the bytes packed four to a word. */
function words(bytes: Buffer): number[] {
  const out = [bytes.length];
  for (let i = 0; i < bytes.length; i += 4)
    out.push(
      (bytes[i] ?? 0) |
        ((bytes[i + 1] ?? 0) << 8) |
        ((bytes[i + 2] ?? 0) << 16) |
        ((bytes[i + 3] ?? 0) << 24),
    );
  return out;
}

/** The generator's input for `template`: the template, then each file of its `f` lines. */
export async function generatorInput(template: string): Promise<Buffer> {
  const tpl = await readFile(template);
  const input = words(tpl);
  for (const line of tpl.toString('utf8').split('\n')) {
    if (!line.startsWith('f ')) continue;
    const path = line.slice(line.lastIndexOf(' ') + 1);
    input.push(...(existsSync(path) ? words(await readFile(path)) : [0]));
  }
  const buf = Buffer.alloc(input.length * 4);
  input.forEach((w, i) => {
    buf.writeUInt32LE(w >>> 0, i * 4);
  });
  return buf;
}

/** Run the built generator on `template`; returns the generated A0 source (checked against the operand budget of tools/site-budget.ts unless `budget` is false). */
export async function generate(
  binary: string,
  template: string,
  options: { readonly budget?: boolean } = {},
): Promise<string> {
  const r = spawnSync(binary, [], {
    input: await generatorInput(template),
    maxBuffer: 64 << 20,
    timeout: 600_000,
  });
  if (r.status !== 0)
    throw new Error(`sitegen failed on ${template} (status ${r.status}): ${String(r.stderr)}`);
  const source = r.stdout.toString('utf8');
  // Every function of the page must fit the A0 toolchain's operand table with room to grow.
  if (options.budget !== false) checkOperandBudget(source, template);
  return source;
}
