/**
 * Source emission for JavaScript (ES module), C (C-compatible, also valid C++), Java,
 * SystemVerilog, direct Darwin AArch64 assembly (src/arm64.ts), and direct x86-64 assembly
 * (src/x86_64.ts, System V, macOS and Linux), direct RISC-V RV64 assembly (src/riscv64.ts,
 * LP64, Linux), direct AVR assembly for the ATmega328P (src/avr.ts, avr-gcc calling
 * convention), direct 32-bit ARM assembly (src/arm32.ts, ARMv7-A), a direct wasm32 binary
 * module (src/wasm.ts; the compiled text is the module's base64, see `wasmModuleBytes`),
 * plus a bounded in-memory function-emission cache.
 *
 * Every backend preserves the exact v0.1 semantics: wrapping u32 arithmetic,
 * logical right shift, shift distance masked to five bits, unsigned comparison,
 * and non-numeric booleans. Identifiers are validated by the core and emitted with
 * a prefix so source names cannot collide with target keywords or runtime symbols.
 */

import { assembleArm32, emitArm32Function } from './arm32.js';
import { assembleArm64, emitArm64Function } from './arm64.js';
import { assembleAvr, emitAvrFunction } from './avr.js';
import {
  A0Error,
  assertVectorSized,
  bitWidth,
  containsIo,
  formatType,
  isPrimitive,
  type Node,
  type Op,
  type Operand,
  type Type,
  type TypedFunc,
  type TypedProgram,
} from './core.js';
import { semanticRevision } from './edit.js';
import { emitSequential, needsSequential, SV_UDIV_MODULE } from './hw.js';
import { optimizeFunction } from './optimize.js';
import { assembleRiscv64, emitRiscv64Function } from './riscv64.js';
import { assembleWasm, emitWasmFunction } from './wasm.js';
import { assembleX86_64, emitX86_64Function } from './x86_64.js';

export const COMPILER_VERSION = 'a0c-0.1.14';

export type Target =
  | 'js'
  | 'c'
  | 'java'
  | 'sv'
  | 'arm64'
  | 'x86_64'
  | 'riscv64'
  | 'avr'
  | 'wasm'
  | 'arm32';
export const TARGETS: readonly Target[] = [
  'js',
  'c',
  'java',
  'sv',
  'arm64',
  'x86_64',
  'riscv64',
  'avr',
  'wasm',
  'arm32',
];

export function isTarget(text: string): text is Target {
  return (TARGETS as readonly string[]).includes(text);
}

const hex = (v: number): string => `0x${v.toString(16).padStart(8, '0')}`;

type Emitter = (fn: TypedFunc) => string;

/** Type of an operand inside a function (params, nodes, literals). */
export function operandTypeOf(fn: TypedFunc, o: Operand): Type {
  switch (o.kind) {
    case 'u32':
      return 'u32';
    case 'bool':
      return 'bool';
    case 'param':
      return fn.params[o.index] ?? 'u32';
    case 'node':
      return fn.types.get(o.id) ?? 'u32';
  }
}

/** `index mod N` for a u32 index: a literal folds, a power-of-two N masks, else `%`. */
function jsIndex(fn: TypedFunc, arr: Operand | undefined, idx: Operand | undefined): string {
  const n = arrayLength(fn, arr);
  if (idx?.kind === 'u32') return String(idx.value % n);
  const i = jsOperand(idx as Operand);
  return (n & (n - 1)) === 0 ? `(${i} & ${n - 1})` : `${i} % ${n}`;
}

function arrayLength(fn: TypedFunc, o: Operand | undefined): number {
  if (o === undefined) throw new A0Error('missing array operand');
  const t = operandTypeOf(fn, o);
  if (isPrimitive(t) || t.kind !== 'arr') throw new A0Error('expected array operand');
  return t.length;
}

/** Injective, identifier-safe name for a type: u, b, a<N>_<elem>, r<N>_<f>..._<f>. */
export function mangleType(t: Type): string {
  if (t === 'u32') return 'u';
  if (t === 'bool') return 'b';
  if (t === 'io') return 'io';
  if (t.kind === 'arr') return `a${t.length}_${mangleType(t.elem)}`;
  return `r${t.fields.length}_${t.fields.map(mangleType).join('_')}`;
}

/** All aggregate types used by a program, nested types first, deduplicated. */
export function aggregateTypes(program: TypedProgram): Type[] {
  const seen = new Set<string>();
  const out: Type[] = [];
  const visit = (t: Type): void => {
    if (isPrimitive(t)) return;
    if (t.kind === 'arr') visit(t.elem);
    else t.fields.forEach(visit);
    const key = formatType(t);
    if (!seen.has(key)) {
      seen.add(key);
      out.push(t);
    }
  };
  for (const fn of program.functions) {
    fn.params.forEach(visit);
    visit(fn.result);
    for (const t of fn.types.values()) visit(t);
  }
  return out;
}

/** JSON shape used by the JS runtime guard. */
function jsShape(t: Type): string {
  if (isPrimitive(t)) return JSON.stringify(t);
  if (t.kind === 'arr') return `["arr",${t.length},${jsShape(t.elem)}]`;
  return `["rec",[${t.fields.map(jsShape).join(',')}]]`;
}

// ---------------------------------------------------------------------------
// JavaScript
// ---------------------------------------------------------------------------

const JS_PRELUDE = `// Generated by A0 ${COMPILER_VERSION}. Exact u32/bool semantics.
const U32_MAX = 0xffffffff;
function a0_u32(v, name) {
  if (typeof v !== 'number' || !Number.isInteger(v) || v < 0 || v > U32_MAX) throw new RangeError(name + ': expected u32');
  return v;
}
function a0_bad(name, shape) { throw new (shape === 'u32' ? RangeError : TypeError)(name + ': expected ' + shape); }
function a0_bool(v, name) {
  if (typeof v !== 'boolean') throw new TypeError(name + ': expected bool');
  return v;
}
function a0_check(v, shape, name) {
  if (shape === 'u32') return a0_u32(v, name);
  if (shape === 'bool') return a0_bool(v, name);
  if (shape === 'io') return a0_io(v, name);
  const typed = v instanceof Uint32Array || v instanceof Uint8Array;
  if (!Array.isArray(v) && !typed) throw new TypeError(name + ': expected ' + shape[0]);
  if (shape[0] === 'arr') {
    if (v.length !== shape[1]) throw new RangeError(name + ': expected ' + shape[1] + ' elements');
    if (shape[2] === 'u32') { if (v instanceof Uint32Array) return v; for (let i = 0; i < v.length; i++) a0_u32(v[i], name + '[' + i + ']'); return Uint32Array.from(v); }
    if (shape[2] === 'bool') { if (v instanceof Uint8Array) return v; for (let i = 0; i < v.length; i++) a0_bool(v[i], name + '[' + i + ']'); return Uint8Array.from(v, (x) => (x ? 1 : 0)); }
    if (typed) throw new TypeError(name + ': expected nested array');
    const c = v.slice();
    for (let i = 0; i < c.length; i++) c[i] = a0_check(c[i], shape[2], name + '[' + i + ']');
    return c;
  } else {
    if (typed) throw new TypeError(name + ': expected record');
    const c = v.slice();
    if (v.length !== shape[1].length) throw new RangeError(name + ': expected ' + shape[1].length + ' fields');
    for (let i = 0; i < c.length; i++) c[i] = a0_check(c[i], shape[1][i], name + '.' + i);
    return c;
  }
}
function a0_with(a, i, v) { const c = a.slice(); c[i] = v; return c; }
// io token: { input: number[], position, output: number[] }. Exhausted input reads 0.
function a0_io(v, name) {
  if (typeof v !== 'object' || v === null || !Array.isArray(v.input) || !Array.isArray(v.output) || typeof v.position !== 'number') throw new TypeError(name + ': expected io token');
  return v;
}
export function a0_make_io(input) { return { input: input.slice(), position: 0, output: [] }; }
function a0_read(t) { const v = t.position < t.input.length ? t.input[t.position++] : 0; return [v, t]; }
function a0_write(t, v) { t.output.push(v); return t; }
function a0_puts(t, a) { t.output.push(a.length); for (let i = 0; i < a.length; i++) t.output.push(a[i]); return t; }
`;

function jsOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return String(o.value);
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

const FRESH_OPS = new Set<Op>(['arr', 'rec', 'set', 'put']);

function sameOp(x: Operand, y: Operand): boolean {
  return (
    (x.kind === 'node' && y.kind === 'node' && x.id === y.id) ||
    (x.kind === 'param' && y.kind === 'param' && x.index === y.index)
  );
}

/**
 * May the aggregate operand `o` be updated in place by the node at `index`?
 * Sound when the value is provably unshared: it is a fresh allocation (arr/rec/set/put result)
 * or a parameter the target owns privately (`ownedParam`: in JS only the p0 state of an
 * iteration body, in C every by-value parameter and the owned loop state); every other use of
 * it is a non-escaping element/field read (`get`/`at` as first operand) that happens before
 * `index`; and it is not returned. `get`/`at` results alias their container and are never mutated.
 */
function mutableHere(
  fn: TypedFunc,
  o: Operand,
  index: number,
  ownedParam: (paramIndex: number) => boolean,
): boolean {
  if (o.kind === 'node') {
    const def = fn.nodes.find((n) => n.id === o.id);
    if (def === undefined || !FRESH_OPS.has(def.op)) return false;
  } else if (!(o.kind === 'param' && ownedParam(o.index))) {
    return false;
  }
  if (sameOp(fn.ret, o)) return false;
  for (const [j, n] of fn.nodes.entries()) {
    if (j === index) continue;
    for (const [k, arg] of n.args.entries()) {
      if (!sameOp(arg, o)) continue;
      if (j > index) return false;
      if (!((n.op === 'get' || n.op === 'at') && k === 0)) return false;
    }
  }
  return true;
}

/** JS ownership: only the p0 state of the owned iteration-body variant is private. */
const jsOwned =
  (ownedP0: boolean) =>
  (i: number): boolean =>
    i === 0 && ownedP0;

/** A node whose result (and therefore whose and/or/xor operands) is bool. */
const isBoolNode = (fn: TypedFunc, node: Node): boolean => fn.types.get(node.id) === 'bool';

function jsExpr(node: Node, fn: TypedFunc, index = -1, ownedP0 = false): string {
  const [a, b, c] = node.args.map(jsOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `(${a} + ${b}) >>> 0`;
    case 'sub':
      return `(${a} - ${b}) >>> 0`;
    case 'mul':
      return `Math.imul(${a}, ${b}) >>> 0`;
    case 'and':
      return isBoolNode(fn, node) ? `(${a} && ${b})` : `(${a} & ${b}) >>> 0`;
    case 'or':
      return isBoolNode(fn, node) ? `(${a} || ${b})` : `(${a} | ${b}) >>> 0`;
    case 'xor':
      return isBoolNode(fn, node) ? `(${a} !== ${b})` : `(${a} ^ ${b}) >>> 0`;
    case 'shl':
      return `(${a} << (${b} & 31)) >>> 0`;
    case 'shr':
      return `${a} >>> (${b} & 31)`;
    case 'div':
      return `(${b} === 0 ? 0xffffffff : Math.floor(${a} / ${b}))`;
    case 'rem':
      return `(${b} === 0 ? ${a} : ${a} % ${b})`;
    case 'eq':
      return `${a} === ${b}`;
    case 'lt':
      return `${a} < ${b}`;
    case 'le':
      return `${a} <= ${b}`;
    case 'gt':
      return `${a} > ${b}`;
    case 'ge':
      return `${a} >= ${b}`;
    case 'ne':
      return `${a} !== ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'call':
      return `a0i_${node.callee ?? ''}(${node.args.map(jsOperand).join(', ')})`;
    case 'arr': {
      // Scalar-element arrays are typed arrays (u32 -> Uint32Array, bool -> Uint8Array of 0/1);
      // nested aggregates stay plain arrays. All array helpers work on both.
      const t = fn.types.get(node.id);
      const elem = t !== undefined && !isPrimitive(t) && t.kind === 'arr' ? t.elem : 'u32';
      // An all-zero literal is a plain allocation (measured: `of(0,...)` costs on small kernels).
      const zeros = node.args.every(
        (o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value),
      );
      if (elem === 'u32')
        return zeros
          ? `new Uint32Array(${node.args.length})`
          : `Uint32Array.of(${node.args.map(jsOperand).join(', ')})`;
      if (elem === 'bool')
        return zeros
          ? `new Uint8Array(${node.args.length})`
          : `Uint8Array.of(${node.args.map((o) => `${jsOperand(o)} ? 1 : 0`).join(', ')})`;
      return `[${node.args.map(jsOperand).join(', ')}]`;
    }
    case 'rec':
      return `[${node.args.map(jsOperand).join(', ')}]`;
    case 'get': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      const elem = !isPrimitive(t) && t.kind === 'arr' ? t.elem : 'u32';
      const read = `${a}[${jsIndex(fn, node.args[0], node.args[1])}]`;
      return elem === 'bool' ? `${read} === 1` : read;
    }
    case 'set': {
      const inPlace =
        index >= 0 && mutableHere(fn, node.args[0] as Operand, index, jsOwned(ownedP0));
      const et = operandTypeOf(fn, node.args[0] as Operand);
      const boolElem = !isPrimitive(et) && et.kind === 'arr' && et.elem === 'bool';
      const value = boolElem ? `(${c} ? 1 : 0)` : c;
      const idx = jsIndex(fn, node.args[0], node.args[1]);
      return inPlace ? `(${a}[${idx}] = ${value}, ${a})` : `a0_with(${a}, ${idx}, ${value})`;
    }
    case 'at':
      return `${a}[${b}]`;
    case 'put': {
      const inPlace =
        index >= 0 && mutableHere(fn, node.args[0] as Operand, index, jsOwned(ownedP0));
      return inPlace ? `(${a}[${b}] = ${c}, ${a})` : `a0_with(${a}, ${b}, ${c})`;
    }
    case 'read':
      return `a0_read(${a})`;
    case 'write':
      return `a0_write(${a}, ${b})`;
    case 'puts':
      return `a0_puts(${a}, ${b})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

/** Emit one JS function body; `owned` marks the p0-owned iteration-body variant. */
function jsBody(fn: TypedFunc, owned: boolean): string[] {
  const stateAggregate = (o: Operand): boolean => !isPrimitive(operandTypeOf(fn, o));
  const body = fn.nodes.map((n, index) => {
    if (n.op !== 'fold' && n.op !== 'loop')
      return `  const n_${n.id} = ${jsExpr(n, fn, index, owned)};`;
    const [count, init, ...extra] = n.args.map(jsOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!a0i_${n.pred ?? ''}(${call})) break;` : '';
    // Aggregate state is owned by the loop so the body may update it in place: copy the initial
    // value once unless it is already provably unshared (fresh and used only here).
    const initOwned = mutableHere(fn, n.args[1] as Operand, index, jsOwned(owned));
    const initExpr = stateAggregate(n.args[1] as Operand) && !initOwned ? `${init}.slice()` : init;
    const bodyName = stateAggregate(n.args[1] as Operand)
      ? `a0o_${n.callee ?? ''}`
      : `a0i_${n.callee ?? ''}`;
    return `  let n_${n.id} = ${initExpr};\n  for (let i = 0; i < ${count}; i++) {${guard} n_${n.id} = ${bodyName}(${call}); }`;
  });
  // An owned variant must return an owned value: copy unless the result is p0 itself or fresh.
  const ret = fn.ret;
  const fresh =
    (ret.kind === 'param' && ret.index === 0) ||
    (ret.kind === 'node' && FRESH_OPS.has(fn.nodes.find((n) => n.id === ret.id)?.op ?? 'mov'));
  const retExpr =
    owned && !isPrimitive(fn.result) && !fresh ? `${jsOperand(ret)}.slice()` : jsOperand(ret);
  return [...body, `  return ${retExpr};`];
}

const emitJsFunction: Emitter = (fn) => {
  const params = fn.params.map((_, i) => `p${i}`).join(', ');
  // Public entry: validate inputs once, then run the unguarded internal function.
  // Internal calls, folds, and loops target the a0i_/a0o_ variants, so guards are paid only at the boundary.
  // Scalar guards are a single comparison: `(v >>> 0) === v` holds exactly for integers in
  // [0, 2^32) and for no string, boolean, object, NaN, or fraction (measured: the call into
  // a0_u32 cost 1.3-1.4x on three-operation kernels).
  const guards = fn.params.map((t, i) =>
    t === 'u32'
      ? `  if ((p${i} >>> 0) !== p${i}) a0_bad('p${i}', 'u32');`
      : t === 'bool'
        ? `  if (typeof p${i} !== 'boolean') a0_bad('p${i}', 'bool');`
        : `  p${i} = a0_check(p${i}, ${jsShape(t)}, 'p${i}');`,
  );
  const lines = [`function a0i_${fn.name}(${params}) {`, ...jsBody(fn, false), '}'];
  const p0 = fn.params[0];
  if (p0 !== undefined && !isPrimitive(p0) && fn.params[1] === 'u32') {
    // Iteration-body shape (state, index, ...): owned-state variant for fold/loop.
    lines.push(`function a0o_${fn.name}(${params}) {`, ...jsBody(fn, true), '}');
  }
  // Scalar-signature entries carry the body after the guards instead of calling a0i_: one frame
  // fewer at the boundary (aggregate entries keep the call, their guards rebind the parameters).
  const scalar = fn.params.every(isPrimitive);
  lines.push(
    `export function ${fn.name}(${params}) {`,
    ...guards,
    ...(scalar ? jsBody(fn, false) : [`  return a0i_${fn.name}(${params});`]),
    '}',
  );
  return lines.join('\n');
};

// ---------------------------------------------------------------------------
// C (also compiles as C++)
// ---------------------------------------------------------------------------

const C_PRELUDE = `/* Generated by A0 ${COMPILER_VERSION}. Exact u32/bool semantics. */
#include <stdint.h>
#include <stdbool.h>
typedef struct a0_io a0_io;
`;

/** Fixed-capacity io runtime for C targets (freestanding-safe: no allocation). */
export const C_IO_INPUT_CAPACITY = 256;
export const C_IO_OUTPUT_CAPACITY = 1024;
const cIoRuntime = (inCap: number, outCap: number): string =>
  `struct a0_io { uint32_t input[${inCap}]; uint32_t ninput; uint32_t position; uint32_t output[${outCap}]; uint32_t noutput; };
static inline a0t_r2_u_io a0_read(a0_io *t) { a0t_r2_u_io r; r.f0 = t->position < t->ninput ? t->input[t->position++] : 0u; r.f1 = t; return r; }
static inline a0_io *a0_write(a0_io *t, uint32_t v) { if (t->noutput < ${outCap}u) t->output[t->noutput++] = v; return t; }
static inline a0_io *a0_puts(a0_io *t, const uint32_t *e, uint32_t n) { a0_write(t, n); for (uint32_t i = 0; i < n; i++) a0_write(t, e[i]); return t; }`;

const cType = (t: Type): string =>
  t === 'u32'
    ? 'uint32_t'
    : t === 'bool'
      ? 'bool'
      : t === 'io'
        ? 'a0_io *'
        : `a0t_${mangleType(t)}`;

/** Typedefs plus constructor/update helpers for one aggregate type (C, also valid C++). */
function cTypeDecl(t: Type): string {
  if (isPrimitive(t)) return '';
  const name = cType(t);
  const m = mangleType(t);
  if (t.kind === 'arr') {
    const e = cType(t.elem);
    const params = Array.from({ length: t.length }, (_, i) => `${e} e${i}`).join(', ');
    const inits = Array.from({ length: t.length }, (_, i) => `r.e[${i}] = e${i};`).join(' ');
    return [
      `typedef struct { ${e} e[${t.length}]; } ${name};`,
      // An all-zero literal of a scalar array is a zero initializer (`{0}` is warning-free in C
      // and C++ only for a flat struct); every other literal uses the element-wise constructor.
      ...(isPrimitive(t.elem)
        ? [`static inline ${name} a0zero_${m}(void) { ${name} r = {0}; return r; }`]
        : []),
      `static inline ${name} a0mk_${m}(${params}) { ${name} r; ${inits} return r; }`,
      `static inline ${name} a0set_${m}(${name} a, uint32_t i, ${e} v) { a.e[i % ${t.length}u] = v; return a; }`,
    ].join('\n');
  }
  const fields = t.fields.map((f, i) => `${cType(f)} f${i};`).join(' ');
  const params = t.fields.map((f, i) => `${cType(f)} f${i}`).join(', ');
  const inits = t.fields.map((_, i) => `r.f${i} = f${i};`).join(' ');
  const puts = t.fields.map(
    (f, i) =>
      `static inline ${name} a0put_${m}_${i}(${name} r, ${cType(f)} v) { r.f${i} = v; return r; }`,
  );
  return [
    `typedef struct { ${fields} } ${name};`,
    `static inline ${name} a0mk_${m}(${params}) { ${name} r; ${inits} return r; }`,
    ...puts,
  ].join('\n');
}

/**
 * C function variants. `value` is the public ABI (aggregates by value, result by value).
 * Iteration bodies (`p0` aggregate state, `p1` u32 index, result of the state type) also get an
 * `owned` variant `void a0o_f(T *p0, ...)` that updates the loop state through the pointer;
 * predicates of that shape returning bool get a `ref` variant `bool a0r_f(const T *p0, ...)`.
 * Every by-value aggregate parameter and the owned state are private to the callee, so a
 * `set`/`put` whose old value is provably dead (`mutableHere`) writes in place; the node is then
 * an alias of the updated storage (no local of its own) instead of a copy. Value semantics are
 * unchanged: any value that is still observable is copied as before.
 */
type CVariant = 'value' | 'owned' | 'ref';

const isIterationShape = (fn: TypedFunc): boolean =>
  fn.params[0] !== undefined && !isPrimitive(fn.params[0]) && fn.params[1] === 'u32';

const hasOwnedVariant = (fn: TypedFunc): boolean =>
  isIterationShape(fn) && formatType(fn.result) === formatType(fn.params[0] as Type);

const hasRefVariant = (fn: TypedFunc): boolean => isIterationShape(fn) && fn.result === 'bool';

interface CContext {
  readonly fn: TypedFunc;
  readonly variant: CVariant;
  /** Nodes updated in place, mapped to the storage they alias (a value node or a parameter). */
  readonly aliases: Map<string, Operand>;
}

function cOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return `${o.value}u`;
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

/** The storage an operand denotes: an alias node resolves to the value it updated in place. */
function cRoot(ctx: CContext, o: Operand): Operand {
  return o.kind === 'node' ? (ctx.aliases.get(o.id) ?? o) : o;
}

/** Value (lvalue) expression of an operand; p0 is a pointer outside the value variant. */
function cVal(ctx: CContext, o: Operand): string {
  const root = cRoot(ctx, o);
  if (root.kind === 'param' && root.index === 0 && ctx.variant !== 'value') return '(*p0)';
  return cOperand(root);
}

/** In C every by-value aggregate parameter is the callee's own copy; a `ref` p0 is read-only. */
const cOwned =
  (variant: CVariant) =>
  (i: number): boolean =>
    !(variant === 'ref' && i === 0);

/** Does the node at `index` update its first operand in place? Records the alias. */
function cInPlace(ctx: CContext, node: Node, index: number): boolean {
  const target = node.args[0] as Operand;
  if (!mutableHere(ctx.fn, target, index, cOwned(ctx.variant))) return false;
  ctx.aliases.set(node.id, cRoot(ctx, target));
  return true;
}

function cExpr(ctx: CContext, node: Node, index: number): string {
  const fn = ctx.fn;
  const vals = node.args.map((o) => cVal(ctx, o));
  const [a, b, c] = vals;
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `(uint32_t)(${a} + ${b})`;
    case 'sub':
      return `(uint32_t)(${a} - ${b})`;
    case 'mul':
      return `(uint32_t)((uint64_t)${a} * (uint64_t)${b})`;
    case 'and':
      return isBoolNode(fn, node) ? `(${a} && ${b})` : `(${a} & ${b})`;
    case 'or':
      return isBoolNode(fn, node) ? `(${a} || ${b})` : `(${a} | ${b})`;
    case 'xor':
      return isBoolNode(fn, node) ? `(${a} != ${b})` : `(${a} ^ ${b})`;
    case 'shl':
      return `(uint32_t)(${a} << (${b} & 31u))`;
    case 'shr':
      return `(${a} >> (${b} & 31u))`;
    case 'div':
      return `(${b} == 0u ? 0xffffffffu : ${a} / ${b})`;
    case 'rem':
      return `(${b} == 0u ? ${a} : ${a} % ${b})`;
    case 'eq':
      return `(${a} == ${b})`;
    case 'lt':
      return `(${a} < ${b})`;
    case 'le':
      return `(${a} <= ${b})`;
    case 'gt':
      return `(${a} > ${b})`;
    case 'ge':
      return `(${a} >= ${b})`;
    case 'ne':
      return `(${a} != ${b})`;
    case 'select':
      return `(${a} ? ${b} : ${c})`;
    case 'call':
      return `a0_${node.callee ?? ''}(${vals.join(', ')})`;
    case 'arr': {
      const t = fn.types.get(node.id) ?? 'u32';
      const zeros =
        !isPrimitive(t) &&
        t.kind === 'arr' &&
        isPrimitive(t.elem) &&
        node.args.every(
          (o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value),
        );
      return zeros ? `a0zero_${mangleType(t)}()` : `a0mk_${mangleType(t)}(${vals.join(', ')})`;
    }
    case 'rec':
      return `a0mk_${mangleType(fn.types.get(node.id) ?? 'u32')}(${vals.join(', ')})`;
    case 'get':
      return `${a}.e[${b} % ${arrayLength(fn, node.args[0])}u]`;
    case 'set': {
      const idx = `${b} % ${arrayLength(fn, node.args[0])}u`;
      // In place: an assignment statement; the node aliases its operand's storage.
      if (cInPlace(ctx, node, index)) return `${a}.e[${idx}] = ${c};`;
      return `a0set_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}(${a}, ${b}, ${c})`;
    }
    case 'at':
      return `${a}.f${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}`;
    case 'put': {
      const k = node.args[1]?.kind === 'u32' ? node.args[1].value : 0;
      if (cInPlace(ctx, node, index)) return `${a}.f${k} = ${c};`;
      return `a0put_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}_${k}(${a}, ${c})`;
    }
    case 'read':
      return `a0_read(${a})`;
    case 'write':
      return `a0_write(${a}, ${b})`;
    case 'puts':
      return `a0_puts(${a}, ${b}.e, ${arrayLength(fn, node.args[1])}u)`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

export function cSignature(fn: TypedFunc): string {
  const params =
    fn.params.length === 0 ? 'void' : fn.params.map((t, i) => `${cType(t)} p${i}`).join(', ');
  return `${cType(fn.result)} a0_${fn.name}(${params})`;
}

function cVariantSignature(fn: TypedFunc, variant: CVariant): string {
  if (variant === 'value') return cSignature(fn);
  const p0 = cType(fn.params[0] as Type);
  const rest = fn.params.slice(1).map((t, i) => `${cType(t)} p${i + 1}`);
  const params = [variant === 'owned' ? `${p0} *p0` : `const ${p0} *p0`, ...rest].join(', ');
  return variant === 'owned'
    ? `static inline void a0o_${fn.name}(${params})`
    : `static inline ${cType(fn.result)} a0r_${fn.name}(${params})`;
}

function cBody(fn: TypedFunc, variant: CVariant): string {
  const ctx: CContext = { fn, variant, aliases: new Map() };
  const lines = fn.nodes.map((n, index) => {
    const t = cType(fn.types.get(n.id) ?? 'u32');
    if (n.op === 'fold' || n.op === 'loop') {
      const [count, init, ...extra] = n.args.map((o) => cVal(ctx, o));
      if (isPrimitive(fn.types.get(n.id) ?? 'u32')) {
        const call = [`n_${n.id}`, 'i', ...extra].join(', ');
        const guard = n.op === 'loop' ? ` if (!a0_${n.pred ?? ''}(${call})) break;` : '';
        return `  ${t} n_${n.id} = ${init};\n  for (uint32_t i = 0; i < ${count}; i++) {${guard} n_${n.id} = a0_${n.callee ?? ''}(${call}); }`;
      }
      // Aggregate state: the body updates it through a pointer and the predicate reads it
      // through a const pointer, so no trip copies the state. The state is the initial value's
      // own storage when that value is provably unshared (as in JS); otherwise one copy.
      const initOperand = n.args[1] as Operand;
      const owned = mutableHere(fn, initOperand, index, cOwned(variant));
      if (owned) ctx.aliases.set(n.id, cRoot(ctx, initOperand));
      const state = owned ? init : `n_${n.id}`;
      const call = [`&${state}`, 'i', ...extra].join(', ');
      const guard = n.op === 'loop' ? ` if (!a0r_${n.pred ?? ''}(${call})) break;` : '';
      const loop = `for (uint32_t i = 0; i < ${count}; i++) {${guard} a0o_${n.callee ?? ''}(${call}); }`;
      return owned ? `  ${loop}` : `  ${t} n_${n.id} = ${init};\n  ${loop}`;
    }
    const expr = cExpr(ctx, n, index);
    if (ctx.aliases.has(n.id)) return `  ${expr}`;
    // `const T x` for values; `T *const x` for the io pointer (the pointee is mutable state).
    const decl = t.endsWith('*') ? `${t}const` : `const ${t}`;
    // Effect results may be legitimately unused (the effect is the point); keep -Wall clean.
    const effect = n.op === 'read' || n.op === 'write' || containsIo(fn.types.get(n.id) ?? 'u32');
    return `  ${decl} n_${n.id} = ${expr};${effect ? ` (void)n_${n.id};` : ''}`;
  });
  // A local updated in place cannot be const: drop the qualifier on every aliased node.
  const roots = new Set(
    [...ctx.aliases.values()].filter((o) => o.kind === 'node').map((o) => cOperand(o)),
  );
  const body = lines.map((line) => {
    const m = /^ {2}const \S+ (n_[a-z0-9_]+) =/.exec(line);
    return m !== null && roots.has(m[1] as string) ? line.replace('  const ', '  ') : line;
  });
  let ret = `  return ${cVal(ctx, fn.ret)};`;
  if (variant === 'owned') {
    // The state is already updated in place when the result aliases p0; otherwise store it.
    const root = cRoot(ctx, fn.ret);
    ret = root.kind === 'param' && root.index === 0 ? '' : `  *p0 = ${cVal(ctx, fn.ret)};`;
  }
  return [`${cVariantSignature(fn, variant)} {`, ...body, ...(ret === '' ? [] : [ret]), '}'].join(
    '\n',
  );
}

const emitCFunction: Emitter = (fn) => {
  const variants: CVariant[] = ['value'];
  if (hasOwnedVariant(fn)) variants.push('owned');
  if (hasRefVariant(fn)) variants.push('ref');
  return variants.map((v) => cBody(fn, v)).join('\n\n');
};

// ---------------------------------------------------------------------------
// Java
// ---------------------------------------------------------------------------

export const JAVA_CLASS = 'A0Module';

const javaType = (t: Type): string =>
  t === 'u32'
    ? 'int'
    : t === 'bool'
      ? 'boolean'
      : t === 'io'
        ? 'A0Io'
        : t.kind === 'arr'
          ? `${javaType(t.elem)}[]`
          : `R_${mangleType(t)}`;

/** Java io runtime with the C runtime's fixed capacities: input truncated to inCap words, writes past outCap dropped. */
const javaIoRuntime = (inCap: number, outCap: number): string => `  public static final class A0Io {
    public final int[] input = new int[${inCap}]; public final int ninput; public int position; public final int[] output = new int[${outCap}]; public int noutput;
    public A0Io(int[] in) { ninput = Math.min(in.length, ${inCap}); System.arraycopy(in, 0, input, 0, ninput); }
  }
  static R_r2_u_io read(A0Io t) { int v = t.position < t.ninput ? t.input[t.position++] : 0; return new R_r2_u_io(v, t); }
  static A0Io write(A0Io t, int v) { if (t.noutput < ${outCap}) t.output[t.noutput++] = v; return t; }
  static A0Io puts(A0Io t, int[] a) { write(t, a.length); for (int v : a) write(t, v); return t; }`;

/** Nested record declarations and copy-on-write helpers for one aggregate type. */
function javaTypeDecl(t: Type): string {
  if (isPrimitive(t)) return '';
  const m = mangleType(t);
  if (t.kind === 'arr') {
    const jt = javaType(t);
    const e = javaType(t.elem);
    return `  static ${jt} set_${m}(${jt} a, int i, ${e} v) { ${jt} c = a.clone(); c[Integer.remainderUnsigned(i, ${t.length})] = v; return c; }`;
  }
  const name = javaType(t);
  const comps = t.fields.map((f, i) => `${javaType(f)} f${i}`).join(', ');
  const puts = t.fields.map((f, i) => {
    const args = t.fields.map((_, k) => (k === i ? 'v' : `r.f${k}()`)).join(', ');
    return `  static ${name} put_${m}_${i}(${name} r, ${javaType(f)} v) { return new ${name}(${args}); }`;
  });
  return [`  record ${name}(${comps}) {}`, ...puts].join('\n');
}

/** Java aggregate literal (arrays need the full nested element type in `new`). */
function javaNew(t: Type, args: readonly string[]): string {
  if (isPrimitive(t)) throw new A0Error('javaNew on primitive');
  if (t.kind === 'arr') return `new ${javaType(t)}{${args.join(', ')}}`;
  return `new ${javaType(t)}(${args.join(', ')})`;
}

function javaOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return hex(o.value);
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

function javaExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(javaOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `${a} + ${b}`;
    case 'sub':
      return `${a} - ${b}`;
    case 'mul':
      return `${a} * ${b}`;
    case 'and':
      return `${a} & ${b}`;
    case 'or':
      return `${a} | ${b}`;
    case 'xor':
      return `${a} ^ ${b}`;
    case 'shl':
      return `${a} << (${b} & 31)`;
    case 'shr':
      return `${a} >>> (${b} & 31)`;
    case 'div':
      return `(${b} == 0 ? 0xffffffff : Integer.divideUnsigned(${a}, ${b}))`;
    case 'rem':
      return `(${b} == 0 ? ${a} : Integer.remainderUnsigned(${a}, ${b}))`;
    case 'eq':
      return `${a} == ${b}`;
    case 'lt':
      return `Integer.compareUnsigned(${a}, ${b}) < 0`;
    case 'le':
      return `Integer.compareUnsigned(${a}, ${b}) <= 0`;
    case 'gt':
      return `Integer.compareUnsigned(${a}, ${b}) > 0`;
    case 'ge':
      return `Integer.compareUnsigned(${a}, ${b}) >= 0`;
    case 'ne':
      return `${a} != ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'call':
      return `${node.callee ?? ''}(${node.args.map(javaOperand).join(', ')})`;
    case 'arr': {
      // An all-zero scalar array is a plain allocation (Java zero-initializes); a literal of
      // 65536 elements would otherwise exceed the 64 KiB method bytecode limit.
      const t = fn.types.get(node.id) ?? 'u32';
      const zeros =
        !isPrimitive(t) &&
        t.kind === 'arr' &&
        isPrimitive(t.elem) &&
        node.args.every(
          (o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value),
        );
      if (zeros) return `new ${javaType(t)}`.replace('[]', `[${node.args.length}]`);
      return javaNew(t, node.args.map(javaOperand));
    }
    case 'rec':
      return javaNew(fn.types.get(node.id) ?? 'u32', node.args.map(javaOperand));
    case 'get':
      return `${a}[Integer.remainderUnsigned(${b}, ${arrayLength(fn, node.args[0])})]`;
    case 'set':
      return `set_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}(${a}, ${b}, ${c})`;
    case 'at':
      return `${a}.f${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}()`;
    case 'put':
      return `put_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}_${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}(${a}, ${c})`;
    case 'read':
      return `read(${a})`;
    case 'write':
      return `write(${a}, ${b})`;
    case 'puts':
      return `puts(${a}, ${b})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

const emitJavaFunction: Emitter = (fn) => {
  const params = fn.params.map((t, i) => `${javaType(t)} p${i}`).join(', ');
  const body = fn.nodes.map((n) => {
    const t = javaType(fn.types.get(n.id) ?? 'u32');
    if (n.op !== 'fold' && n.op !== 'loop') return `    final ${t} n_${n.id} = ${javaExpr(n, fn)};`;
    const [count, init, ...extra] = n.args.map(javaOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!${n.pred ?? ''}(${call})) break;` : '';
    return `    ${t} n_${n.id} = ${init};\n    for (int i = 0; Integer.compareUnsigned(i, ${count}) < 0; i++) {${guard} n_${n.id} = ${n.callee ?? ''}(${call}); }`;
  });
  return [
    `  public static ${javaType(fn.result)} ${fn.name}(${params}) {`,
    ...body,
    `    return ${javaOperand(fn.ret)};`,
    '  }',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// SystemVerilog (combinational; emitted only, see results for validation status)
// ---------------------------------------------------------------------------

export const svType = (t: Type): string =>
  t === 'bool' ? 'logic' : `logic [${bitWidth(t) - 1}:0]`;

/** Bit offset of field k inside a record (field 0 at the LSB). */
export function svFieldOffset(t: Type, k: number): number {
  if (isPrimitive(t) || t.kind !== 'rec') throw new A0Error('field offset on non-record');
  return t.fields.slice(0, k).reduce((n, f) => n + bitWidth(f), 0);
}

export function svOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return `32'd${o.value}`;
    case 'bool':
      return o.value ? "1'b1" : "1'b0";
  }
}

/** Low five bits of the shift distance; a bit-select is illegal on a literal, so mask constants here. */
function svShiftAmount(o: Operand | undefined): string {
  if (o === undefined) throw new A0Error('shift without distance');
  if (o.kind === 'u32') return `5'd${o.value & 31}`;
  return `${svOperand(o)}[4:0]`;
}

export function svExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(svOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `32'(${a} + ${b})`;
    case 'sub':
      return `32'(${a} - ${b})`;
    case 'mul':
      return `32'(${a} * ${b})`;
    case 'and':
      return `${a} & ${b}`;
    case 'or':
      return `${a} | ${b}`;
    case 'xor':
      return `${a} ^ ${b}`;
    case 'shl':
      return `32'(${a} << ${svShiftAmount(node.args[1])})`;
    case 'shr':
      return `${a} >> ${svShiftAmount(node.args[1])}`;
    case 'div':
      return `(${b} == 32'd0) ? 32'hffffffff : ${a} / ${b}`;
    case 'rem':
      return `(${b} == 32'd0) ? ${a} : ${a} % ${b}`;
    case 'eq':
      return `${a} == ${b}`;
    case 'lt':
      return `${a} < ${b}`;
    case 'le':
      return `${a} <= ${b}`;
    case 'gt':
      return `${a} > ${b}`;
    case 'ge':
      return `${a} >= ${b}`;
    case 'ne':
      return `${a} != ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'arr':
    case 'rec':
      // Element/field 0 occupies the least significant bits.
      return `{${[...node.args].reverse().map(svOperand).join(', ')}}`;
    case 'get': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      if (isPrimitive(t) || t.kind !== 'arr') throw new A0Error('get on non-array');
      const w = bitWidth(t.elem);
      const idx = node.args[1];
      const base =
        idx?.kind === 'u32' ? `${(idx.value % t.length) * w}` : `((${b} % ${t.length}) * ${w})`;
      return `${a}[${base} +: ${w}]`;
    }
    case 'at': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      const k = node.args[1]?.kind === 'u32' ? node.args[1].value : 0;
      if (isPrimitive(t) || t.kind !== 'rec') throw new A0Error('at on non-record');
      return `${a}[${svFieldOffset(t, k)} +: ${bitWidth(t.fields[k] as Type)}]`;
    }
    case 'set':
    case 'put':
      throw new A0Error(`${node.op} is emitted as an always_comb block`);
    case 'read':
    case 'write':
    case 'puts':
      throw new A0Error(
        `${node.op}: io effects need sequential state, which the combinational SystemVerilog backend does not implement`,
      );
    case 'call':
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as module instances in SystemVerilog`);
  }
}

/** Largest literal fold trip count the combinational SystemVerilog backend will unroll. */
export const SV_MAX_UNROLL = 256;

const emitSvFunction: Emitter = (fn) => {
  assertVectorSized(fn, 'SystemVerilog');
  if (needsSequential(fn)) return emitSequential(fn);
  const ports = [
    ...fn.params.map((t, i) => `  input ${svType(t)} p${i}`),
    `  output ${svType(fn.result)} result`,
  ].join(',\n');
  const decls = fn.nodes.map((n) => `  ${svType(fn.types.get(n.id) ?? 'u32')} n_${n.id};`);
  const assigns = fn.nodes.map((n) => {
    if (n.op === 'fold' || n.op === 'loop') {
      // Combinational backend: only a literal trip count can be unrolled into a chain of instances.
      const [count, init, ...extra] = n.args;
      if (count === undefined || count.kind !== 'u32') {
        throw new A0Error(
          `${fn.name}.${n.id}: ${n.op} with a non-literal trip count needs sequential state, which the combinational SystemVerilog backend does not implement`,
        );
      }
      if (count.value > SV_MAX_UNROLL) {
        throw new A0Error(
          `${fn.name}.${n.id}: ${n.op} trip count ${count.value} exceeds the SystemVerilog unroll limit ${SV_MAX_UNROLL}`,
        );
      }
      const width = svType(fn.types.get(n.id) ?? 'u32');
      const lines: string[] = [];
      let prev = init === undefined ? "32'd0" : svOperand(init);
      // For loop: done_i latches once the predicate is false; later stages pass the state through.
      let done = "1'b0";
      for (let i = 0; i < count.value; i += 1) {
        const wire = `n_${n.id}_s${i + 1}`;
        const ports = (result: string) => [
          `.p0(${prev})`,
          `.p1(32'd${i})`,
          ...extra.map((arg, k) => `.p${k + 2}(${svOperand(arg)})`),
          `.result(${result})`,
        ];
        if (n.op === 'loop') {
          const cont = `n_${n.id}_c${i}`;
          const next = `n_${n.id}_d${i + 1}`;
          const body = `n_${n.id}_b${i + 1}`;
          lines.push(
            `  logic ${cont};`,
            `  logic ${next};`,
            `  ${width} ${body};`,
            `  ${width} ${wire};`,
          );
          lines.push(`  a0_${n.pred ?? ''} u_${n.id}_p${i} (${ports(cont).join(', ')});`);
          lines.push(`  a0_${n.callee ?? ''} u_${n.id}_${i} (${ports(body).join(', ')});`);
          lines.push(`  assign ${next} = ${done} | ~${cont};`);
          lines.push(`  assign ${wire} = ${next} ? ${prev} : ${body};`);
          done = next;
        } else {
          lines.push(`  ${width} ${wire};`);
          lines.push(`  a0_${n.callee ?? ''} u_${n.id}_${i} (${ports(wire).join(', ')});`);
        }
        prev = wire;
      }
      lines.push(`  assign n_${n.id} = ${prev};`);
      return lines.join('\n');
    }
    if (n.op === 'set' || n.op === 'put') {
      const [a, b, c] = n.args.map(svOperand);
      const t = operandTypeOf(fn, n.args[0] as Operand);
      if (isPrimitive(t)) throw new A0Error(`${n.op} on primitive`);
      let slice: string;
      if (n.op === 'set') {
        if (t.kind !== 'arr') throw new A0Error('set on non-array');
        const w = bitWidth(t.elem);
        const idx = n.args[1];
        const base =
          idx?.kind === 'u32' ? `${(idx.value % t.length) * w}` : `((${b} % ${t.length}) * ${w})`;
        slice = `[${base} +: ${w}]`;
      } else {
        if (t.kind !== 'rec') throw new A0Error('put on non-record');
        const k = n.args[1]?.kind === 'u32' ? n.args[1].value : 0;
        slice = `[${svFieldOffset(t, k)} +: ${bitWidth(t.fields[k] as Type)}]`;
      }
      return `  always_comb begin n_${n.id} = ${a}; n_${n.id}${slice} = ${c}; end`;
    }
    if (n.op !== 'call') return `  assign n_${n.id} = ${svExpr(n, fn)};`;
    // A call is a combinational instance of the callee module, connected by port name.
    const conns = [...n.args.map((arg, i) => `.p${i}(${svOperand(arg)})`), `.result(n_${n.id})`];
    return `  a0_${n.callee ?? ''} u_${n.id} (${conns.join(', ')});`;
  });
  return [
    `module a0_${fn.name} (`,
    ports,
    ');',
    ...decls,
    ...assigns,
    `  assign result = ${svOperand(fn.ret)};`,
    'endmodule',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// Module assembly and emission cache
// ---------------------------------------------------------------------------

const EMITTERS: Readonly<Record<Target, Emitter>> = {
  js: emitJsFunction,
  c: emitCFunction,
  java: emitJavaFunction,
  sv: emitSvFunction,
  arm64: emitArm64Function,
  x86_64: emitX86_64Function,
  riscv64: emitRiscv64Function,
  avr: emitAvrFunction,
  wasm: emitWasmFunction,
  arm32: emitArm32Function,
};

/** True when any function of the program carries an io token anywhere in its types. */
export function usesIo(program: TypedProgram): boolean {
  return program.functions.some(
    (fn) =>
      containsIo(fn.result) ||
      fn.params.some(containsIo) ||
      [...fn.types.values()].some(containsIo),
  );
}

export function assemble(
  target: Target,
  bodies: readonly string[],
  program: TypedProgram,
  options: CompileOptions = {},
): string {
  const types = aggregateTypes(program);
  const io = usesIo(program);
  if (io && !types.some((t) => formatType(t) === '(u32,io)')) {
    types.unshift({ kind: 'rec', fields: ['u32', 'io'] });
  }
  switch (target) {
    case 'arm64':
      return assembleArm64(bodies, COMPILER_VERSION);
    case 'x86_64':
      return assembleX86_64(bodies, COMPILER_VERSION);
    case 'riscv64':
      return assembleRiscv64(bodies, COMPILER_VERSION);
    case 'avr':
      return assembleAvr(bodies, COMPILER_VERSION);
    case 'wasm':
      return Buffer.from(
        assembleWasm(
          bodies,
          program,
          {
            ioInputCapacity: options.ioInputCapacity ?? C_IO_INPUT_CAPACITY,
            ioOutputCapacity: options.ioOutputCapacity ?? C_IO_OUTPUT_CAPACITY,
          },
          COMPILER_VERSION,
        ),
      ).toString('base64');
    case 'arm32':
      return assembleArm32(bodies, COMPILER_VERSION);
    case 'js':
      return `${JS_PRELUDE}\n${bodies.join('\n\n')}\n`;
    case 'c': {
      const decls = types.map(cTypeDecl).filter((d) => d.length > 0);
      if (io)
        decls.push(
          cIoRuntime(
            options.ioInputCapacity ?? C_IO_INPUT_CAPACITY,
            options.ioOutputCapacity ?? C_IO_OUTPUT_CAPACITY,
          ),
        );
      return `${C_PRELUDE}\n${decls.length > 0 ? `${decls.join('\n')}\n\n` : ''}${bodies.join('\n\n')}\n`;
    }
    case 'java': {
      const decls = types.map(javaTypeDecl).filter((d) => d.length > 0);
      if (io)
        decls.push(
          javaIoRuntime(
            options.ioInputCapacity ?? C_IO_INPUT_CAPACITY,
            options.ioOutputCapacity ?? C_IO_OUTPUT_CAPACITY,
          ),
        );
      return `// Generated by A0 ${COMPILER_VERSION}. int carries the u32 bit pattern.\npublic final class ${JAVA_CLASS} {\n  private ${JAVA_CLASS}() {}\n\n${decls.length > 0 ? `${decls.join('\n')}\n\n` : ''}${bodies.join('\n\n')}\n}\n`;
    }
    case 'sv':
      return `// Generated by A0 ${COMPILER_VERSION}. Pure functions combinational; io, iteration, and division clocked. Two-state semantics intended.\n\`timescale 1ns/1ps\n${bodies.some((b) => b.includes('a0_udiv ')) ? `${SV_UDIV_MODULE}\n\n` : ''}${bodies.join('\n\n')}\n`;
  }
}

export interface CompileOptions {
  readonly optimize?: boolean;
  /** C/wasm/Java/C# io capacities in words (defaults C_IO_INPUT_CAPACITY / C_IO_OUTPUT_CAPACITY); prelude only, bodies are unaffected. */
  readonly ioInputCapacity?: number;
  readonly ioOutputCapacity?: number;
}

export interface CompileResult {
  readonly text: string;
  readonly cacheHits: number;
  readonly cacheMisses: number;
}

/**
 * Bounded LRU cache of per-function emitted text. Keys include the compiler
 * version, target, optimization flag, and function content revision. This is not
 * a persistent artifact cache: the program is still validated and hashed, and the
 * module is still assembled on every call.
 */
export class FunctionCache {
  readonly #entries = new Map<string, string>();
  readonly #capacity: number;

  constructor(capacity = 1024) {
    if (!Number.isInteger(capacity) || capacity < 1)
      throw new A0Error('cache capacity must be >= 1');
    this.#capacity = capacity;
  }

  get size(): number {
    return this.#entries.size;
  }

  /** Key: compiler version, target, optimization level, and semantic revision (own content + all transitive callees). */
  static key(target: Target, optimized: boolean, fn: TypedFunc): string {
    return `${COMPILER_VERSION}|${target}|${optimized ? 'O1' : 'O0'}|${semanticRevision(fn)}`;
  }

  get(key: string): string | undefined {
    const value = this.#entries.get(key);
    if (value !== undefined) {
      this.#entries.delete(key);
      this.#entries.set(key, value);
    }
    return value;
  }

  set(key: string, value: string): void {
    this.#entries.delete(key);
    this.#entries.set(key, value);
    if (this.#entries.size > this.#capacity) {
      const oldest = this.#entries.keys().next().value;
      if (oldest !== undefined) this.#entries.delete(oldest);
    }
  }
}

export function emitFunction(target: Target, fn: TypedFunc, options: CompileOptions = {}): string {
  const source = options.optimize === false ? fn : optimizeFunction(fn).fn;
  // Hardware form is decided on the source function so callers and testbenches agree even
  // when optimization removes every iteration or effect.
  if (target === 'sv' && needsSequential(fn)) {
    assertVectorSized(fn, 'SystemVerilog');
    return emitSequential(source);
  }
  return EMITTERS[target](source);
}

export function compile(
  program: TypedProgram,
  target: Target,
  options: CompileOptions = {},
  cache?: FunctionCache,
): CompileResult {
  const optimized = options.optimize !== false;
  let cacheHits = 0;
  let cacheMisses = 0;
  const bodies = program.functions.map((fn) => {
    if (cache === undefined) return emitFunction(target, fn, options);
    const key = FunctionCache.key(target, optimized, fn);
    const hit = cache.get(key);
    if (hit !== undefined) {
      cacheHits += 1;
      return hit;
    }
    cacheMisses += 1;
    const text = emitFunction(target, fn, options);
    cache.set(key, text);
    return text;
  });
  return { text: assemble(target, bodies, program, options), cacheHits, cacheMisses };
}
