/**
 * Source emission for JavaScript (ES module), C (C-compatible, also valid C++), Java,
 * SystemVerilog, direct Darwin AArch64 assembly (src/arm64.ts), and direct x86-64 assembly
 * (src/x86_64.ts, System V, macOS and Linux), direct RISC-V RV64 assembly (src/riscv64.ts,
 * LP64, Linux), direct AVR assembly for the ATmega328P (src/avr.ts, avr-gcc calling
 * convention), direct 32-bit ARM assembly (src/arm32.ts, ARMv7-A), a direct wasm32 binary
 * module (src/wasm.ts; the compiled text is the module's base64, see `wasmModuleBytes`),
 * plus a bounded in-memory function-emission cache.
 *
 * Every backend preserves the exact v0.1 semantics: wrapping u32 arithmetic,
 * logical right shift, shift distance masked to five bits, unsigned comparison,
 * and non-numeric booleans. Identifiers are validated by the core and emitted with
 * a prefix so source names cannot collide with target keywords or runtime symbols.
 */

import { assembleArm32, emitArm32Function } from './arm32.js';
import { assembleArm64, emitArm64Function } from './arm64.js';
import { assembleAvr, emitAvrFunction } from './avr.js';
import {
  A0Error,
  assertVectorSized,
  bitWidth,
  borrowLive,
  containsIo,
  formatType,
  isPrimitive,
  type Node,
  type Op,
  type Operand,
  TRAP_FIX,
  type Type,
  type TypedFunc,
  type TypedProgram,
} from './core.js';
import { semanticRevision } from './edit.js';
import { emitSequential, needsSequential, SV_UDIV_MODULE } from './hw.js';
import { optimizeFunction } from './optimize.js';
import { assembleRiscv64, emitRiscv64Function } from './riscv64.js';
import { assembleWasm, emitWasmFunction } from './wasm.js';
import { assembleX86_64, emitX86_64Function } from './x86_64.js';

export const COMPILER_VERSION = 'a0c-0.1.36';

export type Target =
  | 'js'
  | 'c'
  | 'java'
  | 'sv'
  | 'arm64'
  | 'x86_64'
  | 'riscv64'
  | 'avr'
  | 'wasm'
  | 'arm32';
export const TARGETS: readonly Target[] = [
  'js',
  'c',
  'java',
  'sv',
  'arm64',
  'x86_64',
  'riscv64',
  'avr',
  'wasm',
  'arm32',
];

export function isTarget(text: string): text is Target {
  return (TARGETS as readonly string[]).includes(text);
}

const hex = (v: number): string => `0x${v.toString(16).padStart(8, '0')}`;

type Emitter = (fn: TypedFunc) => string;

/** Type of an operand inside a function (params, nodes, literals). */
export function operandTypeOf(fn: TypedFunc, o: Operand): Type {
  switch (o.kind) {
    case 'u32':
      return 'u32';
    case 'bool':
      return 'bool';
    case 'param':
      return fn.params[o.index] ?? 'u32';
    case 'node':
      return fn.types.get(o.id) ?? 'u32';
  }
}

/** `index mod N` for a u32 index: a literal folds, a power-of-two N masks, else `%`. */
function jsIndex(fn: TypedFunc, arr: Operand | undefined, idx: Operand | undefined): string {
  const n = arrayLength(fn, arr);
  if (idx?.kind === 'u32') return String(idx.value % n);
  const i = jsOperand(idx as Operand);
  return (n & (n - 1)) === 0 ? `(${i} & ${n - 1})` : `${i} % ${n}`;
}

function arrayLength(fn: TypedFunc, o: Operand | undefined): number {
  if (o === undefined) throw new A0Error('missing array operand');
  const t = operandTypeOf(fn, o);
  if (isPrimitive(t) || t.kind !== 'arr') throw new A0Error('expected array operand');
  return t.length;
}

/** Injective, identifier-safe name for a type: u, b, a<N>_<elem>, r<N>_<f>..._<f>. */
export function mangleType(t: Type): string {
  if (t === 'u32') return 'u';
  if (t === 'bool') return 'b';
  if (t === 'io') return 'io';
  if (t.kind === 'arr') return `a${t.length}_${mangleType(t.elem)}`;
  return `r${t.fields.length}_${t.fields.map(mangleType).join('_')}`;
}

/** All aggregate types used by a program, nested types first, deduplicated. */
export function aggregateTypes(program: TypedProgram): Type[] {
  const seen = new Set<string>();
  const out: Type[] = [];
  const visit = (t: Type): void => {
    if (isPrimitive(t)) return;
    if (t.kind === 'arr') visit(t.elem);
    else t.fields.forEach(visit);
    const key = formatType(t);
    if (!seen.has(key)) {
      seen.add(key);
      out.push(t);
    }
  };
  for (const fn of program.functions) {
    fn.params.forEach(visit);
    visit(fn.result);
    for (const t of fn.types.values()) visit(t);
  }
  return out;
}

/** JSON shape used by the JS runtime guard. */
function jsShape(t: Type): string {
  if (isPrimitive(t)) return JSON.stringify(t);
  if (t.kind === 'arr') return `["arr",${t.length},${jsShape(t.elem)}]`;
  return `["rec",[${t.fields.map(jsShape).join(',')}]]`;
}

// ---------------------------------------------------------------------------
// JavaScript
// ---------------------------------------------------------------------------

const JS_PRELUDE = `// Generated by A0 ${COMPILER_VERSION}. Exact u32/bool semantics.
const U32_MAX = 0xffffffff;
function a0_u32(v, name) {
  if (typeof v !== 'number' || !Number.isInteger(v) || v < 0 || v > U32_MAX) throw new RangeError(name + ': expected u32');
  return v;
}
function a0_bad(name, shape) { throw new (shape === 'u32' ? RangeError : TypeError)(name + ': expected ' + shape); }
function a0_bool(v, name) {
  if (typeof v !== 'boolean') throw new TypeError(name + ': expected bool');
  return v;
}
function a0_check(v, shape, name) {
  if (shape === 'u32') return a0_u32(v, name);
  if (shape === 'bool') return a0_bool(v, name);
  if (shape === 'io') return a0_io(v, name);
  const typed = v instanceof Uint32Array || v instanceof Uint8Array;
  if (!Array.isArray(v) && !typed) throw new TypeError(name + ': expected ' + shape[0]);
  if (shape[0] === 'arr') {
    if (v.length !== shape[1]) throw new RangeError(name + ': expected ' + shape[1] + ' elements');
    if (shape[2] === 'u32') { if (v instanceof Uint32Array) return v; for (let i = 0; i < v.length; i++) a0_u32(v[i], name + '[' + i + ']'); return Uint32Array.from(v); }
    if (shape[2] === 'bool') { if (v instanceof Uint8Array) return v; for (let i = 0; i < v.length; i++) a0_bool(v[i], name + '[' + i + ']'); return Uint8Array.from(v, (x) => (x ? 1 : 0)); }
    if (typed) throw new TypeError(name + ': expected nested array');
    const c = v.slice();
    for (let i = 0; i < c.length; i++) c[i] = a0_check(c[i], shape[2], name + '[' + i + ']');
    return c;
  } else {
    if (typed) throw new TypeError(name + ': expected record');
    const c = v.slice();
    if (v.length !== shape[1].length) throw new RangeError(name + ': expected ' + shape[1].length + ' fields');
    for (let i = 0; i < c.length; i++) c[i] = a0_check(c[i], shape[1][i], name + '.' + i);
    return c;
  }
}
function a0_with(a, i, v) { const c = a.slice(); c[i] = v; return c; }
// io token: { input: number[], position, output: number[] }. Exhausted input reads 0.
function a0_io(v, name) {
  if (typeof v !== 'object' || v === null || !Array.isArray(v.input) || !Array.isArray(v.output) || typeof v.position !== 'number') throw new TypeError(name + ': expected io token');
  return v;
}
export function a0_make_io(input) { return { input: input.slice(), position: 0, output: [] }; }
function a0_read(t) { const v = t.position < t.input.length ? t.input[t.position++] : 0; return [v, t]; }
function a0_write(t, v) { t.output.push(v); return t; }
function a0_puts(t, a) { t.output.push(a.length); for (let i = 0; i < a.length; i++) t.output.push(a[i]); return t; }
`;

function jsOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return String(o.value);
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

const FRESH_OPS = new Set<Op>(['arr', 'rec', 'set', 'put']);

function sameOp(x: Operand, y: Operand): boolean {
  return (
    (x.kind === 'node' && y.kind === 'node' && x.id === y.id) ||
    (x.kind === 'param' && y.kind === 'param' && x.index === y.index)
  );
}

/**
 * May the aggregate operand `o` be updated in place by the node at `index`?
 * Sound when the value is provably unshared: it is a fresh allocation (arr/rec/set/put result)
 * or a parameter the target owns privately (`ownedParam`: in JS only the p0 state of an
 * iteration body, in C every by-value parameter and the owned loop state); every other use of
 * it is a non-escaping element/field read (`get`/`at` as first operand) that happens before
 * `index`; and it is not returned. `get`/`at` results alias their container and are never mutated.
 */
function mutableHere(
  fn: TypedFunc,
  o: Operand,
  index: number,
  ownedParam: (paramIndex: number) => boolean,
): boolean {
  if (o.kind === 'node') {
    const def = fn.nodes.find((n) => n.id === o.id);
    if (def === undefined || !FRESH_OPS.has(def.op)) return false;
  } else if (!(o.kind === 'param' && ownedParam(o.index))) {
    return false;
  }
  if (sameOp(fn.ret, o)) return false;
  for (const [j, n] of fn.nodes.entries()) {
    if (j === index) continue;
    for (const [k, arg] of n.args.entries()) {
      if (!sameOp(arg, o)) continue;
      if (j > index) return false;
      if (!((n.op === 'get' || n.op === 'at') && k === 0)) return false;
    }
  }
  return true;
}

/**
 * C only: `mutableHere` with two more facts of the C emitter. A `fold`/`loop`/`call` result is
 * storage of this function (a fresh local, or the loop state aliasing an unshared initial value),
 * so it is fresh like `arr`/`set`. And an earlier use that only reads the value is harmless: a
 * callee or a loop body receives aggregates by const pointer and keeps nothing, so a `call`
 * argument or a `fold`/`loop` extra before `index` does not share it. Uses that could mutate or
 * alias it (a `set`/`put` target, a `fold`/`loop` initial state, a `select` operand) still do.
 */
function mutableHereC(
  fn: TypedFunc,
  o: Operand,
  index: number,
  ownedParam: (paramIndex: number) => boolean,
  ownedNodes: ReadonlySet<string> = NO_NODES,
): boolean {
  if (o.kind === 'node') {
    const def = fn.nodes.find((n) => n.id === o.id);
    if (
      def === undefined ||
      !(FRESH_OPS.has(def.op) || C_FRESH_OPS.has(def.op) || ownedNodes.has(o.id))
    )
      return false;
  } else if (!(o.kind === 'param' && ownedParam(o.index))) {
    return false;
  }
  if (sameOp(fn.ret, o)) return false;
  for (const [j, n] of fn.nodes.entries()) {
    if (j === index) continue;
    for (const [k, arg] of n.args.entries()) {
      if (!sameOp(arg, o)) continue;
      if (j > index) return false;
      if ((n.op === 'get' || n.op === 'at') && k === 0) continue;
      if (n.op === 'call') continue;
      if ((n.op === 'fold' || n.op === 'loop') && k >= 2) continue;
      return false;
    }
  }
  return true;
}
const C_FRESH_OPS = new Set<Op>(['fold', 'loop', 'call']);
const NO_NODES: ReadonlySet<string> = new Set();

/**
 * Field projections the C emitter owns (`mutableHereC`'s `ownedNodes`): an aggregate field read
 * by exactly one `at` node, whose container is storage this function owns, is that node's own
 * storage (`T *const n = &container.fk`, not a const borrow), so a `set`/`put` on it updates the
 * field in place instead of copying it (the front end's paged tables are 64-100 KB each and
 * every token copied them). Two shapes, both only when the container is read through `at`
 * nodes with literal fields and is not the result:
 *  - the owned loop state p0 of an iteration body whose last node is a `rec` (the new state):
 *    `cStateStores` then stores only the fields that changed;
 *  - a large local record built by `rec`/`put`/`call`/`fold`/`loop`.
 * Every other read of the old field value precedes the update (`mutableHereC`), and no borrow of
 * the projection is read after it (`borrowLive`), so value semantics hold.
 */
interface Projections {
  /** Projection node id to its container operand and field. */
  readonly of: ReadonlyMap<string, { readonly container: Operand; readonly field: number }>;
}

function cProjections(fn: TypedFunc, variant: CVariant): Projections {
  const of = new Map<string, { container: Operand; field: number }>();
  const last = fn.nodes[fn.nodes.length - 1];
  const stateOk =
    variant === 'owned' &&
    last !== undefined &&
    last.op === 'rec' &&
    fn.ret.kind === 'node' &&
    fn.ret.id === last.id;
  const containers: Operand[] = [];
  if (stateOk) containers.push({ kind: 'param', index: 0 });
  for (const r of fn.nodes) {
    const t = fn.types.get(r.id) ?? 'u32';
    if (
      !isPrimitive(t) &&
      t.kind === 'rec' &&
      isLargeC(t) &&
      ['rec', 'put', 'call', 'fold', 'loop'].includes(r.op) &&
      !(fn.ret.kind === 'node' && fn.ret.id === r.id)
    )
      containers.push({ kind: 'node', id: r.id });
  }
  for (const c of containers) {
    const byField = new Map<number, string[]>();
    let only = true;
    for (const n of fn.nodes)
      for (const [k, o] of n.args.entries()) {
        if (!sameOp(o, c)) continue;
        const field = n.args[1];
        if (n.op === 'at' && k === 0 && field?.kind === 'u32')
          byField.set(field.value, [...(byField.get(field.value) ?? []), n.id]);
        else only = false;
      }
    if (!only) continue;
    for (const [field, ids] of byField) {
      const id = ids[0] as string;
      const type = fn.types.get(id) ?? 'u32';
      if (ids.length === 1 && !isPrimitive(type) && !sameOp(fn.ret, { kind: 'node', id }))
        of.set(id, { container: c, field });
    }
  }
  return { of };
}

/** JS ownership: only the p0 state of the owned iteration-body variant is private. */
const jsOwned =
  (ownedP0: boolean) =>
  (i: number): boolean =>
    i === 0 && ownedP0;

/** A node whose result (and therefore whose and/or/xor operands) is bool. */
const isBoolNode = (fn: TypedFunc, node: Node): boolean => fn.types.get(node.id) === 'bool';

function jsExpr(node: Node, fn: TypedFunc, index = -1, ownedP0 = false): string {
  const [a, b, c] = node.args.map(jsOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `(${a} + ${b}) >>> 0`;
    case 'sub':
      return `(${a} - ${b}) >>> 0`;
    case 'mul':
      return `Math.imul(${a}, ${b}) >>> 0`;
    case 'and':
      return isBoolNode(fn, node) ? `(${a} && ${b})` : `(${a} & ${b}) >>> 0`;
    case 'or':
      return isBoolNode(fn, node) ? `(${a} || ${b})` : `(${a} | ${b}) >>> 0`;
    case 'xor':
      return isBoolNode(fn, node) ? `(${a} !== ${b})` : `(${a} ^ ${b}) >>> 0`;
    case 'shl':
      return `(${a} << (${b} & 31)) >>> 0`;
    case 'shr':
      return `${a} >>> (${b} & 31)`;
    case 'div':
      return `(${b} === 0 ? 0xffffffff : Math.floor(${a} / ${b}))`;
    case 'rem':
      return `(${b} === 0 ? ${a} : ${a} % ${b})`;
    case 'eq':
      return `${a} === ${b}`;
    case 'lt':
      return `${a} < ${b}`;
    case 'le':
      return `${a} <= ${b}`;
    case 'gt':
      return `${a} > ${b}`;
    case 'ge':
      return `${a} >= ${b}`;
    case 'ne':
      return `${a} !== ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'call':
      return `a0i_${node.callee ?? ''}(${node.args.map(jsOperand).join(', ')})`;
    case 'arr': {
      // Scalar-element arrays are typed arrays (u32 -> Uint32Array, bool -> Uint8Array of 0/1);
      // nested aggregates stay plain arrays. All array helpers work on both.
      const t = fn.types.get(node.id);
      const elem = t !== undefined && !isPrimitive(t) && t.kind === 'arr' ? t.elem : 'u32';
      // An all-zero literal is a plain allocation (measured: `of(0,...)` costs on small kernels).
      const zeros = node.args.every(
        (o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value),
      );
      if (elem === 'u32')
        return zeros
          ? `new Uint32Array(${node.args.length})`
          : `Uint32Array.of(${node.args.map(jsOperand).join(', ')})`;
      if (elem === 'bool')
        return zeros
          ? `new Uint8Array(${node.args.length})`
          : `Uint8Array.of(${node.args.map((o) => `${jsOperand(o)} ? 1 : 0`).join(', ')})`;
      return `[${node.args.map(jsOperand).join(', ')}]`;
    }
    case 'rec':
      return `[${node.args.map(jsOperand).join(', ')}]`;
    case 'get': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      const elem = !isPrimitive(t) && t.kind === 'arr' ? t.elem : 'u32';
      const read = `${a}[${jsIndex(fn, node.args[0], node.args[1])}]`;
      return elem === 'bool' ? `${read} === 1` : read;
    }
    case 'set': {
      const inPlace =
        index >= 0 && mutableHere(fn, node.args[0] as Operand, index, jsOwned(ownedP0));
      const et = operandTypeOf(fn, node.args[0] as Operand);
      const boolElem = !isPrimitive(et) && et.kind === 'arr' && et.elem === 'bool';
      const value = boolElem ? `(${c} ? 1 : 0)` : c;
      const idx = jsIndex(fn, node.args[0], node.args[1]);
      return inPlace ? `(${a}[${idx}] = ${value}, ${a})` : `a0_with(${a}, ${idx}, ${value})`;
    }
    case 'at':
      return `${a}[${b}]`;
    case 'put': {
      const inPlace =
        index >= 0 && mutableHere(fn, node.args[0] as Operand, index, jsOwned(ownedP0));
      return inPlace ? `(${a}[${b}] = ${c}, ${a})` : `a0_with(${a}, ${b}, ${c})`;
    }
    case 'read':
      return `a0_read(${a})`;
    case 'write':
      return `a0_write(${a}, ${b})`;
    case 'puts':
      return `a0_puts(${a}, ${b})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

/** Emit one JS function body; `owned` marks the p0-owned iteration-body variant. */
function jsBody(fn: TypedFunc, owned: boolean): string[] {
  const stateAggregate = (o: Operand): boolean => !isPrimitive(operandTypeOf(fn, o));
  const body = fn.nodes.map((n, index) => {
    if (n.op !== 'fold' && n.op !== 'loop')
      return `  const n_${n.id} = ${jsExpr(n, fn, index, owned)};`;
    const [count, init, ...extra] = n.args.map(jsOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!a0i_${n.pred ?? ''}(${call})) break;` : '';
    // Aggregate state is owned by the loop so the body may update it in place: copy the initial
    // value once unless it is already provably unshared (fresh and used only here; an initial
    // value passed again as an extra is read by every trip).
    const initOwned =
      mutableHere(fn, n.args[1] as Operand, index, jsOwned(owned)) &&
      !n.args.slice(2).some((o) => sameOp(o, n.args[1] as Operand));
    const initExpr = stateAggregate(n.args[1] as Operand) && !initOwned ? `${init}.slice()` : init;
    const bodyName = stateAggregate(n.args[1] as Operand)
      ? `a0o_${n.callee ?? ''}`
      : `a0i_${n.callee ?? ''}`;
    return `  let n_${n.id} = ${initExpr};\n  for (let i = 0; i < ${count}; i++) {${guard} n_${n.id} = ${bodyName}(${call}); }`;
  });
  // An owned variant must return an owned value: copy unless the result is p0 itself or fresh.
  const ret = fn.ret;
  const fresh =
    (ret.kind === 'param' && ret.index === 0) ||
    (ret.kind === 'node' && FRESH_OPS.has(fn.nodes.find((n) => n.id === ret.id)?.op ?? 'mov'));
  const retExpr =
    owned && !isPrimitive(fn.result) && !fresh ? `${jsOperand(ret)}.slice()` : jsOperand(ret);
  return [...body, `  return ${retExpr};`];
}

const emitJsFunction: Emitter = (fn) => {
  const params = fn.params.map((_, i) => `p${i}`).join(', ');
  // Public entry: validate inputs once, then run the unguarded internal function.
  // Internal calls, folds, and loops target the a0i_/a0o_ variants, so guards are paid only at the boundary.
  // Scalar guards are a single comparison: `(v >>> 0) === v` holds exactly for integers in
  // [0, 2^32) and for no string, boolean, object, NaN, or fraction (measured: the call into
  // a0_u32 cost 1.3-1.4x on three-operation kernels).
  const guards = fn.params.map((t, i) =>
    t === 'u32'
      ? `  if ((p${i} >>> 0) !== p${i}) a0_bad('p${i}', 'u32');`
      : t === 'bool'
        ? `  if (typeof p${i} !== 'boolean') a0_bad('p${i}', 'bool');`
        : `  p${i} = a0_check(p${i}, ${jsShape(t)}, 'p${i}');`,
  );
  const lines = [`function a0i_${fn.name}(${params}) {`, ...jsBody(fn, false), '}'];
  const p0 = fn.params[0];
  if (p0 !== undefined && !isPrimitive(p0) && fn.params[1] === 'u32') {
    // Iteration-body shape (state, index, ...): owned-state variant for fold/loop.
    lines.push(`function a0o_${fn.name}(${params}) {`, ...jsBody(fn, true), '}');
  }
  // Scalar-signature entries carry the body after the guards instead of calling a0i_: one frame
  // fewer at the boundary (aggregate entries keep the call, their guards rebind the parameters).
  const scalar = fn.params.every(isPrimitive);
  lines.push(
    `export function ${fn.name}(${params}) {`,
    ...guards,
    ...(scalar ? jsBody(fn, false) : [`  return a0i_${fn.name}(${params});`]),
    '}',
  );
  return lines.join('\n');
};

// ---------------------------------------------------------------------------
// C (also compiles as C++)
// ---------------------------------------------------------------------------

const C_PRELUDE = `/* Generated by A0 ${COMPILER_VERSION}. Exact u32/bool semantics. */
#include <stdint.h>
#include <stdbool.h>
typedef struct a0_io a0_io;
`;

/** The trap runtime of `CompileOptions.cTrap`; `depth` bounds the call chain (no recursion). */
const cTrapRuntime = (maxTrips: number, depth: number): string => {
  if (!Number.isInteger(maxTrips) || maxTrips < 0 || maxTrips > 0xffff_ffff)
    throw new A0Error('cTrap.maxTrips must be a u32', undefined, { code: 'cli' });
  return `#include <stdio.h>
#include <stdlib.h>
/* Trap runtime: a fold/loop trip cap; the stop prints one code line and exits 3. */
static const char *a0_chain[${depth}u];
static uint32_t a0_depth;
static uint32_t a0_budget = ${maxTrips}u;
static inline void a0_enter(const char *fn) { if (a0_depth < ${depth}u) a0_chain[a0_depth] = fn; a0_depth++; }
static inline void a0_leave(void) { a0_depth--; }
static void a0_trap(const char *fn, const char *node, uint32_t trip) {
  fprintf(stderr, "limit: trap iter fn=%s at=%s.%s trip=%u chain=", fn, fn, node, (unsigned)trip);
  for (uint32_t i = 0; i < a0_depth && i < ${depth}u; i++) fprintf(stderr, "%s%s", i == 0 ? "" : ">", a0_chain[i]);
  fprintf(stderr, " fix: ${TRAP_FIX.iter}\\n");
  exit(3);
}
static inline void a0_trip(const char *fn, const char *node, uint32_t i) { if (a0_budget == 0u) a0_trap(fn, node, i); a0_budget--; }`;
};

/** Fixed-capacity io runtime for C targets (freestanding-safe: no allocation). */
export const C_IO_INPUT_CAPACITY = 256;
export const C_IO_OUTPUT_CAPACITY = 1024;
const cIoRuntime = (inCap: number, outCap: number): string =>
  `struct a0_io { uint32_t input[${inCap}]; uint32_t ninput; uint32_t position; uint32_t output[${outCap}]; uint32_t noutput; };
static inline a0t_r2_u_io a0_read(a0_io *t) { a0t_r2_u_io r; r.f0 = t->position < t->ninput && t->position < ${inCap}u ? t->input[t->position++] : 0u; r.f1 = t; return r; }
static inline a0_io *a0_write(a0_io *t, uint32_t v) { if (t->noutput < ${outCap}u) t->output[t->noutput++] = v; return t; }
static inline a0_io *a0_puts(a0_io *t, const uint32_t *e, uint32_t n) { a0_write(t, n); for (uint32_t i = 0; i < n; i++) a0_write(t, e[i]); return t; }`;

export const cType = (t: Type): string =>
  t === 'u32'
    ? 'uint32_t'
    : t === 'bool'
      ? 'bool'
      : t === 'io'
        ? 'a0_io *'
        : `a0t_${mangleType(t)}`;

/**
 * Large aggregates (C targets): a value whose C struct is over `C_LARGE_BYTES` never lives on the
 * C stack, so modules with big tables run with small stacks (wasm32's 1 MiB, embedded targets).
 *  - ABI: a large parameter is `const T *pK` (a read-only borrow of the caller's value); a large
 *    result is written to caller-owned storage passed first: `void a0_f(T *out, ...)`. The same
 *    holds in the `owned`/`ref`/`view` variants (their p0 pointer is unchanged). A function with
 *    no large parameter or result keeps the by-value ABI.
 *  - Storage: a large local is a pointer into the module's arena, a bump allocator in static
 *    memory (`a0arena`, `A0_ARENA_BYTES`); a function that allocates records the top on entry
 *    and restores it before returning, so a call's locals are released with it. The node that is
 *    the function's result is built in `out` directly; `mov`/`select` alias their operand.
 *  - Bound: the call graph is acyclic, so the need is static: a function's large nodes plus the
 *    largest need of its callees (`cArenaBytes`). The arena is exactly the largest need of any
 *    function, so no run can overflow it; a need over `C_ARENA_LIMIT` is an A0 `limit` error at
 *    compile time. The arena is thread-local (`_Thread_local`, C++ `thread_local`), so host
 *    threads may call exported functions concurrently; automatic parallel folds keep the
 *    sequential loop when the body touches a large value.
 *  - Values: a borrowed parameter is not owned, so its first `set`/`put` copies (the copy the
 *    by-value ABI made at the call); fresh locals and the owned loop state update in place under
 *    the same `mutableHere` rule as small values.
 */
export const C_LARGE_BYTES = 4096;
export const C_ARENA_LIMIT = 1 << 28;

/** C size and alignment of a type (pointers counted as 8 bytes: an upper bound on 32-bit). */
function cLayout(t: Type): { readonly size: number; readonly align: number } {
  if (t === 'u32') return { size: 4, align: 4 };
  if (t === 'bool') return { size: 1, align: 1 };
  if (t === 'io') return { size: 8, align: 8 };
  if (t.kind === 'arr') {
    const e = cLayout(t.elem);
    return { size: e.size * t.length, align: e.align };
  }
  let size = 0;
  let align = 1;
  for (const f of t.fields) {
    const l = cLayout(f);
    size = Math.ceil(size / l.align) * l.align + l.size;
    align = Math.max(align, l.align);
  }
  return { size: Math.ceil(size / align) * align, align };
}

export const isLargeC = (t: Type): boolean => !isPrimitive(t) && cLayout(t).size > C_LARGE_BYTES;

/** Arena bytes one allocation of `t` takes (8-byte aligned). */
const arenaSlot = (t: Type): number => Math.ceil(cLayout(t).size / 8) * 8;

/**
 * Upper bound of the arena bytes a call of `fn` (any variant) holds at once: every large node
 * (the emitted function allocates a subset of them; the optimizer only removes nodes) plus the
 * largest bound among its callees.
 */
export function cArenaBytes(fn: TypedFunc, memo = new Map<string, number>()): number {
  const known = memo.get(fn.name);
  if (known !== undefined) return known;
  let local = 0;
  let callees = 0;
  for (const n of fn.nodes) {
    const t = fn.types.get(n.id);
    if (t !== undefined && isLargeC(t)) local += arenaSlot(t);
    for (const name of [n.callee, n.pred]) {
      const g = name === undefined ? undefined : fn.calls.get(name);
      if (g !== undefined) callees = Math.max(callees, cArenaBytes(g, memo));
    }
  }
  memo.set(fn.name, local + callees);
  return local + callees;
}

/** Does `fn` or any function it calls have a large parameter, result, or node? */
function touchesLarge(fn: TypedFunc): boolean {
  if ([...fn.params, fn.result, ...fn.types.values()].some(isLargeC)) return true;
  return [...fn.calls.values()].some(touchesLarge);
}

/** The module's arena, sized to the largest need of any function; absent when none needs one. */
function cArenaRuntime(program: TypedProgram): string | undefined {
  const memo = new Map<string, number>();
  let bytes = 0;
  let worst = '';
  for (const fn of program.functions) {
    const need = cArenaBytes(fn, memo);
    if (need > bytes) [bytes, worst] = [need, fn.name];
  }
  if (bytes === 0) return undefined;
  if (bytes > C_ARENA_LIMIT)
    throw new A0Error(
      `${worst}: large aggregates need ${bytes} arena bytes, over the C limit ${C_ARENA_LIMIT}`,
      undefined,
      {
        code: 'limit',
        fix: 'hold fewer large values live at once (smaller tables, or pages passed separately)',
      },
    );
  return [
    `/* Arena for aggregates over ${C_LARGE_BYTES} bytes: static, sized to the deepest call chain. */`,
    `#define A0_ARENA_BYTES ${bytes}u`,
    // One arena per thread: exported functions stay reentrant across host threads (a shared
    // top would let concurrent calls overlap and push allocations past the static bound).
    '#ifdef __cplusplus',
    '#define A0_ARENA_LOCAL thread_local',
    '#else',
    '#define A0_ARENA_LOCAL _Thread_local',
    '#endif',
    'static A0_ARENA_LOCAL uint64_t a0arena[A0_ARENA_BYTES / 8u];',
    'static A0_ARENA_LOCAL uint32_t a0arena_top;',
    'static inline void *a0arena_alloc(uint32_t n) { void *p = (unsigned char *)a0arena + a0arena_top; a0arena_top += (n + 7u) & ~7u; return p; }',
  ].join('\n');
}

/**
 * Typedefs plus constructor/update helpers for one aggregate type (C, also valid C++). A large
 * type gets its typedef and a pointer zero-fill only: its values are built and updated in place.
 */
function cTypeDecl(t: Type): string {
  if (isPrimitive(t)) return '';
  const name = cType(t);
  const m = mangleType(t);
  if (isLargeC(t)) {
    const decl =
      t.kind === 'arr'
        ? `typedef struct { ${cType(t.elem)} e[${t.length}]; } ${name};`
        : `typedef struct { ${t.fields.map((f, i) => `${cType(f)} f${i};`).join(' ')} } ${name};`;
    return t.kind === 'arr' && isPrimitive(t.elem)
      ? `${decl}\nstatic inline void a0zero_${m}(${name} *r) { for (uint32_t i = 0; i < ${t.length}u; i++) r->e[i] = 0; }`
      : decl;
  }
  if (t.kind === 'arr') {
    const e = cType(t.elem);
    const params = Array.from({ length: t.length }, (_, i) => `${e} e${i}`).join(', ');
    const inits = Array.from({ length: t.length }, (_, i) => `r.e[${i}] = e${i};`).join(' ');
    return [
      `typedef struct { ${e} e[${t.length}]; } ${name};`,
      // An all-zero literal of a scalar array is a zero initializer (`{0}` is warning-free in C
      // and C++ only for a flat struct); every other literal uses the element-wise constructor.
      ...(isPrimitive(t.elem)
        ? [`static inline ${name} a0zero_${m}(void) { ${name} r = {0}; return r; }`]
        : []),
      `static inline ${name} a0mk_${m}(${params}) { ${name} r; ${inits} return r; }`,
      `static inline ${name} a0set_${m}(${name} a, uint32_t i, ${e} v) { a.e[i % ${t.length}u] = v; return a; }`,
    ].join('\n');
  }
  const fields = t.fields.map((f, i) => `${cType(f)} f${i};`).join(' ');
  const params = t.fields.map((f, i) => `${cType(f)} f${i}`).join(', ');
  const inits = t.fields.map((_, i) => `r.f${i} = f${i};`).join(' ');
  const puts = t.fields.map(
    (f, i) =>
      `static inline ${name} a0put_${m}_${i}(${name} r, ${cType(f)} v) { r.f${i} = v; return r; }`,
  );
  return [
    `typedef struct { ${fields} } ${name};`,
    `static inline ${name} a0mk_${m}(${params}) { ${name} r; ${inits} return r; }`,
    ...puts,
  ].join('\n');
}

/**
 * C function variants. `value` is the public ABI (aggregates by value, result by value).
 * Iteration bodies (`p0` aggregate state, `p1` u32 index, result of the state type) also get an
 * `owned` variant `void a0o_f(T *p0, ...)` that updates the loop state through the pointer;
 * predicates of that shape returning bool get a `ref` variant `bool a0r_f(const T *p0, ...)`.
 * Every by-value aggregate parameter and the owned state are private to the callee, so a
 * `set`/`put` whose old value is provably dead (`mutableHere`) writes in place; the node is then
 * an alias of the updated storage (no local of its own) instead of a copy. Value semantics are
 * unchanged: any value that is still observable is copied as before.
 * Scalar-state bodies that read aggregate extras (`(u32, u32, T...) -> u32` with some T an
 * array or record, e.g. a dot product over two arrays) get a `view` variant
 * `a0v_f(p0, p1, const T *p2, ...)`: the extras are read through const pointers instead of being
 * copied into every trip (no aliasing exists, so reading the caller's value is the same value).
 */
type CVariant = 'value' | 'owned' | 'ref' | 'view';

const isIterationShape = (fn: TypedFunc): boolean =>
  fn.params[0] !== undefined && !isPrimitive(fn.params[0]) && fn.params[1] === 'u32';

const hasOwnedVariant = (fn: TypedFunc): boolean =>
  isIterationShape(fn) && formatType(fn.result) === formatType(fn.params[0] as Type);

const hasRefVariant = (fn: TypedFunc): boolean => isIterationShape(fn) && fn.result === 'bool';

/** Scalar state and result, u32 index, and at least one aggregate extra (read by pointer). */
export const hasViewVariant = (fn: TypedFunc): boolean =>
  fn.params[0] !== undefined &&
  isPrimitive(fn.params[0]) &&
  fn.params[0] !== 'io' &&
  fn.params[1] === 'u32' &&
  isPrimitive(fn.result) &&
  fn.params.slice(2).some((t) => !isPrimitive(t));

const isViewParam = (fn: TypedFunc, variant: CVariant, i: number): boolean =>
  variant === 'view' && i >= 2 && !isPrimitive(fn.params[i] as Type);

interface CContext {
  readonly fn: TypedFunc;
  readonly variant: CVariant;
  /** Nodes updated in place, mapped to the storage they alias (a value node or a parameter). */
  readonly aliases: Map<string, Operand>;
  /** Aggregate `get`/`at` nodes held as `const T *` into their container (borrowed reads). */
  readonly borrows: Set<string>;
  /** Owned field projections (`cProjections`): non-const pointers into their container. */
  readonly projections: Projections;
  /** The large node built directly in the caller's `out` storage (the result's root). */
  readonly retOut?: string | undefined;
  /** Arena allocations emitted so far (the body then saves and restores the arena top). */
  arena: number;
}

function cOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return `${o.value}u`;
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

/** The storage an operand denotes: an alias node resolves to the value it updated in place. */
function cRoot(ctx: CContext, o: Operand): Operand {
  return o.kind === 'node' ? (ctx.aliases.get(o.id) ?? o) : o;
}

/** Value (lvalue) expression of an operand; p0 is a pointer outside the value variant. */
function cVal(ctx: CContext, o: Operand): string {
  const root = cRoot(ctx, o);
  if (
    root.kind === 'param' &&
    root.index === 0 &&
    ctx.variant !== 'value' &&
    ctx.variant !== 'view'
  )
    return '(*p0)';
  if (root.kind === 'param' && isViewParam(ctx.fn, ctx.variant, root.index))
    return `(*p${root.index})`;
  // Large values and borrowed reads are pointers: to a borrowed parameter, arena storage,
  // `out`, or a part of another value.
  if (root.kind === 'node' && ctx.borrows.has(root.id)) return `(*${cOperand(root)})`;
  if ((root.kind === 'param' || root.kind === 'node') && isLargeC(operandTypeOf(ctx.fn, root)))
    return `(*${cOperand(root)})`;
  return cOperand(root);
}

/** An argument as passed: large values by pointer, everything else as its value. */
function cArg(ctx: CContext, o: Operand): string {
  const v = cVal(ctx, o);
  if (!(o.kind === 'param' || o.kind === 'node') || !isLargeC(operandTypeOf(ctx.fn, o))) return v;
  return v.startsWith('(*') && v.endsWith(')') ? v.slice(2, -1) : `&${v}`;
}

/**
 * In C every by-value aggregate parameter is the callee's own copy; a `ref` p0, the `view`
 * extras, and large parameters (borrowed by `const` pointer) are read-only. The `owned` p0 is
 * the caller's loop state, owned whatever its size.
 */
const cOwned =
  (variant: CVariant, fn?: TypedFunc) =>
  (i: number): boolean =>
    !(variant === 'ref' && i === 0) &&
    !(fn !== undefined && isViewParam(fn, variant, i)) &&
    !(fn !== undefined && isLargeC(fn.params[i] as Type) && !(variant === 'owned' && i === 0));

/**
 * The C in-place rule: `mutableHereC`, and no borrowed read of the target (an aggregate
 * `get`/`at`, which C holds as a pointer into the target) is read after this update.
 */
function cMutableHere(
  fn: TypedFunc,
  o: Operand,
  index: number,
  owned: (i: number) => boolean,
  selfRead: boolean,
  projections: Projections = { of: new Map() },
): boolean {
  return (
    mutableHereC(fn, o, index, owned, new Set(projections.of.keys())) &&
    !borrowLive(fn, o, index, selfRead)
  );
}

/** Does the node at `index` update its first operand in place? Records the alias. */
function cInPlace(ctx: CContext, node: Node, index: number): boolean {
  const target = node.args[0] as Operand;
  if (!cMutableHere(ctx.fn, target, index, cOwned(ctx.variant, ctx.fn), true, ctx.projections))
    return false;
  ctx.aliases.set(node.id, cRoot(ctx, target));
  return true;
}

/**
 * Would the owned (`a0o_`) variant of `fn` update the `set`/`put` at `index` in place? The same
 * rule the emitter applies (src/parallel.ts relies on it for element-wise map folds).
 */
export function ownedUpdateInPlace(fn: TypedFunc, index: number): boolean {
  const node = fn.nodes[index];
  return (
    node !== undefined &&
    cMutableHere(
      fn,
      node.args[0] as Operand,
      index,
      cOwned('owned', fn),
      true,
      cProjections(fn, 'owned'),
    )
  );
}

/**
 * Optional C fold hook (src/parallel.ts): given one `fold` statement's pieces, return a
 * replacement statement plus helper definitions emitted before the function, or undefined to
 * keep the sequential loop. `decl` declares the state (may be empty when the state aliases its
 * initial value), `loop` is the sequential loop, `state` the state lvalue.
 */
export interface CFoldSite {
  readonly fn: TypedFunc;
  readonly node: Node;
  readonly count: string;
  readonly extra: readonly string[];
  readonly state: string;
  readonly decl: string;
  readonly loop: string;
}
export interface CParallel {
  /** Distinguishes cached emissions (mode and thresholds). */
  readonly key: string;
  /** Runtime appended after the C type declarations. */
  readonly runtime: string;
  readonly fold: (
    site: CFoldSite,
  ) =>
    | { readonly helpers: readonly (readonly [string, string])[]; readonly text: string }
    | undefined;
}

function cExpr(ctx: CContext, node: Node, index: number): string {
  const fn = ctx.fn;
  const vals = node.args.map((o) => cVal(ctx, o));
  const [a, b, c] = vals;
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `(uint32_t)(${a} + ${b})`;
    case 'sub':
      return `(uint32_t)(${a} - ${b})`;
    case 'mul':
      return `(uint32_t)((uint64_t)${a} * (uint64_t)${b})`;
    case 'and':
      return isBoolNode(fn, node) ? `(${a} && ${b})` : `(${a} & ${b})`;
    case 'or':
      return isBoolNode(fn, node) ? `(${a} || ${b})` : `(${a} | ${b})`;
    case 'xor':
      return isBoolNode(fn, node) ? `(${a} != ${b})` : `(${a} ^ ${b})`;
    case 'shl':
      return `(uint32_t)(${a} << (${b} & 31u))`;
    case 'shr':
      return `(${a} >> (${b} & 31u))`;
    case 'div':
      return `(${b} == 0u ? 0xffffffffu : ${a} / ${b})`;
    case 'rem':
      return `(${b} == 0u ? ${a} : ${a} % ${b})`;
    case 'eq':
      return `(${a} == ${b})`;
    case 'lt':
      return `(${a} < ${b})`;
    case 'le':
      return `(${a} <= ${b})`;
    case 'gt':
      return `(${a} > ${b})`;
    case 'ge':
      return `(${a} >= ${b})`;
    case 'ne':
      return `(${a} != ${b})`;
    case 'select':
      return `(${a} ? ${b} : ${c})`;
    case 'call':
      return `a0_${node.callee ?? ''}(${node.args.map((o) => cArg(ctx, o)).join(', ')})`;
    case 'arr': {
      const t = fn.types.get(node.id) ?? 'u32';
      const zeros =
        !isPrimitive(t) &&
        t.kind === 'arr' &&
        isPrimitive(t.elem) &&
        node.args.every(
          (o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value),
        );
      if (zeros) return `a0zero_${mangleType(t)}()`;
      return `a0mk_${mangleType(t)}(${vals.join(', ')})`;
    }
    case 'rec':
      return `a0mk_${mangleType(fn.types.get(node.id) ?? 'u32')}(${vals.join(', ')})`;
    case 'get':
      return `${a}.e[${b} % ${arrayLength(fn, node.args[0])}u]`;
    case 'set': {
      const idx = `${b} % ${arrayLength(fn, node.args[0])}u`;
      // In place: an assignment statement; the node aliases its operand's storage.
      if (cInPlace(ctx, node, index)) return `${a}.e[${idx}] = ${c};`;
      return `a0set_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}(${a}, ${b}, ${c})`;
    }
    case 'at':
      return `${a}.f${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}`;
    case 'put': {
      const k = node.args[1]?.kind === 'u32' ? node.args[1].value : 0;
      if (cInPlace(ctx, node, index)) return `${a}.f${k} = ${c};`;
      return `a0put_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}_${k}(${a}, ${c})`;
    }
    case 'read':
      return `a0_read(${a})`;
    case 'write':
      return `a0_write(${a}, ${b})`;
    case 'puts':
      return `a0_puts(${a}, ${b}.e, ${arrayLength(fn, node.args[1])}u)`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

/** A parameter declaration: large aggregates are borrowed by `const` pointer. */
const cParam = (t: Type, i: number): string =>
  isLargeC(t) ? `const ${cType(t)} *p${i}` : `${cType(t)} p${i}`;

/** The public ABI; a large result goes to caller-owned storage (`T *out` first). */
export function cSignature(fn: TypedFunc): string {
  const params = fn.params.map(cParam);
  if (isLargeC(fn.result))
    return `void a0_${fn.name}(${[`${cType(fn.result)} *out`, ...params].join(', ')})`;
  return `${cType(fn.result)} a0_${fn.name}(${params.length === 0 ? 'void' : params.join(', ')})`;
}

function cVariantSignature(fn: TypedFunc, variant: CVariant): string {
  if (variant === 'value') return cSignature(fn);
  if (variant === 'view') {
    const ps = fn.params.map((t, i) =>
      isViewParam(fn, variant, i) ? `const ${cType(t)} *p${i}` : cParam(t, i),
    );
    return `static inline ${cType(fn.result)} a0v_${fn.name}(${ps.join(', ')})`;
  }
  const p0 = cType(fn.params[0] as Type);
  const rest = fn.params.slice(1).map((t, i) => cParam(t, i + 1));
  const params = [variant === 'owned' ? `${p0} *p0` : `const ${p0} *p0`, ...rest].join(', ');
  return variant === 'owned'
    ? `static inline void a0o_${fn.name}(${params})`
    : `static inline ${cType(fn.result)} a0r_${fn.name}(${params})`;
}

/** Storage for a large node: the caller's `out` when it is the result's root, else the arena. */
function cLargeStorage(ctx: CContext, n: Node): string {
  const t = cType(ctx.fn.types.get(n.id) ?? 'u32');
  if (ctx.retOut === n.id) return `${t} *const n_${n.id} = out;`;
  ctx.arena += 1;
  return `${t} *const n_${n.id} = (${t} *)a0arena_alloc(sizeof(${t}));`;
}

/** Statements computing a large-typed (non-iteration) node through its pointer. */
function cLargeNode(ctx: CContext, n: Node, index: number): string {
  const fn = ctx.fn;
  const t = fn.types.get(n.id) ?? 'u32';
  const name = `n_${n.id}`;
  const [a, b, c] = n.args.map((o) => cVal(ctx, o));
  const [oa, ob, oc] = n.args as [Operand, Operand, Operand];
  switch (n.op) {
    case 'mov':
      return `  const ${cType(t)} *const ${name} = ${cArg(ctx, oa)};`;
    case 'select':
      return `  const ${cType(t)} *const ${name} = ${a} ? ${cArg(ctx, ob)} : ${cArg(ctx, oc)};`;
    case 'set': {
      const at = `.e[${b} % ${arrayLength(fn, oa)}u]`;
      if (cInPlace(ctx, n, index)) return `  ${a}${at} = ${c};`;
      return `  ${cLargeStorage(ctx, n)} *${name} = ${a}; (*${name})${at} = ${c};`;
    }
    case 'put': {
      const at = `.f${ob.kind === 'u32' ? ob.value : 0}`;
      if (cInPlace(ctx, n, index)) return `  ${a}${at} = ${c};`;
      return `  ${cLargeStorage(ctx, n)} *${name} = ${a}; (*${name})${at} = ${c};`;
    }
    case 'arr': {
      const zeros =
        !isPrimitive(t) &&
        t.kind === 'arr' &&
        isPrimitive(t.elem) &&
        n.args.every((o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value));
      const fill = zeros
        ? `a0zero_${mangleType(t)}(${name});`
        : n.args.map((o, k) => `${name}->e[${k}] = ${cVal(ctx, o)};`).join(' ');
      return `  ${cLargeStorage(ctx, n)} ${fill}`;
    }
    case 'rec':
      return `  ${cLargeStorage(ctx, n)} ${n.args.map((o, k) => `${name}->f${k} = ${cVal(ctx, o)};`).join(' ')}`;
    // Only the result's root in `out` is a copy; any other read borrows (see cBorrow).
    case 'get':
      return `  ${cLargeStorage(ctx, n)} *${name} = ${a}.e[${b} % ${arrayLength(fn, oa)}u];`;
    case 'at':
      return `  ${cLargeStorage(ctx, n)} *${name} = ${a}.f${ob.kind === 'u32' ? ob.value : 0};`;
    case 'call':
      return `  ${cLargeStorage(ctx, n)} a0_${n.callee ?? ''}(${[name, ...n.args.map((o) => cArg(ctx, o))].join(', ')});`;
    default:
      throw new A0Error(`${n.op} has no large-aggregate form`);
  }
}

/**
 * A read of an aggregate element or field borrows it: `const T *const n = &c.f;` instead of a
 * copy of the element (a large one would take arena storage and a memcpy on every call). The
 * container is never updated in place while a borrow is read (`cMutableHere`), and nothing
 * writes through a borrow (only fresh values and owned parameters are updated in place), so
 * the value read is the value a copy would hold. The result's root built in `out` stays a copy.
 */
function cBorrow(ctx: CContext, n: Node): string | undefined {
  const t = ctx.fn.types.get(n.id) ?? 'u32';
  if ((n.op !== 'get' && n.op !== 'at') || isPrimitive(t) || ctx.retOut === n.id) return undefined;
  const [oa, ob] = n.args as [Operand, Operand];
  const a = cVal(ctx, oa);
  const part =
    n.op === 'get'
      ? `.e[${cVal(ctx, ob)} % ${arrayLength(ctx.fn, oa)}u]`
      : `.f${ob.kind === 'u32' ? ob.value : 0}`;
  ctx.borrows.add(n.id);
  // An owned projection is not a const borrow: a `set`/`put` on it writes the field in place.
  const kind = ctx.projections.of.has(n.id) ? '' : 'const ';
  return `  ${kind}${cType(t)} *const n_${n.id} = &${a}${part};`;
}

/**
 * The final `rec` of an owned body with state projections, written into the state itself: a
 * field whose new value is its own projection (updated in place or unchanged) is not stored.
 * Stores run in field order and must read no other field's storage, so a value that is, or as a
 * `mov`/`select` pointer may be, another field's projection keeps the copying form.
 */
function cStateStores(ctx: CContext, rec: Node): string | undefined {
  const stores: string[] = [];
  const projectionOf = (x: Operand): number | undefined => {
    const r = cRoot(ctx, x);
    const p = r.kind === 'node' ? ctx.projections.of.get(r.id) : undefined;
    return p !== undefined && p.container.kind === 'param' ? p.field : undefined;
  };
  for (const [m, o] of rec.args.entries()) {
    const roots: Operand[] = [];
    const reach = (x: Operand): void => {
      const def = x.kind === 'node' ? ctx.fn.nodes.find((q) => q.id === x.id) : undefined;
      if (
        def !== undefined &&
        (def.op === 'mov' || def.op === 'select') &&
        isLargeC(operandTypeOf(ctx.fn, x))
      )
        for (const a of def.op === 'mov' ? def.args : def.args.slice(1)) reach(a);
      else roots.push(x);
    };
    reach(o);
    const fields = roots.map(projectionOf);
    if (fields.every((f) => f === m)) continue;
    if (fields.some((f) => f !== undefined && f !== m)) return undefined;
    const self = fields.includes(m) ? `if (${cArg(ctx, o)} != &(*p0).f${m}) ` : '';
    stores.push(`${self}(*p0).f${m} = ${cVal(ctx, o)};`);
  }
  ctx.aliases.set(rec.id, { kind: 'param', index: 0 });
  return stores.length === 0 ? '' : `  ${stores.join(' ')}`;
}

function cBody(
  fn: TypedFunc,
  variant: CVariant,
  parallel?: CParallel,
  helpers?: Map<string, string>,
  trap = false,
): string {
  const first = cBodyWith(fn, variant, undefined, parallel, helpers, trap);
  if (variant !== 'value' || !isLargeC(fn.result)) return first.text;
  // A large result: build its root node in `out` (no final copy) unless the root only aliases.
  const root = cRoot(first.ctx, fn.ret);
  const def = root.kind === 'node' ? fn.nodes.find((n) => n.id === root.id) : undefined;
  if (def === undefined || def.op === 'mov' || def.op === 'select') return first.text;
  return cBodyWith(fn, variant, def.id, parallel, helpers, trap).text;
}

function cBodyWith(
  fn: TypedFunc,
  variant: CVariant,
  retOut: string | undefined,
  parallel?: CParallel,
  helpers?: Map<string, string>,
  trap = false,
): { readonly text: string; readonly ctx: CContext } {
  const ctx: CContext = {
    fn,
    variant,
    aliases: new Map(),
    borrows: new Set(),
    projections: cProjections(fn, variant),
    retOut,
    arena: 0,
  };
  const hooked = (site: CFoldSite): string => {
    // The arena is single-threaded: a fold touching large values keeps its sequential loop.
    const callees = [site.node.callee, site.node.pred].map((c) => fn.calls.get(c ?? ''));
    const large =
      isLargeC(fn.types.get(site.node.id) ?? 'u32') ||
      callees.some((g) => g !== undefined && touchesLarge(g));
    const out = large ? undefined : parallel?.fold(site);
    if (out === undefined) return `${site.decl.length > 0 ? `  ${site.decl}\n` : ''}  ${site.loop}`;
    for (const [name, text] of out.helpers) helpers?.set(name, text);
    return out.text;
  };
  const lines = fn.nodes.map((n, index) => {
    const t = cType(fn.types.get(n.id) ?? 'u32');
    if (n.op === 'fold' || n.op === 'loop') {
      const [count, init, ...extra] = n.args.map((o) => cVal(ctx, o));
      // Extras as passed to a by-value or owned body: large ones by pointer.
      const passed = n.args.slice(2).map((o) => cArg(ctx, o));
      if (isPrimitive(fn.types.get(n.id) ?? 'u32')) {
        const call = [`n_${n.id}`, 'i', ...passed].join(', ');
        const guard = n.op === 'loop' ? ` if (!a0_${n.pred ?? ''}(${call})) break;` : '';
        const decl = `${t} n_${n.id} = ${init};`;
        const body = fn.calls.get(n.callee ?? '');
        // A fold body reading aggregate extras takes them by const pointer (no per-trip copy).
        const view = n.op === 'fold' && body !== undefined && hasViewVariant(body);
        const step = view
          ? `a0v_${n.callee ?? ''}(${[`n_${n.id}`, 'i', ...extra.map((e, k) => (isPrimitive(body.params[k + 2] as Type) ? e : `&${e}`))].join(', ')})`
          : `a0_${n.callee ?? ''}(${call})`;
        const loop = `for (uint32_t i = 0; i < ${count}; i++) {${tripCall(trap, fn, n)}${guard} n_${n.id} = ${step}; }`;
        return hooked({ fn, node: n, count: `${count}`, extra, state: `n_${n.id}`, decl, loop });
      }
      // Aggregate state: the body updates it through a pointer and the predicate reads it
      // through a const pointer, so no trip copies the state. The state is the initial value's
      // own storage when that value is provably unshared (as in JS); otherwise one copy. The
      // initial value passed again as an extra is read by every trip, so it is not unshared.
      const initOperand = n.args[1] as Operand;
      const owned =
        cMutableHere(fn, initOperand, index, cOwned(variant, fn), false, ctx.projections) &&
        !n.args.slice(2).some((o) => sameOp(o, initOperand));
      if (owned) ctx.aliases.set(n.id, cRoot(ctx, initOperand));
      const large = isLargeC(fn.types.get(n.id) ?? 'u32');
      const state = owned ? `${init}` : large ? `(*n_${n.id})` : `n_${n.id}`;
      const call = [`&${state}`, 'i', ...passed].join(', ');
      const guard = n.op === 'loop' ? ` if (!a0r_${n.pred ?? ''}(${call})) break;` : '';
      const loop = `for (uint32_t i = 0; i < ${count}; i++) {${tripCall(trap, fn, n)}${guard} a0o_${n.callee ?? ''}(${call}); }`;
      const decl = owned
        ? ''
        : large
          ? `${cLargeStorage(ctx, n)} *n_${n.id} = ${init};`
          : `${t} n_${n.id} = ${init};`;
      return hooked({ fn, node: n, count: `${count}`, extra, state, decl, loop });
    }
    const borrow = cBorrow(ctx, n);
    if (borrow !== undefined) return borrow;
    if (
      variant === 'owned' &&
      index === fn.nodes.length - 1 &&
      n.op === 'rec' &&
      [...ctx.projections.of.values()].some((p) => p.container.kind === 'param')
    ) {
      const stores = cStateStores(ctx, n);
      if (stores !== undefined) return stores;
    }
    if (isLargeC(fn.types.get(n.id) ?? 'u32')) return cLargeNode(ctx, n, index);
    const expr = cExpr(ctx, n, index);
    if (ctx.aliases.has(n.id)) return `  ${expr}`;
    // `const T x` for values; `T *const x` for the io pointer (the pointee is mutable state).
    const decl = t.endsWith('*') ? `${t}const` : `const ${t}`;
    // Effect results may be legitimately unused (the effect is the point); keep -Wall clean.
    const effect = n.op === 'read' || n.op === 'write' || containsIo(fn.types.get(n.id) ?? 'u32');
    return `  ${decl} n_${n.id} = ${expr};${effect ? ` (void)n_${n.id};` : ''}`;
  });
  // A local updated in place cannot be const: drop the qualifier on every aliased node.
  const roots = new Set(
    [...ctx.aliases.values()].filter((o) => o.kind === 'node').map((o) => cOperand(o)),
  );
  const body = lines.map((line) => {
    const m = /^ {2}const \S+ (n_[a-z0-9_]+) =/.exec(line);
    return m !== null && roots.has(m[1] as string) ? line.replace('  const ', '  ') : line;
  });
  const root = cRoot(ctx, fn.ret);
  const tail: string[] = trap ? ['  a0_leave();'] : [];
  if (variant === 'owned') {
    // The state is already updated in place when the result aliases p0; otherwise store it.
    if (!(root.kind === 'param' && root.index === 0)) tail.push(`  *p0 = ${cVal(ctx, fn.ret)};`);
  } else if (variant === 'value' && isLargeC(fn.result)) {
    if (!(root.kind === 'node' && root.id === retOut)) tail.push(`  *out = ${cVal(ctx, fn.ret)};`);
  }
  // Release this call's arena storage. Memory is not reused before the next allocation, so the
  // result expression may still read it.
  if (ctx.arena > 0) tail.push('  a0arena_top = a0arena_mark;');
  if (variant !== 'owned' && !(variant === 'value' && isLargeC(fn.result)))
    tail.push(`  return ${cVal(ctx, fn.ret)};`);
  const mark = ctx.arena > 0 ? ['  const uint32_t a0arena_mark = a0arena_top;'] : [];
  const enter = trap ? [`  a0_enter("${fn.name}");`] : [];
  const text = [
    `${cVariantSignature(fn, variant)} {`,
    ...enter,
    ...mark,
    ...body,
    ...tail,
    '}',
  ].join('\n');
  return { text, ctx };
}

/** One trip of a fold/loop under the trap runtime: counted against the cap before it runs. */
const tripCall = (trap: boolean, fn: TypedFunc, n: Node): string =>
  trap ? ` a0_trip("${fn.name}", "${n.id}", i);` : '';

const emitCFunction = (fn: TypedFunc, parallel?: CParallel, trap = false): string => {
  const variants: CVariant[] = ['value'];
  if (hasOwnedVariant(fn)) variants.push('owned');
  if (hasRefVariant(fn)) variants.push('ref');
  if (hasViewVariant(fn)) variants.push('view');
  const helpers = new Map<string, string>();
  const bodies = variants.map((v) => cBody(fn, v, parallel, helpers, trap));
  return [...helpers.values(), ...bodies].join('\n\n');
};

// ---------------------------------------------------------------------------
// Java
// ---------------------------------------------------------------------------

export const JAVA_CLASS = 'A0Module';

const javaType = (t: Type): string =>
  t === 'u32'
    ? 'int'
    : t === 'bool'
      ? 'boolean'
      : t === 'io'
        ? 'A0Io'
        : t.kind === 'arr'
          ? `${javaType(t.elem)}[]`
          : `R_${mangleType(t)}`;

/** Java io runtime with the C runtime's fixed capacities: input truncated to inCap words, writes past outCap dropped. */
const javaIoRuntime = (inCap: number, outCap: number): string => `  public static final class A0Io {
    public final int[] input = new int[${inCap}]; public final int ninput; public int position; public final int[] output = new int[${outCap}]; public int noutput;
    public A0Io(int[] in) { ninput = Math.min(in.length, ${inCap}); System.arraycopy(in, 0, input, 0, ninput); }
  }
  static R_r2_u_io read(A0Io t) { int v = t.position < t.ninput ? t.input[t.position++] : 0; return new R_r2_u_io(v, t); }
  static A0Io write(A0Io t, int v) { if (t.noutput < ${outCap}) t.output[t.noutput++] = v; return t; }
  static A0Io puts(A0Io t, int[] a) { write(t, a.length); for (int v : a) write(t, v); return t; }`;

/** Nested record declarations and copy-on-write helpers for one aggregate type. */
function javaTypeDecl(t: Type): string {
  if (isPrimitive(t)) return '';
  const m = mangleType(t);
  if (t.kind === 'arr') {
    const jt = javaType(t);
    const e = javaType(t.elem);
    return `  static ${jt} set_${m}(${jt} a, int i, ${e} v) { ${jt} c = a.clone(); c[Integer.remainderUnsigned(i, ${t.length})] = v; return c; }`;
  }
  const name = javaType(t);
  const comps = t.fields.map((f, i) => `${javaType(f)} f${i}`).join(', ');
  const puts = t.fields.map((f, i) => {
    const args = t.fields.map((_, k) => (k === i ? 'v' : `r.f${k}()`)).join(', ');
    return `  static ${name} put_${m}_${i}(${name} r, ${javaType(f)} v) { return new ${name}(${args}); }`;
  });
  return [`  record ${name}(${comps}) {}`, ...puts].join('\n');
}

/** Java aggregate literal (arrays need the full nested element type in `new`). */
function javaNew(t: Type, args: readonly string[]): string {
  if (isPrimitive(t)) throw new A0Error('javaNew on primitive');
  if (t.kind === 'arr') return `new ${javaType(t)}{${args.join(', ')}}`;
  return `new ${javaType(t)}(${args.join(', ')})`;
}

function javaOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return hex(o.value);
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

function javaExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(javaOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `${a} + ${b}`;
    case 'sub':
      return `${a} - ${b}`;
    case 'mul':
      return `${a} * ${b}`;
    case 'and':
      return `${a} & ${b}`;
    case 'or':
      return `${a} | ${b}`;
    case 'xor':
      return `${a} ^ ${b}`;
    case 'shl':
      return `${a} << (${b} & 31)`;
    case 'shr':
      return `${a} >>> (${b} & 31)`;
    case 'div':
      return `(${b} == 0 ? 0xffffffff : Integer.divideUnsigned(${a}, ${b}))`;
    case 'rem':
      return `(${b} == 0 ? ${a} : Integer.remainderUnsigned(${a}, ${b}))`;
    case 'eq':
      return `${a} == ${b}`;
    case 'lt':
      return `Integer.compareUnsigned(${a}, ${b}) < 0`;
    case 'le':
      return `Integer.compareUnsigned(${a}, ${b}) <= 0`;
    case 'gt':
      return `Integer.compareUnsigned(${a}, ${b}) > 0`;
    case 'ge':
      return `Integer.compareUnsigned(${a}, ${b}) >= 0`;
    case 'ne':
      return `${a} != ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'call':
      return `${node.callee ?? ''}(${node.args.map(javaOperand).join(', ')})`;
    case 'arr': {
      // An all-zero scalar array is a plain allocation (Java zero-initializes); a literal of
      // 65536 elements would otherwise exceed the 64 KiB method bytecode limit.
      const t = fn.types.get(node.id) ?? 'u32';
      const zeros =
        !isPrimitive(t) &&
        t.kind === 'arr' &&
        isPrimitive(t.elem) &&
        node.args.every(
          (o) => (o.kind === 'u32' && o.value === 0) || (o.kind === 'bool' && !o.value),
        );
      if (zeros) return `new ${javaType(t)}`.replace('[]', `[${node.args.length}]`);
      return javaNew(t, node.args.map(javaOperand));
    }
    case 'rec':
      return javaNew(fn.types.get(node.id) ?? 'u32', node.args.map(javaOperand));
    case 'get':
      return `${a}[Integer.remainderUnsigned(${b}, ${arrayLength(fn, node.args[0])})]`;
    case 'set':
      return `set_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}(${a}, ${b}, ${c})`;
    case 'at':
      return `${a}.f${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}()`;
    case 'put':
      return `put_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}_${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}(${a}, ${c})`;
    case 'read':
      return `read(${a})`;
    case 'write':
      return `write(${a}, ${b})`;
    case 'puts':
      return `puts(${a}, ${b})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

const emitJavaFunction: Emitter = (fn) => {
  const params = fn.params.map((t, i) => `${javaType(t)} p${i}`).join(', ');
  const body = fn.nodes.map((n) => {
    const t = javaType(fn.types.get(n.id) ?? 'u32');
    if (n.op !== 'fold' && n.op !== 'loop') return `    final ${t} n_${n.id} = ${javaExpr(n, fn)};`;
    const [count, init, ...extra] = n.args.map(javaOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!${n.pred ?? ''}(${call})) break;` : '';
    return `    ${t} n_${n.id} = ${init};\n    for (int i = 0; Integer.compareUnsigned(i, ${count}) < 0; i++) {${guard} n_${n.id} = ${n.callee ?? ''}(${call}); }`;
  });
  return [
    `  public static ${javaType(fn.result)} ${fn.name}(${params}) {`,
    ...body,
    `    return ${javaOperand(fn.ret)};`,
    '  }',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// SystemVerilog (combinational; emitted only, see results for validation status)
// ---------------------------------------------------------------------------

export const svType = (t: Type): string =>
  t === 'bool' ? 'logic' : `logic [${bitWidth(t) - 1}:0]`;

/** Bit offset of field k inside a record (field 0 at the LSB). */
export function svFieldOffset(t: Type, k: number): number {
  if (isPrimitive(t) || t.kind !== 'rec') throw new A0Error('field offset on non-record');
  return t.fields.slice(0, k).reduce((n, f) => n + bitWidth(f), 0);
}

export function svOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return `32'd${o.value}`;
    case 'bool':
      return o.value ? "1'b1" : "1'b0";
  }
}

/** Low five bits of the shift distance; a bit-select is illegal on a literal, so mask constants here. */
function svShiftAmount(o: Operand | undefined): string {
  if (o === undefined) throw new A0Error('shift without distance');
  if (o.kind === 'u32') return `5'd${o.value & 31}`;
  return `${svOperand(o)}[4:0]`;
}

export function svExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(svOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `32'(${a} + ${b})`;
    case 'sub':
      return `32'(${a} - ${b})`;
    case 'mul':
      return `32'(${a} * ${b})`;
    case 'and':
      return `${a} & ${b}`;
    case 'or':
      return `${a} | ${b}`;
    case 'xor':
      return `${a} ^ ${b}`;
    case 'shl':
      return `32'(${a} << ${svShiftAmount(node.args[1])})`;
    case 'shr':
      return `${a} >> ${svShiftAmount(node.args[1])}`;
    case 'div':
      return `(${b} == 32'd0) ? 32'hffffffff : ${a} / ${b}`;
    case 'rem':
      return `(${b} == 32'd0) ? ${a} : ${a} % ${b}`;
    case 'eq':
      return `${a} == ${b}`;
    case 'lt':
      return `${a} < ${b}`;
    case 'le':
      return `${a} <= ${b}`;
    case 'gt':
      return `${a} > ${b}`;
    case 'ge':
      return `${a} >= ${b}`;
    case 'ne':
      return `${a} != ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'arr':
    case 'rec':
      // Element/field 0 occupies the least significant bits.
      return `{${[...node.args].reverse().map(svOperand).join(', ')}}`;
    case 'get': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      if (isPrimitive(t) || t.kind !== 'arr') throw new A0Error('get on non-array');
      const w = bitWidth(t.elem);
      const idx = node.args[1];
      const base =
        idx?.kind === 'u32' ? `${(idx.value % t.length) * w}` : `((${b} % ${t.length}) * ${w})`;
      return `${a}[${base} +: ${w}]`;
    }
    case 'at': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      const k = node.args[1]?.kind === 'u32' ? node.args[1].value : 0;
      if (isPrimitive(t) || t.kind !== 'rec') throw new A0Error('at on non-record');
      return `${a}[${svFieldOffset(t, k)} +: ${bitWidth(t.fields[k] as Type)}]`;
    }
    case 'set':
    case 'put':
      throw new A0Error(`${node.op} is emitted as an always_comb block`);
    case 'read':
    case 'write':
    case 'puts':
      throw new A0Error(
        `${node.op}: io effects need sequential state, which the combinational SystemVerilog backend does not implement`,
      );
    case 'call':
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as module instances in SystemVerilog`);
  }
}

/** Largest literal fold trip count the combinational SystemVerilog backend will unroll. */
export const SV_MAX_UNROLL = 256;

const emitSvFunction: Emitter = (fn) => {
  assertVectorSized(fn, 'SystemVerilog');
  if (needsSequential(fn)) return emitSequential(fn);
  const ports = [
    ...fn.params.map((t, i) => `  input ${svType(t)} p${i}`),
    `  output ${svType(fn.result)} result`,
  ].join(',\n');
  const decls = fn.nodes.map((n) => `  ${svType(fn.types.get(n.id) ?? 'u32')} n_${n.id};`);
  const assigns = fn.nodes.map((n) => {
    if (n.op === 'fold' || n.op === 'loop') {
      // Combinational backend: only a literal trip count can be unrolled into a chain of instances.
      const [count, init, ...extra] = n.args;
      if (count === undefined || count.kind !== 'u32') {
        throw new A0Error(
          `${fn.name}.${n.id}: ${n.op} with a non-literal trip count needs sequential state, which the combinational SystemVerilog backend does not implement`,
        );
      }
      if (count.value > SV_MAX_UNROLL) {
        throw new A0Error(
          `${fn.name}.${n.id}: ${n.op} trip count ${count.value} exceeds the SystemVerilog unroll limit ${SV_MAX_UNROLL}`,
        );
      }
      const width = svType(fn.types.get(n.id) ?? 'u32');
      const lines: string[] = [];
      let prev = init === undefined ? "32'd0" : svOperand(init);
      // For loop: done_i latches once the predicate is false; later stages pass the state through.
      let done = "1'b0";
      for (let i = 0; i < count.value; i += 1) {
        const wire = `n_${n.id}_s${i + 1}`;
        const ports = (result: string) => [
          `.p0(${prev})`,
          `.p1(32'd${i})`,
          ...extra.map((arg, k) => `.p${k + 2}(${svOperand(arg)})`),
          `.result(${result})`,
        ];
        if (n.op === 'loop') {
          const cont = `n_${n.id}_c${i}`;
          const next = `n_${n.id}_d${i + 1}`;
          const body = `n_${n.id}_b${i + 1}`;
          lines.push(
            `  logic ${cont};`,
            `  logic ${next};`,
            `  ${width} ${body};`,
            `  ${width} ${wire};`,
          );
          lines.push(`  a0_${n.pred ?? ''} u_${n.id}_p${i} (${ports(cont).join(', ')});`);
          lines.push(`  a0_${n.callee ?? ''} u_${n.id}_${i} (${ports(body).join(', ')});`);
          lines.push(`  assign ${next} = ${done} | ~${cont};`);
          lines.push(`  assign ${wire} = ${next} ? ${prev} : ${body};`);
          done = next;
        } else {
          lines.push(`  ${width} ${wire};`);
          lines.push(`  a0_${n.callee ?? ''} u_${n.id}_${i} (${ports(wire).join(', ')});`);
        }
        prev = wire;
      }
      lines.push(`  assign n_${n.id} = ${prev};`);
      return lines.join('\n');
    }
    if (n.op === 'set' || n.op === 'put') {
      const [a, b, c] = n.args.map(svOperand);
      const t = operandTypeOf(fn, n.args[0] as Operand);
      if (isPrimitive(t)) throw new A0Error(`${n.op} on primitive`);
      let slice: string;
      if (n.op === 'set') {
        if (t.kind !== 'arr') throw new A0Error('set on non-array');
        const w = bitWidth(t.elem);
        const idx = n.args[1];
        const base =
          idx?.kind === 'u32' ? `${(idx.value % t.length) * w}` : `((${b} % ${t.length}) * ${w})`;
        slice = `[${base} +: ${w}]`;
      } else {
        if (t.kind !== 'rec') throw new A0Error('put on non-record');
        const k = n.args[1]?.kind === 'u32' ? n.args[1].value : 0;
        slice = `[${svFieldOffset(t, k)} +: ${bitWidth(t.fields[k] as Type)}]`;
      }
      return `  always_comb begin n_${n.id} = ${a}; n_${n.id}${slice} = ${c}; end`;
    }
    if (n.op !== 'call') return `  assign n_${n.id} = ${svExpr(n, fn)};`;
    // A call is a combinational instance of the callee module, connected by port name.
    const conns = [...n.args.map((arg, i) => `.p${i}(${svOperand(arg)})`), `.result(n_${n.id})`];
    return `  a0_${n.callee ?? ''} u_${n.id} (${conns.join(', ')});`;
  });
  return [
    `module a0_${fn.name} (`,
    ports,
    ');',
    ...decls,
    ...assigns,
    `  assign result = ${svOperand(fn.ret)};`,
    'endmodule',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// Module assembly and emission cache
// ---------------------------------------------------------------------------

const EMITTERS: Readonly<Record<Target, Emitter>> = {
  js: emitJsFunction,
  c: emitCFunction,
  java: emitJavaFunction,
  sv: emitSvFunction,
  arm64: emitArm64Function,
  x86_64: emitX86_64Function,
  riscv64: emitRiscv64Function,
  avr: emitAvrFunction,
  wasm: emitWasmFunction,
  arm32: emitArm32Function,
};

/** True when any function of the program carries an io token anywhere in its types. */
export function usesIo(program: TypedProgram): boolean {
  return program.functions.some(
    (fn) =>
      containsIo(fn.result) ||
      fn.params.some(containsIo) ||
      [...fn.types.values()].some(containsIo),
  );
}

export function assemble(
  target: Target,
  bodies: readonly string[],
  program: TypedProgram,
  options: CompileOptions = {},
): string {
  const types = aggregateTypes(program);
  const io = usesIo(program);
  if (io && !types.some((t) => formatType(t) === '(u32,io)')) {
    types.unshift({ kind: 'rec', fields: ['u32', 'io'] });
  }
  switch (target) {
    case 'arm64':
      return assembleArm64(bodies, COMPILER_VERSION);
    case 'x86_64':
      return assembleX86_64(bodies, COMPILER_VERSION);
    case 'riscv64':
      return assembleRiscv64(bodies, COMPILER_VERSION);
    case 'avr':
      return assembleAvr(bodies, COMPILER_VERSION);
    case 'wasm':
      return Buffer.from(
        assembleWasm(
          bodies,
          program,
          {
            ioInputCapacity: options.ioInputCapacity ?? C_IO_INPUT_CAPACITY,
            ioOutputCapacity: options.ioOutputCapacity ?? C_IO_OUTPUT_CAPACITY,
            ...(options.wasmExports === undefined ? {} : { exports: options.wasmExports }),
          },
          COMPILER_VERSION,
        ),
      ).toString('base64');
    case 'arm32':
      return assembleArm32(bodies, COMPILER_VERSION);
    case 'js':
      return `${JS_PRELUDE}\n${bodies.join('\n\n')}\n`;
    case 'c': {
      const decls = types.map(cTypeDecl).filter((d) => d.length > 0);
      if (io)
        decls.push(
          cIoRuntime(
            options.ioInputCapacity ?? C_IO_INPUT_CAPACITY,
            options.ioOutputCapacity ?? C_IO_OUTPUT_CAPACITY,
          ),
        );
      const arena = cArenaRuntime(program);
      if (arena !== undefined) decls.push(arena);
      if (options.cParallel !== undefined) decls.push(options.cParallel.runtime);
      if (options.cTrap !== undefined) {
        if (options.cParallel !== undefined)
          throw new A0Error('cTrap and cParallel cannot be combined', undefined, {
            code: 'cli',
            fix: 'drop the parallel option: the trap runtime is single-threaded',
          });
        decls.push(cTrapRuntime(options.cTrap.maxTrips, program.functions.length + 1));
      }
      return `${C_PRELUDE}\n${decls.length > 0 ? `${decls.join('\n')}\n\n` : ''}${bodies.join('\n\n')}\n`;
    }
    case 'java': {
      const decls = types.map(javaTypeDecl).filter((d) => d.length > 0);
      if (io)
        decls.push(
          javaIoRuntime(
            options.ioInputCapacity ?? C_IO_INPUT_CAPACITY,
            options.ioOutputCapacity ?? C_IO_OUTPUT_CAPACITY,
          ),
        );
      return `// Generated by A0 ${COMPILER_VERSION}. int carries the u32 bit pattern.\npublic final class ${JAVA_CLASS} {\n  private ${JAVA_CLASS}() {}\n\n${decls.length > 0 ? `${decls.join('\n')}\n\n` : ''}${bodies.join('\n\n')}\n}\n`;
    }
    case 'sv':
      return `// Generated by A0 ${COMPILER_VERSION}. Pure functions combinational; io, iteration, and division clocked. Two-state semantics intended.\n\`timescale 1ns/1ps\n${bodies.some((b) => b.includes('a0_udiv ')) ? `${SV_UDIV_MODULE}\n\n` : ''}${bodies.join('\n\n')}\n`;
  }
}

export interface CompileOptions {
  readonly optimize?: boolean;
  /** C/wasm/Java/C# io capacities in words (defaults C_IO_INPUT_CAPACITY / C_IO_OUTPUT_CAPACITY); prelude only, bodies are unaffected. */
  readonly ioInputCapacity?: number;
  readonly ioOutputCapacity?: number;
  /** C target only: automatic parallel folds (src/parallel.ts `parallelC`); absent = sequential. */
  readonly cParallel?: CParallel;
  /**
   * C target only: the trap runtime. The module counts every fold/loop trip against `maxTrips`
   * (the interpreter's `RunOptions.maxTrips`) and tracks the call chain; the trip past the cap
   * prints one line (`limit: trap iter fn=.. at=fn.node trip=.. chain=a>b fix: ..`, the
   * interpreter's `formatTrap` text) to stderr and exits with status 3. Single-threaded, never
   * combined with `cParallel`, and emitted unoptimized so the trips are the interpreter's.
   */
  readonly cTrap?: { readonly maxTrips: number };
  /**
   * wasm target only: the functions to export. Absent, every function is exported as
   * `a0_<name>`; given, only these are, and functions none of them reaches (for example
   * callees every call site inlined) are left out of the module.
   */
  readonly wasmExports?: readonly string[];
  /**
   * wasm target only: simd128 for fill runs (default true; fixed-width SIMD is in every
   * current engine: Chrome/Edge 91+, Firefox 89+, Safari 16.4+, Node 16.4+). false emits
   * scalar code only, for older engines.
   */
  readonly wasmSimd?: boolean;
  /**
   * wasm target only: copies of a small inlined fold body per loop back edge (default 1). V8
   * unrolls such loops itself, so 2 or 4 measured no faster there (STATUS, a0c-0.1.26) and
   * only grows the module; engines without their own unrolling may gain.
   */
  readonly wasmUnroll?: 1 | 2 | 4;
}

export interface CompileResult {
  readonly text: string;
  readonly cacheHits: number;
  readonly cacheMisses: number;
}

/**
 * Bounded LRU cache of per-function emitted text. Keys include the compiler
 * version, target, optimization flag, and function content revision. This is not
 * a persistent artifact cache: the program is still validated and hashed, and the
 * module is still assembled on every call.
 */
export class FunctionCache {
  readonly #entries = new Map<string, string>();
  readonly #capacity: number;

  constructor(capacity = 1024) {
    if (!Number.isInteger(capacity) || capacity < 1)
      throw new A0Error('cache capacity must be >= 1');
    this.#capacity = capacity;
  }

  get size(): number {
    return this.#entries.size;
  }

  /** Key: compiler version, target, optimization level, and semantic revision (own content + all transitive callees). */
  static key(target: Target, optimized: boolean, fn: TypedFunc, variant = ''): string {
    return `${COMPILER_VERSION}|${target}|${optimized ? 'O1' : 'O0'}${variant}|${semanticRevision(fn)}`;
  }

  get(key: string): string | undefined {
    const value = this.#entries.get(key);
    if (value !== undefined) {
      this.#entries.delete(key);
      this.#entries.set(key, value);
    }
    return value;
  }

  set(key: string, value: string): void {
    this.#entries.delete(key);
    this.#entries.set(key, value);
    if (this.#entries.size > this.#capacity) {
      const oldest = this.#entries.keys().next().value;
      if (oldest !== undefined) this.#entries.delete(oldest);
    }
  }
}

export function emitFunction(target: Target, fn: TypedFunc, options: CompileOptions = {}): string {
  // The trap runtime counts the trips the reference interpreter takes, so it keeps every iteration.
  const source =
    options.optimize === false || options.cTrap !== undefined ? fn : optimizeFunction(fn).fn;
  // Hardware form is decided on the source function so callers and testbenches agree even
  // when optimization removes every iteration or effect.
  if (target === 'sv' && needsSequential(fn)) {
    assertVectorSized(fn, 'SystemVerilog');
    return emitSequential(source);
  }
  if (target === 'c' && options.cParallel !== undefined)
    return emitCFunction(source, options.cParallel);
  if (target === 'c' && options.cTrap !== undefined) return emitCFunction(source, undefined, true);
  if (target === 'wasm')
    return emitWasmFunction(source, {
      simd: options.wasmSimd !== false,
      unroll: options.wasmUnroll ?? 1,
    });
  return EMITTERS[target](source);
}

export function compile(
  program: TypedProgram,
  target: Target,
  options: CompileOptions = {},
  cache?: FunctionCache,
): CompileResult {
  const optimized = options.optimize !== false;
  let cacheHits = 0;
  let cacheMisses = 0;
  const bodies = program.functions.map((fn) => {
    if (cache === undefined) return emitFunction(target, fn, options);
    const key = FunctionCache.key(
      target,
      optimized,
      fn,
      target === 'c' && options.cParallel !== undefined
        ? `|${options.cParallel.key}`
        : target === 'c' && options.cTrap !== undefined
          ? '|trap'
          : target === 'wasm'
            ? `${options.wasmSimd === false ? '|nosimd' : ''}${options.wasmUnroll === undefined || options.wasmUnroll === 1 ? '' : `|unroll${options.wasmUnroll}`}`
            : '',
    );
    const hit = cache.get(key);
    if (hit !== undefined) {
      cacheHits += 1;
      return hit;
    }
    cacheMisses += 1;
    const text = emitFunction(target, fn, options);
    cache.set(key, text);
    return text;
  });
  return { text: assemble(target, bodies, program, options), cacheHits, cacheMisses };
}
