/**
 * Source emission for JavaScript (ES module), C (C-compatible, also valid C++),
 * Java, and SystemVerilog, plus a bounded in-memory function-emission cache.
 *
 * Every backend preserves the exact v0.1 semantics: wrapping u32 arithmetic,
 * logical right shift, shift distance masked to five bits, unsigned comparison,
 * and non-numeric booleans. Identifiers are validated by the core and emitted with
 * a prefix so source names cannot collide with target keywords or runtime symbols.
 */

import {
  A0Error,
  bitWidth,
  formatType,
  isScalar,
  type Node,
  type Operand,
  type Type,
  type TypedFunc,
  type TypedProgram,
} from './core.js';
import { semanticRevision } from './edit.js';
import { optimizeFunction } from './optimize.js';

export const COMPILER_VERSION = 'a0c-0.1.0';

export type Target = 'js' | 'c' | 'java' | 'sv';
export const TARGETS: readonly Target[] = ['js', 'c', 'java', 'sv'];

export function isTarget(text: string): text is Target {
  return (TARGETS as readonly string[]).includes(text);
}

const hex = (v: number): string => `0x${v.toString(16).padStart(8, '0')}`;

type Emitter = (fn: TypedFunc) => string;

/** Type of an operand inside a function (params, nodes, literals). */
function operandTypeOf(fn: TypedFunc, o: Operand): Type {
  switch (o.kind) {
    case 'u32':
      return 'u32';
    case 'bool':
      return 'bool';
    case 'param':
      return fn.params[o.index] ?? 'u32';
    case 'node':
      return fn.types.get(o.id) ?? 'u32';
  }
}

function arrayLength(fn: TypedFunc, o: Operand | undefined): number {
  if (o === undefined) throw new A0Error('missing array operand');
  const t = operandTypeOf(fn, o);
  if (isScalar(t) || t.kind !== 'arr') throw new A0Error('expected array operand');
  return t.length;
}

/** Injective, identifier-safe name for a type: u, b, a<N>_<elem>, r<N>_<f>..._<f>. */
export function mangleType(t: Type): string {
  if (t === 'u32') return 'u';
  if (t === 'bool') return 'b';
  if (t.kind === 'arr') return `a${t.length}_${mangleType(t.elem)}`;
  return `r${t.fields.length}_${t.fields.map(mangleType).join('_')}`;
}

/** All aggregate types used by a program, nested types first, deduplicated. */
export function aggregateTypes(program: TypedProgram): Type[] {
  const seen = new Set<string>();
  const out: Type[] = [];
  const visit = (t: Type): void => {
    if (isScalar(t)) return;
    if (t.kind === 'arr') visit(t.elem);
    else t.fields.forEach(visit);
    const key = formatType(t);
    if (!seen.has(key)) {
      seen.add(key);
      out.push(t);
    }
  };
  for (const fn of program.functions) {
    fn.params.forEach(visit);
    visit(fn.result);
    for (const t of fn.types.values()) visit(t);
  }
  return out;
}

/** JSON shape used by the JS runtime guard. */
function jsShape(t: Type): string {
  if (isScalar(t)) return JSON.stringify(t);
  if (t.kind === 'arr') return `["arr",${t.length},${jsShape(t.elem)}]`;
  return `["rec",[${t.fields.map(jsShape).join(',')}]]`;
}

// ---------------------------------------------------------------------------
// JavaScript
// ---------------------------------------------------------------------------

const JS_PRELUDE = `// Generated by A0 ${COMPILER_VERSION}. Exact u32/bool semantics.
const U32_MAX = 0xffffffff;
function a0_u32(v, name) {
  if (typeof v !== 'number' || !Number.isInteger(v) || v < 0 || v > U32_MAX) throw new RangeError(name + ': expected u32');
  return v;
}
function a0_bool(v, name) {
  if (typeof v !== 'boolean') throw new TypeError(name + ': expected bool');
  return v;
}
function a0_check(v, shape, name) {
  if (shape === 'u32') return a0_u32(v, name);
  if (shape === 'bool') return a0_bool(v, name);
  if (!Array.isArray(v)) throw new TypeError(name + ': expected ' + shape[0]);
  if (shape[0] === 'arr') {
    if (v.length !== shape[1]) throw new RangeError(name + ': expected ' + shape[1] + ' elements');
    for (let i = 0; i < v.length; i++) a0_check(v[i], shape[2], name + '[' + i + ']');
  } else {
    if (v.length !== shape[1].length) throw new RangeError(name + ': expected ' + shape[1].length + ' fields');
    for (let i = 0; i < v.length; i++) a0_check(v[i], shape[1][i], name + '.' + i);
  }
  return v;
}
function a0_with(a, i, v) { const c = a.slice(); c[i] = v; return c; }
`;

function jsOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return String(o.value);
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

function jsExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(jsOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `(${a} + ${b}) >>> 0`;
    case 'sub':
      return `(${a} - ${b}) >>> 0`;
    case 'mul':
      return `Math.imul(${a}, ${b}) >>> 0`;
    case 'and':
      return `(${a} & ${b}) >>> 0`;
    case 'or':
      return `(${a} | ${b}) >>> 0`;
    case 'xor':
      return `(${a} ^ ${b}) >>> 0`;
    case 'shl':
      return `(${a} << (${b} & 31)) >>> 0`;
    case 'shr':
      return `${a} >>> (${b} & 31)`;
    case 'eq':
      return `${a} === ${b}`;
    case 'lt':
      return `${a} < ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'call':
      return `${node.callee ?? ''}(${node.args.map(jsOperand).join(', ')})`;
    case 'arr':
    case 'rec':
      return `[${node.args.map(jsOperand).join(', ')}]`;
    case 'get':
      return `${a}[${b} % ${arrayLength(fn, node.args[0])}]`;
    case 'set':
      return `a0_with(${a}, ${b} % ${arrayLength(fn, node.args[0])}, ${c})`;
    case 'at':
      return `${a}[${b}]`;
    case 'put':
      return `a0_with(${a}, ${b}, ${c})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

const emitJsFunction: Emitter = (fn) => {
  const params = fn.params.map((_, i) => `p${i}`).join(', ');
  const guards = fn.params.map((t, i) =>
    isScalar(t) ? `  a0_${t}(p${i}, 'p${i}');` : `  a0_check(p${i}, ${jsShape(t)}, 'p${i}');`,
  );
  const body = fn.nodes.map((n) => {
    if (n.op !== 'fold' && n.op !== 'loop') return `  const n_${n.id} = ${jsExpr(n, fn)};`;
    const [count, init, ...extra] = n.args.map(jsOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!${n.pred ?? ''}(${call})) break;` : '';
    return `  let n_${n.id} = ${init};\n  for (let i = 0; i < ${count}; i++) {${guard} n_${n.id} = ${n.callee ?? ''}(${call}); }`;
  });
  return [
    `export function ${fn.name}(${params}) {`,
    ...guards,
    ...body,
    `  return ${jsOperand(fn.ret)};`,
    '}',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// C (also compiles as C++)
// ---------------------------------------------------------------------------

const C_PRELUDE = `/* Generated by A0 ${COMPILER_VERSION}. Exact u32/bool semantics. */
#include <stdint.h>
#include <stdbool.h>
`;

const cType = (t: Type): string =>
  t === 'u32' ? 'uint32_t' : t === 'bool' ? 'bool' : `a0t_${mangleType(t)}`;

/** Typedefs plus constructor/update helpers for one aggregate type (C, also valid C++). */
function cTypeDecl(t: Type): string {
  if (isScalar(t)) return '';
  const name = cType(t);
  const m = mangleType(t);
  if (t.kind === 'arr') {
    const e = cType(t.elem);
    const params = Array.from({ length: t.length }, (_, i) => `${e} e${i}`).join(', ');
    const inits = Array.from({ length: t.length }, (_, i) => `r.e[${i}] = e${i};`).join(' ');
    return [
      `typedef struct { ${e} e[${t.length}]; } ${name};`,
      `static inline ${name} a0mk_${m}(${params}) { ${name} r; ${inits} return r; }`,
      `static inline ${name} a0set_${m}(${name} a, uint32_t i, ${e} v) { a.e[i % ${t.length}u] = v; return a; }`,
    ].join('\n');
  }
  const fields = t.fields.map((f, i) => `${cType(f)} f${i};`).join(' ');
  const params = t.fields.map((f, i) => `${cType(f)} f${i}`).join(', ');
  const inits = t.fields.map((_, i) => `r.f${i} = f${i};`).join(' ');
  const puts = t.fields.map(
    (f, i) =>
      `static inline ${name} a0put_${m}_${i}(${name} r, ${cType(f)} v) { r.f${i} = v; return r; }`,
  );
  return [
    `typedef struct { ${fields} } ${name};`,
    `static inline ${name} a0mk_${m}(${params}) { ${name} r; ${inits} return r; }`,
    ...puts,
  ].join('\n');
}

function cOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return `${o.value}u`;
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

function cExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(cOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `(uint32_t)(${a} + ${b})`;
    case 'sub':
      return `(uint32_t)(${a} - ${b})`;
    case 'mul':
      return `(uint32_t)((uint64_t)${a} * (uint64_t)${b})`;
    case 'and':
      return `(${a} & ${b})`;
    case 'or':
      return `(${a} | ${b})`;
    case 'xor':
      return `(${a} ^ ${b})`;
    case 'shl':
      return `(uint32_t)(${a} << (${b} & 31u))`;
    case 'shr':
      return `(${a} >> (${b} & 31u))`;
    case 'eq':
      return `(${a} == ${b})`;
    case 'lt':
      return `(${a} < ${b})`;
    case 'select':
      return `(${a} ? ${b} : ${c})`;
    case 'call':
      return `a0_${node.callee ?? ''}(${node.args.map(cOperand).join(', ')})`;
    case 'arr':
    case 'rec':
      return `a0mk_${mangleType(fn.types.get(node.id) ?? 'u32')}(${node.args.map(cOperand).join(', ')})`;
    case 'get':
      return `${a}.e[${b} % ${arrayLength(fn, node.args[0])}u]`;
    case 'set':
      return `a0set_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}(${a}, ${b}, ${c})`;
    case 'at':
      return `${a}.f${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}`;
    case 'put':
      return `a0put_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}_${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}(${a}, ${c})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

export function cSignature(fn: TypedFunc): string {
  const params =
    fn.params.length === 0 ? 'void' : fn.params.map((t, i) => `${cType(t)} p${i}`).join(', ');
  return `${cType(fn.result)} a0_${fn.name}(${params})`;
}

const emitCFunction: Emitter = (fn) => {
  const body = fn.nodes.map((n) => {
    const t = cType(fn.types.get(n.id) ?? 'u32');
    if (n.op !== 'fold' && n.op !== 'loop') return `  const ${t} n_${n.id} = ${cExpr(n, fn)};`;
    const [count, init, ...extra] = n.args.map(cOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!a0_${n.pred ?? ''}(${call})) break;` : '';
    return `  ${t} n_${n.id} = ${init};\n  for (uint32_t i = 0; i < ${count}; i++) {${guard} n_${n.id} = a0_${n.callee ?? ''}(${call}); }`;
  });
  return [`${cSignature(fn)} {`, ...body, `  return ${cOperand(fn.ret)};`, '}'].join('\n');
};

// ---------------------------------------------------------------------------
// Java
// ---------------------------------------------------------------------------

export const JAVA_CLASS = 'A0Module';

const javaType = (t: Type): string =>
  t === 'u32'
    ? 'int'
    : t === 'bool'
      ? 'boolean'
      : t.kind === 'arr'
        ? `${javaType(t.elem)}[]`
        : `R_${mangleType(t)}`;

/** Nested record declarations and copy-on-write helpers for one aggregate type. */
function javaTypeDecl(t: Type): string {
  if (isScalar(t)) return '';
  const m = mangleType(t);
  if (t.kind === 'arr') {
    const jt = javaType(t);
    const e = javaType(t.elem);
    return `  static ${jt} set_${m}(${jt} a, int i, ${e} v) { ${jt} c = a.clone(); c[Integer.remainderUnsigned(i, ${t.length})] = v; return c; }`;
  }
  const name = javaType(t);
  const comps = t.fields.map((f, i) => `${javaType(f)} f${i}`).join(', ');
  const puts = t.fields.map((f, i) => {
    const args = t.fields.map((_, k) => (k === i ? 'v' : `r.f${k}()`)).join(', ');
    return `  static ${name} put_${m}_${i}(${name} r, ${javaType(f)} v) { return new ${name}(${args}); }`;
  });
  return [`  record ${name}(${comps}) {}`, ...puts].join('\n');
}

/** Java aggregate literal (arrays need the full nested element type in `new`). */
function javaNew(t: Type, args: readonly string[]): string {
  if (isScalar(t)) throw new A0Error('javaNew on scalar');
  if (t.kind === 'arr') return `new ${javaType(t)}{${args.join(', ')}}`;
  return `new ${javaType(t)}(${args.join(', ')})`;
}

function javaOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return hex(o.value);
    case 'bool':
      return o.value ? 'true' : 'false';
  }
}

function javaExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(javaOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `${a} + ${b}`;
    case 'sub':
      return `${a} - ${b}`;
    case 'mul':
      return `${a} * ${b}`;
    case 'and':
      return `${a} & ${b}`;
    case 'or':
      return `${a} | ${b}`;
    case 'xor':
      return `${a} ^ ${b}`;
    case 'shl':
      return `${a} << (${b} & 31)`;
    case 'shr':
      return `${a} >>> (${b} & 31)`;
    case 'eq':
      return `${a} == ${b}`;
    case 'lt':
      return `Integer.compareUnsigned(${a}, ${b}) < 0`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'call':
      return `${node.callee ?? ''}(${node.args.map(javaOperand).join(', ')})`;
    case 'arr':
    case 'rec':
      return javaNew(fn.types.get(node.id) ?? 'u32', node.args.map(javaOperand));
    case 'get':
      return `${a}[Integer.remainderUnsigned(${b}, ${arrayLength(fn, node.args[0])})]`;
    case 'set':
      return `set_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}(${a}, ${b}, ${c})`;
    case 'at':
      return `${a}.f${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}()`;
    case 'put':
      return `put_${mangleType(operandTypeOf(fn, node.args[0] as Operand))}_${node.args[1]?.kind === 'u32' ? node.args[1].value : 0}(${a}, ${c})`;
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as a statement`);
  }
}

const emitJavaFunction: Emitter = (fn) => {
  const params = fn.params.map((t, i) => `${javaType(t)} p${i}`).join(', ');
  const body = fn.nodes.map((n) => {
    const t = javaType(fn.types.get(n.id) ?? 'u32');
    if (n.op !== 'fold' && n.op !== 'loop') return `    final ${t} n_${n.id} = ${javaExpr(n, fn)};`;
    const [count, init, ...extra] = n.args.map(javaOperand);
    const call = [`n_${n.id}`, 'i', ...extra].join(', ');
    const guard = n.op === 'loop' ? ` if (!${n.pred ?? ''}(${call})) break;` : '';
    return `    ${t} n_${n.id} = ${init};\n    for (int i = 0; Integer.compareUnsigned(i, ${count}) < 0; i++) {${guard} n_${n.id} = ${n.callee ?? ''}(${call}); }`;
  });
  return [
    `  public static ${javaType(fn.result)} ${fn.name}(${params}) {`,
    ...body,
    `    return ${javaOperand(fn.ret)};`,
    '  }',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// SystemVerilog (combinational; emitted only, see results for validation status)
// ---------------------------------------------------------------------------

const svType = (t: Type): string => (t === 'bool' ? 'logic' : `logic [${bitWidth(t) - 1}:0]`);

/** Bit offset of field k inside a record (field 0 at the LSB). */
function svFieldOffset(t: Type, k: number): number {
  if (isScalar(t) || t.kind !== 'rec') throw new A0Error('field offset on non-record');
  return t.fields.slice(0, k).reduce((n, f) => n + bitWidth(f), 0);
}

function svOperand(o: Operand): string {
  switch (o.kind) {
    case 'node':
      return `n_${o.id}`;
    case 'param':
      return `p${o.index}`;
    case 'u32':
      return `32'd${o.value}`;
    case 'bool':
      return o.value ? "1'b1" : "1'b0";
  }
}

/** Low five bits of the shift distance; a bit-select is illegal on a literal, so mask constants here. */
function svShiftAmount(o: Operand | undefined): string {
  if (o === undefined) throw new A0Error('shift without distance');
  if (o.kind === 'u32') return `5'd${o.value & 31}`;
  return `${svOperand(o)}[4:0]`;
}

function svExpr(node: Node, fn: TypedFunc): string {
  const [a, b, c] = node.args.map(svOperand);
  switch (node.op) {
    case 'mov':
      return `${a}`;
    case 'add':
      return `32'(${a} + ${b})`;
    case 'sub':
      return `32'(${a} - ${b})`;
    case 'mul':
      return `32'(${a} * ${b})`;
    case 'and':
      return `${a} & ${b}`;
    case 'or':
      return `${a} | ${b}`;
    case 'xor':
      return `${a} ^ ${b}`;
    case 'shl':
      return `32'(${a} << ${svShiftAmount(node.args[1])})`;
    case 'shr':
      return `${a} >> ${svShiftAmount(node.args[1])}`;
    case 'eq':
      return `${a} == ${b}`;
    case 'lt':
      return `${a} < ${b}`;
    case 'select':
      return `${a} ? ${b} : ${c}`;
    case 'arr':
    case 'rec':
      // Element/field 0 occupies the least significant bits.
      return `{${[...node.args].reverse().map(svOperand).join(', ')}}`;
    case 'get': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      if (isScalar(t) || t.kind !== 'arr') throw new A0Error('get on non-array');
      const w = bitWidth(t.elem);
      const idx = node.args[1];
      const base =
        idx?.kind === 'u32' ? `${(idx.value % t.length) * w}` : `((${b} % ${t.length}) * ${w})`;
      return `${a}[${base} +: ${w}]`;
    }
    case 'at': {
      const t = operandTypeOf(fn, node.args[0] as Operand);
      const k = node.args[1]?.kind === 'u32' ? node.args[1].value : 0;
      if (isScalar(t) || t.kind !== 'rec') throw new A0Error('at on non-record');
      return `${a}[${svFieldOffset(t, k)} +: ${bitWidth(t.fields[k] as Type)}]`;
    }
    case 'set':
    case 'put':
      throw new A0Error(`${node.op} is emitted as an always_comb block`);
    case 'call':
    case 'fold':
    case 'loop':
      throw new A0Error(`${node.op} is emitted as module instances in SystemVerilog`);
  }
}

/** Largest literal fold trip count the combinational SystemVerilog backend will unroll. */
export const SV_MAX_UNROLL = 256;

const emitSvFunction: Emitter = (fn) => {
  const ports = [
    ...fn.params.map((t, i) => `  input ${svType(t)} p${i}`),
    `  output ${svType(fn.result)} result`,
  ].join(',\n');
  const decls = fn.nodes.map((n) => `  ${svType(fn.types.get(n.id) ?? 'u32')} n_${n.id};`);
  const assigns = fn.nodes.map((n) => {
    if (n.op === 'fold' || n.op === 'loop') {
      // Combinational backend: only a literal trip count can be unrolled into a chain of instances.
      const [count, init, ...extra] = n.args;
      if (count === undefined || count.kind !== 'u32') {
        throw new A0Error(
          `${fn.name}.${n.id}: ${n.op} with a non-literal trip count needs sequential state, which the combinational SystemVerilog backend does not implement`,
        );
      }
      if (count.value > SV_MAX_UNROLL) {
        throw new A0Error(
          `${fn.name}.${n.id}: ${n.op} trip count ${count.value} exceeds the SystemVerilog unroll limit ${SV_MAX_UNROLL}`,
        );
      }
      const width = svType(fn.types.get(n.id) ?? 'u32');
      const lines: string[] = [];
      let prev = init === undefined ? "32'd0" : svOperand(init);
      // For loop: done_i latches once the predicate is false; later stages pass the state through.
      let done = "1'b0";
      for (let i = 0; i < count.value; i += 1) {
        const wire = `n_${n.id}_s${i + 1}`;
        const ports = (result: string) => [
          `.p0(${prev})`,
          `.p1(32'd${i})`,
          ...extra.map((arg, k) => `.p${k + 2}(${svOperand(arg)})`),
          `.result(${result})`,
        ];
        if (n.op === 'loop') {
          const cont = `n_${n.id}_c${i}`;
          const next = `n_${n.id}_d${i + 1}`;
          const body = `n_${n.id}_b${i + 1}`;
          lines.push(
            `  logic ${cont};`,
            `  logic ${next};`,
            `  ${width} ${body};`,
            `  ${width} ${wire};`,
          );
          lines.push(`  a0_${n.pred ?? ''} u_${n.id}_p${i} (${ports(cont).join(', ')});`);
          lines.push(`  a0_${n.callee ?? ''} u_${n.id}_${i} (${ports(body).join(', ')});`);
          lines.push(`  assign ${next} = ${done} | ~${cont};`);
          lines.push(`  assign ${wire} = ${next} ? ${prev} : ${body};`);
          done = next;
        } else {
          lines.push(`  ${width} ${wire};`);
          lines.push(`  a0_${n.callee ?? ''} u_${n.id}_${i} (${ports(wire).join(', ')});`);
        }
        prev = wire;
      }
      lines.push(`  assign n_${n.id} = ${prev};`);
      return lines.join('\n');
    }
    if (n.op === 'set' || n.op === 'put') {
      const [a, b, c] = n.args.map(svOperand);
      const t = operandTypeOf(fn, n.args[0] as Operand);
      if (isScalar(t)) throw new A0Error(`${n.op} on scalar`);
      let slice: string;
      if (n.op === 'set') {
        if (t.kind !== 'arr') throw new A0Error('set on non-array');
        const w = bitWidth(t.elem);
        const idx = n.args[1];
        const base =
          idx?.kind === 'u32' ? `${(idx.value % t.length) * w}` : `((${b} % ${t.length}) * ${w})`;
        slice = `[${base} +: ${w}]`;
      } else {
        if (t.kind !== 'rec') throw new A0Error('put on non-record');
        const k = n.args[1]?.kind === 'u32' ? n.args[1].value : 0;
        slice = `[${svFieldOffset(t, k)} +: ${bitWidth(t.fields[k] as Type)}]`;
      }
      return `  always_comb begin n_${n.id} = ${a}; n_${n.id}${slice} = ${c}; end`;
    }
    if (n.op !== 'call') return `  assign n_${n.id} = ${svExpr(n, fn)};`;
    // A call is a combinational instance of the callee module, connected by port name.
    const conns = [...n.args.map((arg, i) => `.p${i}(${svOperand(arg)})`), `.result(n_${n.id})`];
    return `  a0_${n.callee ?? ''} u_${n.id} (${conns.join(', ')});`;
  });
  return [
    `module a0_${fn.name} (`,
    ports,
    ');',
    ...decls,
    ...assigns,
    `  assign result = ${svOperand(fn.ret)};`,
    'endmodule',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// Module assembly and emission cache
// ---------------------------------------------------------------------------

const EMITTERS: Readonly<Record<Target, Emitter>> = {
  js: emitJsFunction,
  c: emitCFunction,
  java: emitJavaFunction,
  sv: emitSvFunction,
};

function assemble(target: Target, bodies: readonly string[], program: TypedProgram): string {
  const types = aggregateTypes(program);
  switch (target) {
    case 'js':
      return `${JS_PRELUDE}\n${bodies.join('\n\n')}\n`;
    case 'c': {
      const decls = types.map(cTypeDecl).filter((d) => d.length > 0);
      return `${C_PRELUDE}\n${decls.length > 0 ? `${decls.join('\n')}\n\n` : ''}${bodies.join('\n\n')}\n`;
    }
    case 'java': {
      const decls = types.map(javaTypeDecl).filter((d) => d.length > 0);
      return `// Generated by A0 ${COMPILER_VERSION}. int carries the u32 bit pattern.\npublic final class ${JAVA_CLASS} {\n  private ${JAVA_CLASS}() {}\n\n${decls.length > 0 ? `${decls.join('\n')}\n\n` : ''}${bodies.join('\n\n')}\n}\n`;
    }
    case 'sv':
      return `// Generated by A0 ${COMPILER_VERSION}. Combinational, two-state semantics intended.\n\`timescale 1ns/1ps\n${bodies.join('\n\n')}\n`;
  }
}

export interface CompileOptions {
  readonly optimize?: boolean;
}

export interface CompileResult {
  readonly text: string;
  readonly cacheHits: number;
  readonly cacheMisses: number;
}

/**
 * Bounded LRU cache of per-function emitted text. Keys include the compiler
 * version, target, optimization flag, and function content revision. This is not
 * a persistent artifact cache: the program is still validated and hashed, and the
 * module is still assembled on every call.
 */
export class FunctionCache {
  readonly #entries = new Map<string, string>();
  readonly #capacity: number;

  constructor(capacity = 1024) {
    if (!Number.isInteger(capacity) || capacity < 1)
      throw new A0Error('cache capacity must be >= 1');
    this.#capacity = capacity;
  }

  get size(): number {
    return this.#entries.size;
  }

  /** Key: compiler version, target, optimization level, and semantic revision (own content + all transitive callees). */
  static key(target: Target, optimized: boolean, fn: TypedFunc): string {
    return `${COMPILER_VERSION}|${target}|${optimized ? 'O1' : 'O0'}|${semanticRevision(fn)}`;
  }

  get(key: string): string | undefined {
    const value = this.#entries.get(key);
    if (value !== undefined) {
      this.#entries.delete(key);
      this.#entries.set(key, value);
    }
    return value;
  }

  set(key: string, value: string): void {
    this.#entries.delete(key);
    this.#entries.set(key, value);
    if (this.#entries.size > this.#capacity) {
      const oldest = this.#entries.keys().next().value;
      if (oldest !== undefined) this.#entries.delete(oldest);
    }
  }
}

export function emitFunction(target: Target, fn: TypedFunc, options: CompileOptions = {}): string {
  const source = options.optimize === false ? fn : optimizeFunction(fn).fn;
  return EMITTERS[target](source);
}

export function compile(
  program: TypedProgram,
  target: Target,
  options: CompileOptions = {},
  cache?: FunctionCache,
): CompileResult {
  const optimized = options.optimize !== false;
  let cacheHits = 0;
  let cacheMisses = 0;
  const bodies = program.functions.map((fn) => {
    if (cache === undefined) return emitFunction(target, fn, options);
    const key = FunctionCache.key(target, optimized, fn);
    const hit = cache.get(key);
    if (hit !== undefined) {
      cacheHits += 1;
      return hit;
    }
    cacheMisses += 1;
    const text = emitFunction(target, fn, options);
    cache.set(key, text);
    return text;
  });
  return { text: assemble(target, bodies, program), cacheHits, cacheMisses };
}
