/**
 * Metal Shading Language emission (GPU, Gate 8).
 *
 * MSL is a C++14 dialect, so the C backend's output is mapped by a small, explicit type
 * layer rather than a second emitter: uint32_t -> uint, uint64_t -> ulong, and the C
 * headers/io runtime are replaced. Semantics are unchanged (exact 32-bit integer ops,
 * masked shifts, unsigned compares). io functions have no GPU form and are excluded by
 * the caller (`ioFreeSubset`). For every driver-callable scalar function a kernel wrapper
 * applies it elementwise over an input buffer (one thread per case).
 */

import { compile } from './backends.js';
import {
  A0Error,
  assertTargetSupports,
  assertVectorSized,
  containsIo,
  isScalar,
  type TypedFunc,
  type TypedProgram,
} from './core.js';

const MSL_PRELUDE = `#include <metal_stdlib>
using namespace metal;
`;

export function kernelName(fn: TypedFunc): string {
  return `k_${fn.name}`;
}

export function isKernelCallable(fn: TypedFunc): boolean {
  return fn.params.every(isScalar) && isScalar(fn.result);
}

/** Emit an MSL translation unit: mapped C functions plus elementwise kernels. */
export function emitMetal(program: TypedProgram): string {
  assertTargetSupports('metal', program);
  for (const fn of program.functions) {
    if (fn.params.some(containsIo) || containsIo(fn.result)) {
      throw new A0Error(`${fn.name}: io functions have no GPU form; use ioFreeSubset first`);
    }
    assertVectorSized(fn, 'Metal');
  }
  const c = compile(program, 'c').text;
  const body = c
    .replace(/\/\* Generated by A0[^\n]*\n/, '')
    .replace('#include <stdint.h>\n#include <stdbool.h>\ntypedef struct a0_io a0_io;\n', '')
    .replace(/\buint32_t\b/g, 'uint')
    .replace(/\buint64_t\b/g, 'ulong')
    .replace(/\bstatic inline\b/g, 'inline')
    // MSL pointers need an address space: the C backend's aggregate pointers (owned loop state,
    // const predicate state, in-place update aliases) all point at thread-local storage.
    .replace(/\b(a0t_\w+) \*/g, 'thread $1 *');
  const kernels = program.functions.filter(isKernelCallable).map((fn) => {
    const k = fn.params.length;
    const args = fn.params
      .map((t, i) => (t === 'u32' ? `in[id * ${k}u + ${i}u]` : `(bool)in[id * ${k}u + ${i}u]`))
      .join(', ');
    const result =
      fn.result === 'u32' ? `a0_${fn.name}(${args})` : `(a0_${fn.name}(${args}) ? 1u : 0u)`;
    return `kernel void ${kernelName(fn)}(device const uint *in [[buffer(0)]], device uint *out [[buffer(1)]], uint id [[thread_position_in_grid]]) {\n  out[id] = ${result};\n}`;
  });
  return `${MSL_PRELUDE}\n${body}\n${kernels.join('\n\n')}\n`;
}
